#filter emptyLines

#define MOZ_LANGPACK_CREATOR Aviary.pl
#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Aviary.pl</em:contributor> <em:contributor>Piotr Komoda</em:contributor> <em:contributor>Zbigniew Braniecki</em:contributor> <em:contributor>Marek Wawoczny</em:contributor> <em:contributor>Piotr Bartecki</em:contributor> <em:contributor>Stefan Plewako</em:contributor>

#unfilter emptyLines
