
#define JS_STANDALONE 1
#define MOZILLA_VERSION ""
#define MOZILLA_VERSION_U 
#define MOZILLA_UAVERSION ""
#define MOZJS_MAJOR_VERSION 
#define MOZJS_MINOR_VERSION 
#define _CRT_SECURE_NO_WARNINGS 1
#define _CRT_NONSTDC_NO_WARNINGS 1
#define WINVER 0x502
#define _WIN32_WINNT 0x502
#define _WIN32_IE 0x0603
#define MOZ_WINSDK_TARGETVER 0x06030000
#define MOZ_NTDDI_WIN7 0x06010000
#define HAVE_LOCALECONV 1
#define HAVE_HYPOT 1
#define HAVE__GETC_NOLOCK 1
#define X_DISPLAY_MISSING 1
#define HAVE_64BIT_BUILD 1
#define HAVE_SNPRINTF 1
#define HAVE__MSIZE 1
#define _WINDOWS 1
#define WIN32 1
#define XP_WIN 1
#define XP_WIN32 1
#define HW_THREADS 1
#define STDC_HEADERS 1
#define WIN32_LEAN_AND_MEAN 1
#define NO_X11 1
