[package]
name = "servo_arc"
version = "0.0.1"
authors = ["The Servo Project Developers"]
license = "MPL-2.0"
publish = false

[lib]
name = "servo_arc"
path = "lib.rs"

[features]
servo = ["serde", "heapsize"]

[dependencies]
heapsize = {version = "0.4.0", optional = true}
nodrop = {version = "0.1.8"}
serde = {version = "1.0", optional = true}
stable_deref_trait = "1.0.0"
