#filter emptyLines

#define MOZ_LANGPACK_CREATOR mozilla.org

# If non-English locales wish to credit multiple contributors, uncomment this

# variable definition and use the format specified.

#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Alexandru Szasz</em:contributor><em:contributor>Raul Nicolae Malea</em:contributor> <em:contributor>Cristian Silaghi</em:contributor> <em:contributor>Jobava</em:contributor>

#unfilter emptyLines
