#filter emptyLines

#define MOZ_LANGPACK_CREATOR Thunderbird Breton Team

# If non-English locales wish to credit multiple contributors, uncomment this

# variable definition and use the format specified.

#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Alan Monfort</em:contributor> <em:contributor>Philippe Basciano-Le Gall</em:contributor> <em:contributor>Denis Arnaud</em:contributor> <em:contributor>Michel Nédélec</em:contributor>

#unfilter emptyLines
