# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

rights-title = Haklarınız Hakkında
rights-intro = { -brand-full-name }, dünya çapındaki binlerce kişiden oluşan bir topluluk tarafından geliştirilen özgür ve açık kaynaklı bir yazılımdır. Bilmeniz gereken birkaç şey var:
rights-intro-point-1 = { -brand-short-name } <a data-l10n-name="mozilla-public-license-link">Mozilla Kamu Lisansı</a> altında dağıtılmaktadır. Yani { -brand-short-name } serbestçe kullanılabilir, kopyalanabilir ve başkalarına dağıtılabilir. Ayrıca ihtiyaçlarınıza göre { -brand-short-name } kaynak kodlarını değiştirmekte de özgürsünüz. Mozilla Kamu Lisansı, değiştirdiğiniz sürümleri dağıtma hakkını da size vermektedir.
rights-intro-point-2 = Mozilla Vakfı’nın veya başka bir kurumun herhangi bir ticari markasını (Firefox logosu ve adı da dahil olmak üzere) kullanma hakkına sahip değilsiniz. Ticari markalarla ilgili ayrıntılı bilgi <a data-l10n-name="mozilla-trademarks-link">burada bulunabilir</a>.
rights-intro-point-3 = { -brand-short-name } tarayıcısındaki Çökme Habercisi gibi bazı özellikler size { -vendor-short-name }'ya geri bildirimde bulunma seçeneği sunar. Geri bildirimde bulunmayı tercih ederseniz, { -vendor-short-name }'ya ürünlerini geliştirmek için bu geri bildirimi kullanma, geri bildirimi web sitelerinde yayımlama ve geri bildirimi dağıtma izni vermiş olursunuz.
rights-intro-point-4 = Kişisel bilgilerinizi ve { -brand-short-name } üzerinden { -vendor-short-name }'ya gönderdiğiniz geri bildirimleri nasıl kullandığımız <a data-l10n-name="mozilla-privacy-policy-link">{ -brand-short-name } Gizlilik İlkelerinde</a> açıklanmıştır.
rights-intro-point-4-unbranded = Bu ürünle ilgili tüm gizlilik ilkeleri burada listelenmelidir.
rights-intro-point-5 = Bazı { -brand-short-name } özellikleri web tabanlı bilgi hizmetlerinden yararlanır, ancak bunların tamamen doğru ve hatasız olduklarını garanti edemeyiz. Bu hizmetleri kullanan özelliklerin devre dışı bırakılmasıyla ilgili daha fazla bilgiyi <a data-l10n-name="mozilla-service-terms-link">hizmet koşulları</a> sayfasında bulabilirsiniz.
rights-intro-point-5-unbranded = Bu ürün web hizmetleriyle bağlantı kuruyorsa, hizmet(ler) ile ilgili tüm hizmet koşulları <a data-l10n-name="mozilla-website-services-link">Web Sitesi Hizmetleri</a> bölümüne bağlanmalıdır.
rights-intro-point-6 = Bazı video türlerini oynatabilmek için { -brand-short-name } üçüncü taraflara ait bazı içerik çözme modüllerini indirir.
rights-webservices-header = { -brand-full-name } Web Tabanlı Bilgi Hizmetleri
rights-webservices = { -brand-full-name } bu ikili { -brand-short-name } sürümünde kullanımınıza sunulan bazı özellikler için, aşağıdaki açıklanan koşullar kapsamında web tabanlı bilgi hizmetlerinden ("Hizmetler") yararlanır. Hizmetlerden birini veya birkaçını kullanmak istemiyorsanız veya aşağıdaki koşulları kabul etmiyorsanız ilgili özelliği ve Hizmet(ler)i devre dışı bırakabilirsiniz. Özellik veya Hizmetleri devre dışı bırakmanız için izleyebileceğiniz yönergeler <a data-l10n-name="mozilla-disable-service-link">burada</a> bulunabilir. Diğer özellikler ve Hizmetler uygulama tercihlerinde devre dışı bırakılabilir.
rights-safebrowsing = <strong>SafeBrowsing: </strong>Güvenli Gezinti özelliğini devre dışı bırakmanız güvensiz siteleri ziyaret etmenizle sonuçlanabileceği için tavsiye edilmez. Bu özelliği tamamen devre dışı bırakmak istiyorsanız şu adımları izleyin:
rights-safebrowsing-term-1 = Uygulama tercihlerini açın
rights-safebrowsing-term-2 = Güvenlik bölümünü seçin
rights-safebrowsing-term-3 = "{ enableSafeBrowsing-label }" seçeneğinin işaretini kaldırın
enableSafeBrowsing-label = Tehlikeli ve aldatıcı içerikleri engelle
rights-safebrowsing-term-4 = Güvenli Gezinti artık devre dışıdır
rights-locationawarebrowsing = <strong>Konuma Duyarlı Tarama: </strong>her zaman sizin isteğinizle çalışır. Sizin izniniz alınmadan asla konum bilgisi gönderilmez. Bu özelliği tamamen devre dışı bırakmak istiyorsanız şu adımlar izleyin:
rights-locationawarebrowsing-term-1 = Adres çubuğuna şunu yazın: <code>about:config</code>
rights-locationawarebrowsing-term-2 = geo.enabled yazın
rights-locationawarebrowsing-term-3 = geo.enabled tercihine çift tıklayın
rights-locationawarebrowsing-term-4 = Konuma Duyarlı Gezinti artık devre dışıdır
rights-webservices-unbranded = Ürünün içerdiği web sitesi hizmetlerine genel bakış ve varsa devre dışı bırakma yönergeleri buraya eklenmelidir.
rights-webservices-term-unbranded = Bu ürünle ilgili tüm hizmet koşulları burada listelenmelidir.
rights-webservices-term-1 = { -vendor-short-name } ve ona katkıda bulunanlar, lisans sahipleri ve iş ortakları en eksiksiz ve güncel Hizmetleri sunmak için birlikte çalışmaktadır. Buna rağmen bu bilgilerin kapsamlı ve hatasız olduğunu garanti edemeyiz. Örneğin, Güvenli Tarama Hizmeti bazı riskli siteleri tanımayabilir ve bazı güvenli siteleri hatalı tanıyabilir. Konuma Duyarlı Hizmet'te hizmet sağlayıcılarımız tarafından döndürülen tüm konumlar yalnızca tahmindir ve ne biz ne de hizmet sağlayıcılarımız bu konumların doğruluğunu garanti etmemekteyiz.
rights-webservices-term-2 = { -vendor-short-name } kendi isteğiyle Hizmetleri durdurabilir veya değiştirebilir.
rights-webservices-term-3 = Bu Hizmetleri uyumlu { -brand-short-name } sürümüyle kullanmakta özgürsünüz ve { -vendor-short-name } size bu hakları sunmaktadır. { -vendor-short-name } ve lisans sahipleri Hizmetler üzerindeki diğer tüm haklara sahiptir.  Bu koşullar { -brand-short-name } ve ilgili { -brand-short-name } kaynak kodu sürümlerinde geçerli olan açık kaynak lisansı haklarınızı hiçbir şekilde kısıtlamaz.
rights-webservices-term-4 = <strong>Hizmetler "oldukları gibi" sağlanmaktadır.  { -vendor-short-name }, ona katkıda bulunanlar, lisans sahipleri ve dağıtıcılar; Hizmetlerin ticari değeri olduğu ve ihtiyaçlarınıza uygun olacağı konusunda yazılı veya sözlü herhangi bir garantide bulunmaz.  İhtiyaçlarınızı karşılamak için Hizmetleri tercih ederseniz kalite ve performansa dair tüm risk size aittir. Bazı yasalar garantilerin hariç tutulmasına veya kısıtlanmasına izin vermiyor olabilir. Bu durumda bu koşullar sizin için geçerli olmayacaktır.</strong>
rights-webservices-term-5 = <strong>Kanun gereksinimleri dışında; { -vendor-short-name }, ona katkıda bulunanlar, lisans sahipleri ve dağıtıcıları { -brand-short-name } ürünün ve Hizmetlerin kullanımından doğabilecek herhangi bir dolaylı, özel, rastlantısal, cezai veya örnek teşkil edici hasardan sorumlu tutulamaz.  Bu şartlar altındaki toplu sorumluluk tutarı 500 $'ı (beş yüz dolar) geçemez. Bazı yargı hükümleri belli hasarların istisnai tutulmasına veya kısıtlanmasına izin vermeyebilir, bu durumda bu istisna ve kısıtlama sizin için geçerli olmayabilir.</strong>
rights-webservices-term-6 = { -vendor-short-name } gerekli gördüğünde bu şartları zaman zaman güncelleyebilir. Bu şartlar { -vendor-short-name }'nın yazılı onayı olmadan değiştirilemez veya iptal edilemez.
rights-webservices-term-7 = Bu koşullar, kanun ihtilafi hükümleri hariç olmak üzere, ABD California eyalet yasalarıyla korunur. Bu koşulların herhangi bir kısmının hükümsüz veya uygulanamaz olması halinde geri kalan kısımlar geçerli ve etkili olmaya devam edecektir. Bu koşulların çeviri sürümüyle İngilizce sürümü arasında bir çelişki olması halinde İngilizce sürüm geçerli sayılacaktır.
