# This Source Code Form is subject to the terms of the Waterfox Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with
# your locale code, and link to your translated pages as soon as they're
# live.

#define bookmarks_title Lesezeichen
#define bookmarks_heading Lesezeichen

#define bookmarks_toolbarfolder Lesezeichen-Symbolleiste
#define bookmarks_toolbarfolder_description Lesezeichen, die Sie in diesem Ordner ablegen, werden in der Lesezeichen-Symbolleiste angezeigt.

# LOCALIZATION NOTE (getting_started):
# link title for https://www.mozilla.org/en-US/firefox/central/
#define getting_started Erste Schritte

# LOCALIZATION NOTE (firefox_heading):
# Waterfox links folder name
#define firefox_heading Waterfox Waterfox

# LOCALIZATION NOTE (firefox_help):
# link title for https://www.mozilla.org/en-US/firefox/help/
#define firefox_help Hilfe und Anleitungen

# LOCALIZATION NOTE (firefox_get_help):
# link title for https://www.mozilla.org/en-US/firefox/help/
#define firefox_get_help Hilfe erhalten

# LOCALIZATION NOTE (firefox_customize):
# link title for https://www.mozilla.org/en-US/firefox/customize/
#define firefox_customize Waterfox anpassen

# LOCALIZATION NOTE (firefox_community):
# link title for https://www.mozilla.org/en-US/contribute/
#define firefox_community Machen Sie mit

# LOCALIZATION NOTE (firefox_about):
# link title for https://www.mozilla.org/en-US/about/
#define firefox_about Über uns

# LOCALIZATION NOTE (nightly_heading):
# Waterfox Nightly links folder name
#define nightly_heading Ressourcen zu Waterfox Nightly

# LOCALIZATION NOTE (nightly_blog):
# Nightly builds only, link title for https://blog.nightly.mozilla.org/
#define nightly_blog Blog zu Waterfox Nightly (englisch)

# LOCALIZATION NOTE (bugzilla):
# Nightly builds only, link title for https://bugzilla.mozilla.org/
#define bugzilla Fehler und Vorschläge melden (englisch)

# LOCALIZATION NOTE (mdn):
# Nightly builds only, link title for https://developer.mozilla.org/
#define mdn Waterfox Developer Network

# LOCALIZATION NOTE (nightly_tester_tools):
# Nightly builds only, link title for https://addons.mozilla.org/en-US/firefox/addon/nightly-tester-tools/
#define nightly_tester_tools Nightly Tester Tools (englisch)

# LOCALIZATION NOTE (crashes):
# Nightly builds only, link title for about:crashes
#define crashes Alle Absturzberichte

# LOCALIZATION NOTE (planet):
# Nightly builds only, link title for https://planet.mozilla.org/
#define planet Planet Waterfox (englisch)

#unfilter emptyLines
