# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with
# your locale code, and link to your translated pages as soon as they're
# live.

#define bookmarks_title စာမှတ်များ
#define bookmarks_heading စာမှတ်များ

#define bookmarks_toolbarfolder စာမှတ်ကိရိယာဘားတန်း ဖိုင်တွဲ
#define bookmarks_toolbarfolder_description မှတ်သားလိပ်စာများအား မှတ်သားလိပ်စာဘားတန်းမှာပေါ်စေရန် ဤဖိုင်ထဲသို့ထည့်ပါ။

# LOCALIZATION NOTE (getting_started):
# link title for https://www.mozilla.org/en-US/firefox/central/
#define getting_started စတင်အသုံးပြုခြင်း

# LOCALIZATION NOTE (firefox_heading):
# Firefox links folder name
#define firefox_heading Mozilla Firefox

# LOCALIZATION NOTE (firefox_help):
# link title for https://www.mozilla.org/en-US/firefox/help/
#define firefox_help အကူအညီများနှင့်ကျူတိုရီရယ်များ

# LOCALIZATION NOTE (firefox_customize):
# link title for https://www.mozilla.org/en-US/firefox/customize/
#define firefox_customize Firefox ကို စိတ်ကြိုက်ပြုပြင်ရန်

# LOCALIZATION NOTE (firefox_community):
# link title for https://www.mozilla.org/en-US/contribute/
#define firefox_community ပါဝင်ဆောင်ရွက်ပါ

# LOCALIZATION NOTE (firefox_about):
# link title for https://www.mozilla.org/en-US/about/
#define firefox_about ကျွန်ုပ်တို့အကြောင်း

# LOCALIZATION NOTE (nightly_heading):
# Firefox Nightly links folder name
#define nightly_heading Firefox Nightly ရင်းမြစ်များ

# LOCALIZATION NOTE (nightly_blog):
# Nightly builds only, link title for https://blog.nightly.mozilla.org/
#define nightly_blog Firefox Nightly ဘလောဂ့်

# LOCALIZATION NOTE (bugzilla):
# Nightly builds only, link title for https://bugzilla.mozilla.org/
#define bugzilla Mozilla Bug Tracker

# LOCALIZATION NOTE (mdn):
# Nightly builds only, link title for https://developer.mozilla.org/
#define mdn Mozilla Developer Network

# LOCALIZATION NOTE (nightly_tester_tools):
# Nightly builds only, link title for https://addons.mozilla.org/en-US/firefox/addon/nightly-tester-tools/
#define nightly_tester_tools Nightly စမ်းသပ်သူများသုံး ကိရိယာများ

# LOCALIZATION NOTE (crashes):
# Nightly builds only, link title for about:crashes
#define crashes ပျက်စီးမှုများအားလုံး

# LOCALIZATION NOTE (irc):
# Nightly builds only, link title for ircs://irc.mozilla.org/nightly
#define irc Nightly ဆိုင်ရာများကို IRC ပေါ်တွင် ဆွေးနွေးပါ

# LOCALIZATION NOTE (planet):
# Nightly builds only, link title for https://planet.mozilla.org/
#define planet Planet Mozilla

#unfilter emptyLines
