# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#filter emptyLines

#define MOZ_LANGPACK_CREATOR mozilla.org

# If non-English locales wish to credit multiple contributors, uncomment this

# variable definition and use the format specified.

#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>أيمن حورية</em:contributor> <em:contributor>جهاد عفيفي</em:contributor><em:contributor>خالد حسني</em:contributor><em:contributor>سبأ برتو</em:contributor><em:contributor>عبد الرحمن حسني </em:contributor><em:contributor>علاء كساب</em:contributor><em:contributor>أنس الحسيني</em:contributor>

#unfilter emptyLines
