#filter emptyLines

#define MOZ_LANGPACK_CREATOR Waterfox Lietuvoje

# If non-English locales wish to credit multiple contributors, uncomment this

# variable definition and use the format specified.

#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Gintautas Grigas</em:contributor> <em:contributor>Tatjana Jevsikova</em:contributor> <em:contributor>Rimas Kudelis</em:contributor> <em:contributor>Sigita Pedzevičienė</em:contributor>

#unfilter emptyLines
