# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

rights-title = Oer jo rjochten
rights-intro = { -brand-full-name } is fergees en iepen boarne software, makke troch in mienskip fan tûzenen fan oeral oer de wrâld. Der binne in pear dingen dy't jo witte moatte:
rights-intro-point-1 = { -brand-short-name } is jo beskikber makke ûnder de betingsten fan de <a data-l10n-name="mozilla-public-license-link">Mozilla Publike Lisinsje</a>. Dit betsjut dat jo { -brand-short-name } brûke meie, kopiearje en distribuearje nei oaren.  Jo binne ek wolkom om de boarnekoade te bewurkjen of { -brand-short-name } sa as jo dat wolle. De Mozilla Publike Lisinsje jout jo ek it rjocht om jo oanpaste ferzje te fersprieden.
rights-intro-point-2 = Jo krije gjin inkelde hannelsrjochten of lisinsjes foar de hannelsmerken fan de Mozilla Foundation of oare partijen, ynklusyf en sûnder beheining ta de namme of it logo fan Thunderbird . Fierdere ynformaasje oer hannelsmerken kin <a data-l10n-name="mozilla-trademarks-link">hjir</a> fûn wurde.
rights-intro-point-3 = Inkelde ûnderdielen yn { -brand-short-name }, lykas de Ungelokrapportearder, jouwe jo de mooglikheid om kommentaar te leverjen oan { -vendor-short-name }. As jo kieze om kommentaar te leverjen, jouwe jo { -vendor-short-name } tastimming om it kommentaar te brûken om har produkten te ferbetterjen, it kommentaar te publisearjen op syn websites en om it kommentaar te fersprieden.
rights-intro-point-4 = Hoe't wy jo persoanlike ynformaasje en kommentaar oanlevere oan { -vendor-short-name } troch { -brand-short-name } brûke is beskrean yn it <a data-l10n-name="mozilla-privacy-policy-link">{ -brand-short-name } Privacybelied</a>.
rights-intro-point-4-unbranded = Tapaste privacybetingsten foar dit produkt soene hjir toand wurde moatte.
rights-intro-point-5 = Inkelde { -brand-short-name } funksjes meitsje gebrûk fan web-basearre ynformaasje tsjinsten, mar, wy kinne net fersekerje dat se 100% akkuraat of flaterfrij binne. Mear details, ynklusyf ynformaasje oer hoe't jo dizze funksjes útskeakelje kinne dy't dizze tsjinsten brûke, kinne fûn wurde yn de <a data-l10n-name="mozilla-service-terms-link">tsjinsttermen</a>.
rights-intro-point-5-unbranded = As dit produkt webtsjinsten brûkt, moat elke tapaste tsjinsttermen foar de tsjinst(en) keppele nei de <a data-l10n-name="mozilla-website-services-link">Websitetsjinsten</a> seksje.
rights-intro-point-6 = Om bepaalde typen fideo-ynhâld ôf te spyljen, downloadt { -brand-short-name } bepaalde ynhâlddekodearringsmodules fan tredden.
rights-webservices-header = { -brand-full-name } Web-basearre ynformaasjetsjinsten
rights-webservices = { -brand-full-name } brûkt web-basearre ynformaasjetsjinsten (‘Tsjinsten’) om funksjes oan te bieden foar jo gebrûk mei dizze binêre ferzje fan { -brand-short-name } ûnder de betingsten as hjirûnder beskreaun. As jo ien of mear fan dizze Tsjinsten net brûke wolle of de betingsten hjirûnder binne net te akseptearjen, kinne jo de funksjes of Tsjinst(en) útskeakelje. Ynstruksjes oer hoe't jo in bepaalde funksje of Tsjinst útskeakelje kinne, kinne jo <a data-l10n-name="mozilla-disable-service-link">hjir</a> fine. Oare ûnderdielen en tsjinsten kinne útskeakele wurde yn de opsjes fan de tapassing.
rights-locationawarebrowsing = <strong>Lokaasjebewust sneupe: </strong>is altyd opt-yn.  Lokaasje-ynformaasje wurdt nea ferstjoerd sûnder jo tastimming.  As jo dizze funksje folslein útskeakelje wolle, folgje dan dizze stappen:
rights-locationawarebrowsing-term-1 = Typ yn de adresbalke <code>about:config</code>
rights-locationawarebrowsing-term-2 = Typ geo.enabled
rights-locationawarebrowsing-term-3 = Dûbelklik op de foarkar geo.enabled
rights-locationawarebrowsing-term-4 = Lokaasjebewust sneupe is no útskeakele
rights-webservices-unbranded = In oersicht fan de websitetsjinsten dy't yn it produkt sitte, tegearre mei ynstruksjes oer hoe't jo se útskeakelje kinne, wannear mooglik, soe hjir stean moatte.
rights-webservices-term-unbranded = Tapaste tsjinstbetingsten moatte hjir oanjûn wurde.
rights-webservices-term-1 = { -vendor-short-name } en syn meiwurkers, lisinsje-útjouwers en partners wurkje oan de meast akkurate en by-de-tiid tsjinsten. It kin net garandearre wurde dat dizze ynformaasje grut genôch en flaterfrij is. Bygelyks, de Feilich sneupe tsjinst kin risikofolle siden miskien net identifisearje en guon feilige siden meie identifisearre wêze as in flater en de lokaasjes fan de Lokaasjetsjinst opjûn troch ús tsjinstjouwers binne allinnich skattingen en noch wy noch ús tsjinstjouwer garandearje de akkuratesse fan de opjûne lokaasjes.
rights-webservices-term-2 = { -vendor-short-name } mei de Tsjinsten stoppe of wizigje nei eigen goedtinken.
rights-webservices-term-3 = Jo binne wolkom om dizze Tsjinsten te brûken mei de byhearende ferzje fan { -brand-short-name }, en { -vendor-short-name } jout jo alle rjochten om dat te dwaan.  { -vendor-short-name } en syn lisinsje-útjouwers behâlde alle rjochten yn de Tsjinsten.  Dizze betingsten binne net bedoeld om jo rjochten te beheinen foar rjochten jûn ûnder iepen boarne lisinsjes fan tapassing op { -brand-short-name } en ta oerienkommende boarnekoade ferzjes fan { -brand-short-name }.
rights-webservices-term-4 = <strong>De Tjinsten wurde "as-is" oanbean.  { -vendor-short-name }, syn meiwurkers, lisinsje-útjouwers, en distributeurs, ûntkenne alle garânsjes, ekspres of mei opsetsin, ynklusyf sûnder beheining, garânsjes dat de Tsjinsten ferhannelber binne en oerienkomme mei jo spesifike doel.  Jo drage it folsleine risiko foar it selektearjen fan de Tsjinsten foar jo doel en foar de kwaliteit en prestaasje fan de Tsjinsten. Guon jurisdiksjes stean útsluting, beheining of ymplisite garânsjes net ta, dus dizze disclaimer kin foar jo net fan tapassing wêze.</strong>
rights-webservices-term-5 = <strong>Utsein as ferplicht troch de wet, { -vendor-short-name }, syn meiwurkers, lisinsje-útjouwers, en distributeurs sille net oanspraaklik wêze foar elke yndirekte, spesjale, ynsidintele, konsekwinsjele, bestraffende, of eksimplaryske skansearring as gefolch fan of op ien oft oare manier relatearre ta it gebrûk fan { -brand-short-name } en de Tsjinsten.  De kollektive oanspraaklikheid ûnder dizze betingsten sille net heger wurde as $500 (fiifhûndert dollar). Guon jurisdiksjes stean útsluting, beheining of ymplisite garânsjes net ta, dus dizze disclaimer kin foar jo net fan tapassing wêze.</strong>
rights-webservices-term-6 = { -vendor-short-name } mei dizze betingsten sa no en dan fernije as it nedich is. Dizze betingsten meie net bewurke of annulearre wurde sûnder in skreaune oerienkomst fan { -vendor-short-name }.
rights-webservices-term-7 = Dizze betingsten binne regele troch de wetten fan de steat California, U.S.A., mei útsluting fan konflikten fan wettelike bepalings. As in part fan dizze betingsten net jildich binne of net ôf te dwingen, dan bliuwe de oare parten noch hieltiid folslein fan tapassing. As der in konflikt is tusken de oersette ferzje fan dizze betingsten en de Ingelske taalferzje, dan sil de Ingelske taalferzje liedend wêze.
