#filter emptyLines

#define MOZ_LANGPACK_CREATOR Waterfox-NL

# If non-English locales wish to credit multiple contributors, uncomment this
# variable definition and use the format specified.
#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Gert-Paul van der Beek</em:contributor><em:contributor>Tim Maks van den Broek</em:contributor><em:contributor>Laurens Holst</em:contributor><em:contributor>Ton Kensen</em:contributor><em:contributor>Anne van Kesteren</em:contributor><em:contributor>Hendrik Maryns</em:contributor><em:contributor>Martijn Ras</em:contributor><em:contributor>leden MozBrowser-forum</em:contributor>

#unfilter emptyLines
