#filter emptyLines

#define MOZ_LANGPACK_CREATOR Translate.org.za

# If non-English locales wish to credit multiple contributors, uncomment this

# variable definition and use the format specified.

#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Translate.org.za</em:contributor> <em:contributor>Dwayne Bailey</em:contributor> <em:contributor>Samuel Murray</em:contributor> <em:contributor>Friedel Wolff</em:contributor>

#unfilter emptyLines
