# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!! 
# This file is built by mktables from e.g. UnicodeData.txt.
# Any changes made here will be lost!

#
# NumericType category 'Numeric'
#
return <<'END';
00BC	00BE	
09F4	09F7	
09F9		
0BF0	0BF2	
0F2A	0F33	
1372	137C	
16EE	16F0	
17F0	17F9	
2153	2182	
2469	2473	
247D	2487	
2491	249B	
24EB	24F4	
24FE		
277F		
2789		
2793		
2CFD		
3007		
3021	3029	
3038	303A	
3192	3195	
3220	3229	
3251	325F	
3280	3289	
32B1	32BF	
10107	10133	
10140	10178	
1018A		
10320	10323	
1034A		
103D1	103D5	
10A44	10A47	
END
