# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with
# your locale code, and link to your translated pages as soon as they're
# live.

#define bookmarks_title სანიშნები
#define bookmarks_heading სანიშნები

#define bookmarks_toolbarfolder სანიშნების ხელსაწყოთა ზოლის საქაღალდე
#define bookmarks_toolbarfolder_description დაამატეთ სანიშნები ამ საქაღალდეში, რომ იხილოთ ისინი სანიშნეთა ზოლზე

# LOCALIZATION NOTE (getting_started):
# link title for https://www.mozilla.org/en-US/firefox/central/
#define getting_started დაწყება

# LOCALIZATION NOTE (firefox_heading):
# Firefox links folder name
#define firefox_heading Mozilla Firefox

# LOCALIZATION NOTE (firefox_help):
# link title for https://www.mozilla.org/en-US/firefox/help/
#define firefox_help დახმარება და სახელმძღვანელო

# LOCALIZATION NOTE (firefox_customize):
# link title for https://www.mozilla.org/en-US/firefox/customize/
#define firefox_customize მოირგეთ Firefox

# LOCALIZATION NOTE (firefox_community):
# link title for https://www.mozilla.org/en-US/contribute/
#define firefox_community შემოგვიერთდით

# LOCALIZATION NOTE (firefox_about):
# link title for https://www.mozilla.org/en-US/about/
#define firefox_about ჩვენ შესახებ

# LOCALIZATION NOTE (nightly_heading):
# Firefox Nightly links folder name
#define nightly_heading Firefox Nightly მასალები

# LOCALIZATION NOTE (nightly_blog):
# Nightly builds only, link title for https://blog.nightly.mozilla.org/
#define nightly_blog Firefox Nightly სვეტი (ბლოგი)

# LOCALIZATION NOTE (bugzilla):
# Nightly builds only, link title for https://bugzilla.mozilla.org/
#define bugzilla Mozilla ხარვეზების კვლევა

# LOCALIZATION NOTE (mdn):
# Nightly builds only, link title for https://developer.mozilla.org/
#define mdn Mozilla-ს შემმუშავებლების ერთობა

# LOCALIZATION NOTE (nightly_tester_tools):
# Nightly builds only, link title for https://addons.mozilla.org/en-US/firefox/addon/nightly-tester-tools/
#define nightly_tester_tools Nightly-ის კვლევის ხელსაწყოები

# LOCALIZATION NOTE (crashes):
# Nightly builds only, link title for about:crashes
#define crashes უეცარი გათიშვები

# LOCALIZATION NOTE (irc):
# Nightly builds only, link title for ircs://irc.mozilla.org/nightly
#define irc განიხილეთ Nightly IRC-ზე

# LOCALIZATION NOTE (planet):
# Nightly builds only, link title for https://planet.mozilla.org/
#define planet პლანეტა Mozilla

#unfilter emptyLines
