/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"

interface nsIFile;

/**
 * Some additional methods in the same style as nsIComponentManager
 */
[scriptable, uuid(fe5948c1-458a-464f-9251-310f8535a34c)]
interface nsIComponentManagerExtra : nsISupports
{
    /**
     * Register an extension manifest. This is either the path to the unpacked extension folder, or
     * the path to the xpi file.
     *
     * @param {nsIFile} aLocation       The file pointing to the extension root
     */
    void addLegacyExtensionManifestLocation(in nsIFile aLocation);
};
