#filter emptyLines

#define MOZ_LANGPACK_CREATOR mozilla.se

# If non-English locales wish to credit multiple contributors, uncomment this
# variable definition and use the format specified.
#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Lars P M</em:contributor> <em:contributor>Stefan Hermes</em:contributor> <em:contributor>Mikael Hedberg</em:contributor> <em:contributor>Hasse Wallanger</em:contributor>

#unfilter emptyLines
