[package]
name = "mozprofile"
version = "0.6.0"
authors = ["Mozilla"]
description = "Library for working with Mozilla profiles."
repository = "https://hg.mozilla.org/mozilla-central/file/tip/testing/mozbase/rust/mozprofile"
license = "MPL-2.0"
edition = "2018"

[dependencies]
tempfile = "3"
