# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

rights-title = Пра вашы правы
rights-intro = { -brand-full-name } – свабоднае праграмнае забеспячэнне з адкрытым зыходным кодам, створанае шматлюднай сусветнай супольнасцю. Вам будзе цікава ведаць:
rights-intro-point-1 = { -brand-short-name } даступны вам згодна з умовамі <a data-l10n-name="mozilla-public-license-link">Публічнай Ліцэнзіі Mozilla</a>. Яна дазваляе вам выкарыстоўваць, капіяваць і распаўсюджваць { -brand-short-name }.  Вы таксама можаце змяняць зыходны код { -brand-short-name } для задавальнення вашых патрэбаў. Публічная Ліцэнзія Mozilla дазваляе вам распаўсюджваць вашы змененыя версіі.
rights-intro-point-2 = Вам не прадстаўляюцца ніякія правы ці дазволы на гандлёвыя маркі Mozilla Foundation або іншых бакоў, уключаючы, без абмежавання, назву і эмблему Firefox. Дадатковыя звесткі пра гандлёвыя маркі можна знайсці <a data-l10n-name="mozilla-trademarks-link">тут</a>.
rights-intro-point-3 = Асобныя магчымасці { -brand-short-name }, такія як паведамляльнік пра крахі, даюць вам магчымасць даслаць водгук у { -vendor-short-name }. Дасылаючы водгук, вы даяце { -vendor-short-name } дазвол выкарыстоўваць гэты водгук для паляпшэння сваіх прадуктаў, публікаваць водгук на сваіх вэб-сайтах, і распаўсюджваць гэты водгук.
rights-intro-point-4 = Як мы выкарыстоўваем вашы асабістыя звесткі і водгукі, пададзеныя ў { -vendor-short-name } з { -brand-short-name }, апісана ў <a data-l10n-name="mozilla-privacy-policy-link">палітыцы прыватнасці { -brand-short-name }</a>.
rights-intro-point-4-unbranded = Усе прыдатныя палітыкі прыватнасці для гэтага прадукту павінны быць пералічаны тут.
rights-intro-point-5 = Асобныя магчымасці { -brand-short-name } ужываюць сеціўныя інфармацыйныя сэрвісы, аднак мы не гарантуем, што яны працуюць на 100% правільна і без памылак. Падрабязнасці, разам з звесткамі, як адключыць магчымасці, што выкарыстоўваюць гэтыя сэрвісы, можна знайсці ў <a data-l10n-name="mozilla-service-terms-link">умовах абслугоўвання</a>.
rights-intro-point-5-unbranded = Калі гэты прадукт уключае ў сябе вэб-сэрвісы, усе прыдатныя ўмовы абслугоўвання павінны мець спасылкі ў раздзеле <a data-l10n-name="mozilla-website-services-link">Сеціўныя сэрвісы</a> .
rights-intro-point-6 = Для прайгравання пэўных тыпаў відэакантэнту { -brand-short-name } сцягвае пэўныя плагіны расшыфроўкі кантэнту ад іншых вытворцаў.
rights-webservices-header = Сеткавыя звесткавыя службы { -brand-full-name }
rights-webservices = { -brand-full-name } выкарыстоўвае інфармацыйныя вэб-службы ("Службы") для забеспячэння некаторых функцый, якія даступныя вам для выкарыстання ў гэтай бінарнай версіі { -brand-short-name } на ўмовах, апісаных ніжэй. Калі вы не хочаце выкарыстоўваць адну ці больш з Службаў або ўмовы пагаднення непрымальныя, вы можаце адключыць гэту функцыю ці Службу(ы). Прадпісанні, у якіх апісваецца, як гэта зрабіць, можна адшукаць <a data-l10n-name="mozilla-disable-service-link">тут</a>. Іншыя асаблівасці і службы могуць быць забаронены ў наладах праграмы.
rights-safebrowsing = <strong>Бяспечнае агляданне: </strong>Адключаць функцыю бяспечнага аглядання не рэкамендуецца, бо ў выніку вы можаце патрапіць на небяспечныя сайты.  Калі вы хочаце адключыць гэту функцыю цалкам, зрабіце наступнае:
rights-safebrowsing-term-1 = Адкрыйце налады праграмы
rights-safebrowsing-term-2 = Выберыце раздзел "Бяспека"
rights-safebrowsing-term-3 = Зніміце сцяжок "{ enableSafeBrowsing-label }"
enableSafeBrowsing-label = Блакаваць небяспечнае і падманлівае змесціва
rights-safebrowsing-term-4 = Бяспечнае агляданне зараз забаронена
rights-locationawarebrowsing = <strong>Месцазалежнае агляданне: </strong>заўсёды неабавязковае.  Ніякія звесткі пра месцазнаходжанне не дасылаюцца без вашага дазволу.  Калі вы хочаце адключыць гэту магчымасць цалкам, зрабіце наступнае:
rights-locationawarebrowsing-term-1 = Набярыце ў адрасным радку <code>about:config</code>
rights-locationawarebrowsing-term-2 = Набярыце geo.enabled
rights-locationawarebrowsing-term-3 = Двойчы пстрыкніце перавагу geo.enabled
rights-locationawarebrowsing-term-4 = Месцазалежнае агляданне зараз забаронена
rights-webservices-unbranded = Агляд сеціўных сервісаў, якія ўключаны ў прадукт, разам з інструкцыямі, як адключыць гэтыя сервісы, калі гэта магчыма, павінны быць пералічаны тут.
rights-webservices-term-unbranded = Усе прыдатныя ўмовы пагаднення службаў гэтага прадукту павінны быць пералічаны тут.
rights-webservices-term-1 = { -vendor-short-name } і яго ўкладчыкі, ліцэнзіяты і ўдзельнікі працуюць над тым, каб забяспечыць найбольш дакладныя і сучасныя службы.  Аднак мы не можам паручыцца, што гэтыя звесткі вычарпальныя і ў іх адсутнічаюць хібы.  Напрыклад, служба бяспечнага аглядання можа не вызначаць асобныя сайты як небяспечныя і вызначаць такімі асобныя бяспечныя сайты памылкова, служба месцазалежнага аглядання карыстаецца месцазнаходжаннямі, якія нашы дастаўшчыкі даюць прыблізна, і ні мы, ні нашы дастаўшчыкі не гарантуюць дакладнасць месцазнаходжанняў.
rights-webservices-term-2 = { -vendor-short-name } можа самастойна перастаць карыстацца службай ці змяніць яе.
rights-webservices-term-3 = Вы можаце карыстацца гэтымі службамі разам з дадзенай версіяй  { -brand-short-name }, вы маеце ўсе неабходныя правы. { -vendor-short-name } і ўсе ліцэнзіяты захоўваюць за сабой усе іншыя правы Службаў. Гэтыя ўмовы пагадненняў не абмяжоўваюць правоў, якія дадзеныя ліцэнзіямі адкрытых зыходнікаў, прыдатных для { -brand-short-name } і адпаведных версіяў зыходнага кода { -brand-short-name }.
rights-webservices-term-4 = <strong>Паслугі прадастаўляюцца "як ёсць"  { -vendor-short-name }, яго супрацоўнікі, ліцэнзіяры і дыстрыб'ютары адмаўляюцца ад усіх гарантыйных абавязкаў, відавочных і няяўных, а таксама не даюць гарантый таго, што паслугі застаюцца прыгоднымі для продажу і адпавядаюць вашым мэтам.  Вы бераце на сябе ўсю рызыку як па выбары паслуг для сябе, так і па якасці і эфектыўнасці паслуг. Некаторыя юрысдыкцыі не дапускаюць выключэнне або абмежаванне гарантыйных абавязкаў, таму гэта адмова можа вас не тычыцца.</strong>
rights-webservices-term-5 = <strong>Except as required by law, { -vendor-short-name }, its contributors, licensors, and distributors will not be liable for any indirect, special, incidental, consequential, punitive, or exemplary damages arising out of or in any way relating to the use of { -brand-short-name } and the Services.  The collective liability under these terms will not exceed $500 (five hundred dollars). Some jurisdictions do not allow the exclusion or limitation of certain damages, so this exclusion and limitation may not apply to you.</strong>
rights-webservices-term-6 = { -vendor-short-name } можа абнаўляць гэтыя ўмовы пагаднення час ад часу, калі гэта будзе неабходна. Гэтыя ўмовы не могуць быць зменены або скасованы без пісьмовага дазволу { -vendor-short-name }.
rights-webservices-term-7 = These terms are governed by the laws of the state of California, U.S.A., excluding its conflict of law provisions. If any portion of these terms is held to be invalid or unenforceable, the remaining portions will remain in full force and effect. In the event of a conflict between a translated version of these terms and the English language version, the English language version shall control.
