# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with

# your locale code, and link to your translated pages as soon as they're

# live.


#define bookmarks_title Boekmerke


#define bookmarks_heading Boekmerke


#define bookmarks_toolbarfolder Boekmerknutsbalk-vouer


#define bookmarks_toolbarfolder_description Voeg boekmerke by hierdie vouer om hulle in die Boekmerknutsbalk te sien


# LOCALIZATION NOTE (getting_started):


# link title for https://www.mozilla.org/en-US/firefox/central/


#define getting_started Hoe om te begin


# LOCALIZATION NOTE (firefox_heading):


# Firefox links folder name


#define firefox_heading Mozilla Firefox


# LOCALIZATION NOTE (firefox_help):


# link title for https://www.mozilla.org/en-US/firefox/help/


#define firefox_help Hulp en tutoriale


# LOCALIZATION NOTE (firefox_customize):


# link title for https://www.mozilla.org/en-US/firefox/customize/


#define firefox_customize Doelmaak Firefox


# LOCALIZATION NOTE (firefox_community):


# link title for https://www.mozilla.org/en-US/contribute/


#define firefox_community Raak betrokke


# LOCALIZATION NOTE (firefox_about):


# link title for https://www.mozilla.org/en-US/about/


#define firefox_about Meer oor ons


# LOCALIZATION NOTE (nightly_heading):


# Firefox Nightly links folder name


#define nightly_heading Inligting oor Firefox Nightly


# LOCALIZATION NOTE (nightly_blog):


# Nightly builds only, link title for https://blog.nightly.mozilla.org/


#define nightly_blog Joernaal oor Firefox Nightly


# LOCALIZATION NOTE (bugzilla):


# Nightly builds only, link title for https://bugzilla.mozilla.org/


#define bugzilla Mozilla-foutdatabasis


# LOCALIZATION NOTE (mdn):


# Nightly builds only, link title for https://developer.mozilla.org/


#define mdn Mozilla-ontwikkelaarsnetwerk


# LOCALIZATION NOTE (nightly_tester_tools):


# Nightly builds only, link title for https://addons.mozilla.org/en-US/firefox/addon/nightly-tester-tools/


#define nightly_tester_tools Gereedskap vir Nightly-toetsers


# LOCALIZATION NOTE (crashes):


# Nightly builds only, link title for about:crashes


#define crashes Al die omvalverslae


# LOCALIZATION NOTE (irc):


# Nightly builds only, link title for ircs://irc.mozilla.org/nightly


#define irc Bespreek Nightly op IRC


# LOCALIZATION NOTE (planet):


# Nightly builds only, link title for https://planet.mozilla.org/


#define planet Mozilla-planeet


#unfilter emptyLines
