# -*- Mode: python; indent-tabs-mode: nil; tab-width: 40 -*-
# vim: set filetype=python:
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

Classes = [
    {
        'cid': '{2d9e9d0d-8c4d-4f9f-84b0-0ce9fe3f6c1a}',
        'contract_ids': ['@waterfox.com/waterfox-blocker-engine;1'],
        'legacy_constructor': 'waterfox_blocker_xpcom_constructor',
        'headers': ['/waterfox/browser/components/blocker/WaterfoxBlockerXPCOM.h'],
    },
    {
        'cid': '{5f4bca75-36bb-4de4-9261-c20354216f25}',
        'contract_ids': ['@waterfox.com/waterfox-blocker-content-policy;1'],
        'type': 'WaterfoxBlockerContentPolicy',
        'headers': ['/waterfox/browser/components/blocker/WaterfoxBlockerXPCOM.h'],
        'processes': ProcessSelector.MAIN_PROCESS_ONLY,
        'categories': {'content-policy': '@waterfox.com/waterfox-blocker-content-policy;1'},
    },
]
