#filter emptyLines

#define MOZ_LANGPACK_CREATOR mozfr.org

# If non-English locales wish to credit multiple contributors, uncomment this
# variable definition and use the format specified.
#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Frédéric Chateaux</em:contributor><em:contributor>Théo Chevalier</em:contributor><em:contributor>François Constantineau</em:contributor><em:contributor>Cédric Corazza</em:contributor><em:contributor>Philippe Dessante</em:contributor><em:contributor>Hugues Fournier</em:contributor><em:contributor>Marie Léger-Saint-Jean</em:contributor><em:contributor>Benoit Leseul</em:contributor><em:contributor>Alexandre Lissy</em:contributor><em:contributor>Jean-Bernard Marcon</em:contributor>

#unfilter emptyLines
