#filter emptyLines

#define MOZ_LANGPACK_CREATOR The ChatZilla Team

#define MOZ_LANGPACK_HOMEPAGE http://chatzilla.hacksrus.com/

# If non-English locales wish to credit multiple contributors, uncomment this
# variable definition and use the format specified.
#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Carlos Simão</em:contributor> <em:contributor>João Miguel Neves</em:contributor> 

#unfilter emptyLines
