.TH WATERFOX 1 "June 2026" "Waterfox" "Waterfox Manual"
.SH NAME
waterfox \- a privacy conscious web browser
.SH SYNOPSIS
.B waterfox
[\fIOPTIONS\fR] [\fIURL\fR]
.SH DESCRIPTION
Waterfox is a customizable, privacy conscious web browser based on Firefox.
.SH OPTIONS
.TP
.B \-\-new\-window \fIURL\fR
Open \fIURL\fR in a new window.
.TP
.B \-\-private\-window \fIURL\fR
Open \fIURL\fR in a new private window.
.TP
.B \-\-ProfileManager
Start with the profile manager.
.PP
For the full list of options, run \fBwaterfox \-\-help\fR.
.SH FILES
.TP
.I /usr/lib/waterfox
The Waterfox installation directory.
.SH BUGS
Report issues at https://github.com/BrowserWorks/Waterfox/issues.
.SH SEE ALSO
.I https://www.waterfox.net/
