# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

rights-title = Tocante a los tos drechos
rights-intro = { -brand-full-name } ye llibre y de códigu abiertu, fechu por una comunidá de milenta de persones de tol mundu. Hai delles coses que deberíes saber:
rights-intro-point-1 = { -brand-short-name } ta disponible pa ti so los términos de la <a data-l10n-name="mozilla-public-license-link">Mozilla Public License</a>. Esto quier dicir que podríes usar, copiar y distribuyir { -brand-short-name } a otros. Tamién pues camudar el códigu fonte de { -brand-short-name } tolo que te pete p'adautalu a les tos necesidaes. La Mozilla Public License tamién te da drechu a distribuyir les versiones que modifiques.
rights-intro-point-3 = Delles carauterístiques en { -brand-short-name }, como por exemplu l'informador de casques, dante la opción d'apurrir comentarios a { -vendor-short-name }. Escoyendo unvialu, das-y a { -vendor-short-name } permisu pa usar les opiniones p'ameyorar los sos productos, pa espublizalu nos sos sitios web y pa distribuyilu.
rights-intro-point-4 = El mou nel qu'usamos la to información personal y les opiniones unviaes a { -vendor-short-name } pente { -brand-short-name } descríbese na <a data-l10n-name="mozilla-privacy-policy-link">Política de privacidá de { -brand-short-name }</a>.
rights-intro-point-5 = Delles carauterístiques de { -brand-short-name } usen servicios d'información basaos na web; por embargu, nun podemos garantizar que seyan 100% precisos nin llibres de fallos. Pues alcontrar más detalles, incluyendo información tocante a cómo desactivar les carauterístiques qu'usen estos servicios, nos <a data-l10n-name="mozilla-service-terms-link">términos del serviciu</a>.
rights-intro-point-5-unbranded = Si esti productu incorpora servicios web, cualesquier términu de serviciu aplicable al serviciu (o servicios) deberíen enllazase en <a data-l10n-name="mozilla-website-services-link">Servicios de sitiu web</a> seición.
rights-intro-point-6 = Pa reproducir ciertes tribes de conteníu de videu, { -brand-short-name } baxa ciertos módulos de descifráu de conteníu dende terceres partes.
rights-webservices-header = Servicios d'información de { -brand-full-name } basaos na web
rights-webservices = { -brand-full-name }{ -brand-full-name } usa servicios d'información basaos na web («Servicios») pa fornir delles carauterístiques apurríes pol to usu con esta versión binaria de { -brand-short-name } so los términos descritos embaxo. Si nun quies usar ún o más de los servicios, o los términos d'embaxo son inaceutables, quiciabes quieras desactivar la carauterística serviciu(os). Podríes alcontrar les instrucciones en cómo desactivar la carauterística o serviciu <a data-l10n-name="mozilla-disable-service-link">equí</a>. Otres carauterístiques y servicios puen desactivase nes preferencies de l'aplicación.
rights-locationawarebrowsing = <strong>Restolar según l'allugamientu: </strong>siempres son a eleición del usuariu.   Enxamás s'unvia información d'allugamientu ensin el to permisu.  Si desees desactivar dafechu la carauterística, sigui estos pasos:
rights-locationawarebrowsing-term-1 = Na barra de direiciones, teclexa <code>about:config</code>
rights-locationawarebrowsing-term-2 = Teclexa geo.enabled
rights-locationawarebrowsing-term-3 = Fai clic doblu na preferencia geo.enabled
rights-locationawarebrowsing-term-4 = Agora'l restolar según l'allugamientu ta desactiváu
rights-webservices-unbranded = Un vistazu xeneral de los servicios web qu'inclúi'l productu, xunto colos instrucciones tocante a cómo desactivales si ye posible.
rights-webservices-term-unbranded = Equí debería llistase cualesquier términu de serviciu aplicable a esti productu.
rights-webservices-term-1 = { -vendor-short-name } y los sos collaboradores, llicenciatarios y socios trabayen p'apurrir los servicios más precisos y anovaos. Sicasí, nun podemos garantizar qu'esta información seya completa y tea llibre d'errores. Por exemplu, el serviciu de navegación segura pue que nun identifique dalgunos sitios peligrosos y pue qu'identifique dalgunos sitios seguros por error y les direiciones devueltes polos nuesos fornidores del serviciu de navegación basada na llocalización son namái estimaciones y nin nosotros nin los nuesos fornidores garantizamos la exactitú de les llocalizaciones proporcionaes.
rights-webservices-term-2 = { -vendor-short-name } pue dexar de suministrar, o camudar, los Servicios a discreción.
rights-webservices-term-3 = Pues usar estos servicios cola versión correspondiente de { -brand-short-name }, y { -vendor-short-name } date derechos pa facelo. { -vendor-short-name } y los sos llicenciatarios resérvense'l restu de derechos de los servicios. Estos términos nun llimiten dengún derechu dau poles llicencies de códigu abiertu aplicables a { -brand-short-name } y les versiones del códigu fonte correspondiente de { -brand-short-name }.
rights-webservices-term-4 = <strong>Los Servicios proporciónense "tal cual". { -vendor-short-name }, los sos contribuyentes, llicenciadores y distribuidores refuguen toa responsabilidá, explícita o implícita, incluyendo (ensin llimitación) la garantía de que los Servicios son comerciales y s'adauten a los tos envises particulares. Tú lleves la totalidá del riesgu al seleicionar los Servicios pa los tos envises y sobre la calidá y les prestaciones de los Servicios. Dalgunes xurisdicciones nun permiten la exclusión o llimitación de les garantíes implícites, polo que ye dable qu'esta renuncia de responsabilidá nun seya d'aplicación nel to casu.</strong>
rights-webservices-term-5 = <strong>Coles esceiciones espresaes pola llei, nin { -vendor-short-name }, nin los sos contribuyentes, llicenciadores y distribuidores fáense responsables de dengún dañu indireutu, especial, incidental, consecuente, punitivu o exemplar darréu de, o de dalguna forma rellacionao col usu de { -brand-short-name } y los Servicios. La responsabilidá colectiva sobre estos términos nun escederán de $500 (quinientos dólares). Dalgunes xurisdicciones nun permiten la exclusión o llimitación de ciertos daños, polo que pue qu'esta exclusión y llimitación nun seya d'aplicación nel to casu.</strong>
rights-webservices-term-6 = { -vendor-short-name } pue anovar estos términos dalcuando, de precisalo. Quiciabes nun se modifiquen o encaboxen ensin l'alcuerdu escritu de { -vendor-short-name }.
rights-webservices-term-7 = Estos términos tán regulaos poles lleis del Estáu de California, EE.UU., a esceición de les disposiciones llegales coles qu'entre en conflictu. Si dalguna parte d'estos términos se consideren non válidos o inaplicables, les partes restantes caltendrán tola so potencia y efeutos. el casu d'un conflictu ente una versión traducía d'estos términos y la versión en llingua inglesa, esta cabera, tendrá prioridá.
