# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with

# your locale code, and link to your translated pages as soon as they're

# live.


#define bookmarks_title نشانک‌ها


#define bookmarks_heading نشانک‌ها


#define bookmarks_toolbarfolder پوشهٔ نوار ابزار نشانک‌ها


#define bookmarks_toolbarfolder_description نشانک‌های این پوشه در «نوار ابزار نشانک‌ها» نمایش داده خواهند شد


# LOCALIZATION NOTE (getting_started):


# link title for https://www.mozilla.org/en-US/firefox/central/


#define getting_started چگونه شروع کنم


# LOCALIZATION NOTE (firefox_heading):


# Firefox links folder name


#define firefox_heading موزیلا فایرفاکس


# LOCALIZATION NOTE (firefox_help):


# link title for https://www.mozilla.org/en-US/firefox/help/


#define firefox_help راهنما و برنامه‌های آموزشی


# LOCALIZATION NOTE (firefox_customize):


# link title for https://www.mozilla.org/en-US/firefox/customize/


#define firefox_customize سفارشی‌سازی فایرفاکس


# LOCALIZATION NOTE (firefox_community):


# link title for https://www.mozilla.org/en-US/contribute/


#define firefox_community مشارکت کردن


# LOCALIZATION NOTE (firefox_about):


# link title for https://www.mozilla.org/en-US/about/


#define firefox_about دربارهٔ ما


# LOCALIZATION NOTE (nightly_heading):


# Firefox Nightly links folder name


#define nightly_heading منابع فایرفاکس نایتلی


# LOCALIZATION NOTE (nightly_blog):


# Nightly builds only, link title for https://blog.nightly.mozilla.org/


#define nightly_blog وبلاگ فایرفاکس نایتلی


# LOCALIZATION NOTE (bugzilla):


# Nightly builds only, link title for https://bugzilla.mozilla.org/


#define bugzilla سیستم مدیریت خطاهای موزیلا


# LOCALIZATION NOTE (mdn):


# Nightly builds only, link title for https://developer.mozilla.org/


#define mdn شبکه توسعه‌دهندگان موزیلا


# LOCALIZATION NOTE (nightly_tester_tools):


# Nightly builds only, link title for https://addons.mozilla.org/en-US/firefox/addon/nightly-tester-tools/


#define nightly_tester_tools ابزارهای آزمایش نایتلی


# LOCALIZATION NOTE (crashes):


# Nightly builds only, link title for about:crashes


#define crashes تمام فروپاشی‌های شما


# LOCALIZATION NOTE (irc):


# Nightly builds only, link title for ircs://irc.mozilla.org/nightly


#define irc گفتگو در مورد نایتلی در IRC


# LOCALIZATION NOTE (planet):


# Nightly builds only, link title for https://planet.mozilla.org/


#define planet سیاره موزیلا


#unfilter emptyLines
