# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

rights-title = Om dine rettigheder
rights-intro = { -brand-full-name } er software med fri og åben kildekode, skabt af en sammenslutning af tusindvis af mennesker over hele kloden. Der er et par ting, som du bør vide:
rights-intro-point-1 = { -brand-short-name } gøres tilgængelig for dig under retningslinjerne i <a data-l10n-name="mozilla-public-license-link">Mozilla Public License</a>. Dette betyder at du må bruge, kopiere og videregive { -brand-short-name } til andre. Du er er også velkommen til at ændre i kildekoden til { -brand-short-name } for at opfylde dine behov. Mozilla Public License tildeler dig også retten til at videregive dine ændrede versioner.
rights-intro-point-2 = Du tildeles ikke nogen rettigheder eller licens til varemærker tilhørende Mozilla Foundation eller tredjepartier, herunder (uden undtagelse) produktet Firefox og dets tilhørende logo. Yderligere information om varemærker kan findes <a data-l10n-name="mozilla-trademarks-link">her</a>.
rights-intro-point-3 = Nogle funktioner i { -brand-short-name }, såsom Fejlrapportør, giver dig mulighed for at give feedback til  { -vendor-short-name }. Ved at vælge at sende feedback giver du { -vendor-short-name } tilladelse til at bruge de givne informationer til at forbedre deres produkter, offenliggøre disse på deres webside(r) samt at videredistribuere disse frit.
rights-intro-point-4 = Hvordan vi bruger dine personlige oplysninger og indsendt feedback til { -vendor-short-name } med  { -brand-short-name } er beskrevet i <a data-l10n-name="mozilla-privacy-policy-link">{ -brand-short-name } Privatlivspolitik</a>.
rights-intro-point-4-unbranded = Alle relevante privatlivspolitikker for dette produkt bør være beskrevet her.
rights-intro-point-5 = Nogle { -brand-short-name } funktioner gør brug af webbaserede informationstjenester, men vi kan ikke garantere at de er 100% korrekte eller fejlfrie. Yderligere detaljer, inklusiv information om at deaktivere disse tjenester, kan findes under punktet <a data-l10n-name="mozilla-service-terms-link">tjenstevilkår</a>.
rights-intro-point-5-unbranded = Hvis dette produkt bruger webbaserede tjenester skal alle vedkommende vilkår for tjenesterne linkes til under afsnittet <a data-l10n-name="mozilla-website-services-link">Webbaserede tjenester</a>.
rights-intro-point-6 = For at kunne afspille visse typer af video skal { -brand-short-name } hente dekrypteringsmoduler fra tredjepart.
rights-webservices-header = { -brand-full-name } webbaserede informationstjenester
rights-webservices = { -brand-full-name } bruger webbaserede informationstjenester ("Tjenester") som gøres tilgængelig for dig ved brug af denne binære version af { -brand-short-name } som beskrevet i de nedenstående vilkår. Hvis du ikke ænsker at bruge en eller flere af disse tjenester, eller hvis du ikke kan tilslutte dig de nedenstående vilkår, kan du deaktivere funktionen eller tjenesten. Instruktioner til at deaktivere en given funktion eller tjeneste kan findes <a data-l10n-name="mozilla-disable-service-link">her</a>. Andre funktioner og tjenester kan deaktiveres i indstillingerne.
rights-safebrowsing = <strong>SafeBrowsing: </strong>Deaktivering af Safe Browsing funktionen er ikke anbefalet da det kan resultere i at du besøger usikre websteder. Hvis du ønsker at deaktivere denne funktion fuldstændigt, kan dette gøres ved følgene trin:
rights-safebrowsing-term-1 = Åbn programmets indstillinger
rights-safebrowsing-term-2 = Vælg gruppen Sikkerhed
rights-safebrowsing-term-3 = Fjern markeringen for at "{ enableSafeBrowsing-label }"
enableSafeBrowsing-label = Bloker farlige og vildledende websteder
rights-safebrowsing-term-4 = Safe Browsing er nu deaktiveret
rights-locationawarebrowsing = <strong>Positionsbevidst browsing: </strong>Du bliver altid spurgt om du ønsker at dele din position. Din position bliver aldrig sendt uden dit samtykke. Hvis du ønsker at deaktivere denne funktion fuldstændigt kan det gøres ved følgende trin:
rights-locationawarebrowsing-term-1 = Skriv følgende i adressefeltet <code>about:config</code>
rights-locationawarebrowsing-term-2 = Tast geo.enabled
rights-locationawarebrowsing-term-3 = Dobbeltklik på geo.enabled præferencen
rights-locationawarebrowsing-term-4 = Positionsbevidt browsing er nu deaktiveret
rights-webservices-unbranded = Et overblik over de webbaserede tjenester, produktet bruger, samt instruktioner om, hvordan de deaktiveres (hvis muligt), skal inkluderes her.
rights-webservices-term-unbranded = Alle vedkommende tjenestevilkår for dette produkt bør optegnes her.
rights-webservices-term-1 = { -vendor-short-name } og dets bidragydere, licensholdere og forretningspartnere arbejder på at yde de mest korrekte og ajourførte tjenester. Vi kan dog ikke garantere at denne information er fyldestgørende eller fejlfri. Eksempelvis kan Safe Browsing-tjenesten ikke altid identificere risikofyldte websteder og kan tillige fejlagtigt blokere for sikre websteder. Ved positionsbevidst browsing vil positioner returneret af vores tjenesteudbydere kun være omtrentlige og vi garanterer ikke for præcisionen.
rights-webservices-term-2 = { -vendor-short-name } kan afslutte eller ændre tjenesten når de ønsker dette.
rights-webservices-term-3 = Det står dig frit for at bruge de i { -brand-short-name } medfølgende tjenester og { -vendor-short-name } giver dig rettighed til dette. { -vendor-short-name } og dets licensholdere forbeholder sig alle andre rettigheder vedrørende disse tjenester. Disse vilkår er ikke tiltænkt at begrænse rettigheder under åben kildekode licenser vedrørende { -brand-short-name } og de tilhørende kildekode versioner af { -brand-short-name }.
rights-webservices-term-4 = <strong>Tjenesten leveres "som den fremstår." { -vendor-short-name }, dets bidragydere, licensholdere og distributører fraskriver sig alle garantier, udtrykt eller indforstået, inklusive garantier om hvorvidt tjenesten er handelsgyldig eller passer til dit formål. Du bærer den fulde risiko ved at bruge tjenesten til dine formål samt kvaliteten og ydelsen, som tjenesten leverer. Nogle retskredse tillader ikke eksklusion eller begrænsning af indforståede garantier, så denne fraskrivelse af garanti kan i visse tilfælde ikke berøre dig.</strong>
rights-webservices-term-5 = <strong>Undtaget som lovpåkrævet vil { -vendor-short-name }, dets bidragydere, licensholdere og distributører ikke hæfte for nogen indirekte, specielle, incidentale, afledte, strafmæssige eller statutmæssige krav som opstår af, eller på nogen måde er relateret til brugen af { -brand-short-name } og dets tjenester. Den samlede hæfte under disse vilkår kan ikke overstige $500 (Femhundrede dollars USD). Nogle retskredse tillader ikke eksklusion eller begrænsning af hæfte/krav, så denne fraskrivelse af hæfte kan i visse tilfælde ikke berøre dig.</strong>
rights-webservices-term-6 = { -vendor-short-name } må fra tid til anden opdatere disse vilkår efter behov. Disse vilkår må ikke ændres eller annulleres uden skriftlig aftale med { -vendor-short-name }.
rights-webservices-term-7 = Disse vilkår styres af loven i Californien, U.S.A., dets conflict of law provisioner. Hvis dele af disse vilkår ikke har gyldighed eller kan opretholdes vil den resterende del stadig være fuld ud gyldig og vedstående. I tilfælde af tvist mellem en oversat version af disse vilkår og den engelske version skal den engelske version være den gældende.
