.TH SSH-KEYGEN 1 "September 25, 1999" ""
.SH NAME
\fBssh-keygen\fP
\- authentication key generation, management and conversion
.SH SYNOPSIS
.br
\fBssh-keygen\fP
[\fB\-q\fP]
[\fB\-b\fP \fIbits\fP]
\fB\-t\fP \fItype\fP
[\fB\-N\fP \fInew_passphrase\fP]
[\fB\-C\fP \fIcomment\fP]
[\fB\-f\fP \fIoutput_keyfile\fP]
.br
\fBssh-keygen\fP
\fB\-p\fP
[\fB\-P\fP \fIold_passphrase\fP]
[\fB\-N\fP \fInew_passphrase\fP]
[\fB\-f\fP \fIkeyfile\fP]
.br
\fBssh-keygen\fP
\fB\-i\fP
[\fB\-f\fP \fIinput_keyfile\fP]
.br
\fBssh-keygen\fP
\fB\-e\fP
[\fB\-f\fP \fIinput_keyfile\fP]
.br
\fBssh-keygen\fP
\fB\-y\fP
[\fB\-f\fP \fIinput_keyfile\fP]
.br
\fBssh-keygen\fP
\fB\-c\fP
[\fB\-P\fP \fIpassphrase\fP]
[\fB\-C\fP \fIcomment\fP]
[\fB\-f\fP \fIkeyfile\fP]
.br
\fBssh-keygen\fP
\fB\-l\fP
[\fB\-f\fP \fIinput_keyfile\fP]
.br
\fBssh-keygen\fP
\fB\-B\fP
[\fB\-f\fP \fIinput_keyfile\fP]
.br
\fBssh-keygen\fP
\fB\-D\fP \fIreader\fP
.br
\fBssh-keygen\fP
\fB\-F\fP \fIhostname\fP
[\fB\-f\fP \fIknown_hosts_file\fP]
.br
\fBssh-keygen\fP
\fB\-H\fP
[\fB\-f\fP \fIknown_hosts_file\fP]
.br
\fBssh-keygen\fP
\fB\-R\fP \fIhostname\fP
[\fB\-f\fP \fIknown_hosts_file\fP]
.br
\fBssh-keygen\fP
\fB\-U\fP \fIreader\fP
[\fB\-f\fP \fIinput_keyfile\fP]
.br
\fBssh-keygen\fP
\fB\-r\fP \fIhostname\fP
[\fB\-f\fP \fIinput_keyfile\fP]
[\fB\-g\fP]
.br
\fBssh-keygen\fP
\fB\-G\fP \fIoutput_file\fP
[\fB\-v\fP]
[\fB\-b\fP \fIbits\fP]
[\fB\-M\fP \fImemory\fP]
[\fB\-S\fP \fIstart_point\fP]
.br
\fBssh-keygen\fP
\fB\-T\fP \fIoutput_file\fP
\fB\-f\fP \fIinput_file\fP
[\fB\-v\fP]
[\fB\-a\fP \fInum_trials\fP]
[\fB\-W\fP \fIgenerator\fP]
.SH DESCRIPTION
\fBssh-keygen\fP
generates, manages and converts authentication keys for
\fBssh\fP(1).
\fBssh-keygen\fP
can create RSA keys for use by SSH protocol version 1 and RSA or DSA
keys for use by SSH protocol version 2.
The type of key to be generated is specified with the
\fB\-t\fP
option.
If invoked without any arguments,
\fBssh-keygen\fP
will generate an RSA key for use in SSH protocol 2 connections.

\fBssh-keygen\fP
is also used to generate groups for use in Diffie-Hellman group
exchange (DH-GEX).
See the
.B MODULI GENERATION
section for details.

Normally each user wishing to use SSH
with RSA or DSA authentication runs this once to create the authentication
key in
\fI~/.ssh/identity\fP,
\fI~/.ssh/id_dsa\fP
or
\fI~/.ssh/id_rsa\fP.
Additionally, the system administrator may use this to generate host keys,
as seen in
\fI/etc/rc\fP.

Normally this program generates the key and asks for a file in which
to store the private key.
The public key is stored in a file with the same name but
``.pub''
appended.
The program also asks for a passphrase.
The passphrase may be empty to indicate no passphrase
(host keys must have an empty passphrase), or it may be a string of
arbitrary length.
A passphrase is similar to a password, except it can be a phrase with a
series of words, punctuation, numbers, whitespace, or any string of
characters you want.
Good passphrases are 10-30 characters long, are
not simple sentences or otherwise easily guessable (English
prose has only 1-2 bits of entropy per character, and provides very bad
passphrases), and contain a mix of upper and lowercase letters,
numbers, and non-alphanumeric characters.
The passphrase can be changed later by using the
\fB\-p\fP
option.

There is no way to recover a lost passphrase.
If the passphrase is
lost or forgotten, a new key must be generated and copied to the
corresponding public key to other machines.

For RSA1 keys,
there is also a comment field in the key file that is only for
convenience to the user to help identify the key.
The comment can tell what the key is for, or whatever is useful.
The comment is initialized to
``user@host''
when the key is created, but can be changed using the
\fB\-c\fP
option.

After a key is generated, instructions below detail where the keys
should be placed to be activated.

The options are as follows:
.TP
\fB\-a\fP \fItrials\fP
Specifies the number of primality tests to perform when screening DH-GEX
candidates using the
\fB\-T\fP
command.
.TP
\fB\-B\fP
Show the bubblebabble digest of specified private or public key file.
.TP
\fB\-b\fP \fIbits\fP
Specifies the number of bits in the key to create.
For RSA keys, the minimum size is 768 bits and the default is 2048 bits.
Generally, 2048 bits is considered sufficient.
DSA keys must be exactly 1024 bits as specified by FIPS 186-2.
.TP
\fB\-C\fP \fIcomment\fP
Provides a new comment.
.TP
\fB\-c\fP
Requests changing the comment in the private and public key files.
This operation is only supported for RSA1 keys.
The program will prompt for the file containing the private keys, for
the passphrase if the key has one, and for the new comment.
.TP
\fB\-D\fP \fIreader\fP
Download the RSA public key stored in the smartcard in
\fIreader\fP.
.TP
\fB\-e\fP
This option will read a private or public OpenSSH key file and
print the key in
RFC 4716 SSH Public Key File Format
to stdout.
This option allows exporting keys for use by several commercial
SSH implementations.
.TP
\fB\-F\fP \fIhostname\fP
Search for the specified
\fIhostname\fP
in a
\fIknown_hosts\fP
file, listing any occurrences found.
This option is useful to find hashed host names or addresses and may also be
used in conjunction with the
\fB\-H\fP
option to print found keys in a hashed format.
.TP
\fB\-f\fP \fIfilename\fP
Specifies the filename of the key file.
.TP
\fB\-G\fP \fIoutput_file\fP
Generate candidate primes for DH-GEX.
These primes must be screened for
safety (using the
\fB\-T\fP
option) before use.
.TP
\fB\-g\fP
Use generic DNS format when printing fingerprint resource records using the
\fB\-r\fP
command.
.TP
\fB\-H\fP
Hash a
\fIknown_hosts\fP
file.
This replaces all hostnames and addresses with hashed representations
within the specified file; the original content is moved to a file with
a .old suffix.
These hashes may be used normally by
\fBssh\fP
and
\fBsshd\fP,
but they do not reveal identifying information should the file's contents
be disclosed.
This option will not modify existing hashed hostnames and is therefore safe
to use on files that mix hashed and non-hashed names.
.TP
\fB\-i\fP
This option will read an unencrypted private (or public) key file
in SSH2-compatible format and print an OpenSSH compatible private
(or public) key to stdout.
\fBssh-keygen\fP
also reads the
RFC 4716 SSH Public Key File Format.
This option allows importing keys from several commercial
SSH implementations.
.TP
\fB\-l\fP
Show fingerprint of specified public key file.
Private RSA1 keys are also supported.
For RSA and DSA keys
\fBssh-keygen\fP
tries to find the matching public key file and prints its fingerprint.
.TP
\fB\-M\fP \fImemory\fP
Specify the amount of memory to use (in megabytes) when generating
candidate moduli for DH-GEX.
.TP
\fB\-N\fP \fInew_passphrase\fP
Provides the new passphrase.
.TP
\fB\-P\fP \fIpassphrase\fP
Provides the (old) passphrase.
.TP
\fB\-p\fP
Requests changing the passphrase of a private key file instead of
creating a new private key.
The program will prompt for the file
containing the private key, for the old passphrase, and twice for the
new passphrase.
.TP
\fB\-q\fP
Silence
\fBssh-keygen\fP.
Used by
\fI/etc/rc\fP
when creating a new key.
.TP
\fB\-R\fP \fIhostname\fP
Removes all keys belonging to
\fIhostname\fP
from a
\fIknown_hosts\fP
file.
This option is useful to delete hashed hosts (see the
\fB\-H\fP
option above).
.TP
\fB\-r\fP \fIhostname\fP
Print the SSHFP fingerprint resource record named
\fIhostname\fP
for the specified public key file.
.TP
\fB\-S\fP \fIstart\fP
Specify start point (in hex) when generating candidate moduli for DH-GEX.
.TP
\fB\-T\fP \fIoutput_file\fP
Test DH group exchange candidate primes (generated using the
\fB\-G\fP
option) for safety.
.TP
\fB\-t\fP \fItype\fP
Specifies the type of key to create.
The possible values are
``rsa1''
for protocol version 1 and
``rsa''
or
``dsa''
for protocol version 2.
.TP
\fB\-U\fP \fIreader\fP
Upload an existing RSA private key into the smartcard in
\fIreader\fP.
.TP
\fB\-v\fP
Verbose mode.
Causes
\fBssh-keygen\fP
to print debugging messages about its progress.
This is helpful for debugging moduli generation.
Multiple
\fB\-v\fP
options increase the verbosity.
The maximum is 3.
.TP
\fB\-W\fP \fIgenerator\fP
Specify desired generator when testing candidate moduli for DH-GEX.
.TP
\fB\-y\fP
This option will read a private
OpenSSH format file and print an OpenSSH public key to stdout.
.SH MODULI GENERATION
\fBssh-keygen\fP
may be used to generate groups for the Diffie-Hellman Group Exchange
(DH-GEX) protocol.
Generating these groups is a two-step process: first, candidate
primes are generated using a fast, but memory intensive process.
These candidate primes are then tested for suitability (a CPU-intensive
process).

Generation of primes is performed using the
\fB\-G\fP
option.
The desired length of the primes may be specified by the
\fB\-b\fP
option.
For example:

Dl # ssh-keygen -G moduli-2048.candidates -b 2048

By default, the search for primes begins at a random point in the
desired length range.
This may be overridden using the
\fB\-S\fP
option, which specifies a different start point (in hex).

Once a set of candidates have been generated, they must be tested for
suitability.
This may be performed using the
\fB\-T\fP
option.
In this mode
\fBssh-keygen\fP
will read candidates from standard input (or a file specified using the
\fB\-f\fP
option).
For example:

Dl # ssh-keygen -T moduli-2048 -f moduli-2048.candidates

By default, each candidate will be subjected to 100 primality tests.
This may be overridden using the
\fB\-a\fP
option.
The DH generator value will be chosen automatically for the
prime under consideration.
If a specific generator is desired, it may be requested using the
\fB\-W\fP
option.
Valid generator values are 2, 3, and 5.

Screened DH groups may be installed in
\fI/etc/moduli\fP.
It is important that this file contains moduli of a range of bit lengths and
that both ends of a connection share common moduli.
.SH FILES
.TP
.B ~/.ssh/identity
Contains the protocol version 1 RSA authentication identity of the user.
This file should not be readable by anyone but the user.
It is possible to
specify a passphrase when generating the key; that passphrase will be
used to encrypt the private part of this file using 3DES.
This file is not automatically accessed by
\fBssh-keygen\fP
but it is offered as the default file for the private key.
\fBssh\fP(1)
will read this file when a login attempt is made.
.TP
.B ~/.ssh/identity.pub
Contains the protocol version 1 RSA public key for authentication.
The contents of this file should be added to
\fI~/.ssh/authorized_keys\fP
on all machines
where the user wishes to log in using RSA authentication.
There is no need to keep the contents of this file secret.
.TP
.B ~/.ssh/id_dsa
Contains the protocol version 2 DSA authentication identity of the user.
This file should not be readable by anyone but the user.
It is possible to
specify a passphrase when generating the key; that passphrase will be
used to encrypt the private part of this file using 3DES.
This file is not automatically accessed by
\fBssh-keygen\fP
but it is offered as the default file for the private key.
\fBssh\fP(1)
will read this file when a login attempt is made.
.TP
.B ~/.ssh/id_dsa.pub
Contains the protocol version 2 DSA public key for authentication.
The contents of this file should be added to
\fI~/.ssh/authorized_keys\fP
on all machines
where the user wishes to log in using public key authentication.
There is no need to keep the contents of this file secret.
.TP
.B ~/.ssh/id_rsa
Contains the protocol version 2 RSA authentication identity of the user.
This file should not be readable by anyone but the user.
It is possible to
specify a passphrase when generating the key; that passphrase will be
used to encrypt the private part of this file using 3DES.
This file is not automatically accessed by
\fBssh-keygen\fP
but it is offered as the default file for the private key.
\fBssh\fP(1)
will read this file when a login attempt is made.
.TP
.B ~/.ssh/id_rsa.pub
Contains the protocol version 2 RSA public key for authentication.
The contents of this file should be added to
\fI~/.ssh/authorized_keys\fP
on all machines
where the user wishes to log in using public key authentication.
There is no need to keep the contents of this file secret.
.TP
.B /etc/moduli
Contains Diffie-Hellman groups used for DH-GEX.
The file format is described in
\fBmoduli\fP(5).
.SH SEE ALSO
\fBssh\fP(1),
\fBssh-add\fP(1),
\fBssh-agent\fP(1),
\fBmoduli\fP(5),
\fBsshd\fP(8)

, \fIThe Secure Shell (SSH) Public Key File Format\fP, 2006.
.SH AUTHORS
OpenSSH is a derivative of the original and free
ssh 1.2.12 release by Tatu Ylonen.
Aaron Campbell, Bob Beck, Markus Friedl, Niels Provos,
Theo de Raadt and Dug Song
removed many bugs, re-added newer features and
created OpenSSH.
Markus Friedl contributed the support for SSH
protocol versions 1.5 and 2.0.
