# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#filter emptyLines

#define MOZ_LANGPACK_CREATOR firefox.no

# If non-English locales wish to credit multiple contributors, uncomment this

# variable definition and use the format specified.

#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Vebjørn Sture</em:contributor> <em:contributor>Torstein Hønsi</em:contributor> <em:contributor>Kurt-Rune Bergset</em:contributor> <em:contributor>Ronny Vårdal</em:contributor> <em:contributor>Tom Ottar Røw</em:contributor> <em:contributor>Kristian Svanes</em:contributor> <em:contributor>Åsmund Skjæveland</em:contributor> <em:contributor>Erik Klepsvik</em:contributor> <em:contributor>Håvar Henriksen</em:contributor> <em:contributor>Håvard Mork</em:contributor> <em:contributor>Jan-Espen Pettersen</em:contributor> <em:contributor>Pascual Strømsnæs</em:contributor> <em:contributor>Bjørn I. Svindseth</em:contributor>

#unfilter emptyLines
