# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

rights-title = Acerca de sus derechos
rights-intro = { -brand-full-name } es software libre y de código abierto, creado por una comunidad de miles de personas a lo largo del mundo. Hay algunas cosas que debe saber:
rights-intro-point-1 = { -brand-short-name } está disponible bajo los términos de la <a data-l10n-name="mozilla-public-license-link">Licencia Pública de Mozilla (MPL)</a>. Esto significa que puede usar, copiar y compartir { -brand-short-name } con otras personas. También tiene la posibilidad de modificar el código fuente de { -brand-short-name } como desee a fin de que éste se ajuste a sus necesidades. La Licencia Pública de Mozilla también le otorga el derecho a distribuir esas versiones modificadas.
rights-intro-point-2 = No tiene concedido ningún derecho de marca o licencia sobre las marcas registradas de Mozilla Foundation o cualquier parte, incluyendo sin limitaciones el nombre y logo de Firefox. Puede encontrar información adicional sobre las marcas registradas <a data-l10n-name="mozilla-trademarks-link">aquí</a>.
rights-intro-point-3 = Algunas características de { -brand-short-name }, como el informe de errores, dan la oportunidad de dar su opinión a { -vendor-short-name }. Al elegir enviar su opinión, le da permiso a { -vendor-short-name } para usar esa opinión para mejorar sus productos, publicarla en sus sitios web y distribuirla.
rights-intro-point-4 = Cómo usaremos su información personal y las opiniones enviadas a  { -vendor-short-name } a través de { -brand-short-name } se describen en la <a data-l10n-name="mozilla-privacy-policy-link">política de privacidad de { -brand-short-name }</a>.
rights-intro-point-4-unbranded = Todas las políticas de privacidad aplicables para este producto deben enumerarse aquí.
rights-intro-point-5 = Algunas características de { -brand-short-name } hacen uso de servicios de información basados en la web, sin embargo, no podemos garantizar que sean 100% exactas o libres de errores. Más detalles, incluyendo información sobre como deshabilitar las características que usan estos servicios, pueden encontrarse en los <a data-l10n-name="mozilla-service-terms-link">términos del servicio</a>.
rights-intro-point-5-unbranded = Si este producto incorpora servicios web, cualquier término de servicio aplicable para los servicios debe ser enlazado a la sección del <a data-l10n-name="mozilla-website-services-link">sitio web del servicio.</a>
rights-intro-point-6 = Para poder reproducir ciertos tipos de contenido de video, { -brand-short-name } descarga ciertos módulos de descifrado de contenido desde terceros.
rights-webservices-header = Servicios de información basados en web de { -brand-full-name }
rights-webservices = { -brand-full-name } usa servicios de información basados en la web ("Servicios") para proveer algunas de las características que puede usar en esta versión binaria de { -brand-short-name } bajo los términos descriptos debajo. Si no quiere usar alguno de los servicios o los términos no son aceptables, puede deshabilitar las características o servicio(s). Las instrucciones sobre como deshabilitar una característica o servicio en particular pueden encontrarse <a data-l10n-name="mozilla-disable-service-link">aquí</a>. Otras funcionalidades y servicios pueden deshabilitarse en las preferencias de la aplicación.
rights-locationawarebrowsing = <strong>Navegación con ubicación geográfica: </strong>siempre es opcional.  Nunca se envía información de ubicación sin su permiso.  Si quiere deshabilitar esta característica por completo, siga estos pasos:
rights-locationawarebrowsing-term-1 = En la barra de direcciones ingrese <code>about:config</code>
rights-locationawarebrowsing-term-2 = Ingrese geo.enabled
rights-locationawarebrowsing-term-3 = Haga doble clic en la preferencia geo.enabled
rights-locationawarebrowsing-term-4 = La navegación con ubicación geográfica ahora está deshabilitada
rights-webservices-unbranded = Aquí debe incluirse un resumen de los servicios de sitios web que el producto incorpora, junto con instrucciones de cómo deshabilitarlas, en caso de ser necesario.
rights-webservices-term-unbranded = Cualquier término de servicio para este producto debe ser listado aquí.
rights-webservices-term-1 = { -vendor-short-name } y sus contribuyentes, licenciatarios y socios trabajan para proveer los servicios más actualizados y libres de errores.  Por ejemplo, el servicio de navegación segura puede no identificar algunos sitios riesgosos y puede identificar algunos sitios seguros por error y en el servicio de Location Aware, todas las ubicaciones devueltas por los proveedores del servicio son estimadas y ni nosotros ni el proveedor del servicio garantizan la exactitud de los lugares previstos.
rights-webservices-term-2 = { -vendor-short-name } puede discontinuar o cambiar los servicios según considere oportuno.
rights-webservices-term-3 = Puede usar estos servicios con esta versión de { -brand-short-name }, y { -vendor-short-name } le da los derechos para hacerlo. { -vendor-short-name } y sus licenciatarios se reservan todos los demás derechos en cuanto a los servicios. Estos términos no tienen la intención de limitar ningún derecho otorgado por una licencia de código abierto aplicable a { -brand-short-name } y las versiones correspondientes en base al código de { -brand-short-name }.
rights-webservices-term-4 = <strong>Los servicios son ofrecidos "tal como está."  { -vendor-short-name }, sus contribuyentes, licenciatarios y distribuidores rechazan toda clase de garantía, explícita o implícita, incluídas, sin perjuicio de lo antes mencionado, las garantías de que el servicio es comercializable y que cumple con sus necesidades particulares. Usted acepta el riesgo que implica seleccionar este servicio para su propósito así como a la calidad y el desempeño del servicio. Algunas jurisdicciones no permiten la exclusión o limitación de las garantías implícitas, por lo tanto, esta exención de responsabilidad puede no ser aplicable en su caso.</strong>
rights-webservices-term-5 = <strong>Excepto cuando sea obligatorio ante la Ley, { -vendor-short-name }, sus contribuyentes, licenciatarios y distribuidores no podrán ser responsables por ningún daño o perjuicio indirecto, especial, incidental, resultante, punitivo o ejemplar relacionado con el uso de { -brand-short-name } y los servicios. La responsabilidad colectiva bajo estos términos no podrá exceder los U$S500 (quinientos dólares estadounidenses). Algunas jurisdicciones no permiten la exclusión o limitación de ciertos daños, Por consiguiente que esta exclusión y limitación puede no ser aplicable en su caso.</strong>
rights-webservices-term-6 = De ser necesario, { -vendor-short-name } puede actualizar estos términos en forma esporádica. Estos términos no pueden ser modificados o cancelados sin el consentimiento por escrito de { -vendor-short-name }.
rights-webservices-term-7 = Estos términos están regidos por las leyes del estado de California, EE.UU., excluyendo sus conflictos con otras estipulaciones de la ley. Si cualquier sección de estos términos no es válida o aplicable, las secciones restantes continuarán teniendo plena vigencia. En caso de existir un conflicto entre una versión traducida de estos términos y la versión en idioma inglés, la versión en inglés será la que tendrá validez.
