#filter emptyLines

#define MOZ_LANGPACK_CREATOR mozilla.org

# If non-English locales wish to credit multiple contributors, uncomment this

# variable definition and use the format specified.

#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>वसन्त कृष्ण श्रेष्ठ</em:contributor> <em:contributor>basanta.shrestha@gmail.com</em:contributor> <em:contributor>मदन पुरस्कार पुस्तकालय</em:contributor>

#unfilter emptyLines
