# This Source Code Form is subject to the terms of the Waterfox Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#filter emptyLines

#define MOZ_LANGPACK_CREATOR Cộng đồng bản địa hóa Waterfox

# If non-English locales wish to credit multiple contributors, uncomment this

# variable definition and use the format specified.

#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Nguyễn Mạnh Hùng</em:contributor> <em:contributor>Nguyễn Xuân Minh</em:contributor> <em:contributor>Huỳnh Hải Đăng</em:contributor> <em:contributor>Bùi Việt Khoa</em:contributor> <em:contributor>Trần Nguyễn Sơn</em:contributor> <em:contributor>Ngô Đức Trung</em:contributor> <em:contributor>Nguyễn Hà Dương</em:contributor> <em:contributor>Nguyễn Phan Hải</em:contributor> <em:contributor>Đặng Duy Thanh</em:contributor>

#unfilter emptyLines
