# This Source Code Form is subject to the terms of the Waterfox Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

rights-title = Az Ön jogai
rights-intro = A { -brand-full-name } ingyenes és nyílt forrású szoftver, amelyet világszerte több ezer ember fejleszt. Néhány dologról tudnia kell:
rights-intro-point-1 = A { -brand-short-name } a <a data-l10n-name="mozilla-public-license-link">Waterfox Public License</a> feltételei szerint lett közreadva. Ez azt jelenti, hogy a  { -brand-short-name } használható, másolható és terjeszthető. A { -brand-short-name } forráskódjának igény szerinti módosítása szintén megengedett. A Waterfox Public License megadja a jogot a módosított verziók terjesztésére is.
rights-intro-point-2 = Ön nem kapott jogot vagy felhatalmazást a védjegyek használatára sem a Waterfox Foundationtől, sem mástól, beleértve – de nem csak erre korlátozva – a Waterfox nevet és logót. A védjegyekről további információ <a data-l10n-name="mozilla-trademarks-link">itt</a> olvasható.
rights-intro-point-3 = A { -brand-short-name } egyes funkciói, például a Hibajelentő, lehetőséget ad a visszajelzésre a { -vendor-short-name } felé. A visszajelzés elküldésével Ön engedélyt ad a { -vendor-short-name } részére, hogy a visszajelzést a termékei fejlesztésére használja fel, a visszajelzést közzétegye a webhelyein, valamint a visszajelzést terjessze.
rights-intro-point-4 = A { -vendor-short-name } részére a { -brand-short-name } által beküldött személyes adatokat és visszajelzéseket a <a data-l10n-name="mozilla-privacy-policy-link">{ -brand-short-name } Adatvédelmi Irányelvek</a> szerint kezeljük.
rights-intro-point-4-unbranded = Itt kell felsorolni a termékben alkalmazott adatvédelmi irányelveket.
rights-intro-point-5 = A { -brand-short-name } webalapú információs szolgáltatásokat is nyújt, mindazonáltal nem garantálható, hogy ezek 100%-osan pontosak és hibamentesek. A szolgáltatások letiltásáról szóló információk a <a data-l10n-name="mozilla-service-terms-link">szolgáltatás feltételei</a> dokumentumban olvashatók.
rights-intro-point-5-unbranded = Ha ez a termék webes szolgáltatásokat is tartalmaz, akkor ezen szolgáltatások feltételei a <a data-l10n-name="mozilla-website-services-link">Webhely-információs szolgáltatások</a> szakaszban vannak hivatkozva.
rights-intro-point-6 = Bizonyos típusú videotartalmak lejátszásához a { -brand-short-name } tartalom-visszafejtési modulokat tölt le külső szolgáltatóktól.
rights-webservices-header = { -brand-full-name } webalapú információs szolgáltatások
rights-webservices = A { -brand-full-name } webalapú információs szolgáltatásokat („Szolgáltatások”) használ egyes funkciók megvalósítására. Ezek a Szolgáltatások a { -brand-short-name } bináris verziójával együtt érhetők el az alább leírt módon. Ha nem akarja használni a Szolgáltatásokat, illetve az alábbi feltételek elfogadhatatlanok, letilthatja a funkciót vagy a Szolgáltatásokat. Egy adott funkció vagy Szolgáltatás letiltásáról <a data-l10n-name="mozilla-disable-service-link">itt</a> található információ. Más funkciók és szolgáltatások az alkalmazás beállításaiban kapcsolhatók ki.
rights-safebrowsing = <strong>SafeBrowsing: </strong>A Safe Browsing (biztonságos böngészés) funkciót nem ajánlott letiltani, mert akkor nem biztonságos webhelyekre is eljuthat. Ha teljesen le akarja tiltani a funkciót, kövesse az alábbi lépéseket:
rights-safebrowsing-term-1 = Nyissa meg az alkalmazás beállítópaneljét.
rights-safebrowsing-term-2 = Válassza a Biztonság csoportot.
rights-safebrowsing-term-3 = Törölje a „{ enableSafeBrowsing-label }” beállítást
enableSafeBrowsing-label = Veszélyes és félrevezető tartalom blokkolása
rights-safebrowsing-term-4 = A Safe Browsing most le van tiltva.
rights-locationawarebrowsing = <strong>Location Aware Browsing: </strong>A helyfüggő böngészés nincs alapból bekapcsolva. Az engedélye nélkül nem kerül elküldésre semmilyen adat a tartózkodási helyéről. Ha teljesen le akarja tiltani a funkciót, kövesse az alábbi lépéseket:
rights-locationawarebrowsing-term-1 = A címsávba írja be: <code>about:config</code>
rights-locationawarebrowsing-term-2 = Írja be: geo.enabled
rights-locationawarebrowsing-term-3 = Kattintson duplán a geo.enabled beállításon.
rights-locationawarebrowsing-term-4 = A Location-Aware Browsing most le van tiltva.
rights-webservices-unbranded = Itt kell megadni az információkat a termékbe beépített webhely-információs szolgáltatásokról, beleértve letiltásuk módját.
rights-webservices-term-unbranded = Itt kell megadni a termékre vonatkozó szolgáltatási feltételeket.
rights-webservices-term-1 = A { -vendor-short-name }, a közreműködők, a licencadók és a partnerek azon dolgoznak, hogy a lehető legpontosabb és legfrissebb Szolgáltatásokat nyújtsák. Mindazonáltal nem garantáljuk, hogy ez az információ teljes és hibamentes. Például a Safe Browsing szolgáltatás nem feltétlenül azonosít egyes kockázatos webhelyeket, vagy tévedésből biztonságos webhelyre nem enged be, valamint a Location Aware szolgáltatás által visszaadott tartózkodási helyet a szolgáltatóink közlik, ezek csak becslések, és sem mi, sem a szolgáltatóink nem garantáljuk a megadott tartózkodási hely pontosságát.
rights-webservices-term-2 = A { -vendor-short-name } saját hatáskörében megszüntetheti vagy módosíthatja a Szolgáltatásokat.
rights-webservices-term-3 = Ön igénybe veheti ezeket a Szolgáltatásokat a { -brand-short-name } mellékelt verziójával, a { -vendor-short-name } ehhez minden jogot megad. A { -vendor-short-name } és licencadói minden más jogot fenntartanak a Szolgáltatásokkal kapcsolatban. Ezek a feltételek nem korlátozzák a { -brand-short-name } programra és a { -brand-short-name } forráskódjára alkalmazott nyílt forrású licencek által biztosított jogokat.
rights-webservices-term-4 = <strong>A Szolgáltatások „olyanok, amilyenek”. A { -vendor-short-name }, a közreműködők, a licencadók és a terjesztők minden garanciát elutasítanak, legyen az kifejezett vagy vélelmezett, beleértve, de nem erre korlátozva azt, hogy a Szolgáltatások hasznosak és megfelelnek a felhasználó céljainak. Teljes egészében a felhasználó viseli annak kockázatát, hogy a Szolgáltatásokat saját céljára igénybe veszi, és hogy a Szolgáltatások az adott minőségben és teljesítménnyel működnek. Egyes jogrendszerek nem teszik lehetővé a vélelmezett garanciák kizárását vagy korlátozását, tehát ez az elutasítás lehet, hogy Önre nem vonatkozik.</strong>
rights-webservices-term-5 = <strong>Ha a törvény másképp nem rendelkezik, a { -vendor-short-name }, a közreműködők, a licencadók és a terjesztők nem felelnek semmilyen közvetlen, különleges, következményes, büntetőjogi vagy példamutató kárért, amely a { -brand-short-name } és a Szolgáltatások használatából következett, vagy azzal bármilyen módon összefüggésbe hozható. A kollektív felelősség ezen feltételek szerint nem haladja meg az 500 (ötszáz) USA-dollárt. Egyes jogrendszerek nem teszik lehetővé bizonyos károk kizárását vagy korlátozását, tehát ez a kizárás és korlátozás lehet, hogy Önre nem vonatkozik.</strong>
rights-webservices-term-6 = A { -vendor-short-name } időről időre frissítheti ezeket a feltételeket, ha szükségesnek látja. Ezek a feltételek nem módosíthatók vagy érvényteleníthetők a { -vendor-short-name } írásos beleegyezése nélkül.
rights-webservices-term-7 = A feltételekre Kalifornia (USA) állam törvényei vonatkoznak, kivéve ha ütközik helyi jogszabályokkal. Ha a feltételek egyes részei érvénytelenek vagy nem kikényszeríthetők, a többi rész attól még teljes mértékben érvényes és hatályos. Ha a feltételek lefordított változata ellentmond az angol változatnak, akkor az angol változat az irányadó.
