# This Source Code Form is subject to the terms of the Waterfox Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

rights-title = Over uw rechten
rights-intro = { -brand-full-name } is vrije en opensourcesoftware, gebouwd door een gemeenschap van duizenden mensen over de hele wereld. Er zijn een paar zaken die u moet weten:
rights-intro-point-1 = { -brand-short-name } wordt beschikbaar gesteld onder de voorwaarden van de <a data-l10n-name="mozilla-public-license-link">Waterfox Public License</a>. Dit betekent dat u { -brand-short-name } mag gebruiken, kopiëren en naar anderen mag distribueren. Ook mag u de broncode van { -brand-short-name } modificeren naar een vorm die aan uw eisen voldoet. De Waterfox Public License geeft u tevens het recht uw aangepaste versies te distribueren.
rights-intro-point-2 = Er worden u geen rechten of licenties verleend op de handelsmerken van de Waterfox Foundation of enige andere partij, met inbegrip van en zonder beperking tot de naam of het logo van Waterfox. Aanvullende informatie over handelsmerken is <a data-l10n-name="mozilla-trademarks-link">hier</a> te vinden.
rights-intro-point-3 = Enkele onderdelen in { -brand-short-name }, zoals de Crashreporter, bieden u de mogelijkheid feedback aan { -vendor-short-name } te leveren. Door het indienen van feedback geeft u { -vendor-short-name } toestemming de feedback te gebruiken om zijn producten te verbeteren, de feedback op zijn websites te publiceren en de feedback te verspreiden.
rights-intro-point-4 = Hoe we uw persoonlijke gegevens en feedback gebruiken die via { -brand-short-name } naar { -vendor-short-name } wordt verzonden, wordt beschreven in het <a data-l10n-name="mozilla-privacy-policy-link">{ -brand-short-name }-privacybeleid</a>.
rights-intro-point-4-unbranded = Privacybeleidsregels die op dit product van toepassing zijn, dienen hier te worden vermeld.
rights-intro-point-5 = Sommige { -brand-short-name }-functies maken gebruik van webgebaseerde informatiediensten. We kunnen echter niet garanderen dat deze 100% nauwkeurig of foutvrij zijn. Meer details, waaronder informatie over het uitschakelen van de functies die deze diensten gebruiken, is te vinden in de <a data-l10n-name="mozilla-service-terms-link">servicevoorwaarden</a>.
rights-intro-point-5-unbranded = Als in dit product webdiensten zijn opgenomen, dienen enige van toepassing zijnde servicevoorwaarden voor deze dienst(en) te worden gekoppeld aan de sectie <a data-l10n-name="mozilla-website-services-link">Websitediensten</a>.
rights-intro-point-6 = Om bepaalde typen video-inhoud af te spelen, downloadt { -brand-short-name } bepaalde inhouddecoderingsmodules van derden.
rights-webservices-header = Webgebaseerde informatiediensten van { -brand-full-name }
rights-webservices = { -brand-full-name } maakt gebruik van webgebaseerde informatiediensten (‘Diensten’) om een aantal functies die met deze binaire versie van { -brand-short-name } worden meegeleverd onder de onderstaande voorwaarden te gebruiken. Als u een of meer van de diensten niet wilt gebruiken of de onderstaande voorwaarden niet wilt accepteren, kunt u de functie of dienst(en) uitschakelen. Instructies over het uitschakelen van een bepaalde functie of dienst kunt u <a data-l10n-name="mozilla-disable-service-link">hier</a> vinden. Andere onderdelen en diensten kunnen worden uitgeschakeld in de voorkeuren van de toepassing.
rights-safebrowsing = <strong>Safe Browsing: </strong>uitschakelen van de functie Safe Browsing wordt niet aanbevolen, omdat dit ervoor kan zorgen dat u onveilige websites bezoekt. Als u de functie volledig wilt uitschakelen, volg dan deze stappen:
rights-safebrowsing-term-1 = Open de toepassingsvoorkeuren
rights-safebrowsing-term-2 = Selecteer de sectie Beveiliging
rights-safebrowsing-term-3 = Vink de optie ‘{ enableSafeBrowsing-label }’ uit
enableSafeBrowsing-label = Gevaarlijke en misleidende inhoud blokkeren
rights-safebrowsing-term-4 = Safe Browsing is nu uitgeschakeld
rights-locationawarebrowsing = <strong>Locatiebewust navigeren: </strong>vraagt altijd om toestemming. Er worden nooit locatiegegevens verzonden zonder uw toestemming. Als u de functie volledig wilt uitschakelen, volg dan deze stappen:
rights-locationawarebrowsing-term-1 = Typ in de URL-balk <code>about:config</code>
rights-locationawarebrowsing-term-2 = Typ geo.enabled
rights-locationawarebrowsing-term-3 = Dubbelklik op de voorkeursinstelling geo.enabled
rights-locationawarebrowsing-term-4 = Locatiebewust navigeren is nu uitgeschakeld
rights-webservices-unbranded = Een overzicht van de in het product opgenomen websitediensten, samen met instructies over het uitschakelen ervan, wanneer van toepassing, dienen hier te worden bijgesloten.
rights-webservices-term-unbranded = Servicevoorwaarden die op dit product van toepassing zijn, dienen hier te worden vermeld.
rights-webservices-term-1 = { -vendor-short-name } en zijn medewerkers, licentiegevers en partners werken aan het verstrekken van de meest nauwkeurige en bijgewerkte Diensten. We kunnen echter niet garanderen dat deze informatie volledig en foutvrij is. De dienst Safe Browsing bijvoorbeeld identificeert mogelijk bepaalde riskante websites niet, en bepaalde veilige websites ten onrechte wel. Alle locaties die door de dienst Locatiebewust navigeren van onze serviceproviders worden verkregen, zijn enkel schattingen. Noch wij, noch de serviceproviders garanderen de nauwkeurigheid van de gegeven locaties.
rights-webservices-term-2 = { -vendor-short-name } kan de Diensten naar eigen goeddunken discontinueren of wijzigen.
rights-webservices-term-3 = U kunt deze Diensten gebruiken met de bijgeleverde versie van { -brand-short-name }, en { -vendor-short-name } geeft u alle benodigde rechten om dit te doen. { -vendor-short-name } en zijn licentiegevers behouden alle overige rechten in de Diensten. Deze voorwaarden zijn niet bedoeld om enige rechten die zijn verleend onder opensourcelicenties welke van toepassing zijn op { -brand-short-name } en overeenkomende broncodeversies van { -brand-short-name } te beperken.
rights-webservices-term-4 = <strong>De Diensten worden aangeboden zonder enige garantie. { -vendor-short-name }, zijn medewerkers, licentiegevers en distributeurs wijzen alle uitdrukkelijke of impliciete garanties af, met inbegrip van, maar niet beperkt tot garanties van verhandelbaarheid en geschiktheid van de Diensten voor een bepaald doel. U draagt de volledige verantwoordelijkheid wat betreft het selecteren van de Diensten voor uw doeleinden en wat betreft de kwaliteit en prestaties van de Diensten. Sommige wetgevingen staan uitsluitingen of beperkingen van impliciete garanties niet toe, dus mogelijk is deze disclaimer op u niet van toepassing.</strong>
rights-webservices-term-5 = <strong>Behoudens zoals vereist bij de wet zijn { -vendor-short-name }, zijn medewerkers, licentiegevers en distributeurs niet aansprakelijk voor enige indirecte, speciale, incidentele, straffende of gevolgschade voortvloeiend uit of op enige manier verband houdend met het gebruik van { -brand-short-name } en de Diensten. De collectieve aansprakelijkheid onder deze voorwaarden zal het bedrag van $500 (vijfhonderd dollar) niet overschrijden. Sommige wetgevingen staan uitsluitingen of beperkingen van bepaalde garanties niet toe, dus mogelijk zijn deze uitsluiting en beperking op u niet van toepassing.</strong>
rights-webservices-term-6 = { -vendor-short-name } is te allen tijde gerechtigd deze voorwaarden te wijzigen. Deze voorwaarden mogen niet worden gewijzigd of geannuleerd zonder schriftelijke toestemming van { -vendor-short-name }.
rights-webservices-term-7 = Deze voorwaarden vallen onder de wetten van de staat Californië, U.S.A., met uitzondering van zijn bepalingen van internationaal privaatrecht. Als een of meer van deze voorwaarden als ongeldig of onafdwingbaar worden beschouwd, blijven de overige bepalingen onverminderd van kracht. In geval van strijdigheid tussen een vertaalde versie van deze voorwaarden en de Engelse versie prevaleert de Engelse versie.
