# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#filter emptyLines

#define MOZ_LANGPACK_CREATOR mozilla.rs

# If non-English locales wish to credit multiple contributors, uncomment this

# variable definition and use the format specified.

#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Вања Тумбас</em:contributor> <em:contributor>Марко Андрејић</em:contributor><em:contributor>Никола Радовановић</em:contributor><em:contributor>Горан Ракић</em:contributor><em:contributor>Филип Милетић</em:contributor><em:contributor>Игор Милетић</em:contributor><em:contributor>Љубиша Радовановић</em:contributor><em:contributor>Иван Ичин</em:contributor><em:contributor>проф. др Драган Јанковић</em:contributor><em:contributor>проф. др Милорад Тошић</em:contributor><em:contributor>дипл. инж. Оливера Тошић</em:contributor><em:contributor>Бранимир Станковић</em:contributor><em:contributor>дипл. инж. Душан Вучковић</em:contributor><em:contributor>Владана Михајловић</em:contributor><em:contributor>Драган Митровић</em:contributor>

#unfilter emptyLines
