# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with

# your locale code, and link to your translated pages as soon as they're

# live.


#define bookmarks_title புத்தகக்குறிகள்


#define bookmarks_heading புத்தகக்குறிகள்


#define bookmarks_toolbarfolder புத்தகக்குறிகளுக்கான கருவிப்பட்டி அடைவு


#define bookmarks_toolbarfolder_description இந்த கோப்புறையில் புத்தகக்குறிகள் சேர்ப்பு அவைகளின் புத்தகக்குறிகளுக்கான கருவிப்பட்டையில் காட்டப்படும்


# LOCALIZATION NOTE (getting_started):


# link title for https://www.mozilla.org/en-US/firefox/central/


#define getting_started தொடங்குதல்


# LOCALIZATION NOTE (firefox_heading):


# Firefox links folder name


#define firefox_heading Mozilla Firefox


# LOCALIZATION NOTE (firefox_help):


# link title for https://www.mozilla.org/en-US/firefox/help/


#define firefox_help உதவி மற்றும் பயிற்சிகள்


# LOCALIZATION NOTE (firefox_customize):


# link title for https://www.mozilla.org/en-US/firefox/customize/


#define firefox_customize Firefox தனிப்பயனாக்கம்


# LOCALIZATION NOTE (firefox_community):


# link title for https://www.mozilla.org/en-US/contribute/


#define firefox_community பங்குபெற


# LOCALIZATION NOTE (firefox_about):


# link title for https://www.mozilla.org/en-US/about/


#define firefox_about எங்களைப் பற்றி


# LOCALIZATION NOTE (nightly_heading):


# Firefox Nightly links folder name


#define nightly_heading இராக் கால பயர்பாக்ஸ் வளங்கள்


# LOCALIZATION NOTE (nightly_blog):


# Nightly builds only, link title for https://blog.nightly.mozilla.org/


#define nightly_blog இராக் கால பயர்பாக்ஸ் வலைப்பூ


# LOCALIZATION NOTE (bugzilla):


# Nightly builds only, link title for https://bugzilla.mozilla.org/


#define bugzilla Mozilla பிழை தடமறிவான்


# LOCALIZATION NOTE (mdn):


# Nightly builds only, link title for https://developer.mozilla.org/


#define mdn Mozilla உருவாக்குநர் வலையம்


# LOCALIZATION NOTE (nightly_tester_tools):


# Nightly builds only, link title for https://addons.mozilla.org/en-US/firefox/addon/nightly-tester-tools/


#define nightly_tester_tools Nightly ஆய்வுக்கருவிகள்


# LOCALIZATION NOTE (crashes):


# Nightly builds only, link title for about:crashes


#define crashes உங்கள் அனைத்து நொறுக்கல்கள்


# LOCALIZATION NOTE (irc):


# Nightly builds only, link title for ircs://irc.mozilla.org/nightly


#define irc Nightly குறித்து IRC இல் விவாதிக்கவும்


# LOCALIZATION NOTE (planet):


# Nightly builds only, link title for https://planet.mozilla.org/


#define planet Planet Mozilla


#unfilter emptyLines
