[package]
name = "webrender"
version = "0.48.0"
authors = ["Glenn Watson <gw@intuitionlibrary.com>"]
license = "MPL-2.0"
repository = "https://github.com/servo/webrender"
build = "build.rs"

[features]
default = ["freetype-lib", "webgl"]
freetype-lib = ["freetype/servo-freetype-sys"]
profiler = ["thread_profiler/thread_profiler"]
webgl = ["offscreen_gl_context", "webrender_api/webgl"]

[dependencies]
app_units = "0.5"
bincode = "0.8"
bit-set = "0.4"
byteorder = "1.0"
euclid = "0.15.1"
fnv = "1.0"
gleam = "0.4.7"
lazy_static = "0.2"
log = "0.3"
num-traits = "0.1.32"
offscreen_gl_context = {version = "0.11", features = ["serde", "osmesa"], optional = true}
time = "0.1"
rayon = "0.8"
webrender_api = {path = "../webrender_api"}
bitflags = "0.9"
gamma-lut = "0.2"
thread_profiler = "0.1.1"
plane-split = "0.6"

[dev-dependencies]
angle = {git = "https://github.com/servo/angle", branch = "servo"}
rand = "0.3"                # for the benchmarks
servo-glutin = "0.11"     # for the example apps

[target.'cfg(any(target_os = "android", all(unix, not(target_os = "macos"))))'.dependencies]
freetype = { version = "0.2", default-features = false }

[target.'cfg(target_os = "windows")'.dependencies]
dwrote = "0.4"

[target.'cfg(target_os = "macos")'.dependencies]
core-graphics = "0.8.0"
core-text = { version = "6.1", default-features = false }
