<menuitem
    id="context_copyTabUrl"
    class="tabFeature"
    oncommand="TabFeatures.copyTabUrl(TabContextMenu.contextTab.linkedBrowser.currentURI.spec, window);"
    data-lazy-l10n-id="copy-url"
    preference="browser.tabs.copyurl"
/>
<menuitem
    id="context_copyAllTabUrls"
    class="tabFeature"
    oncommand="TabFeatures.copyAllTabUrls(window);"
    data-lazy-l10n-id="copy-all-urls"
    preference="browser.tabs.copyallurls"
/>