#filter emptyLines

#define MOZ_LANGPACK_CREATOR id-Waterfox - Komunitas Waterfox Indonesia

# If non-English locales wish to credit multiple contributors, uncomment this

# variable definition and use the format specified.

#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Dody Suria Wijaya</em:contributor><em:contributor>Milda Irhamni</em:contributor><em:contributor>Romi Hardiyanto</em:contributor>

#unfilter emptyLines
