# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#filter emptyLines

#define MOZ_LANGPACK_CREATOR mozilla.org

# If non-English locales wish to credit multiple contributors, uncomment this

# variable definition and use the format specified.

#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>San James</em:contributor> <em:contributor>War Child Holland-Uganda</em:contributor><em:contributor>Acuma George Patrick</em:contributor> <em:contributor>Keneth Ogwal</em:contributor><em:contributor>Dan Jasper Okello</em:contributor> <em:contributor>Opio June Brian</em:contributor><em:contributor>Kaloba Haron</em:contributor><em:contributor>Komakech S. B. Ford</em:contributor><em:contributor>Akena David Akeni</em:contributor><em:contributor>Acire Samuel</em:contributor><em:contributor>Ojara David Prince</em:contributor>

#unfilter emptyLines
