# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

rights-title = Par jūsu tiesībām
rights-intro = { -brand-full-name } ir brīva bezmaksas atvērtā koda programma, ko veido tūkstošiem brīvprātīgo no visas pasaules. Ir dažas lietas, ko jums būtu vērts zināt:
rights-intro-point-1 = { -brand-short-name } ir pieejams ar <a data-l10n-name="mozilla-public-license-link">Mozilla publiskās licences</a>nosacījumiem. Tas nozīmē, ka jūs varat brīvi izmantot, pavairot uz izplatīt { -brand-short-name } citiem.  Tāpat jūs droši varat mainīt un papildināt { -brand-short-name } pirmkodu pēc saviem ieskatiem. Mozilla publiskā licence dod jums tiesības brīvi izplatīt savas modificētās versijas.
rights-intro-point-2 = Mozilla nedod jums tiesības izmantot Mozilla un Firefox preču zīmes un logo. Papildus informācija par preču zīmēm ir atrodama <a data-l10n-name="mozilla-trademarks-link">šeit</a>.
rights-intro-point-3 = Dažas no { -brand-short-name } iespējām, piemēram, avāriju gadījumu ziņošanas rīks, piedāvā jums iespēju nosūtīt savu viedokli par { -vendor-short-name }. Izvēloties nosūtīt savu viedokli, jūs dodat atļauju { -vendor-short-name } izmantot šo jūsu sniegto informāciju, lai uzlabotu savus produktus, publicēt to savās mājas lapās vai kā citādi izplatīt šo saņemto informāciju.
rights-intro-point-4 = Tas kā mēs izmantojam jūsu personisko informāciju un { -vendor-short-name } nosūtīto viedokli izmantojot { -brand-short-name } ir aprakstīts <a data-l10n-name="mozilla-privacy-policy-link">{ -brand-short-name } privātuma politikā</a>.
rights-intro-point-4-unbranded = Visām aktuālajām privātuma politikām būtu jābūt uzskaitītām šeit.
rights-intro-point-5 = Dažas { -brand-short-name } iespējas izmanto tīmeklī bāzētus pakalpojumus, taču, mēs nevaram garantēt, ka tie ir 100% pareizi un kļūdu brīvi. Papildus informācija par šiem pakalpojumiem un to kā tos deaktivēt, ir pieejama <a data-l10n-name="mozilla-service-terms-link">pakalpojumu nosacījumu aprakstā</a>.
rights-intro-point-5-unbranded = Ja šajā produktā ir iekļauti tīmekļa pakalpojumi, visiem aktuālajiem pakalpojuma nosacījumiem jābūt pieejamiem <a data-l10n-name="mozilla-website-services-link">mājas lapu pakalpojumu</a> sadaļā.
rights-intro-point-6 = Lai varētu atskaņot dažu tipu video, { -brand-short-name } lejupielādē zināmus satura atkodēšanas moduļus no trešajām pusēm.
rights-webservices-header = { -brand-full-name } tīmeklī bāzētie informācijas pakalpojumi
rights-webservices = { -brand-full-name } izmanto tīmeklī bāzētus informācijas pakalpojumus ("Pakalpojumi"), lai nodrošinātu dažas no funkcijām, kas pieejamas binārajā { -brand-short-name } versijā ar zemāk aprakstītajiem nosacījumiem. Ja nevēlaties izmantot kādu no aprakstītajiem pakalpojumiem vai arī to izmantošanas nosacījumi jums nav pieņemami, jūs varat deaktivet šos pakalpojumus. Instrukcijas, kā deaktivēt konkrētu pakalpojumi ir pieejamas <a data-l10n-name="mozilla-disable-service-link">te</a>. Citas iespējas un pakalpojumus var deaktivēt programmas iestatījumos.
rights-safebrowsing = <strong>Drošā pārlūkošana: </strong>Drošās pārlūkošanas deaktivēšana nav ieteicama, jo šādā veidā jūs varat nonākt nedrošās interneta lapās. Ja tomēr vēlaties to deaktivēt, rīkojieties sekojoši:
rights-safebrowsing-term-1 = Atveriet programmas iestatījumus
rights-safebrowsing-term-2 = Izvēlieties sadaļu Drošība
rights-safebrowsing-term-3 = Izņemiet iezīmi pie "{ enableSafeBrowsing-label }"
enableSafeBrowsing-label = Bloķēt bīstamu un maldinošu saturu
rights-safebrowsing-term-4 = Drošā pārlūkošana tagad ir deaktivēta
rights-locationawarebrowsing = <strong>Atrašanās vietu zinoša pārlūkošana: </strong>informācija par jūsu atrašanās vietu nekad netiek sūtīta bez jūsu piekrišanas.  Ja vēlaties pilnībā deaktivēt šo iespēju, rīkojieties sekojoši:
rights-locationawarebrowsing-term-1 = Adreses joslā ierakstiet <code>about:config</code>
rights-locationawarebrowsing-term-2 = Ierakstiet geo.enabled
rights-locationawarebrowsing-term-3 = Ar dubultklikšķi uzklikšķiniet uz geo.enabled iestatījuma
rights-locationawarebrowsing-term-4 = Vietu zinošā pārlūkošana tagad ir deaktivēta
rights-webservices-unbranded = Pieejamo mājas lapu pakalpojumu apraksti un instrukcijas kā vajadzības gadījumā deaktivēt tos ir pieejami šeit.
rights-webservices-term-unbranded = Aktuālajiem pakalpojumu izmantošanas noteikumiem būtu jābūt aprakstītiem šeit.
rights-webservices-term-1 = { -vendor-short-name } kopā ar brīvprātīgajiem, licenču partneriem un partneriem strādā pie tā, lai nodrošinātu visprecīzākos un aktuālākos pakalpojumus. Taču mēs nevaram garantēt, ka šī informācija ir visaptveroša un bez kļūdām. Piemēram, drošās pārlūkošanas pakalpojums var nezināt, ka kāda lapa ir bīstama vai arī kļūdaini uzskatīt kādu drošu lapu par bīstamu. Mūsu partneru piedāvātā atrašanās vietas noteikšana ir tikai aptuvena un nedz mēs, nedz mūsu partneri negarantē piedāvātās atrašanās vietas informācijas pareizību.
rights-webservices-term-2 = { -vendor-short-name } var pārtraukt Pakalpojumus pēc saviem ieskatiem.
rights-webservices-term-3 = Mēs laipni lūdzam jūs izmantot šos { -brand-short-name } piedāvātos pakalpojumus, un { -vendor-short-name } sniedz jums tiesības to darīt.  { -vendor-short-name } un tās licenču partneri patur visas citas tiesības šajos pakalpojumos.  Šie nosacījumi nav domāti, lai ierobežotu jūsu tiesības, ko jums sniedz ar { -brand-short-name } saistītās atvērtā koda licences vai { -brand-short-name } pirmkoda licences.
rights-webservices-term-4 = <strong>Pakalpojumi tiek piedāvāti "kādi tie ir."  { -vendor-short-name }, tās palīg, licencētāji un izplatītāji atsakās no jebkādām garantijām, neatkarīgi no tā vai tās ir paustas rakstiski vai tiek pieņemtas kā esošas, ieskaitot jebkādas garantijas par to, ka Pakalpojumi ir funkcionāli un atbilstoši jūsu vajadzībām.  Visa atbildība par Pakalpojumu izmantošanu gulstas uz jūsu pleciem attiecībā uz to kvalitāti un atbilstību veicamajām funkcijām.  Zināmos juridiskos apstākļos nav iespējams atteikties no iedomātajām garantijām, līdz ar to šī atruna var uz jums neattiekties.</strong>
rights-webservices-term-5 = <strong>Izņemot gadījumus, kur to pieprasa likumdošana, { -vendor-short-name }, tās palīgi, licencētāji un izplatītāji nebūs atbildīgi par jebkādiem tīšiem, netiešiem, nejaušiem vai jebkādiem cita veida bojājumiem, kas jebkādā veidā saistāmi ar { -brand-short-name } un tā Pakalpojumu izmantošanu.  Kopējā atbildība pēc šo nosacījumu principiem nepārsniegs $500 (piecus simtus ASV dolāru). Zināmos juridiskos apstākļos nav iespējams atteikties no iedomātajām garantijām, līdz ar to šī atruna var uz jums neattiekties.</strong>
rights-webservices-term-6 = { -vendor-short-name } drīkst brīvi mainīt vai papildināt šos nosacījumus pēc saviem ieskatiem. Šie nosacījumi nevar tikt modificēti vai atcelti bez iepriekšēja rakstiska apliecinājuma no { -vendor-short-name }.
rights-webservices-term-7 = Šos noteikumus pārvalda Kalifornijas štata likumdošana, A.S.V. Ja kāda šo nosacījumu daļa tiek uzskatīta par nederīgu vai to nav iespējams piemērot, atlikušās daļas paliek spēkā. Domstarpību gadījumos starp šo nosacījumu tulkotajām un angļu valodas versiju, Angļu valodas versija tiek uzskatīta par galveno.
