# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

rights-title = Pri viaj rajtoj
rights-intro = { -brand-full-name } estas libera kaj malfermitkoda programo, konstruita de komunumo de miloj de personoj el la tuta mondo. Estas kelkaj aferoj kiujn vi devus scii:
rights-intro-point-1 = { -brand-short-name } estas akirebla de vi laŭ la kondiĉoj de la permesilo <a data-l10n-name="mozilla-public-license-link">Mozilla Public License</a>. Tio signifas ke vi povas uzi, kopii kaj distribui { -brand-short-name } al aliaj homoj. Oni kuraĝigas vin modifi la fontan kodon de { -brand-short-name } kiel ajn vi volas por akomodi ĝin al viaj bezonoj. La Mozilla Public License ankaŭ rajtigas vin distribui viajn modifitajn versiojn.
rights-intro-point-2 = Neniu rajto pri la registrita marko aŭ uzopermesilo por la registritaj markoj de Mozilla Foundation aŭ de iu alia estas ceditaj al vi. Tio inkluzivas, sed ne nur tion, la nomon aŭ emblemon de Firefox.  Pli da informo pri registritaj markoj estas trovebla <a data-l10n-name="mozilla-trademarks-link">ĉi tie</a>.
rights-intro-point-3 = Kelkaj trajtoj de { -brand-short-name }, kiel la Panea Raportisto, ebligas al vi sendi raporton al { -vendor-short-name }. Se vi decidas sendi raporton, vi donas al  { -vendor-short-name } la permeson uzi tiun raporton por plibonigi ĝiajn produktojn, publikigi la raporton en ĝiaj retejoj kaj distribui ĝin.
rights-intro-point-4 = Priskribo pri kiel ni uzas viajn personajn datumojn kaj la raportojn senditajn al { -vendor-short-name } per { -brand-short-name } troveblas en la <a data-l10n-name="mozilla-privacy-policy-link">{ -brand-short-name } Politiko pri privateco</a>.
rights-intro-point-4-unbranded = Ĉiu aplikebla privateca politiko por tiu ĉi produkto devus esti listita ĉi tie.
rights-intro-point-5 = Kelkaj trajtoj de { -brand-short-name } uzas TTT-bazitajn informservojn. Ni tamen ne povas garantii ke ili estas 100% precizaj aŭ seneraraj.  Pli da detaloj, kiuj inkluzivas informon pri kiel malaktivigi la trajtojn kiuj uzas tiajn servojn, troveblas en la <a data-l10n-name="mozilla-service-terms-link">servaj kondiĉoj</a>.
rights-intro-point-5-unbranded = Se tiu ĉi produkto inkluzivas retejajn servojn, ĉiu aplikebla kondiĉo de uzado por tiuj servoj devus esti ligita el la<a data-l10n-name="mozilla-website-services-link">Retejaj servoj</a>sekcio.
rights-intro-point-6 = Por povi montri kelkajn tipojn de videa enhavo, { -brand-short-name } elŝutas kelkajn malĉifrajn blokojn de aliaj provizantoj.
rights-webservices-header = { -brand-full-name } TTT-bazitaj informservoj
rights-webservices = { -brand-full-name } uses web-based information services ("Services") to provide some of the features provided for your use with this binary version of { -brand-short-name } under the terms described below. If you do not want to use one or more of the Services or the terms below are unacceptable, you may disable the feature or Service(s). Instructions on how to disable a particular feature or Service may be found <a data-l10n-name="mozilla-disable-service-link">ĉi tie</a>. Aliaj servoj kaj trajtoj povas esti malaktivigitaj en la preferoj de la programo.
rights-safebrowsing = <strong>Sekura retumo: </strong>Ne estas konsilinde malelekti la trajton de sekura retumo, ĉar el tio povus rezulti vizitoj al nesekuraj retejoj. Se vi volas plene malaktivigi la trajton, sekvu la jenajn paŝojn:
rights-safebrowsing-term-1 = Malfermu la preferojn de la programo
rights-safebrowsing-term-2 = Elektu la sekcion Sekureco
rights-safebrowsing-term-3 = Malelektu la elekteblon por "{ enableSafeBrowsing-label }"
enableSafeBrowsing-label = Bloki danĝeran aŭ trompan enhavon
rights-safebrowsing-term-4 = Sekura retumo estas nun malaktiva
rights-locationawarebrowsing = <strong>Location Aware Browsing: </strong>is always opt-in.  No location information is ever sent without your permission.  If you wish to disable the feature completely, follow these steps:
rights-locationawarebrowsing-term-1 = En la adresa strio tajpu <code>about:config</code>
rights-locationawarebrowsing-term-2 = Tajpu geo.enabled
rights-locationawarebrowsing-term-3 = Duoble alklaku la preferon geo.enabled
rights-locationawarebrowsing-term-4 = Location-Aware Browsing is now disabled
rights-webservices-unbranded = Superrigardo de la retejaj servoj inkluzivitaj de la produkto, kune kun instrukcioj pri kiel malaktivigi ilin, se eblas, devus aperi ĉi tie.
rights-webservices-term-unbranded = Ĉiu aplikebla kondiĉo de servoj por tiu ĉi produko devus esti listita ĉi tie.
rights-webservices-term-1 = { -vendor-short-name } and its contributors, licensors and partners work to provide the most accurate and up-to-date Services.  However, we cannot guarantee that this information is comprehensive and error-free.  For example, the Safe Browsing Service may not identify some risky sites and may identify some safe sites in error and the Location Aware Service all locations returned by our service providers are estimates only and neither we nor our service providers guarantee the accuracy of the locations provided.
rights-webservices-term-2 = { -vendor-short-name } povas maldaŭrigi aŭ ŝanĝi la servojn laŭ ĝia volo.
rights-webservices-term-3 = You are welcome to use these Services with the accompanying version of { -brand-short-name }, and { -vendor-short-name } grants you its rights to do so.  { -vendor-short-name } and its licensors reserve all other rights in the Services.  These terms are not intended to limit any rights granted under open source licenses applicable to { -brand-short-name } and to corresponding source code versions of { -brand-short-name }.
rights-webservices-term-4 = <strong>The Services are provided "as-is."  { -vendor-short-name }, its contributors, licensors, and distributors, disclaim all warranties, whether express or implied, including without limitation, warranties that the Services are merchantable and fit for your particular purposes.  You bear the entire risk as to selecting the Services for your purposes and as to the quality and performance of the Services. Some jurisdictions do not allow the exclusion or limitation of implied warranties, so this disclaimer may not apply to you.</strong>
rights-webservices-term-5 = <strong>Except as required by law, { -vendor-short-name }, its contributors, licensors, and distributors will not be liable for any indirect, special, incidental, consequential, punitive, or exemplary damages arising out of or in any way relating to the use of { -brand-short-name } and the Services.  The collective liability under these terms will not exceed $500 (five hundred dollars). Some jurisdictions do not allow the exclusion or limitation of certain damages, so this exclusion and limitation may not apply to you.</strong>
rights-webservices-term-6 = { -vendor-short-name } may update these terms as necessary from time to time. These terms may not be modified or canceled without { -vendor-short-name }'s written agreement.
rights-webservices-term-7 = These terms are governed by the laws of the state of California, U.S.A., excluding its conflict of law provisions. If any portion of these terms is held to be invalid or unenforceable, the remaining portions will remain in full force and effect. In the event of a conflict between a translated version of these terms and the English language version, the English language version shall control.
