#filter emptyLines

#define MOZ_LANGPACK_CREATOR Mozilla Brasil

# If non-English locales wish to credit multiple contributors, uncomment this

# variable definition and use the format specified.

#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Caio Tiago Oliveira</em:contributor> <em:contributor>Carlos Une</em:contributor> <em:contributor>Marco Aurélio Krause</em:contributor>

#unfilter emptyLines
