# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
---
loader: taskgraph.loader.transform:loader

transforms:
    - taskgraph.transforms.release_deps:transforms
    - taskgraph.transforms.release_started:transforms
    - taskgraph.transforms.job:transforms
    - taskgraph.transforms.task:transforms

job-defaults:
    name: notify-release-drivers-started
    description: Sends email to release-drivers telling release was started.
    run-on-projects: []
    shipping-phase: promote
    worker-type: b-linux
    worker:
        docker-image: {in-tree: "debian9-base"}
        max-run-time: 600
    emails:
        by-project:
            mozilla-(beta|release|esr.*): ["release-signoff@mozilla.org"]
            try: ["{config[params][owner]}"]
            default: []

jobs:
    firefox:
        shipping-product: firefox
    devedition:
        shipping-product: devedition
