# This Source Code Form is subject to the terms of the Waterfox Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

rights-title = À propos de vos droits
rights-intro = { -brand-full-name } est un logiciel libre et ouvert, réalisé par une communauté de milliers de contributeurs dans le monde. Voici ce que vous devriez savoir :
rights-intro-point-1 = { -brand-short-name } est disponible suivant les modalités de la <a data-l10n-name="mozilla-public-license-link">Waterfox Public License</a> (Licence publique Waterfox). Ceci signifie que vous pouvez utiliser, copier et distribuer { -brand-short-name } à d’autres personnes. Vous pouvez également modifier le code source de { -brand-short-name } à votre gré pour répondre à vos besoins. La Licence publique Waterfox vous autorise aussi à distribuer vos versions modifiées.
rights-intro-point-2 = Il ne vous est cédé aucun droit ou licence sur les marques déposées de la Fondation Waterfox ou de tiers, y compris et sans limitation, sur le nom et le logo de Thunderbird. Vous pouvez consulter des informations complémentaires sur les marques déposées <a data-l10n-name="mozilla-trademarks-link">ici</a>.
rights-intro-point-3 = Certaines fonctionnalités de { -brand-short-name }, comme le rapporteur de plantages, vous permettent de fournir un retour à { -vendor-short-name }. En choisissant d’envoyer ces informations, vous donnez à { -vendor-short-name } la permission d’utiliser ce retour pour améliorer ses logiciels, de le publier sur ses sites web et de le distribuer.
rights-intro-point-4 = La manière dont nous utilisons vos informations personnelles et le retour envoyés à { -vendor-short-name } par l’intermédiaire de { -brand-short-name } est décrite dans la <a data-l10n-name="mozilla-privacy-policy-link">politique de confidentialité de { -brand-short-name }</a>.
rights-intro-point-4-unbranded = Toutes les politiques de confidentialité applicables à ce logiciel devraient être listées ici.
rights-intro-point-5 = Certaines fonctionnalités de { -brand-short-name } utilisent des services d’information sur le Web, cependant nous ne pouvons pas garantir à 100 % qu’ils sont appropriés ou dénués d’erreurs. Vous pouvez trouver plus de détails, y compris des informations sur la manière de désactiver les services, dans les <a data-l10n-name="mozilla-service-terms-link">modalités d’utilisation</a>.
rights-intro-point-5-unbranded = Si ce logiciel intègre des services web, toutes les modalités d’utilisation applicables pour le ou les services doivent être liées à la section <a data-l10n-name="mozilla-website-services-link">Services de sites web</a>.
rights-intro-point-6 = Afin de pouvoir lire certains types de contenus vidéos, { -brand-short-name } télécharge certains modules de déchiffrement de contenu depuis des tiers.
rights-webservices-header = Services d’informations web de { -brand-full-name }
rights-webservices = { -brand-full-name } utilise des services d’informations web (« Les Services ») pour fournir certaines des fonctionnalités qui sont mises à votre disposition dans cette version binaire de { -brand-short-name } comme décrit ci-dessous. Si vous ne voulez pas utiliser l’un ou l’autre de ces Services ou si vous trouvez que les modalités ci-dessous ne sont pas acceptables, vous pouvez désactiver la fonctionnalité ou le Service. Pour ce faire, veuillez consulter ces <a data-l10n-name="mozilla-disable-service-link">instructions</a> décrivant la manière de désactiver un Service ou une fonctionnalité en particulier. Les autres fonctionnalités ou Services peuvent être désactivés dans les préférences de l’application.
rights-locationawarebrowsing = <strong>Navigation selon la localisation géographique : </strong>se fait toujours à la demande. Aucune information concernant votre localisation n’est jamais envoyée sans votre permission. Si vous souhaitez désactiver la fonctionnalité complètement, suivez ces instructions :
rights-locationawarebrowsing-term-1 = Dans la barre d’adresse, saisissez <code>about:config</code>
rights-locationawarebrowsing-term-2 = Faites une recherche sur geo.enabled
rights-locationawarebrowsing-term-3 = Double-cliquez sur la préférence geo.enabled
rights-locationawarebrowsing-term-4 = La localisation géographique est alors désactivée.
rights-webservices-unbranded = Un aperçu des services de sites web intégrés dans le logiciel, accompagné des instructions sur la manière de les désactiver, le cas échéant, doit être indiqué ici.
rights-webservices-term-unbranded = Toutes les modalités d’utilisation applicables pour ce logiciel doivent être indiquées ici.
rights-webservices-term-1 = { -vendor-short-name } et ses contributeurs, concédants de licence et partenaires travaillent pour produire les Services les plus exacts et les plus à jour. Cependant, nous ne pouvons pas garantir que ces informations sont exhaustives et dénuées d’erreur. Par exemple, le service de blocage des sites malveillants peut ne pas identifier certains sites dangereux ou identifier à tort certains sites sûrs comme malveillants. Par ailleurs, tous les emplacements indiqués par le service de localisation géographique ne sont que des estimations et ni nous ni nos fournisseurs de service ne pouvons garantir leur précision.
rights-webservices-term-2 = { -vendor-short-name } peut arrêter ou modifier Les Services à sa discrétion.
rights-webservices-term-3 = Vous pouvez utiliser ces Services avec la version de { -brand-short-name } qui les accompagne, et { -vendor-short-name } vous garantit les droits nécessaires pour le faire. { -vendor-short-name } et ses concédants de licence se réservent tous les autres droits dans les Services. Les présentes modalités ne sont pas destinées à limiter les droits concédés par les licences de logiciels libres applicables à { -brand-short-name } et au code source des versions correspondantes de { -brand-short-name }.
rights-webservices-term-4 = <strong>Les Services sont fournis « tels quels ». { -vendor-short-name }, ses contributeurs, concédants de licence et distributeurs, déclinent toutes garanties, expresses ou implicites, y compris mais sans s’y limiter, les garanties que les Services sont commercialisables et s’adaptent à vos besoins particuliers. Vous supportez intégralement les risques quant à la sélection des Services pour vos besoins et quant à la qualité et aux performances des Services. Certaines juridictions n’autorisent pas l’exclusion ou la limitation des garanties implicites, et donc cette clause de non-garantie peut ne pas s’appliquer pour vous.</strong>
rights-webservices-term-5 = <strong>Sauf si requis par la loi, { -vendor-short-name }, ses contributeurs, concédants de licence et distributeurs ne seront pas passibles de dommages indirects, particuliers, accessoires, de dommages et intérêts punitifs ou exemplaires résultant de l’utilisation ou par tout moyen relatif à l’utilisation de { -brand-short-name } et des Services. La responsabilité collective sous les présentes modalités n’excédera pas 500 $ (cinq cents dollars). Certaines juridictions n’autorisent pas l’exclusion ou la limitation de certains dommages, et donc ces exclusions et limitations peuvent ne pas s’appliquer pour vous.</strong>
rights-webservices-term-6 = { -vendor-short-name } peut mettre à jour les présentes modalités si nécessaire de temps à autre. Ces modalités ne peuvent pas être modifiées ou annulées sans l’accord écrit de { -vendor-short-name }.
rights-webservices-term-7 = Les présentes modalités sont régies par les lois de l’état de Californie, États-Unis d’Amérique, à l’exclusion de conflit avec des dispositions légales. Si une partie de ces modalités est invalidée ou ne peut pas être mise en application, les parties restantes demeureront pleinement applicables. Dans l’éventualité d’un conflit entre une version traduite de ces modalités et la version en langue anglaise, la version en langue anglaise fera foi.
