[package]
name = "fluent-ffi"
version = "0.1.0"
authors = ["Zibi Braniecki <zibi@braniecki.net>"]
edition = "2018"

[dependencies]
fluent = { version = "0.11" , features = ["fluent-pseudo"] }
fluent-pseudo = "0.2"
intl-memoizer = "0.4"
unic-langid = "0.8"
nsstring = { path = "../../../../xpcom/rust/nsstring" }
thin-vec = { version = "0.1.0", features = ["gecko-ffi"] }
