[package]
name = "audioipc-server"
version = "0.2.3"
authors = [
        "Matthew Gregan <kinetik@flim.org>",
        "Dan Glastonbury <dan.glastonbury@gmail.com>"
        ]
description = "Remote cubeb server"
edition = "2018"

[dependencies]
audio_thread_priority = "0.22"
audioipc = { path = "../audioipc" }
cubeb-core = "0.7.0"
futures = "0.1.29"
once_cell = "1.2.0"
log = "0.4"
slab = "0.4"
tokio = "0.1"

[dependencies.error-chain]
version = "0.11.0"
default-features = false
