#filter emptyLines

#define MOZ_LANGPACK_CREATOR thunderbird-mail.de
# If non-English locales wish to credit multiple contributors, uncomment this
# variable definition and use the format specified.
#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Sebastian Hengst</em:contributor> <em:contributor>Alexander Ihrig</em:contributor> <em:contributor>Robert Kaiser</em:contributor> <em:contributor>Abdulkadir Topal</em:contributor>

#unfilter emptyLines
