[package]
name = "cubeb-ffi"
version = "0.0.1"
authors = ["Dan Glastonbury <dglastonbury@mozilla.com>"]
description = "FFI bindings for implementing cubeb backends"

[dependencies]
bitflags = "^0.7.0"
