---
target: obj-x86_64-pc-linux-gnu
# It is used by 'mach static-analysis' and 'mozreview static-analysis bot'
# in order to have consistency across the used checkers.
platforms:
  - linux64
infer_checkers:
  # no issues were ever trigger by this
  - name: check-nullable
    publish: !!bool no
  - name: biabduction
    publish: !!bool yes
  # very very noisy
  # it could be useful, but it won't be part of the default enabled checkers
  - name: eradicate
    publish: !!bool no
  # hard to use, not useful
  - name: quandary
    publish: !!bool no
  - name: starvation
    publish: !!bool yes
  # experimental
  - name: litho
    publish: !!bool no
  - name: racerd
    publish: !!bool yes
  # I think this is only for c++, can't trigger these errors in Java
  - name: liveness
    publish: !!bool no
# Third party files from mozilla-central
third_party: tools/rewriting/ThirdPartyPaths.txt
generated: tools/rewriting/Generated.txt
