# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

rights-title = Apie jūsų teises
rights-intro = „{ -brand-full-name }“ yra laisvoji atviroji programa, kuriama bendruomenės, apimančios tūkstančius žmonių iš viso pasaulio. Keletas dalykų, kuriuos turėtumėte žinoti:
rights-intro-point-1 = Jums leidžiama naudotis „{ -brand-short-name }“ programa, vadovaujantis <a data-l10n-name="mozilla-public-license-link">„Mozilla“ viešąja licencija (Mozilla Public License)</a>. Ši licencija leidžia naudotis „{ -brand-short-name }“ programa, ją dauginti ir platinti.  Be to, galite laisvai modifikuoti programos pirminius tekstus. Licencija nedraudžia platinti ir jūsų modifikuotų programos versijų.
rights-intro-point-2 = Jums nesuteikiamos jokios prekės ženklo teisės ar licencijos į „Mozilla Foundation“ ar kitų šalių prekės ženklus, tame tarpe – į „Thunderbird“ vardą ar logotipą. Papildomą informaciją apie prekės ženklus rasite <a data-l10n-name="mozilla-trademarks-link">čia</a>.
rights-intro-point-3 = Kai kurios „{ -brand-short-name }“ savybės, pavyzdžiui, strigčių pranešiklis, suteikia galimybę siųsti atsiliepimus „{ -vendor-short-name }i“. Siųsdami atsiliepimus, jūs suteikiate „{ -vendor-short-name }i“ teisę jais naudotis savo kuriamų produktų tobulinimo tikslais, skelbti juos savo svetainėse ir platinti juos kitais būdais.
rights-intro-point-4 = Kaip jūsų asmeninius duomenis ir per „{ -brand-short-name }“ pateiktus atsiliepimus naudoja „{ -vendor-short-name }“, nurodyta <a data-l10n-name="mozilla-privacy-policy-link">„{ -brand-short-name }“ privatumo nuostatuose</a>.
rights-intro-point-4-unbranded = Čia turėtų būti išvardintos šiai programai taikomos privatumo nuostatos.
rights-intro-point-5 = Kai kurie „{ -brand-short-name }“ komponentai suteikia galimybę naudotis papildomomis saityno tarnybų paslaugomis, tačiau mes negalime užtikrinti, kad šios tarnybos niekada neklysta ir veikia nepriekaištingai. Daugiau informacijos apie šiuos komponentus ir apie tai, kaip juos išjungti, rasite <a data-l10n-name="mozilla-service-terms-link">naudojimosi paslaugomis nuostatuose</a>.
rights-intro-point-5-unbranded = Jei šioje programoje naudojamos kokios nors saityno tarnybos, nuorodos į jų naudojimosi taisykles turėtų būti pateiktos skyrelyje <a data-l10n-name="mozilla-website-services-link">„Naudojamos saityno tarnybos“</a>.
rights-intro-point-6 = Kad galėtų atkurti tam tikrus vaizdo turinio formatus, „{ -brand-short-name }“ parsisiunčia tam tikrus turinio iššifravimo modulius iš trečiųjų šalių.
rights-webservices-header = „{ -brand-full-name }“ naudojamos informacinės saityno tarnybos
rights-webservices = Programoje „{ -brand-full-name }“ naudojamos informacinių saityno tarnybų paslaugos (toliau – „Paslaugos“), kurios reikalingos kai kurioms šios programos „{ -brand-short-name }“ versijos funkcijoms įgyvendinti. Šių Paslaugų teikimo nuostatai pateikiami žemiau. Jeigu nenorite naudotis kuriomis nors Paslaugomis, arba nesutinkate su jų teikimo nuostatais, galite išjungti atitinkamas programos funkcijas arba atsisakyti Paslaugų. Instrukcijos, kaip išjungti konkrečias funkcijas ar atsisakyti Paslaugų, pateikiamos <a data-l10n-name="mozilla-disable-service-link">čia</a>. Kitas galimybes ir tarnybų paslaugas galite išjungti programos nuostatose.
rights-locationawarebrowsing = <strong>Naršymas nustatant geografinę vietą: </strong>Ši funkcija yra pasirenkama – be atskiro jūsų leidimo jokia informacija apie geografinę vietą nebus siunčiama. Jeigu norite šią funkciją išjungti visiškai, darykite tai taip:
rights-locationawarebrowsing-term-1 = adreso lauke įrašykite <code>about:config;</code>
rights-locationawarebrowsing-term-2 = filtro lauke įrašykite „geo.enabled“;
rights-locationawarebrowsing-term-3 = dukart spustelėkite nuostatą „geo.enabled“;
rights-locationawarebrowsing-term-4 = naršymas nustatant geografinę vietą išjungtas.
rights-webservices-unbranded = Čia turėtų būti pateiktas šioje programoje naudojamų saityno paslaugų aprašas bei instrukcijos, kaip šių paslaugų naudojimo atsisakyti, jei tai įmanoma.
rights-webservices-term-unbranded = Čia turėtų būti pateiktos šioje programoje naudojamų saityno paslaugų naudojimosi taisyklės.
rights-webservices-term-1 = „{ -vendor-short-name }“ ir jos talkininkai, licencijų išdavėjai ir partneriai nuolat dirba, stengdamiesi teikti tiksliausias ir šviežiausias Paslaugas. Deja, neįmanoma užtikrinti, jog šie duomenys būtų išsamūs ir be klaidų. Pavyzdžiui, saugaus naršymo paslauga gali neatpažinti kai kurių pavojingų svetainių, o kai kurias saugias gali klaidingai palaikyti pavojingomis, o naršymo nustatant geografinę vietą Paslaugos nustatoma geografinė vieta visada yra tik apytikslė – nei mes, nei mūsų Paslaugų teikėjai negarantuojame, kad nustatoma vieta yra tiksli.
rights-webservices-term-2 = „{ -vendor-short-name }“ gali vienašališkai nutraukti ar pakeisti Paslaugų teikimą.
rights-webservices-term-3 = Jūs esate kviečiami naudotis šiomis Paslaugomis su šia „{ -brand-short-name }“ laida, ir „{ -vendor-short-name }“ jums suteikia visas jos turimas tam reikalingas teises.  „{ -vendor-short-name }“ ir jos licencijų išdavėjai pasilieka visas kitas su Paslaugomis susijusias teises.  Šiomis taisyklėmis nesiekiama apriboti teisių, kurias jums suteikia programai „{ -brand-short-name }“ ir jos pirminiams tekstams taikoma atvirųjų programų licencija.
rights-webservices-term-4 = <strong>Paslaugos teikiamos „tokios, kokios yra“. „{ -vendor-short-name }“, jos bendradarbiai, licencijų išdavėjai ir platintojai atsiriboja nuo bet kokių išreikštų ar numanomų garantijų, kaip antai nuo garantijų, jog Paslaugos yra veiksmingos ir atitiks jūsų poreikius. Jūs prisiimate visą riziką, susijusią su Paslaugų, atitinkančių jūsų poreikius, pasirinkimu, kokybe ir veiksnumu. Kai kuriose jurisdikcijose atsiriboti nuo numanomų garantijų neleidžiama, tad gali būti, kad jums ši taisyklė negalioja.</strong>
rights-webservices-term-5 = <strong>Išskyrus kiek to reikalauja įstatymai, „{ -vendor-short-name }“, jos bendradarbiai, licencijų išdavėjai ir platintojai nebus laikomi atsakingais už bet kokią netiesioginę, tyčinę, netyčinę, pasėkminę, baudžiamąją ar kitokią žalą, kilusią dėl „{ -brand-short-name }“ ir Paslaugų naudojimo ar bet kokiu būdu su tuo susijusią.  Pagal šias taisykles, kolektyvinė atsakomybė negali viršyti 500 (penkių šimtų) JAV dolerių.  Kai kuriose jurisdikcijose atsiriboti nuo kai kurių tipų žalos neleidžiama, tad gali būti, kad jums ši taisyklė negalioja.</strong>
rights-webservices-term-6 = Kilus poreikiui, „{ -vendor-short-name }“ šias taisykles gali keisti. Be raštiško „Mozillos“ sutikimo šios taisyklės negali būti taisomos ar atšaukiamos.
rights-webservices-term-7 = Šiose taisyklėse vadovaujamasi JAV Kalifornijos valstijoje galiojančiais įstatymais. Kilus neatitikimams tarp šių taisyklių ir įstatymų, įstatymai laikomi viršesniais. Jei kuri nors šių taisyklių dalis neatitinka įstatymų ar negali būti įgyvendanama, kitos jų dalys bus laikomos galiojančiomis. Jei tarp išverstos šių taisyklių versijos ir originalių taisyklių anglų kalba yra neatitikimų, turi būti vadovaujamasi angliškąja taisyklių versija.
