#filter emptyLines

#define MOZ_LANGPACK_CREATOR mozilla org suomennosprojekti:

# If non-English locales wish to credit multiple contributors, uncomment this
# variable definition and use the format specified.
#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Lasse Liehu</em:contributor> <em:contributor>Jarmo Juslin</em:contributor> <em:contributor>Ville Pohjanheimo</em:contributor>

#unfilter emptyLines
