# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
---
loader: taskgraph.loader.transform:loader

kind-dependencies:
    - toolchain

transforms:
    - taskgraph.transforms.build_attrs:transforms
    - taskgraph.transforms.build_lints:transforms
    - taskgraph.transforms.job:transforms
    - taskgraph.transforms.task:transforms

job-defaults:
    attributes:
        retrigger: true

jobs:
    linux64-valgrind/opt:
        description: "Linux64 Valgrind Opt"
        index:
            product: firefox
            job-name: linux64-valgrind-opt
        treeherder:
            platform: linux64/opt
            symbol: V
            kind: build
            tier: 1
        worker-type: b-linux-aws
        worker:
            docker-image: {in-tree: valgrind-build}
            max-run-time: 72000
            env:
                PERFHERDER_EXTRA_OPTIONS: valgrind
        run:
            using: mozharness
            actions: [get-secrets, build, valgrind-test]
            custom-build-variant-cfg: valgrind
            config:
                - builds/releng_base_firefox.py
                - builds/releng_base_linux_64_builds.py
            script: "mozharness/scripts/fx_desktop_build.py"
            secrets: true
            tooltool-downloads: public
            need-xvfb: true
        fetches:
            toolchain:
                - linux64-binutils
                - linux64-clang
                # bug 1632735
                - linux64-rust-1.41
                - linux64-cbindgen
                - linux64-sccache
                - linux64-nasm
                - linux64-node
                - linux64-lucetc
                - wasi-sysroot
        optimization:
            push-interval-10:
                - linux
