#filter emptyLines

#define MOZ_LANGPACK_CREATOR mozilla.ba

# If non-English locales wish to credit multiple contributors, uncomment this

# variable definition and use the format specified.

#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Kerim Kalamujić</em:contributor> <em:contributor>Alma Granov</em:contributor> <em:contributor>Elvir Ćesko</em:contributor> <em:contributor>Kenan Dervišević</em:contributor> <em:contributor>Mirzet Omerović</em:contributor>

#unfilter emptyLines
