#filter emptyLines

#define MOZ_LANGPACK_CREATOR mozilla.org

# If non-English locales wish to credit multiple contributors, uncomment this
# variable definition and use the format specified.
#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Артем Поліванчук</em:contributor> <em:contributor>Сергій Хоружин</em:contributor> <em:contributor>Тимофій Бабич</em:contributor> <em:contributor>Тимур Фараджев</em:contributor>

#unfilter emptyLines
