# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

rights-title = Sobre os seus dereitos
rights-intro = { -brand-full-name } é un software de código aberto e libre, construído por unha comunidade de centos de persoas de todo o mundo. Hai algunhas cousas que debería saber:
rights-intro-point-1 = { -brand-short-name } está dispoñíbel nos termos da <a data-l10n-name="mozilla-public-license-link">Mozilla Public License</a>. Isto significa que vostede pode usar, copiar e distribuír { -brand-short-name } a outras persoas. Vostede pode modificar o código fonte de { -brand-short-name } para satisfacer as súas necesidades. A licenza Mozilla Public License tamén lle outorga o dereito a distribuír as súas versións modificadas.
rights-intro-point-2 = Non se lle outorga ningún dereito nin licenza sobre as marcas da Fundación Mozilla ou as súas filiais, incluíndo sen limitación o nome ou o logo do Firefox. Información adicional sobre as marcas pode atoparse <a data-l10n-name="mozilla-trademarks-link">aquí</a>.
rights-intro-point-3 = Algunhas características do { -brand-short-name }, como o Informador de erros, dánlle a opción de fornecer información a { -vendor-short-name }. Cando escolle enviar esa información, dálle a { -vendor-short-name } permiso para usala para mellorar os seus produtos, para publicala nos seus sitios web e para distribuíla.
rights-intro-point-4 = Como usamos a súa información persoal e as opinións enviadas a { -vendor-short-name } a través do { -brand-short-name } descríbese na <a data-l10n-name="mozilla-privacy-policy-link">Política de privacidade de { -brand-short-name }</a>.
rights-intro-point-4-unbranded = Calquera política de privacidade aplicábel a este produto debe ser listada aquí.
rights-intro-point-5 = Algunhas características de { -brand-short-name } fan uso de servizos de información baseados na web, porén, non podemos garantirlle que sexan 100% precisos ou libres de erros. Pode atopar máis información, incluso información sobre como desactivar as características que usan estes servizos, en <a data-l10n-name="mozilla-service-terms-link">termos do servizo</a>.
rights-intro-point-5-unbranded = Se este produto incorpora servizos web, calquera termo do servizo aplicábel aos servizos deberían enlazarse nos <a data-l10n-name="mozilla-website-services-link">Servizos de sitios web</a>, na súa sección apropiada.
rights-intro-point-6 = Para reproducir certos tipos de contido de vídeo, { -brand-short-name } descarga certos módulos de descifrado de contido de terceiros.
rights-webservices-header = Servizos de información do { -brand-full-name } baseados na web
rights-webservices = { -brand-full-name } usa servizos de información baseados na web ("Servizos") para fornecer algunhas das características ofrecidas para o seu uso con esta versión binaria do { -brand-short-name } baixo os termos descritos a continuación. Se non quere usar un ou máis dos servizos ou os termos que seguen non son aceptábeis, pode desactivar a característica ou servizo(s). As instrucións sobre como desactivar unha característica ou servizo concreto poden atoparse <a data-l10n-name="mozilla-disable-service-link">aquí</a>. Outras características e servizos poden desactivarse nas preferencias do aplicativo.
rights-safebrowsing = <strong>SafeBrowsing: </strong>Non se recomenda desactivar a característica de navegación segura porque pode dar como resultado que visite sitios no seguros. Se desexa desactivar esta característica por completo, siga estes pasos:
rights-safebrowsing-term-1 = Abrir as preferencias do aplicativo
rights-safebrowsing-term-2 = Seleccione o panel de Seguranza
rights-safebrowsing-term-3 = Desmarque a opción para «{ enableSafeBrowsing-label }»
enableSafeBrowsing-label = Bloquear contido perigoso e enganoso
rights-safebrowsing-term-4 = Agora a navegación segura está desactivada
rights-locationawarebrowsing = <strong>Navegación baseada na localización: </strong>sempre son a elección do usuario. Nunca se envía información sobre a súa localización sen o seu permiso. Se desexa desactivar esta característica por completo, siga estes pasos:
rights-locationawarebrowsing-term-1 = Na barra de navegación, escriba <code>about:config</code>
rights-locationawarebrowsing-term-2 = Introduza geo.enabled
rights-locationawarebrowsing-term-3 = Prema dúas veces na preferencia geo.enabled
rights-locationawarebrowsing-term-4 = Agora a navegación baseada na localización está desactivada
rights-webservices-unbranded = Deben ser incluídas aquí unha visión xeral dos servizos web que incorpora o produto así como instrucións para desactivalas, de ser o caso.
rights-webservices-term-unbranded = Calquera termo de servizo aplicábel para este produto debe ser listado aquí.
rights-webservices-term-1 =
    { -vendor-short-name } e as persoas colaboradoras, licenciadoras e socios traballan para fornecer os servizos máis precisos e actualizados. Porén, non é posíbel garantir que esta información sexa exhaustiva e libre de erros. Por exemplo, o Servizo de navegación segura pode non identificar algúns sitios perigosos e pode identificar algúns sitios seguros por erro e os enderezos que devolven os nosos provedores do servizo de navegación baseado na localización só son estimacións e nin nos nin os nosos provedores garanten a exactitude das localizacións fornecidas.
rights-webservices-term-2 = { -vendor-short-name } podería interromper ou modificar a prestación dos Servizos unilateralmente.
rights-webservices-term-3 = Pode usar estes servizos coa versión correspondente do { -brand-short-name }, e { -vendor-short-name } outórgalle dereitos para facelo. { -vendor-short-name } e os seus licenciadores resérvanse o resto de dereitos dos servizos. Estes termos non limitan ningún dereito outorgado polas licenzas de código aberto aplicábeis ó { -brand-short-name } e as versións do código fonte correspondente do { -brand-short-name }.
rights-webservices-term-4 = <strong>Os Servizos fornécense "tal cal" { -vendor-short-name }, as persoas colaboradoras, licenciatarias e distribuidoras, renuncian a toda garantía, tanto explícitas como implícitas, incluíndo sen limitación, garantías que os Servizos son comercializábeis e satisfagan os seus propósitos particulares. Vostede asume completamente o risco tanto de seleccionar os Servizos como a súa calidade e desempeño. Algunhas xurisdicións non permiten a exclusión de limitacións ou garantías implicadas, de modo que este rexeite de responsabilidades podería non ser aplicábel no seu caso.</strong>
rights-webservices-term-5 = <strong>Agás requirimento legal, { -vendor-short-name }, as persoas contribuidoras, licenzatarias e distribuidoras non serán responsábeis de calquera prexuízo indirecto, especial, incidental, consecuente, punitivo ou exemplarizante relacionado co uso de { -brand-short-name } e os Servizos.  A responsabilidade colectiva baixo estes termos non excederá os 500 $ (cincocentos dólares). Algunhas xurisdicións non permiten a exclusión ou limitación de determinados danos, de modo que esta exclusión e limitación podería non ser aplicábel no seu caso.</strong>
rights-webservices-term-6 = { -vendor-short-name } podería actualizar estes termos cando sexa necesario. Os termos non deben ser modificados ou anulados sen consentimento escrito de { -vendor-short-name }.
rights-webservices-term-7 = Estes termos operan baixo as leis do estado de California dos Estados Unidos de Norteamérica, excluíndo os seus conflitos sobre as provisións legais. Se calquera parte destes termos fora susceptíbel de ser non válido ou non conscriptivo, as porcións restantes manterán toda a forza e efectos. No caso de conflito entre a versión traducida e a orixinal en inglés, prevalecerá esta última.
