# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
---
name: raptor
manifest: testing/raptor/raptor/raptor.ini
suites:
    desktop:
        description: "Tests for page-load performance."
        tests:
            raptor-tp6-amazon: "Cold and warm desktop page-load performance tests for amazon on firefox, chrome, and chromium using WebExtension."
            raptor-tp6-facebook: "Cold and warm desktop page-load performance test for facebook, chrome, and chromium using WebExtension."
            raptor-tp6-google: "Cold and warm desktop page-load performance test for google on firefox, chrome, and chromium using WebExtension."
            raptor-tp6-youtube: "Cold and warm desktop page-load performance test for youtube on firefox, chrome, and chromium using WebExtension."
            raptor-tp6-docs: "Cold and warm desktop page-load performance test for docs on firefox, chrome, and chromium using WebExtension."
            raptor-tp6-sheets: "Cold and warm desktop page-load performance test for sheets on firefox, chrome, and chromium using WebExtension."
            raptor-tp6-slides: "Cold and warm desktop page-load performance test for slides on firefox, chrome, and chromium using WebExtension."
            raptor-tp6-imdb: "Cold and warm desktop page-load performance test for imdb on firefox, chrome, and chromium using WebExtension."
            raptor-tp6-imgur: "Cold and warm desktop page-load performance test for imgur on firefox, chrome, and chromium using WebExtension."
            raptor-tp6-fandom: "Cold and warm desktop page-load performance test for fandom on firefox, chrome, and chromium using WebExtension."
            raptor-tp6-bing: "Cold and warm desktop page-load performance test for bing on firefox, chrome, and chromium using WebExtension."
            raptor-tp6-yandex: "Cold and warm desktop page-load performance test for yandex on firefox, chrome, and chromium using WebExtension."
            raptor-tp6-twitch: "Cold and warm desktop page-load performance test for twitch on firefox, chrome, and chromium using WebExtension."
            raptor-tp6-apple: "Cold and warm desktop page-load performance test for apple on firefox, chrome, and chromium using WebExtension."
            raptor-tp6-microsoft: "Cold and warm desktop page-load performance test for microsoft on firefox, chrome, and chromium using WebExtension."
            raptor-tp6-reddit: "Cold and warm desktop page-load performance test for reddit on firefox, chrome, and chromium using WebExtension."
            raptor-tp6-yahoo-news: "Cold and warm desktop page-load performance test for yahoo-news on firefox, chrome, and chromium using WebExtension."
            raptor-tp6-netflix: "Cold and warm desktop page-load performance test for netflix on firefox, chrome, and chromium using WebExtension."
            raptor-tp6-instagram: "Cold and warm desktop page-load performance test for instagram on firefox, chrome, and chromium using WebExtension."
            raptor-tp6-twitter: "Cold and warm desktop page-load performance test for twitter on firefox, chrome, and chromium using WebExtension."
            raptor-tp6-yahoo-mail: "Cold and warm desktop page-load performance test for yahoo-mail on firefox, chrome, and chromium using WebExtension."
            raptor-tp6-ebay: "Cold and warm desktop page-load performance test for ebay on firefox, chrome, and chromium using WebExtension."
            raptor-tp6-linkedin: "Cold and warm desktop page-load performance test for linkedin on firefox, chrome, and chromium using WebExtension."
            raptor-tp6-wikipedia: "Cold and warm desktop page-load performance test for and wikipedia on firefox, chrome, and chromium using WebExtension."
            raptor-tp6-google-mail: "Cold and warm desktop page-load performance test google-mail on firefox, chrome, and chromium using WebExtension."
            raptor-tp6-office: "Cold and warm desktop page-load performance test office on firefox, chrome, and chromium using WebExtension."
            raptor-tp6-outlook: "Cold and warm desktop page-load performance test outlook on firefox, chrome, and chromium using WebExtension."
            raptor-tp6-pinterest: "Cold and warm desktop page-load performance test pinterest on firefox, chrome, and chromium using WebExtension."
            raptor-tp6-paypal: "Cold and warm desktop page-load performance test for paypal on firefox, chrome, and chromium using WebExtension."
            raptor-tp6-tumblr: "Cold and warm desktop page-load performance test for tumblr on firefox, chrome, and chromium using WebExtension."
            raptor-tp6-binast-instagram-firefox: "Desktop page-load performance test for instagram on firefox with binast recordings and flag enabled using WebExtension."
            amazon: "Desktop page-load performance test for amazon, and youtube using Browsertime."
            bing-search: "Desktop page-load performance test for bing-search using Browsertime."
            facebook: "Desktop page-load performance test for facebook using Browsertime."
            google-search: "Desktop page-load performance test for google-search using Browsertime."
            google-slides: "Desktop page-load performance test for google-slides using Browsertime."
            wikipedia: "Desktop page-load performance test for wikipedia using Browsertime."
            yahoo-news: "Desktop page-load performance test for yahoo-news using Browsertime."
            youtube: "Desktop page-load performance test for youtube using Browsertime."
    mobile:
        description: "Page-load performance test suite on Android."
        tests:
            raptor-tp6m-amazon: "Cold and warm android page-load performance test for amazon on geckoview, refbrow, fenix, and fennec68 using WebExtension."
            raptor-tp6m-facebook: "Cold and warm android page-load performance test for facebook on geckoview, refbrow, fenix, and fennec68 using WebExtension."
            raptor-tp6m-google: "Cold and warm android page-load performance test for google on geckoview, refbrow, fenix, and fennec68 using WebExtension."
            raptor-tp6m-youtube: "Cold and warm android page-load performance test for youtube on geckoview, refbrow, fenix, and fennec68 using WebExtension."
            raptor-tp6m-instagram: "Cold and warm android page-load performance test for instagram on geckoview, refbrow, fenix, and fennec68 using WebExtension."
            raptor-tp6m-bing: "Cold and warm android page-load performance test for bing on geckoview, refbrow, fenix, and fennec68 using WebExtension."
            raptor-tp6m-bing-restaurants: "Cold and warm android page-load performance test for bing-restaurants on geckoview, refbrow, fenix, and fennec68 using WebExtension."
            raptor-tp6m-ebay-kleinanzeigen: "Cold and warm android page-load performance test for ebay-kleinanzeigen on geckoview, refbrow, fenix, and fennec68 using WebExtension."
            raptor-tp6m-google-maps: "Cold and warm android page-load performance test for google-maps on geckoview, refbrow, fenix, and fennec68 using WebExtension."
            raptor-tp6m-google-restaurants: "Cold and warm android page-load performance test for google-restaurants on geckoview, refbrow, fenix, and fennec68 using WebExtension."
            raptor-tp6m-booking: "Cold and warm android page-load performance test for booking on geckoview, refbrow, fenix, and fennec68 using WebExtension."
            raptor-tp6m-cnn: "Cold and warm android page-load performance test for cnn on geckoview, refbrow, fenix, and fennec68 using WebExtension."
            raptor-tp6m-cnn-ampstories: "Cold and warm android page-load performance test for booking on geckoview, refbrow, fenix, and fennec68 using WebExtension."
            raptor-tp6m-amazon-search: "Cold and warm android page-load performance test for amazon-search on geckoview, refbrow, fenix, and fennec68 using WebExtension."
            raptor-tp6m-wikipedia: "Cold and warm android page-load performance test for wikipedia on geckoview, refbrow, fenix, and fennec68 using WebExtension."
            raptor-tp6m-youtube-watch: "Cold and warm android page-load performance test for youtube-watch on geckoview, refbrow, fenix, and fennec68 using WebExtension."
            raptor-tp6m-reddit: "Cold and warm android page-load performance test for reddit on geckoview, refbrow, fenix, and fennec68 using WebExtension."
            raptor-tp6m-bbc: "Cold and warm android page-load performance test for bbc on geckoview, refbrow, fenix, and fennec68 using WebExtension."
            raptor-tp6m-stackoverflow: "Cold and warm android page-load performance test for stackoverflow on geckoview, refbrow, fenix, and fennec68 using WebExtension."
            raptor-tp6m-microsoft-support: "Cold and warm android page-load performance test for microsoft-support on geckoview, refbrow, fenix, and fennec68 using WebExtension."
            raptor-tp6m-jianshu: "Cold and warm android page-load performance test for jianshu on geckoview, refbrow, fenix, and fennec68 using WebExtension."
            raptor-tp6m-imdb: "Cold and warm android page-load performance test for imdb on geckoview, refbrow, fenix, and fennec68 using WebExtension."
            raptor-tp6m-allrecipes: "Cold and warm android page-load performance test for allrecipesjianshu on geckoview, refbrow, fenix, and fennec68 using WebExtension."
            raptor-tp6m-espn: "Cold and warm android page-load performance test for espn on geckoview, refbrow, fenix, and fennec68 using WebExtension."
            raptor-tp6m-web-de: "Cold and warm android page-load performance test for web-de on geckoview, refbrow, fenix, and fennec68 using WebExtension."
            raptor-tp6m-facebook-cristiano: "Cold and warm android page-load performance test for facebook-cristiano on geckoview, refbrow, fenix, and fennec68 using WebExtension."
            amazon: "Android page-load performance test for amazon using Browsertime."
            youtube: "Android page-load performance test for youtube using Browsertime."
            allrecipes: "Android page-load performance test for allrecipes using Browsertime."
            amazon-search: "Android page-load performance test for amazon-search using Browsertime."
            bbc: "Android page-load performance test for bbc using Browsertime."
            bing: "Android page-load performance test for bing using Browsertime."
            bing-search-restaurants: "Android page-load performance test for bing-search-restaurants using Browsertime."
            booking: "Android page-load performance test for booking using Browsertime."
            cnn: "Android page-load performance test for cnn using Browsertime."
            cnn-ampstories: "Android page-load performance test for cnn-ampstories using Browsertime."
            ebay-kleinanzeigen: "Android page-load performance test for ebay-kleinanzeigen using Browsertime."
            ebay-kleinanzeigen-search: "Android page-load performance test for ebay-kleinanzeigen-search using Browsertime."
            espn: "Android page-load performance test for espn using Browsertime."
            facebook: "Android page-load performance test for facebook using Browsertime."
            facebook-cristiano: "Android page-load performance test for facebook-cristiano using Browsertime."
            google: "Android page-load performance test for google using Browsertime."
            google-maps: "Android page-load performance test for google-maps using Browsertime."
            google-search-restaurants: "Android page-load performance test for google-search-restaurants using Browsertime."
            imdb: "Android page-load performance test for imdb using Browsertime."
            instagram: "Android page-load performance test for instagram using Browsertime."
            jianshu: "Android page-load performance test for jianshu using Browsertime."
            microsoft-support: "Android page-load performance test for microsoft-support using Browsertime."
            reddit: "Android page-load performance test for reddit using Browsertime."
            stackoverflow: "Android page-load performance test for stackoverflow using Browsertime."
            web-de: "Android page-load performance test for web-de using Browsertime."
            wikipedia: "Android page-load performance test for wikipedia using Browsertime."
            youtube-watch: "Android page-load performance test for youtube-watch using Browsertime."
    live:
        description: "A set of test pages that are run as live sites instead of recorded versions. These tests are available on all browsers, on all platforms."
    benchmarks:
        description: "Standard benchmarks are third-party tests (i.e. Speedometer) that we have integrated into Raptor to run per-commit in our production CI. "
    scenario:
        description: "Tests that perform a specific action (a scenario), i.e. idle application, idle application in background, etc."
    unittests:
        description: "These tests aren't used in standard testing, they are only used in the Raptor unit tests (they are similar to raptor-tp6 tests though)."
