# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#filter emptyLines

#define MOZ_LANGPACK_CREATOR Fennec Breton Team

# If non-English locales wish to credit multiple contributors, uncomment this

# variable definition and use the format specified.

#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Alan Monfort</em:contributor> <em:contributor>Philippe Basciano-Le Gall</em:contributor> <em:contributor>Denis Arnaud</em:contributor> <em:contributor>Michel Nédélec</em:contributor>

#unfilter emptyLines
