# This Source Code Form is subject to the terms of the Waterfox Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#filter emptyLines

#define MOZ_LANGPACK_CREATOR Waterfox Lietuvoje

# If non-English locales wish to credit multiple contributors, uncomment this

# variable definition and use the format specified.

#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Gintautas Grigas</em:contributor> <em:contributor>Tatjana Jevsikova</em:contributor> <em:contributor>Rimas Kudelis</em:contributor>

#unfilter emptyLines
