# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with
# your locale code, and link to your translated pages as soon as they're
# live.

#define bookmarks_title ఇష్టాంశాలు
#define bookmarks_heading ఇష్టాంశాలు

#define bookmarks_toolbarfolder ఇష్టాంశాల పనిముట్లపట్టీ సంచయం
#define bookmarks_toolbarfolder_description ఇష్టాంశాల పనిముట్లపట్టీలో చూడాలనుకునే ఇష్టాంశాలను ఈ సంచయంలో చేర్చండి

# LOCALIZATION NOTE (getting_started):
# link title for https://www.mozilla.org/en-US/firefox/central/
#define getting_started ప్రారంభించబడుతోంది

# LOCALIZATION NOTE (firefox_heading):
# Firefox links folder name
#define firefox_heading Mozilla Firefox

# LOCALIZATION NOTE (firefox_help):
# link title for https://www.mozilla.org/en-US/firefox/help/
#define firefox_help సహాయం మరియు బోధనలు

# LOCALIZATION NOTE (firefox_customize):
# link title for https://www.mozilla.org/en-US/firefox/customize/
#define firefox_customize Firefox ను మలచు

# LOCALIZATION NOTE (firefox_community):
# link title for https://www.mozilla.org/en-US/contribute/
#define firefox_community పాలుపంచుకోండి

# LOCALIZATION NOTE (firefox_about):
# link title for https://www.mozilla.org/en-US/about/
#define firefox_about మా గురించి

# LOCALIZATION NOTE (nightly_heading):
# Firefox Nightly links folder name
#define nightly_heading Firefox Nightly వనరులు

# LOCALIZATION NOTE (nightly_blog):
# Nightly builds only, link title for https://blog.nightly.mozilla.org/
#define nightly_blog Firefox Nightly బ్లాగు

# LOCALIZATION NOTE (bugzilla):
# Nightly builds only, link title for https://bugzilla.mozilla.org/
#define bugzilla Mozilla బగ్ ట్రాకర్

# LOCALIZATION NOTE (mdn):
# Nightly builds only, link title for https://developer.mozilla.org/
#define mdn Mozilla Developer Network

# LOCALIZATION NOTE (nightly_tester_tools):
# Nightly builds only, link title for https://addons.mozilla.org/en-US/firefox/addon/nightly-tester-tools/
#define nightly_tester_tools Nightly Tester Tools

# LOCALIZATION NOTE (crashes):
# Nightly builds only, link title for about:crashes
#define crashes మీ క్రాషులన్నీ

# LOCALIZATION NOTE (irc):
# Nightly builds only, link title for ircs://irc.mozilla.org/nightly
#define irc Nightly గురించి IRCలో చర్చించు

# LOCALIZATION NOTE (planet):
# Nightly builds only, link title for https://planet.mozilla.org/
#define planet Planet Mozilla

#unfilter emptyLines
