# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

rights-title = O vašim pravima
rights-intro = { -brand-full-name } je besplatan softver otvorenog koda, kojeg je razvila zajednica sačinjena od hiljada ljudi iz cijelog svijeta. Postoji nekoliko stvari koje biste trebali znati:
rights-intro-point-1 = { -brand-short-name } vam je dostupan pod uslovima <a data-l10n-name="mozilla-public-license-link">Mozilla Public License</a>. Ovo znači da možete koristiti, kopirati i distribuirati { -brand-short-name } drugima. Također smijete mijenjati izvorni kod { -brand-short-name }a prema vašim potrebama. Mozilla Public License vam daje pravo da distribuirate vaše modificirane verzije.
rights-intro-point-2 = Vama nisu dodijeljena nikakva prava ili licence za zaštićene znakove Mozilla Foundationa ili drugog lica, uključujući bez ograničenja i Firefox ime i logo. Dodatne informacije o zaštićenim znakovima možete pronaći <a data-l10n-name="mozilla-trademarks-link">ovdje</a>.
rights-intro-point-3 = Neke opcije u { -brand-short-name }u, poput Izvjestioca o rušenju, daju vam mogućnost da pošaljete povratne informacije { -vendor-short-name }-i. Slanjem povratnih informacija, { -vendor-short-name }-i dajete pravo da iste iskoristi za poboljšanje svojih proizvoda, da objavi informacije na svojim web stranicama, i da distribuira informacije.
rights-intro-point-4 = Načini na koje koristimo vaše lične i povratne informacije koje ste poslali { -vendor-short-name }-i putem { -brand-short-name }a opisani su u <a data-l10n-name="mozilla-privacy-policy-link">{ -brand-short-name } Polici privatnosti</a>.
rights-intro-point-4-unbranded = Bilo koje primjenjivo pravilo privatnosti za ovaj proizvod bi trebalo biti izlistano ovdje.
rights-intro-point-5 = Neke { -brand-short-name } opcije koriste web-bazirane informacijske servise, međutim, ne možemo garantovati da su 100% tačne ili bez greške. Više detalja, uključujući kako onemogućiti opcije koje koriste ove servise, možete pronaći u <a data-l10n-name="mozilla-service-terms-link">uvjeti servisa</a>.
rights-intro-point-5-unbranded = Ukoliko su web servisi uključeni u ovaj proizvod, bilo kakvi primjenjivi uvjeti za uslugu(e) bi trebali biti vezani za <a data-l10n-name="mozilla-website-services-link">Web Site servisi</a> sekciju.
rights-intro-point-6 = Da bi mogao reproducirati neke vrste video zapisa, { -brand-short-name }  od trećih lica preuzima određene module za dekripciju.
rights-webservices-header = { -brand-full-name } Web-bazirani informacioni servisi
rights-webservices = { -brand-full-name } koristi web-bazirane servise ("Servisi") da bi vam omogućio neke od opcija koje možete koristiti uz ovu binarnu verziju { -brand-short-name }a pod uslovima opisanim u nastavku. Ukoliko ne želite koristiti jedan ili više Servisa ili su vam uslovi korištenja neprihvatljivi, možete onemogućiti opciju ili Servis(e). Instrukcije kako onemogućiti opciju ili Servis možete pronaći <a data-l10n-name="mozilla-disable-service-link">ovdje</a>. Druge mogućnosti i Usluge mogu biti onemogućeni u postavkama aplikacije.
rights-safebrowsing = <strong>Sigurno surfanje: </strong>Onemogućavanje Sigurnog surfanja nije preporučeno jer bi moglo rezultirati vašim posjetama nesigurnim stranicama. Ukoliko želite da onemogućite ovu opciju u potpunosti, pratite sljedeće korake:
rights-safebrowsing-term-1 = Otvorite postavke aplikacije
rights-safebrowsing-term-2 = Izaberite sekciju Sigurnost
rights-safebrowsing-term-3 = Isključite opciju kako biste "{ enableSafeBrowsing-label }"
enableSafeBrowsing-label = Blokiraj opasan i obmanjujući sadržaj
rights-safebrowsing-term-4 = Sigurno surfanje je sada onemogućeno
rights-locationawarebrowsing = <strong>Lokacijski-svjesno surfanje: </strong>je uvijek opcionalno. Nijedna informacija o lokaciji nije poslata bez vaše dozvole. Ukoliko želite da onemogućite ovu opciju u potpunosti, pratite sljedeće korake:
rights-locationawarebrowsing-term-1 = U traci za URL, upišite <code>about:config</code>
rights-locationawarebrowsing-term-2 = Upišite geo.enabled
rights-locationawarebrowsing-term-3 = Dva puta kliknite na geo.enabled postavku
rights-locationawarebrowsing-term-4 = Lokacijski-svjesno surfanje je sada onemogućeno
rights-webservices-unbranded = Pregled servisa web stranica uključenih u proizvod, zajedno sa uputstvima kako da ih onemogućite, trebao bi biti prikazan ovdje.
rights-webservices-term-unbranded = Bilo kakvi primjenjivi uslovi korištenja za ovaj proizvod trebaju biti navedeni ovdje.
rights-webservices-term-1 = { -vendor-short-name } i njeni saradnici, davatelji licenci i partneri rade kako bi omogućili najpreciznije Servise. Međutim, mi ne možemo garantovati da je ova informacija opsežna i bez greške. Naprimjer, servis Sigurnog surfanja može ne identifikovati neku riskantnu stranicu, a neke sigurne stranice pogrešno identifikovati, dok su sve lokacije koje vrate naši pružatelji usluga Lokacijski-svjesnog surfanja samo procjena i niti mi niti naši pružatelji usluga ne možemo garantovati njihovu potpunu tačnost.
rights-webservices-term-2 = { -vendor-short-name } može ukinuti ili promijeniti Servise prema vlastitom nahođenju.
rights-webservices-term-3 = Dobrodošli ste da koristite ove Servise sa pratećom verzijom { -brand-short-name }a, i { -vendor-short-name } vam daje pravo na to. { -vendor-short-name } i njeni davaoci licenci zadržavaju sva ostala prava na Servise. Ovi uslovi nisu namijenjeni da ograniče bilo koje pravo izdato pod open source licencama primjenjivim na { -brand-short-name } i odgovarajuće source code verzije { -brand-short-name }-a.
rights-webservices-term-4 = <strong>Servisi su omogućeni "as-is." { -vendor-short-name }, sa svojim saradnicima, davateljima licenci, i distributerima, odriče se garancija, bilo izravnih ili neizravnih, uključujući bez ograničenja, garancije da su Servisi podesni za prodaju i da odgovaraju vašim posebnim potrebama. Vi snosite cjelokupan rizik za izbor Servisa za vaše potrebe kao i za kvalitetu i performanse Servisa. Neke jurisdikcije ne dopuštaju isključivanje ili ograničavanje podrazumijevanih garancija, pa se to odricanje ne odnosi na vas.</strong>
rights-webservices-term-5 = <strong>Osim u slučajevima propisanim zakonom, { -vendor-short-name }, sa svojim saradnicima, davateljima licenci, i distributerima neće biti odgovorna za bilo kakve neizravne, posebne, slučajne, posljedične, kaznene ili primjerne štete koje proizlaze iz ili se na bilo koji način odnose na korištenje { -brand-short-name }a i Servisa. Kolektivna odgovornost pod ovim uvjetima neće biti veća od $500 (petsto dolara). Neke jurisdikcije ne dopuštaju isključenje ili ograničenje određenih šteta, tako da se ovo isključenje i ograničenje možda ne odnose na vas.</strong>
rights-webservices-term-6 = { -vendor-short-name } može promijeniti ove uslove prema potrebi s vremena na vrijeme. Ovi uslovi se ne smiju mijenjati ili odbaciti bez pismene saglasnosti { -vendor-short-name }-e.
rights-webservices-term-7 = Ovi uslovi su uređeni prema zakonu države Kalifornija, SAD, isključujući sukob zakonskih odredbi. Ako se bilo koji dio ovih uvjeta smatra nevažećim ili neprimjenjivim, preostali dijelovi će ostati u punoj snazi i efektu. U slučaju sukoba između prevedene verzije ovih uslova i verzije na engleskom jeziku, verzija na engleskom jeziku preuzima kontrolu.
