#filter emptyLines

#define MOZ_LANGPACK_CREATOR Mozilla.cz

#define MOZ_LANGPACK_HOMEPAGE https://www.mozilla.cz/

# If non-English locales wish to credit multiple contributors, uncomment this
# variable definition and use the format specified.
#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Pavel Franc</em:contributor> <em:contributor>Michal Kec</em:contributor> <em:contributor>Michal Stanke</em:contributor>

#unfilter emptyLines
