#filter emptyLines

#define MOZ_LANGPACK_CREATOR mozilla.org

# If non-English locales wish to credit multiple contributors, uncomment this

# variable definition and use the format specified.

#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Огнян Кулев</em:contributor> <em:contributor>Митко Митев</em:contributor> <em:contributor>Златко Попов</em:contributor> <em:contributor>Милен Иванов</em:contributor> <em:contributor>Стоян Димитров</em:contributor>

#unfilter emptyLines
