#filter emptyLines

#define MOZ_LANGPACK_CREATOR Mozilla.sk

#define MOZ_LANGPACK_HOMEPAGE http://www.mozilla.sk/

# If non-English locales wish to credit multiple contributors, uncomment this
# variable definition and use the format specified.
#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Vlado Valaštiak (wladow)</em:contributor> <em:contributor>Ján Kendi (Jacen)</em:contributor>

#unfilter emptyLines
