[package]
name = "malloc_size_of"
version = "0.0.1"
authors = ["The Servo Project Developers"]
license = "MIT/Apache-2.0"
publish = false

[lib]
path = "lib.rs"

[features]
servo = [
    "crossbeam-channel",
    "hyper",
    "hyper_serde",
    "keyboard-types",
    "serde",
    "serde_bytes",
    "string_cache",
    "time",
    "url",
    "webrender_api",
    "xml5ever",
    "content-security-policy",
    "uuid",
    "accountable-refcell",
]

[dependencies]
accountable-refcell = { version = "0.2.0", optional = true }
app_units = "0.7"
content-security-policy = {version = "0.3.0", features = ["serde"], optional = true}
crossbeam-channel = { version = "0.3", optional = true }
cssparser = "0.28"
euclid = "0.20"
hashglobe = { path = "../hashglobe" }
hyper = { version = "0.12", optional = true }
hyper_serde = { version = "0.11", optional = true }
keyboard-types = {version = "0.4.3", optional = true}
selectors = { path = "../selectors" }
serde = { version = "1.0.27", optional = true }
serde_bytes = { version = "0.11", optional = true }
servo_arc = { path = "../servo_arc" }
smallbitvec = "2.3.0"
smallvec = "1.0"
string_cache = { version = "0.8", optional = true }
thin-slice = "0.1.0"
time = { version = "0.1.17", optional = true }
url = { version = "2.0", optional = true }
webrender_api = { git = "https://github.com/servo/webrender", optional = true }
xml5ever = { version = "0.16", optional = true }
void = "1.0.2"
uuid = {version = "0.8", features = ["v4"], optional = true}
