# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

rights-title = ನಿಮ್ಮ ಹಕ್ಕುಗಳ ಬಗ್ಗೆ
rights-intro = { -brand-full-name } ಒಂದು ಸ್ವತಂತ್ರ ಮತ್ತು ಮುಕ್ತ ತಂತ್ರಾಂಶವಾಗಿದ್ದು, ಇದನ್ನು ವಿಶ್ವದಾದ್ಯಂತ ಹರಡಿರುವ ಸಾವಿರಾರು ಸಂಖ್ಯೆಯ ಸಮುದಾಯ ರಚಿಸಲಾಗಿದೆ. ನೀವು ತಿಳಿಯಬೇಕಾದ ಕೆಲವು ವಿಷಯಗಳಿವೆ:
rights-intro-point-1 = { -brand-short-name } ಅನ್ನು ಮೋಝಿಲ್ಲಾ ಸಾರ್ವಜನಿಕ ಲೈಸೆನ್ಸಿನ ಅಡಿಯಲ್ಲಿ<a data-l10n-name="mozilla-public-license-link">ನಿಮಗೆ ಲಭ್ಯವಾಗುವಂತೆ ಮಾಡಲಾಗಿದೆ</a>. This means you may use, copy and distribute { -brand-short-name } to others.  You are also welcome to modify the source code of { -brand-short-name } as you want to meet your needs. The Mozilla Public License also gives you the right to distribute your modified versions.
rights-intro-point-2 = You are not granted any trademark rights or licenses to the trademarks of the Mozilla Foundation or any party, including without limitation the Firefox name or logo. Additional information on trademarks may be found <a data-l10n-name="mozilla-trademarks-link">ಇಲ್ಲಿ</a>.
rights-intro-point-3 = ಕುಸಿತ ವರದಿಗಾರನಂತಹ { -brand-short-name } ನಲ್ಲಿನ ಕೆಲವು ಸೌಲಭ್ಯಗಳು, { -vendor-short-name } ಕುರಿತು ನಿಮ್ಮ ಅಭಿಪ್ರಾಯವನ್ನು ಒದಗಿಸಲು ಅವಕಾಶವನ್ನು ಒದಗಿಸುತ್ತದೆ. ಅಭಿಪ್ರಾಯವನ್ನು ಒದಗಿಸು ಎನ್ನುವುದನ್ನು ಆರಿಸುವ ಮೂಲಕ, ನೀವು { -vendor-short-name } ಗೆ ತನ್ನ ಉತ್ಪನ್ನಗಳನ್ನು ಉತ್ತಮಗೊಳಿಸಲು ಅಭಿಪ್ರಾಯಗಳನ್ನು ಬಳಸಿಕೊಳ್ಳಲು, ತನ್ನ ಜಾಲತಾಣಗಳಲ್ಲಿ ಅಭಿಪ್ರಾಯವನ್ನು ಪ್ರಕಟಿಸಲು, ಮತ್ತು ಅಭಿಪ್ರಾಯವನ್ನು ವಿತರಿಸಲು ನೀವು ಅನುಮತಿಯನ್ನು ನೀಡುತ್ತೀರಿ.
rights-intro-point-4 = { -brand-short-name } ಮೂಲಕ { -vendor-short-name } ಗೆ ಸಲ್ಲಿಸಿದ ನಿಮ್ಮ ವೈಯಕ್ತಿಕ ಮಾಹಿತಿ ಮತ್ತು ಅಭಿಪ್ರಾಯವನ್ನು ನಾವು ಹೇಗೆ ಬಳಸುತ್ತೇವೆ ಎನ್ನುವುದು <a data-l10n-name="mozilla-privacy-policy-link">{ -brand-short-name } ಗೌಪ್ಯತಾ ನೀತಿಯಲ್ಲಿ ವಿವರಿಸಲಾಗಿರುತ್ತದೆ</a>.
rights-intro-point-4-unbranded = ಈ ಉತ್ಪನ್ನಕ್ಕಾಗಿ ಅನ್ವಯಿಸಲ್ಪಡುವ ಗೌಪ್ಯತಾ ನೀತಿಗಳನ್ನು ಇಲ್ಲಿ ಪಟ್ಟಿ ಮಾಡಬೇಕು.
rights-intro-point-5 = ಕೆಲವು { -brand-short-name } ಸೌಲಭ್ಯಗಳು ಜಾಲ-ಆಧರಿತವಾದ ಮಾಹಿತಿ ಸೇವೆಗಳನ್ನು ಬಳಸುತ್ತವೆ, ಆದರೆ, ಅವುಗಳು 100% ನಿಖರವಾಗಿವೆ ಅಥವ ದೋಷ-ಮುಕ್ತವಾಗಿವೆ ಎಂದು ನಾವು ಖಚಿತತೆಯನ್ನು ನೀಡುವುದಿಲ್ಲ. ಈ ಸೇವೆಗಳನ್ನು ಬಳಸುವ ಸೌಲಭ್ಯಗಳನ್ನು ಹೇಗೆ ನಿಷ್ಕ್ರಿಯಗೊಳಿಸಬೇಕು ಎನ್ನುವ ಕುರಿತಾದ ಮಾಹಿತಿಯೂ ಸೇರಿದಂತೆ ಹೆಚ್ಚಿನ ವಿವರಗಳನ್ನು <a data-l10n-name="mozilla-service-terms-link">ಸೇವೆಯ ನಿಯಮಗಳಲ್ಲಿ ಕಾಣಬಹುದು</a>.
rights-intro-point-5-unbranded = ಈ ಉತ್ಪನ್ನವು ಜಾಲ ಸೇವೆಗಳನ್ನು ಅಳವಡಿಸಿದಲ್ಲಿ, ಸೇವೆಗಾಗಿ(ಗಳಿಗಾಗಿ) ಅನ್ವಯಿಸಲ್ಪಡುವ ಸೇವೆಯ ನಿಯಮಗಳನ್ನು ಇಲ್ಲಿಗೆ ಕೊಂಡಿ ಜೋಡಿಸಬೇಕು<a data-l10n-name="mozilla-website-services-link">ಜಾಲತಾಣ ಸೇವೆಗಳು</a>ವಿಭಾಗ.
rights-intro-point-6 = ಕೆಲವು ತರಹದ ವೀಡಿಯೋಗಳನ್ನು ತೋರಿಸಲು, { -brand-short-name } ಕೆಲವು ವಿಷಯ ಡೀಕ್ರಿಪ್ಷನ್ ಮೊಡ್ಯುಲ್‌ಗಳನ್ನು ಮೂರನೆಯವರಿಂದ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿಕೊಳ್ಳಲಾಗುವುದು.
rights-webservices-header = { -brand-full-name } ಜಾಲ-ಆಧರಿತ ಮಾಹಿತಿ ಸೇವೆಗಳು
rights-webservices = { -brand-full-name } uses web-based information services ("Services") to provide some of the features provided for your use with this binary version of { -brand-short-name } under the terms described below. If you do not want to use one or more of the Services or the terms below are unacceptable, you may disable the feature or Service(s). Instructions on how to disable a particular feature or Service may be found <a data-l10n-name="mozilla-disable-service-link">ಇಲ್ಲಿ</a>. ಅನ್ವಯದ ಆದ್ಯತೆಗಳಲ್ಲಿ ಇತರೆ ಸೌಲಭ್ಯಗಳನ್ನು ಮತ್ತು ಸೇವೆಗಳನ್ನು ನಿಷ್ಕ್ರಿಯಗೊಳಿಸಬಹುದು.
rights-safebrowsing = <strong>ಸುರಕ್ಷಿತವೀಕ್ಷಣೆ:</strong>ಸುರಕ್ಷಿತ ಜಾಲವೀಕ್ಷಣೆ ಸೌಲಭ್ಯವನ್ನು ನಿಷ್ಕ್ರಿಯಗೊಳಿಸುವುದನ್ನು ಸಲಹೆ ಮಾಡಲಾಗುವುದಿಲ್ಲ ಏಕೆಂದರೆ ಇದು ಸುರಕ್ಷಿತವಲ್ಲದ ತಾಣಗಳಿಗೆ ನೀವು ಹೋಗುವ ಸಾಧ್ಯತೆ ಇದೆ.  ನೀವು ಈ ಸೌಲಭ್ಯವನ್ನು ಸಂಪೂರ್ಣವಾಗಿ ನಿಷ್ಕ್ರಿಯಗೊಳಿಸಲು ಬಯಸಿದರೆ, ಈ ಹಂತಗಳನ್ನು ಅನುಸರಿಸಿ:
rights-safebrowsing-term-1 = ಅನ್ವಯದ ಆದ್ಯತೆಗಳನ್ನು ತೆರೆಯಿರಿ
rights-safebrowsing-term-2 = ಸುರಕ್ಷತಾ ಆಯ್ಕೆಯನ್ನು ಆರಿಸು
rights-safebrowsing-term-3 = "{ enableSafeBrowsing-label }" ಆಯ್ಕೆಯನ್ನು ತೆಗೆ
enableSafeBrowsing-label = ಅಪಾಯಕಾರಿ ಮತ್ತು ವಂಚಕ ವಿಷಯಗಳನ್ನು ನಿರ್ಬಂಧಿಸಿ
rights-safebrowsing-term-4 = ಸುರಕ್ಷತ ವೀಕ್ಷಣೆಯನ್ನು ನಿಷ್ಕ್ರಿಯಗೊಂಡಿದೆ
rights-locationawarebrowsing = <strong>ಸ್ಥಳದ ಅರಿವಿರುವ ಜಾಲವೀಕ್ಷಣೆ:  </strong>ಯಾವಾಗಲೂ ಆರಿಸಲಾಗಿರುತ್ತದೆ.  ಯಾವುದೆ ಸ್ಥಳದ ಮಾಹಿತಿಯನ್ನು ಎಂದಿಗೂ ಸಹ ನಿಮ್ಮ ಅನುಮತಿ ಇಲ್ಲದೆ ಕಳುಹಿಸಲಾಗುವುದಿಲ್ಲ.  ನೀವು ಈ ಸೌಲಭ್ಯವನ್ನು ಸಂಪೂರ್ಣವಾಗಿ ಬಳಸಲು ನೀವು ಬಯಸಿದರೆ, ಈ ಕೆಳಗಿನ ಹಂತಗಳನ್ನು ಬಳಸಿ:
rights-locationawarebrowsing-term-1 = URL ಪಟ್ಟಿಯಲ್ಲಿ, ಹೀಗೆ ನಮೂದಿಸಿ <code>about:config</code>
rights-locationawarebrowsing-term-2 = geo.enabled ಎಂದು ನಮೂದಿಸಿ
rights-locationawarebrowsing-term-3 = geo.enabled ಆದ್ಯತೆಯ ಮೇಲೆ ಎರಡು ಬಾರಿ ಕ್ಲಿಕ್ ಮಾಡಿ
rights-locationawarebrowsing-term-4 = ಸ್ಥಳದ-ಅರಿವಿರುವ ಜಾಲವೀಕ್ಷಣೆಯನ್ನು ಈ ನಿಷ್ಕ್ರಿಯಗೊಳಿಸಲಾಗಿದೆ
rights-webservices-unbranded = An overview of the website services the product incorporates, along with instructions on how to disable them, if applicable, should be included here.
rights-webservices-term-unbranded = ಈ ಉತ್ಪನ್ನಕ್ಕಾಗಿ ಅನ್ವಯಿಸಲ್ಪಡುವ ಯಾವುದೆ ಸೇವೆಯ ನಿಯಮಗಳನ್ನು ಇಲ್ಲಿ ಪಟ್ಟಿ ಮಾಡಲಾಗುತ್ತದೆ.
rights-webservices-term-1 = { -vendor-short-name } and its contributors, licensors and partners work to provide the most accurate and up-to-date Services.  However, we cannot guarantee that this information is comprehensive and error-free.  For example, the Safe Browsing Service may not identify some risky sites and may identify some safe sites in error and the Location Aware Service all locations returned by our service providers are estimates only and neither we nor our service providers guarantee the accuracy of the locations provided.
rights-webservices-term-2 = { -vendor-short-name } may discontinue or change the Services at its discretion.
rights-webservices-term-3 = You are welcome to use these Services with the accompanying version of { -brand-short-name }, and { -vendor-short-name } grants you its rights to do so.  { -vendor-short-name } and its licensors reserve all other rights in the Services.  These terms are not intended to limit any rights granted under open source licenses applicable to { -brand-short-name } and to corresponding source code versions of { -brand-short-name }.
rights-webservices-term-4 = <strong>The Services are provided "as-is."  { -vendor-short-name }, its contributors, licensors, and distributors, disclaim all warranties, whether express or implied, including without limitation, warranties that the Services are merchantable and fit for your particular purposes.  You bear the entire risk as to selecting the Services for your purposes and as to the quality and performance of the Services. Some jurisdictions do not allow the exclusion or limitation of implied warranties, so this disclaimer may not apply to you.</strong>
rights-webservices-term-5 = <strong>Except as required by law, { -vendor-short-name }, its contributors, licensors, and distributors will not be liable for any indirect, special, incidental, consequential, punitive, or exemplary damages arising out of or in any way relating to the use of { -brand-short-name } and the Services.  The collective liability under these terms will not exceed $500 (five hundred dollars). Some jurisdictions do not allow the exclusion or limitation of certain damages, so this exclusion and limitation may not apply to you.</strong>
rights-webservices-term-6 = { -vendor-short-name } may update these terms as necessary from time to time. These terms may not be modified or canceled without { -vendor-short-name }'s written agreement.
rights-webservices-term-7 = These terms are governed by the laws of the state of California, U.S.A., excluding its conflict of law provisions. If any portion of these terms is held to be invalid or unenforceable, the remaining portions will remain in full force and effect. In the event of a conflict between a translated version of these terms and the English language version, the English language version shall control.
