#filter emptyLines

#define MOZ_LANGPACK_CREATOR mozilladanmark.dk

# If non-English locales wish to credit multiple contributors, uncomment this
# variable definition and use the format specified.

#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Jesper Kristensen</em:contributor> <em:contributor>Søren Lønbæk Nygaard Christensen</em:contributor> <em:contributor>Søren Munk Skrøder</em:contributor>

#unfilter emptyLines
