[package]
name = "peek-poke"
version = "0.3.0"
authors = ["Dan Glastonbury <dan.glastonbury@gmail.com>"]
repository = "https://github.com/servo/webrender"
description = "A mechanism for serializing and deserializing data into/from byte buffers, for use in WebRender."
license = "MIT OR Apache-2.0"
edition = "2018"

[dependencies]
euclid = { version = "0.22.0", optional = true }
peek-poke-derive = { version = "0.3", path = "./peek-poke-derive", optional = true }

[features]
default = ["derive"]
derive = ["peek-poke-derive"]
extras = ["derive", "euclid"]
