;; Quail package `chinese-punct
;;   Generated by the command `titdic-convert'
;;	Original TIT dictionary file: Punct.tit

;; # -*- coding: euc-china -*-
;; # HANZI input table for cxterm
;; # To be used by cxterm, convert me to .cit format first
;; # .cit version 1
;; ENCODE:	GB
;; MULTICHOICE:	YES
;; PROMPT:	汉字输入∷标点符号∷\243\240
;; #
;; COMMENT	Copyright 1991 by Yongguang Zhang.
;; COMMENT Permission to use/modify/copy for any purpose is hereby granted.
;; COMMENT Absolutely no fee and no warranties.
;; COMMENT
;; COMMENT	use <CTRL-f> to move to the right
;; COMMENT	use <CTRL-b> to move to the left
;; # define keys
;; VALIDINPUTKEY:	"\043$%&'()*+,-./0123456789:;<=>?@[\134]^_`abcdefghijklm
;; VALIDINPUTKEY:	nopqrstuvwxyz|~
;; SELECTKEY:	1\040
;; SELECTKEY:	2
;; SELECTKEY:	3
;; SELECTKEY:	4
;; SELECTKEY:	5
;; SELECTKEY:	6
;; SELECTKEY:	7
;; SELECTKEY:	8
;; SELECTKEY:	9
;; SELECTKEY:	0
;; BACKSPACE:	\010\177
;; DELETEALL:	\015\025
;; MOVERIGHT:	\006
;; MOVELEFT:	\002
;; REPEATKEY:	\020\022
;; # the following line must not be removed
;; BEGINDICTIONARY

;;; End of the header of original TIT dictionary.

;;; Code:

(require 'quail)

(quail-define-package "chinese-punct" "Chinese-GB" "标G"
 t
"汉字输入∷标点符号∷\243\240

	Copyright 1991 by Yongguang Zhang.
 Permission to use/modify/copy for any purpose is hereby granted.
 Absolutely no fee and no warranties.

	use <CTRL-f> to move to the right
	use <CTRL-b> to move to the left

Input method for Chinese punctuation and symbols of GB2312
(`chinese-gb2312').
"
 '(("\C-?" . quail-delete-last-char)
   
   
   )
 nil nil nil nil)

(quail-define-rules
("\"" "＂“”″")
("#" "＃")
("$" "￥＄￠￡")
("%" "％‰")
("'" "＇‘’′")
("(" "（「『")
(")" "）」』")
("*" "＊×∏∧∩")
("+" "＋±∑∨∪")
("," "，、")
("-" "－ˉ—～")
("." "．。·¨…∵∴°⊙")
("/" "／÷√＼")
("0" "０⒑⒛⑽⒇⑩㈩Ⅹ")
("1" "１⒈⒒⑴⑾①㈠Ⅰ")
("2" "２⒉⒓⑵⑿②㈡Ⅱ")
("3" "３⒊⒔⑶⒀③㈢Ⅲ")
("4" "４⒋⒕⑷⒁④㈣Ⅳ")
("5" "５⒌⒖⑸⒂⑤㈤Ⅴ")
("6" "６⒍⒗⑹⒃⑥㈥Ⅵ")
("7" "７⒎⒘⑺⒄⑦㈦Ⅶ")
("8" "８⒏⒙⑻⒅⑧㈧Ⅷ")
("9" "９⒐⒚⑼⒆⑨㈨Ⅸ")
(":" "：∷")
("<" "＜〈《≮≤")
("=" "＝≠≈≡≌")
(">" "＞〉》≯≥")
("@" "＠⊙")
("[" "［〔〖【｛")
("\\" "＼／")
("]" "］〕〗】｝")
("^" "＾ˇ⌒")
("_" "＿⊥")
("`" "｀‘’")
("logo" "☆★○●◎◇◆□■△▲※→←↑↓〓")
("math" "±×÷∶∧∨∑∏∪∩∈∷√⊥∥∠⌒⊙∫∮≡≌≈∽∝≠≮≯≤≥∞∵∴")
("punct" "　、。·ˉˇ¨〃々—～‖…‘’“”〔〕〈〉《》「」『』〖〗【】")
("symbol" "♂♀°′″℃＄¤￠￡‰§№")
("|" "｜‖∥")
("~" "￣～∽∝∞")
)
;; Local Variables:
;; version-control: never
;; no-update-autoloads: t
;; coding: chinese-iso-8bit-unix
;; End:
