;; Quail package `chinese-qj
;;   Generated by the command `titdic-convert'
;;	Original TIT dictionary file: QJ.tit

;; # -*- coding: euc-china -*-
;; # HANZI input table for cxterm
;; # To be used by cxterm, convert me to .cit format first
;; # .cit version 2
;; ENCODE:	GB
;; AUTOSELECT:	YES
;; PROMPT:	汉字输入∷全角∷
;; #
;; COMMENT Copyright 1991 by Yongguang Zhang.      (ygz@cs.purdue.edu)
;; COMMENT Permission to use/modify/copy for any purpose is hereby granted.
;; COMMENT Absolutely no warranties.
;; # define keys
;; VALIDINPUTKEY:	\040!"\043$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMN
;; VALIDINPUTKEY:	OPQRSTUVWXYZ[\134]^_`abcdefghijklmnopqrstuvwxyz{|}~
;; # the following line must not be removed
;; BEGINDICTIONARY

;;; End of the header of original TIT dictionary.

;;; Code:

(require 'quail)

(quail-define-package "chinese-qj" "Chinese-GB" "全G"
 t
"汉字输入∷全角∷

 Copyright 1991 by Yongguang Zhang.      (ygz@cs.purdue.edu)
 Permission to use/modify/copy for any purpose is hereby granted.
 Absolutely no warranties.
"
 '(("\C-?" . quail-delete-last-char)
   
   ("." . quail-next-translation)
   (">" . quail-next-translation)
   ("," . quail-prev-translation)
   ("<" . quail-prev-translation))
 nil nil nil nil)

(quail-define-rules
(" " "　")
("!" "！")
("\"" "＂")
("#" "＃")
("$" "￥")
("%" "％")
("&" "＆")
("'" "＇")
("(" "（")
(")" "）")
("*" "＊")
("+" "＋")
("," "，")
("-" "－")
("." "．")
("/" "／")
("0" "０")
("1" "１")
("2" "２")
("3" "３")
("4" "４")
("5" "５")
("6" "６")
("7" "７")
("8" "８")
("9" "９")
(":" "：")
(";" "；")
("<" "＜")
("=" "＝")
(">" "＞")
("?" "？")
("@" "＠")
("A" "Ａ")
("B" "Ｂ")
("C" "Ｃ")
("D" "Ｄ")
("E" "Ｅ")
("F" "Ｆ")
("G" "Ｇ")
("H" "Ｈ")
("I" "Ｉ")
("J" "Ｊ")
("K" "Ｋ")
("L" "Ｌ")
("M" "Ｍ")
("N" "Ｎ")
("O" "Ｏ")
("P" "Ｐ")
("Q" "Ｑ")
("R" "Ｒ")
("S" "Ｓ")
("T" "Ｔ")
("U" "Ｕ")
("V" "Ｖ")
("W" "Ｗ")
("X" "Ｘ")
("Y" "Ｙ")
("Z" "Ｚ")
("[" "［")
("\\" "＼")
("]" "］")
("^" "＾")
("_" "＿")
("`" "｀")
("a" "ａ")
("b" "ｂ")
("c" "ｃ")
("d" "ｄ")
("e" "ｅ")
("f" "ｆ")
("g" "ｇ")
("h" "ｈ")
("i" "ｉ")
("j" "ｊ")
("k" "ｋ")
("l" "ｌ")
("m" "ｍ")
("n" "ｎ")
("o" "ｏ")
("p" "ｐ")
("q" "ｑ")
("r" "ｒ")
("s" "ｓ")
("t" "ｔ")
("u" "ｕ")
("v" "ｖ")
("w" "ｗ")
("x" "ｘ")
("y" "ｙ")
("z" "ｚ")
("{" "｛")
("|" "｜")
("}" "｝")
("~" "￣")
)
;; Local Variables:
;; version-control: never
;; no-update-autoloads: t
;; coding: chinese-iso-8bit-unix
;; End:
