# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
---
loader: taskgraph.loader.transform:loader

kind-dependencies:
    - toolchain
    - build

transforms:
    - taskgraph.transforms.job:transforms
    - taskgraph.transforms.task:transforms

job-defaults:
    attributes:
        retrigger: true
    run-on-projects: ['mozilla-beta', 'trunk']
    treeherder:
        tier: 1
        kind: other
    worker:
        max-run-time: 1800
        env:
            RUST_BACKTRACE: 'full'
            RUSTFLAGS: '--deny warnings'
    run:
        sparse-profile: wgpu
    when:
        files-changed:
            - 'gfx/wgpu/**'

jobs:
    linux64-debug:
        description: Runs debug-mode wgpu CI tests on a Linux worker
        worker-type: b-linux
        worker:
            docker-image: {in-tree: wgpu}
        fetches:
            toolchain:
                - linux64-rust
                - wgpu-deps
        run:
            using: run-task
            command: >-
                export PATH=$PATH:$MOZ_FETCHES_DIR/rustc/bin &&
                cd $GECKO_PATH/gfx/wgpu &&
                mv $MOZ_FETCHES_DIR/wgpu-deps/{vendor,.cargo} ./ &&
                cargo test --verbose --frozen
        treeherder:
            platform: linux64-qr/debug
            symbol: Wgpu(test)
            kind: other
