# This Source Code Form is subject to the terms of the Waterfox Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

rights-title = Über Ihre Rechte
rights-intro = { -brand-full-name } ist freie und quelloffene Software, entwickelt von einer Gemeinschaft tausender Gleichgesinnter, verteilt über die gesamte Welt. Es gibt da einige Dinge, die Sie wissen sollten:
rights-intro-point-1 = { -brand-short-name } wird Ihnen unter den Bedingungen der <a data-l10n-name="mozilla-public-license-link">Waterfox Public License</a> zur Verfügung gestellt. Das bedeutet, Sie dürfen { -brand-short-name } verwenden, kopieren und an andere verteilen. Sie sind auch gerne eingeladen, den Quellcode von { -brand-short-name } zu verändern und an Ihre eigenen Bedürfnisse anzupassen. Die Waterfox Public License gibt Ihnen auch das Recht, Ihre veränderte Version an andere zu verteilen.
rights-intro-point-2 = Waterfox gibt Ihnen keine Markenrechte oder Lizenzen an den Handelsmarken der Waterfox Foundation oder irgendeiner Partei, einschließlich ohne Einschränkungen am Namen "Waterfox" oder dem Waterfox-Logo. Weitere Informationen zur Nutzung der Marken finden Sie <a data-l10n-name="mozilla-trademarks-link">hier</a>.
rights-intro-point-3 = Manche Funktionen in { -brand-short-name }, wie z.B. der Absturzmelder, geben Ihnen die Möglichkeit, { -vendor-short-name } Feedback zu geben. Indem Sie das Feedback absenden, erteilen Sie { -vendor-short-name } die Erlaubnis, das Feedback zur Verbesserung von Produkten zu nutzen, es auf Webseiten zu veröffentlichen und es zu verteilen.
rights-intro-point-4 = Wie wir Ihre über { -brand-short-name } an { -vendor-short-name } abgesendeten persönlichen Daten und Ihr Feedback nutzen, ist beschrieben in der <a data-l10n-name="mozilla-privacy-policy-link">{ -brand-short-name }-Datenschutzerklärung</a>.
rights-intro-point-4-unbranded = Jegliche Datenschutzerklärungen, die für dieses Produkt gelten, sollten hier gelistet werden:
rights-intro-point-5 = Einige { -brand-short-name }-Funktionen verwenden web-basierte Informationsdienste. Allerdings können wir keine Garantie dafür übernehmen, dass sie 100% genau und fehlerfrei sind. Weitere Details, inklusive Informationen darüber, wie Sie diese Funktionen deaktivieren können, finden Sie in den <a data-l10n-name="mozilla-service-terms-link">Service-Bedingungen</a>.
rights-intro-point-5-unbranded = Falls dieses Produkt Web-Dienste enthält, sollten gültige Service-Bedingungen für den Dienst oder die Dienste zum Bereich <a data-l10n-name="mozilla-website-services-link">Website-Dienste</a> verlinkt werden.
rights-intro-point-6 = Zur Wiedergabe einiger Videoinhalte lädt { -brand-short-name } bestimmte Entschlüsselungskomponenten von Dritten herunter.
rights-webservices-header = { -brand-full-name } web-basierte Informationsdienste
rights-webservices = { -brand-full-name } verwendet web-basierte Informationsdienste ("Services"), um einige der Funktionen anbieten zu können, die Ihnen für den Gebrauch mit der Binaryversion von { -brand-short-name } unter den unten angegebenen Bedingungen zur Verfügung gestellt werden. Falls Sie die Dienste oder einen davon nicht verwenden möchten oder die Bedingungen für Sie nicht akzeptabel sind, können Sie die Funktion oder die Service(s) deaktivieren. Anleitungen dafür, wie Sie eine bestimmte Funktion oder einen Service deaktivieren können, finden Sie <a data-l10n-name="mozilla-disable-service-link">hier</a>. Andere Funktionen und Dienste können in den Anwendungseinstellungen deaktiviert werden.
rights-safebrowsing = <strong>SafeBrowsing: </strong>Das Deaktivieren von SafeBrowsing wird nicht empfohlen, da Sie auf unsichere Seiten stoßen könnten.  Wenn Sie diese Funktion komplett deaktivieren möchten, führen Sie bitte folgende Schritte aus:
rights-safebrowsing-term-1 = Öffnen Sie das Einstellungen-Fenster
rights-safebrowsing-term-2 = Wählen Sie den Tab Sicherheit
rights-safebrowsing-term-3 = Wählen Sie die Option "{ enableSafeBrowsing-label }" ab
enableSafeBrowsing-label = Gefährliche und betrügerische Inhalte blockieren
rights-safebrowsing-term-4 = SafeBrowsing ist nun deaktiviert
rights-locationawarebrowsing = <strong>Standortbezogenes Browsing: </strong>ist immer eine Opt-in-Funktion.  Standortdaten werden niemals ohne Ihre Erlaubnis gesendet.  Wenn Sie diese Funktion komplett deaktivieren möchten, führen Sie bitte folgende Schritte aus:
rights-locationawarebrowsing-term-1 = Rufen Sie in der Adressleiste<code>about:config</code>
rights-locationawarebrowsing-term-2 = auf. Tippen Sie dann geo.enabled
rights-locationawarebrowsing-term-3 = Führen Sie einen Doppelklick auf geo.enabled aus
rights-locationawarebrowsing-term-4 = Standortbezogenes Browsing ist nun deaktiviert
rights-webservices-unbranded = Ein Überblick über die verwendeten Website-Dienste und eine Anleitung, wie sie deaktiviert werden können, wenn das vorgesehen ist, sollte hier eingefügt werden.
rights-webservices-term-unbranded = Jegliche Bedingungen für die Dienste, die dieses Produkt verwendet, sollten hier gelistet werden.
rights-webservices-term-1 = { -vendor-short-name } und die Mitwirkenden, Lizenzgeber und Partner versuchen die genausten und aktuellsten Services zur Verfügung zu stellen. Allerdings kann nicht garantiert werden, dass die Daten umfassend und fehlerfrei sind.  Beispielsweise könnte der SafeBrowsing-Service manche riskanten Websites als sicher einstufen und manche sicheren Websites fälschlicherweise als riskant. Und für standortbezogene Dienste gilt, dass alle Standortdaten, die von unseren Service-Providern geliefert werden, nur Schätzungen darstellen, und weder wir noch unsere Service-Provider garantieren für die Genauigkeit der Standortdaten.
rights-webservices-term-2 = { -vendor-short-name } kann die Dienste nach eigenem Ermessen abschalten oder verändern.
rights-webservices-term-3 = Sie sind eingeladen, diese Dienste mit der dazugehörigen { -brand-short-name }-Version zu verwenden, und { -vendor-short-name } erteilt Ihnen die Rechte dies zu tun. { -vendor-short-name } und ihre Lizenzgeber behalten sich alle anderen Rechte an den Diensten vor. Diese Bedingungen beabsichtigen nicht, jegliche Rechte einzuschränken, die von Open-Source-Lizenzen gewährt werden, die auf { -brand-short-name } und entsprechende Quellcode-Versionen von { -brand-short-name } anwendbar sind.
rights-webservices-term-4 = <strong>Die Dienste werden "wie es ist" zur Verfügung gestellt. { -vendor-short-name }, ihre Mitwirkenden, Lizenzgeber und Distributoren gewähren keinerlei Gewährleistung, weder ausdrücklich noch implizit, einschließlich – aber nicht begrenzt auf – Marktreife oder Verwendbarkeit für einen bestimmten Zweck. Das volle Risiko bezüglich der Auswahl des für Sie richtigen Dienstes und die Qualität und Leistungsfähigkeit des Dienstes liegt bei Ihnen. Manche Gerichtsbarkeiten erlauben nicht den Ausschluss oder die Eingrenzung von implizierten Risiken, so dass dieser Haftungsausschluss möglicherweise nicht für Sie gilt.</strong>
rights-webservices-term-5 = <strong>In keinem Fall, außer wenn durch geltendes Recht gefordert, sind { -vendor-short-name }, ihre Mitwirkenden, Lizenzgeber oder Distributoren für irgendwelchen indirekten oder speziellen Schäden, Schäden durch Seiteneffekte (Nebenwirkungen) oder Folgeschäden, die aus der Benutzung von { -brand-short-name } oder den Diensten folgen, haftbar. Die gesamte Haftbarkeit unter diesen Bedingungen beschränkt sich auf maximal $500 (fünfhundert Dollar). Manche Gerichtsbarkeiten erlauben nicht den Ausschluss oder die Eingrenzung von bestimmten Risiken, so dass diese Ausschlüsse oder Eingrenzungen möglicherweise nicht für Sie gelten.</strong>
rights-webservices-term-6 = { -vendor-short-name } kann diese Bedingungen bei Bedarf von Zeit zu Zeit aktualisieren. Diese Bedingungen können nicht ohne eine schriftliche Zusicherung von { -vendor-short-name } verändert oder aufgehoben werden.
rights-webservices-term-7 = Diese Bedingungen werden durch die Gesetze des Staates Kalifornien, USA, geschützt, ausschließlich den damit in Konflikt stehenden Rechtsvorschriften. Sollten einzelne Bestimmungen dieser Bedingungen unwirksam oder undurchführbar sein, bleibt davon die Wirksamkeit der anderen Bedingungen unberührt. Falls ein Konflikt bestehen sollte, zwischen der übersetzen Version dieser Bedingungen und der englischsprachigen Version, gelten die Bedingungen der englischsprachigen Version.
