# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

rights-title = Huqularingiz haqida
rights-intro = { -brand-full-name } butun dunyo boʻyicha minglab jamoalar hissasini qoʻshib, tuzilgan erkin va ochiq kodli dasturiy ta`minot. Bu yerda bilishingiz kerak boʻlgan ba`zi narsalar bor:
rights-intro-point-1 = { -brand-short-name } <a data-l10n-name="mozilla-public-license-link">"Mozilla Public License" (Mozilla ochiq litsenziyasi) shartlari boʻyicha mavjud.</a>. Bu degani siz { -brand-short-name }dan foydalanishingiz, nusxa koʻchirishingiz va boshqalarga tarqatishingiz mumkin. Shuningdek, kerak boʻlsa { -brand-short-name }ning kodlarini oʻzgartirishingiz ham mumkin. "The Mozilla Public License" (Mozilla ochiq litsenziyasi) sizga kodlari oʻzgartiriglan versiyalarini tarqatish huquqini ham beradi.
rights-intro-point-2 = Mozilla jamiyati tomonidan birorta ham savdo belgisi litsenziyalari yoki huquqlar bilan kafolat berilmaydi  yoki Firefox nomi yoki belgisi cheklovi qoʻshilgan birorta tarafga ham kafolat bermaydi. Savdo boʻyicha qoʻshimcha ma`lumotlarni <a data-l10n-name="mozilla-trademarks-link">bu yerdan topishingiz mumkin</a>.
rights-intro-point-3 = { -brand-short-name }ning ba`zi xususiyatlari, masalan, "Nosozlik xabar bergichi" { -vendor-short-name }ga mulohazalar joʻnatish imkonini beradi. Mulohaza joʻnatishni tanlab, { -vendor-short-name }ga mahsulotlarini yaxshilashda, tavsiyalarni oʻzining saytida e`lon qilishda va fikrlarni tarqatishda mulohazalardan foydalanish huquqini berasiz..
rights-intro-point-4 = { -vendor-short-name }ga { -brand-short-name } orqali joʻnatgan mulohazalaringiz va shaxsiy ma`lumotlaringizdan qanday qilib foydalanishimiz  <a data-l10n-name="mozilla-privacy-policy-link">"{ -brand-short-name } "Maxfiylik nazorati"da yozilgan</a>.
rights-intro-point-4-unbranded = Ushbu mahsulot uchun har qanday xavfsizlik nazoratini qoʻllash bu yerdagi roʻyxatda keltirilgan boʻlishi kerak.
rights-intro-point-5 = Ba`zi { -brand-short-name } xossalari internetga asoslangan ma`lumot xizmatlaridan foydalanadi, shunday ekan, biz ularning 100% xatolardan holi ekanligiga kafolat bera olmaymiz. Ushbu xizmatlardan foydalanish xossasini oʻchirib qoʻyish haqidagi va boshqa koʻplab ma`lumotlarni <a data-l10n-name="mozilla-service-terms-link">xizmat shartlaridan olishingiz mumkin</a>.
rights-intro-point-5-unbranded = Agar ushbu mahsulot veb xizmatlar bilan bogʻliq boʻlsa, ushbu xizmat(lar) uchun har qanday qabul qilinadigan shartlar <a data-l10n-name="mozilla-website-services-link">Veb sayt xizmatlari</a> boʻlimida keltirilgan boʻlishi kerak.
rights-intro-point-6 = Aniq bir turdagi video fayllarni ijro etish uchun { -brand-short-name } uchinchi tomondan kerakli kontent ta’rifi modullarini yuklab oladi.
rights-webservices-header = { -brand-full-name } internetga asoslangan ma`lumot berish xizmatlari
rights-webservices = { -brand-full-name } internetga asoslangan ma`lumot xizmatlari ("Xizmatlar")dan { -brand-short-name }ning quyida keltirilgan shartlar ostidagi ushbu ikkilik versiyasidan foydalanishda ba`zi xususiyatlarini ta`minlash uchun foydalanadi.Agar "Xizmatlar"dan biri yoki bir nechtasidan foydalanishni xohlamasangiz yoki pastdagi shartlarni qoʻllab boʻlmasa, xususiyatlar yoki "Xizmatlar"ni oʻchirib qoʻyishingiz mumkin. Ba`zi xususiyatlarni yoki "Xizmatlar"ni qanday qilib oʻchirish boʻyicha koʻrsatmani  <a data-l10n-name="mozilla-disable-service-link">bu yerdan topishingiz mumkin</a>. Boshqa xususiyatlar va "Xizmatlar"ni ilova dasturlar moslamalaridan oʻchirib qoʻyish mumkin.
rights-safebrowsing = <strong>SafeBrowsing: </strong>"Xavfsiz koʻrish" xususiyatini oʻchirib qoʻyish tavsiya qilinmaydi, chunki siz xavfli saytlarga kirib qolishingiz mumkin.  Agar siz ushbu xususiyatni butunlay, oʻchirmoqchi boʻlsangiz quyidagi bosqichlardan oʻtishingiz kerak:
rights-safebrowsing-term-1 = Ilova dastur moslamalarini oching
rights-safebrowsing-term-2 = "Xavfsizlikni tanlash"ni tanlang
rights-safebrowsing-term-3 = "{ enableSafeBrowsing-label }"dan belgini olib tashlang
enableSafeBrowsing-label = Xavfli va yolg‘on saytlarni bloklash
rights-safebrowsing-term-4 = "Xavfsiz koʻrish" - hozir oʻchirib qoʻyilgan
rights-locationawarebrowsing = <strong>Manzilni bilib internetni koʻrish:</strong>- doimiy tanlov. Manzil ma`lumotlari ruxsatingizsiz umuman joʻnatilmaydi. Agar ushbu xususiyatni butunlay oʻchirib qoʻymoqchi boʻlsangiz, quyidagi bosqichlardan oʻtishingiz kerak:
rights-locationawarebrowsing-term-1 = URL paneliga yozing <code>about:config</code>
rights-locationawarebrowsing-term-2 = geo.enabled deb yozing
rights-locationawarebrowsing-term-3 = geo.enabled moslamalari ustiga ikki marta bosing
rights-locationawarebrowsing-term-4 = Manzilni bilib internetni koʻrish - oʻchirib qoʻyilgan
rights-webservices-unbranded = Veb saytlar ma`lumotlarini koʻrib chiqish xizmati mahsulotga ularni qanday oʻchirish boʻyicha koʻrsatmalar qoʻshilgan, agar bu talab qilinsa, bu yerga qoʻshilishi kerak.
rights-webservices-term-unbranded = Ushbu mahsuloat uchun ba`zi qabul qilingan xizmat shartlari bu yerda koʻrsatilgan boʻlishi kerak.
rights-webservices-term-1 = { -vendor-short-name }  va uning hissa qoʻshuvchilari, litsenziyachilari hamda hamkorlari  "Xizmatlar" orqali eng aniq va yangi ma`lumotlarni berish uchun bor kuchlari bilan harakat qilishadi, lekin ushbu ma`lumotlarni toʻliq va xatolardan holi ekanligiga kafolat bera olmaymiz.  Masalan, "Xavfsiz koʻrish" xizmati ba`zi xavfli saytlarni xavfsiz, ba`zi xavfsiz saytlarni esa xato tufayli xavfli deb koʻrsatishi mumkin, shuningdek, "Manzilni aniqlash xizmati"ga qaytariladigan barcha joylashgan manzillar aniq boʻlmasligi mumkin, biz ham xizmat koʻrsatuvchilarimiz ham bu manzillar aniqligiga 100% kafolat bera olmaymiz.
rights-webservices-term-2 = { -vendor-short-name } ehtiyotkorlik uchun "Xizmarlar" koʻrsatishni toʻxtatishi yoki uni oʻzgartirishi mumkin.
rights-webservices-term-3 = Siz ushbu "Xizmatlar"dan { -brand-short-name }ning mavjud versiyasi bilan birga foydalanishingiz mumkin, { -vendor-short-name } ushbu huquqlar boʻyicha foydalanish imkonini beradi. { -vendor-short-name } va uning litsenziyachilari barcha boshqa huquqlarni "Xizmatlar"ga saqlaydi.  Ushbu shartlar { -brand-short-name }da qoʻllanadigan  ochiq kod litsenziyalari ostidagi kafolatlangan huquqlarni va { -brand-short-name } versiyalari manba kodini oʻzgartirishni cheklamaydi.
rights-webservices-term-4 = <strong>Ushbu xizmat "boricha" koʻrsatiladi.  { -vendor-short-name }, uning dasturchilar, litsenziya egalari va tarqatuvchilari barcha kafolatlarni rad etishadi (tezlik yoki biror narsaga tegishli, shaxsiy maqsadlarda foydalanish yoki savdo maqsadidagi xizmatlarda).  Xizmatlar ijrosi va sifatiga munosabatda va maqsadlaringiz uchun xizmat tanlash bilan siz butun xavf-xatarni o‘z zimmangizga olasiz. Bir nechta huquqiy hujjatlar istisno yoki kafolatga ta’sir qiladigan cheklovlarga ruxsat bermaydi, shunday ekan ushbu rad qilishning sizga aloqasi yo‘q.</strong>
rights-webservices-term-5 = <strong>Istisno holatlarda qonun qiyidagilarni talab qiladi, { -vendor-short-name }, uning ishchilar, litsenziya beruvchilar va tarqatuvchilar noto‘g‘ri, maxsus, tasodifiy, davom etadigan yoki  jarima to‘lanadigan yoki zarar uchun jazolash, { -brand-short-name }dan foydalanishda ishdan chiqish va xizmatlar uchun javob bermaydi.  Ushbu shartlarga muvofiq ish jamoasi javobgarligi  $500 (besh yuz dollar)dan oshmasligi kerak. Ba’zi huquqiy qonunlar istisnoga yoki aniqlangan zararni cheklashga ruxsat bermaydi, shuning uchun hozirgi istisno va cheklovlarning sizga aloqasi yo‘q.</strong>
rights-webservices-term-6 = { -vendor-short-name } kerak boʻlganda vaqti-vaqti bilan oʻzining shartlarini yangilashi mumkin. Ushbu shartlarni { -vendor-short-name }ning yozma roziligisiz oʻzgartirish va bekor qilish mumkin emas.
rights-webservices-term-7 = Ushbu shartlar AQSH va Kaliforniya shtatlari qonunlari (qonunga toʻgʻri kelmaydiganlaridan boshqalari) tomonidan boshqariladi. Ushbu shartlardan biror qismi huquqiy amalda bo‘lmasa yoki bajarib bo‘lmasa, qolgan qismi to‘liq o‘zining huquqiy kuchini saqlab qoladi. Ushbu shartlarning tarjima qilingan va ingliz tilidagi asl manbalari o‘rtasida ziddiyatlar paydo bo‘lsa, ingliz tilidagi versiyasiga amal qilish kerak bo‘ladi.
