# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with

# your locale code, and link to your translated pages as soon as they're

# live.


#define bookmarks_title Marcapachinas


#define bookmarks_heading Marcapachinas


#define bookmarks_toolbarfolder Carpeta d'a barra de marcapachinas


#define bookmarks_toolbarfolder_description Adhiba marcadors a ista carpeta ta veyer-los en a barra de ferramientas de marcapachinas


# LOCALIZATION NOTE (getting_started):


# link title for https://www.mozilla.org/en-US/firefox/central/


#define getting_started Primers trangos


# LOCALIZATION NOTE (firefox_heading):


# Firefox links folder name


#define firefox_heading Mozilla Firefox


# LOCALIZATION NOTE (firefox_help):


# link title for https://www.mozilla.org/en-US/firefox/help/


#define firefox_help Aduya y guidas


# LOCALIZATION NOTE (firefox_customize):


# link title for https://www.mozilla.org/en-US/firefox/customize/


#define firefox_customize Personalice o Firefox


# LOCALIZATION NOTE (firefox_community):


# link title for https://www.mozilla.org/en-US/contribute/


#define firefox_community Embreque-se-ie


# LOCALIZATION NOTE (firefox_about):


# link title for https://www.mozilla.org/en-US/about/


#define firefox_about Arredol de nusatros


# LOCALIZATION NOTE (nightly_heading):


# Firefox Nightly links folder name


#define nightly_heading Recursos en desenvolvimiento de Firefox


# LOCALIZATION NOTE (nightly_blog):


# Nightly builds only, link title for https://blog.nightly.mozilla.org/


#define nightly_blog Blog de desenvolvimiento de Firefox


# LOCALIZATION NOTE (bugzilla):


# Nightly builds only, link title for https://bugzilla.mozilla.org/


#define bugzilla Seguidor de Bugs de Mozilla


# LOCALIZATION NOTE (mdn):


# Nightly builds only, link title for https://developer.mozilla.org/


#define mdn Ret de Desenvolvedors de Mozilla


# LOCALIZATION NOTE (nightly_tester_tools):


# Nightly builds only, link title for https://addons.mozilla.org/en-US/firefox/addon/nightly-tester-tools/


#define nightly_tester_tools Ferramientas de testeyo de desenvolvimiento


# LOCALIZATION NOTE (crashes):


# Nightly builds only, link title for about:crashes


#define crashes Totz los tuyos crashes


# LOCALIZATION NOTE (irc):


# Nightly builds only, link title for ircs://irc.mozilla.org/nightly


#define irc Discutor versión en desenvolvimiento en IRC


# LOCALIZATION NOTE (planet):


# Nightly builds only, link title for https://planet.mozilla.org/


#define planet Planeta Mozilla


#unfilter emptyLines
