#filter emptyLines

#define MOZ_LANGPACK_CREATOR Waterfox Russia

#define MOZ_LANGPACK_HOMEPAGE http://www.mozilla-russia.org/

# If non-English locales wish to credit multiple contributors, uncomment this
# variable definition and use the format specified.
#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Alexander Slovesnik</em:contributor> <em:contributor>Victor Bychek</em:contributor><em:contributor>Harry</em:contributor> <em:contributor>ZzEdovec</em:contributor><em:contributor>Andrey Shinkaryov</em:contributor>

#unfilter emptyLines
