# This Source Code Form is subject to the terms of the Waterfox Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#filter emptyLines

#define MOZ_LANGPACK_CREATOR Waterfox Taiwan Community (MozTW)

# If non-English locales wish to credit multiple contributors, uncomment this
# variable definition and use the format specified.
#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Hung-Te Lin(piaip)</em:contributor> <em:contributor>Wei-Lun Sun(josesun)</em:contributor> <em:contributor>Tim Guan-Tin Chien(timdream)</em:contributor> <em:contributor>Peter Pin-Guang Chen(petercpg)</em:contributor>

#unfilter emptyLines
