# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#filter emptyLines

#define MOZ_LANGPACK_CREATOR mozilla.org

# If non-English locales wish to credit multiple contributors, uncomment this

# variable definition and use the format specified.

#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Danishka Navin</em:contributor><em:contributor>Kalpa Pathum</em:contributor> <em:contributor>Gayan Kalhara</em:contributor><em:contributor>RohanaDasanayaka</em:contributor>  <em:contributor>SrishanuLokupathirage</em:contributor> <em:contributor>HarshanaWeerasinghe</em:contributor> <em:contributor> Lahiru Himesh</em:contributor><em:contributor>Nuwan Indika</em:contributor> <em:contributor>Lohan Gunaweera</em:contributor>

#unfilter emptyLines
