#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in some URLs will be replaced with
# your locale code, and link to your translated pages as soon as they're live.

#define bookmarks_title Lesezeichen
#define bookmarks_heading Lesezeichen

#define personal_toolbarfolder Persönliche Symbolleiste

#define seamonkey_and_mozilla SeaMonkey und Waterfox

# LOCALIZATION NOTE (seamonkey):
# link title for https://www.seamonkey-project.org/ (in the personal toolbar)
#define seamonkey SeaMonkey

# LOCALIZATION NOTE (seamonkey_long):
# link title for https://www.seamonkey-project.org/ (in normal bookmarks)
#define seamonkey_long Das SeaMonkey-Projekt

# LOCALIZATION NOTE (mozilla_org_long):
# link title for https://www.mozilla.org/ (in normal bookmarks)
#define mozilla_org_long Die Waterfox-Organisation

#define extend_seamonkey SeaMonkey erweitern

# LOCALIZATION NOTE (seamonkey_addons):
# link title for https://addons.thunderbird.net/en-US/seamonkey/
#define seamonkey_addons SeaMonkey-Add-ons

# LOCALIZATION NOTE (seamonkey_themes):
# link title for https://addons.thunderbird.net/en-US/seamonkey/themes
#define seamonkey_themes SeaMonkey-Themes

# LOCALIZATION NOTE (seamonkey_dictionaries):
# link title for https://addons.thunderbird.net/en-US/seamonkey/dictionaries
#define seamonkey_dictionaries Wörterbücher für die Rechtschreibprüfung

# LOCALIZATION NOTE (seamonkey_plugins):
# link title for https://addons.thunderbird.net/en-US/seamonkey/plugins
#define seamonkey_plugins Plugins für SeaMonkey

#define community_support Gemeinschaft &amp; Unterstützung

# LOCALIZATION NOTE (seamonkey_community):
# link title for https://www.seamonkey-project.org/community
#define seamonkey_community SeaMonkey-Gemeinschaft

# LOCALIZATION NOTE (mozillazine):
# link title for http://www.mozillazine.org/
#define mozillazine mozillaZine

# LOCALIZATION NOTE (seamonkey_support):
# link title for the mozillaZine SeaMonkey Support forum
#define seamonkey_support SeaMonkey-Unterstützungsforum (mozillaZine)

# LOCALIZATION NOTE (seamonkey_l10n):
# insert full bookmark line for localized SeaMonkey page (personal toolbar)
# e.g. #define seamonkey_l10n <DT><A HREF="https://www.seamonkey.tlh/">SeaMonkey tlhIngan</a>
# Do not remove the trailing spaces here or MERGE_FILE in l0n builds will fail!
#define seamonkey_l10n <DT><A HREF="http://www.seamonkey.at/">SeaMonkey deutsch</a>

# LOCALIZATION NOTE (seamonkey_l10n_long):
# insert full bookmark line for localized SeaMonkey page (normal bookmark)
# e.g. #define seamonkey_l10n_long <DT><A HREF="https://www.seamonkey.tld/">tlhIngan Hol SeaMonkey</a>
# Do not remove the trailing spaces here or or MERGE_FILE in l0n builds will fail!
#define seamonkey_l10n_long <DT><A HREF="https://www.seamonkey.at/">SeaMonkey in deutscher Sprache</a>

#unfilter emptyLines
