# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#filter emptyLines

#define MOZ_LANGPACK_CREATOR mozilla.org

# If non-English locales wish to credit multiple contributors, uncomment this
# variable definition and use the format specified.
#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Richard von Moltke</em:contributor> <em:contributor>Vedran Tomicic</em:contributor> <em:contributor>Carlos Riveros</em:contributor> <em:contributor>Joaquín Haeussler</em:contributor> <em:contributor>Emilio Sepúlveda</em:contributor> <em:contributor>Pablo Olmos De Aguilera</em:contributor> <em:contributor>Eduardo Escárez</em:contributor> <em:contributor>Ricardo Varas</em:contributor>

#unfilter emptyLines
