# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

rights-title = Perihal Hak Anda
rights-intro = { -brand-full-name } adalah perisian percuma dan sumber terbuka, dibina oleh komuniti yang terdiri daripada ribuan penyumbang dari seluruh dunia. Ada beberapa perkara yang anda perlu tahu:
rights-intro-point-1 = { -brand-short-name } disediakan untuk anda di bawah terma <a data-l10n-name="mozilla-public-license-link">Lesen Awam Mozilla</a>. Ini bermakna anda boleh guna, salin dan edarkan { -brand-short-name } kepada pihak lain.  Anda juga dialu-alukan untuk mengubahsuai kod sumber { -brand-short-name } untuk memenuhi keperluan anda. Lesen Umum Mozilla juga memberikan anda hak untuk mengedarkan versi yang diubah suai.
rights-intro-point-2 = Anda tidak diberi hak tanda dagangan atau lesen untuk tanda dagangan Mozilla Foundation atau mana-mana pihak, termasuk tidak terhad kepada nama Firefox atau logonya. Maklumat tambahan mengenai tanda dagangan boleh ditemui di <a data-l10n-name="mozilla-trademarks-link">di sini</a>.
rights-intro-point-3 = Beberapa ciri dalam { -brand-short-name }, seperti Crash Reporter akan memberikan anda pilihan untuk memberikan maklum balas kepada { -vendor-short-name }. Dengan memilih untuk memberikan maklum balas, anda akan memberikan { -vendor-short-name } kebenaran untuk menggunakan maklum balas tersebut untuk menambahbaik produknya, untuk memaparkan maklum balas tersebut di laman web, dan untuk menyebarkan maklum balas tersebut.
rights-intro-point-4 = Bagaimana kami menggunakan maklumat peribadi dan maklum balas yang dihantar kepada { -vendor-short-name } melalui { -brand-short-name } adalah seperti yang diterangkan di dalam <a data-l10n-name="mozilla-privacy-policy-link">{ -brand-short-name } Polisi Privasi</a>.
rights-intro-point-4-unbranded = Sebarang polisi privasi lain yang diguna pakai untuk produk ini hendaklah disenaraikan di sini.
rights-intro-point-5 = Beberapa { -brand-short-name } ciri-ciri menggunakan perkhidmatan-perkhidmatan maklumat berlandaskan web, walaubagaimana, kami tidak boleh menjamin bahawa ciri-ciri tersebut 100%; tepat atau tiada ralat. Maklumat lanjut, termasuk maklumat mengenai bagaimana untuk mematikan ciri-ciri yang menggunakan perkhidmatan-perkhidmatan ini, boleh didapati dalamnya <a data-l10n-name="mozilla-service-terms-link">terma perkhidmatan</a>.
rights-intro-point-5-unbranded = Sekiranya produk ini merangkumi perkhidmatan web, sebarang terma perkhidmatan yang diguna pakai untuk perkhidmatan ini perlu dihubungkan ke <a data-l10n-name="mozilla-website-services-link">Servis Laman Web</a> bahagian.
rights-intro-point-6 = Untuk main semula sesetengah jenis kandungan video, { -brand-short-name } memuat turun sesetengah modul dekripsi kandungan daripada pihak ketiga.
rights-webservices-header = { -brand-full-name } Servis Informasi berdasarkan Web
rights-webservices = { -brand-full-name } menggunakan perkhidmatan maklumat -berasaskan-web ("Perkhidmatans") untuk menyediakan beberapa ciri yang disediakan untuk kegunaan anda dengan versi binari { -brand-short-name } di bawah terma yang dinyatakan dibawah. Jika anda tidak mahu menggunakan salah satu daripada Perkhidmatan atau tidak menerima terma di bawah, anda boleh nyahdayakan mana-mana ciri Perkhidmatan tersebut. Arahan mengenai cara untuk menyahdayakan ciri atau Perkhidmatan tertentu boleh ditemui di <a data-l10n-name="mozilla-disable-service-link">di sini</a>. Ciri lain dan Services boleh dinyahdayakan dalam keutamaan aplikasi.
rights-safebrowsing = <strong>SafeBrowsing: </strong>Anda tidak disyorkan untuk menyahaktifkan ciri Pelayaran Selamat kerana anda mungkin melayari laman yang tidak selamat.  Jika anda mahu menyahaktifkan semua ciri ini, ikuti langkah berikut:
rights-safebrowsing-term-1 = Buka tetapan keutamaan aplikasi
rights-safebrowsing-term-2 = Pilih pilihan keselamatan
rights-safebrowsing-term-3 = Nyahpilih pilihan untuk "{ enableSafeBrowsing-label }"
enableSafeBrowsing-label = Sekat isi kandung berbahaya dan memperdayakan
rights-safebrowsing-term-4 = Pelayaran Selamat kini dinyahaktifkan
rights-locationawarebrowsing = <strong>Pelayaran Sedar Lokasi: </strong>adalah satu ciri pilihan.  Tiada maklumat lokasi yang akan dihantar tanpa keizinan anda.  Jika anda mahu menyahaktifkan ciri ini secara keseluruhan, ikuti arahan berikut:
rights-locationawarebrowsing-term-1 = Di bar URL, taip <code>about:config</code>
rights-locationawarebrowsing-term-2 = Taip geo.enabled
rights-locationawarebrowsing-term-3 = Klik-dua kali pada keutamaan geo.enabled
rights-locationawarebrowsing-term-4 = Location-Aware Browsing kini dinyahdayakan
rights-webservices-unbranded = Gambaran keseluruhan perkhidmatan laman web yang mengandungi produk, berserta arahan untuk menyahdayakannya, jika ada, perlu disertakan di sini.
rights-webservices-term-unbranded = Apa jua terma perkhidmatan yang diguna pakai bagi produk ini mestilah disenaraikan di sini.
rights-webservices-term-1 = { -vendor-short-name } serta semua penyumbang, pemberi lesen dan rakan kongsi berusaha untuk menyediakan perkhidmatan yang paling tepat dan terkini.  Walau bagaimanapun, kami tidak dapat menjamin bahawa maklumat ini komprehensif dan bebas daripada ralat. Sebagai contoh, Safe Browsing Service mungkin tidak dapat mengenal pasti beberapa laman berisiko dan mungkin mengenal pasti beberapa laman selamat semasa ralat dan Location Aware Service mengenal pasti semua lokasi yang dikembalikan oleh pembekal perkhidmatan kami hanyalah anggaran sahaja dan kami atau pembekal perkhidmatan kami tidak menjamin ketepatan lokasi yang disediakan.
rights-webservices-term-2 = { -vendor-short-name } boleh memberhentikan atau mengubah Perkhidmatan mengikut budi bicara.
rights-webservices-term-3 = Anda dialu-alukan menggunakan Perkhidmatan ini berserta versi iringan { -brand-short-name }, dan { -vendor-short-name } memberikan anda hak berbuat sedemikian.  { -vendor-short-name } dan pemegang lesennya mempunyai semua hak terhadap Perkhidmatan tersebut.  Terma ini tidak bertujuan untuk menghadkan sebarang hak yang diberikan di bawah lesen sumber terbuka { -brand-short-name } dan versi kod sumber yang ada kaitan dengan { -brand-short-name }.
rights-webservices-term-4 = <strong>Perkhidmatan ini disediakan "mengikut" { -vendor-short-name }, penyumbang, pemberi lesen, dan pengedar, menafikan semua jaminan, sama ada yang dinyatakan atau yang tersirat, termasuk tanpa batasan, jaminan bahawa Perkhidmatan yang boleh diperdagangkan dan sesuai untuk tujuan anda yang tertentu.  Anda menanggung risiko secara menyeluruh untuk memilih Perkhidmatan untuk apa jua tujuan anda dan kepada kualiti dan prestasi Perkhidmatan. Sesetengah bidang kuasa tidak membenarkan pengecualian atau batasan jaminan yang tersirat, jadi penafian ini tidak mungkin dikenakan  kepada anda.</strong>
rights-webservices-term-5 = <strong>Kecuali dikehendaki oleh undang-undang, { -vendor-short-name }, para penyumbang, pemberi lesen dan para pengedar tidak bertanggungjawab ke atas mana-mana kerugian sampingan, khusus, tidak sengaja, berbangkit, punitif atau teladan yang terhasil daripada atau cara yang dikaitkan dengan penggunaan { -brand-short-name } dan Perkhidmatan ini.  Liabiliti kolektif di bawah terma ini tidak akan melebihi $500 (lima ratus dolar). Sesetengah bidang kuasa tidak membenarkan pengecualian atau had kerugian tertentu, jadi pengecualian ini dan had mungkin tidak dikenakan kepada anda.</strong>
rights-webservices-term-6 = { -vendor-short-name } mungkin mengemaskini terma ini jika diperlukan daripada masa ke semasa. Terma ini tidak boleh diubah atau dibatalkan tanpa persetujuan bertulis { -vendor-short-name }.
rights-webservices-term-7 = Terma ini ditadbir oleh undang-undang negeri California, Amerika Syarikat, tidak termasuk konflik peruntukan undang-undang. Jika mana-mana bahagian terma ini diputuskan sebagai tidak sah atau tidak boleh dikuatkuasakan, bahagian yang tinggal akan terus berkuat kuasa dan berkesan sepenuhnya. Sekiranya berlaku percanggahan antara terma versi terjemahan ini dengan versi Bahasa Inggeris, versi Bahasa Inggeris akan diguna pakai.
