[package]
name = "gkrust-gtest"
version = "0.1.0"
authors = ["nobody@mozilla.org"]
license = "MPL-2.0"
description = "Testing code for libgkrust"

[features]
quantum_render = ["gkrust-shared/quantum_render"]
cubeb-remoting = ["gkrust-shared/cubeb-remoting"]
cubeb_coreaudio_rust = ["gkrust-shared/cubeb_coreaudio_rust"]
cubeb_pulse_rust = ["gkrust-shared/cubeb_pulse_rust"]
gecko_debug = ["gkrust-shared/gecko_debug"]
gecko_refcount_logging = ["gkrust-shared/gecko_refcount_logging"]
simd-accel = ["gkrust-shared/simd-accel"]
moz_memory = ["gkrust-shared/moz_memory"]
moz_places = ["gkrust-shared/moz_places"]
spidermonkey_rust = ["gkrust-shared/spidermonkey_rust"]
cranelift_x86 = ["gkrust-shared/cranelift_x86"]
cranelift_arm32 = ["gkrust-shared/cranelift_arm32"]
cranelift_arm64 = ["gkrust-shared/cranelift_arm64"]
cranelift_none = ["gkrust-shared/cranelift_none"]
smoosh = ["gkrust-shared/smoosh"]
gecko_profiler = ["gkrust-shared/gecko_profiler"]
gecko_profiler_parse_elf = ["gkrust-shared/gecko_profiler_parse_elf"]
bitsdownload = ["gkrust-shared/bitsdownload"]
new_xulstore = ["gkrust-shared/new_xulstore"]
new_cert_storage = ["gkrust-shared/new_cert_storage"]
fuzzing_interfaces = ["gkrust-shared/fuzzing_interfaces", "gecko-fuzz-targets"]
webrtc = ["gkrust-shared/webrtc"]
wasm_library_sandboxing = ["gkrust-shared/wasm_library_sandboxing"]
webgpu = ["gkrust-shared/webgpu"]
remote_agent = ["gkrust-shared/remote"]
glean = ["gkrust-shared/glean"]
rust_fxa_client = ["gkrust-shared/rust_fxa_client"]

[dependencies]
bench-collections-gtest = { path = "../../../../xpcom/rust/gtest/bench-collections" }
mp4parse-gtest = { path = "../../../../dom/media/gtest" }
nsstring-gtest = { path = "../../../../xpcom/rust/gtest/nsstring" }
xpcom-gtest = { path = "../../../../xpcom/rust/gtest/xpcom" }
gkrust-shared = { path = "../../rust/shared" }
gecko-fuzz-targets = { path = "../../../../tools/fuzzing/rust", optional = true }
# Workaround for https://github.com/rust-lang/rust/issues/58393
mozglue-static = { path = "../../../../mozglue/static/rust" }

[lib]
path = "lib.rs"
crate-type = ["staticlib"]
test = false
doctest = false
bench = false
doc = false
plugin = false
harness = false
