# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

rights-title = Hüquqlarınız Haqqında
rights-intro = { -brand-full-name }, dünya səviyyəsində minlərlə insandan ibarət bir birlik tərəfindən inkişaf etdirilən azad və açıq qaynaqlı bir proqramdır. Bilməli olduğunuz bir neçə şey var:
rights-intro-point-1 = { -brand-short-name } <a data-l10n-name="mozilla-public-license-link">Mozilla İctimai Lisenziyası</a> ilə yayımlanmaqdadır. Yəni { -brand-short-name } sərbəst şəkildə istifadə oluna bilər, köçürülə bilər və parçalana bilər. Və ehtiyaclarınıza görə { -brand-short-name } qaynaq kodlarını da dəyişdirə bilərsiniz. Mozilla İctimai Lisenziyası, dəyişdirdiyiniz versiyaları yaymaq haqqını da sizə verir.
rights-intro-point-2 = Mozilla Fondu və ya başqa tərəfin hər hansı bir əmtəə nişanı və ya lisenziyası, Firefox adı və loqosu da daxil olmaqla, üzərində heç bir haqqınız yoxdur. Əmtəə nişanları ilə əlaqəli ətraflı məlumat <a data-l10n-name="mozilla-trademarks-link">buradan baxa bilərsiniz</a>açıqlanmışdır.
rights-intro-point-3 = { -brand-short-name } səyyahınızdakı Çökmə Xəbərçisi kimi bəzi funksiyalar sizə { -vendor-short-name } üçün əks əlaqə vermə imkanı verir. Əks əlaqə verməyi seçməklə { -vendor-short-name } tərəfinə məhsullarını inkişaf etdirmək üçün bu məlumatı istifadə etmə, verdiyiniz əks əlaqəni saytlarında nəşr etmək və əks əlaqənizlə bölüşmək icazəsi vermiş olursunuz.
rights-intro-point-4 = Şəxsi məlumat və əks əlaqənizi { -brand-short-name } ilə { -vendor-short-name }-ya göndərdiyinizdə necə istifadə etdiyimiz <a data-l10n-name="mozilla-privacy-policy-link">{ -brand-short-name } Məxfilik Siyasətində</a> təsvir edilib.
rights-intro-point-4-unbranded = Bu məhsulla bağlı bütün məxfilik siyasətləri burada sıralanmalıdır.
rights-intro-point-5 = Bəzi { -brand-short-name } funksiyaları veb əsaslı məlumat xidmətlərindən yararlanır, ancaq bunların 100% doğru və ya xətasız olduğuna zəmanət verə bilmərik. Daha ətraflı və həmçinin bu xidmətlərin necə söndürülməsi haqqında məlumatı buradan tapa bilərsiz:<a data-l10n-name="mozilla-service-terms-link">xidmət şərtləri</a>açıqlanmışdır.
rights-intro-point-5-unbranded = Bu məhsul web xidmətləri ilə bağlantı qurursa, xidmət(lər) ilə bağlı bütün xidmət şərtləri <a data-l10n-name="mozilla-website-services-link">Web Sayt Xidmətləri</a> bölməsinə bağlanmalıdır.
rights-intro-point-6 = Bəzi video məzmunları oxutmaq üçün { -brand-short-name } bəzi üçüncü tərəf məzmun dekodlaşdırma modullarını endirir.
rights-webservices-header = { -brand-full-name } Web Əsaslı Məlumat Xidmətləri
rights-webservices = { -brand-full-name } bu cütlük { -brand-short-name } versiyasında istifadənizə verilən bəzi funksiyalar üçün, aşağıda açıqlanan şərtlər əsasında web əsaslı məlumat xidmətlərindən ("Servislər") faydalanır. Xidmətlərdən birini və ya bir neçəsini istifadə etmək istəmirsinizsə və ya aşağıdakı şərtləri qəbul etmirsinizsə müvafiq funksiyanı və Xidmət(lər)i deaktiv edə bilərsiniz. Funksiya və Xidmətləri deaktiv etmək üçün təlimatlar <a data-l10n-name="mozilla-disable-service-link">buradan baxa bilərsiniz</a>. Digər xüsusiyətlər və Servislər tətbiqetmə seçimlərindən deaktiv edilə bilərlər.
rights-safebrowsing = <strong>Təhlükəsiz baxış: </strong>Təhlükəsiz Baxış funsiyasını söndürməyiniz etibar edilməyən saytlara girməyinizlə nəticələnə biləcəyi üçün tövsiyyə edilmir. Bu funksiyanı tamam söndürmək istəyirsinizsə bu addımları təkrarlayın:
rights-safebrowsing-term-1 = Proqram tərcehlərini aç
rights-safebrowsing-term-2 = Təhlükəsizlik bölməsini seçin
rights-safebrowsing-term-3 = "{ enableSafeBrowsing-label }" aktivləşdirmək üçün seçimi qaldır
enableSafeBrowsing-label = Təhlükəli və aldadıcı məzmunu blokla
rights-safebrowsing-term-4 = Təhlükəsiz baxış artıq söndürülüb
rights-locationawarebrowsing = <strong>Vəziyyətə həssas baxış: </strong>həmişə sizin istəyinizlə işləyər.  İcazəniz olmadan heç vaxt mövqe məlumatlarınız göndərilməyib.  Əgər funksiyanı tamamən söndürmək istəyirsinizsə bu addımları təkrarlayın:
rights-locationawarebrowsing-term-1 = Ünvan sətirinə bunu yazın: URL <code>about:config</code>
rights-locationawarebrowsing-term-2 = geo.enabled yazın
rights-locationawarebrowsing-term-3 = geo.enabled seçiminə iki dəfə tıklayın
rights-locationawarebrowsing-term-4 = Vəziyyətə həssas baxış artıq söndürülüb
rights-webservices-unbranded = Məhsuluna daxil olan web sayt xidmətlərinə ümumi baxış və varsa söndürülmə təlimatları buraya əlavə edilməlidir.
rights-webservices-term-unbranded = Bu məhsulla bağlı bütün xidmət şərtləri burada yazılmalıdır.
rights-webservices-term-1 = { -vendor-short-name } və ona kömək edənlər, lisenziya sahibləri və iş ortaqları ən əksiksiz və aktual Xidmətləri təqdim etmək üçün birlikdə işləməkdədir. Buna baxmayaraq bu məlumatların hərtərəfli və xətasız olduğuna zəmanət verə bilmərik. Məsələn: Təhlükəsiz Baxış xidməti bəzi risqli saytları tanımaya bilər və bəzi təhlükəsiz saytları yanlış tanıya bilər. Vəziyyətə həssas Xidmət də xidmət təminatçılarımız tərəfindən göstərilən bütün vəziyyətlər sadəcə ehtimaldır və nə biz nə də xitmət təminatçılarımız bu vəziyyətlərin doğruluğuna zəmanət vermirik.
rights-webservices-term-2 = { -vendor-short-name } öz istəyi ilə Xidmətləri dayandıra və ya dəyişdirə bilər.
rights-webservices-term-3 = Bu xidmətləri uyğun { -brand-short-name } istifadə etməkdə sərbəstsiniz və  { -vendor-short-name } sizə bu haqları verir. { -vendor-short-name } və lisenziya sahibləri üzərindəki digər bütün haqlara sahibdir.  Bu şərtlər { -brand-short-name } və əlaqəli { -brand-short-name } qaynaq kodu versiyalarında etibarlı olan açıq qaynaq lisenziya haqlarınızı heç bir şəkildə məhdudlaşdırmır.
rights-webservices-term-4 = <strong>Servislər "olduqları kimi" təmin olunur.  { -vendor-short-name }, ona yardım edənlər, lisenziya sahibləri və paylayıcılar, servislərin ticari dəyəri olduğu və ehtiyyaclarına uyğun olacağı barədə yazılı və ya sözlü hər hansı bir sığorta verməz.  Ehtiyaclarınızı qarşılamaq üçün Servisləri seçsəniz keyfiyyət və performans ilə bağlı bütün risklər sizə aiddir. Bəzı qanunlar sığortaların xaric tutulmasına və ya məhdudlaşdırılmasına icazə verməyə bilər. Bu halda bu şərtlər sizin üçün keçərli olmayacaqdır.</strong>
rights-webservices-term-5 = <strong>Qanunun tələb etdiyi vaxtlar xaric, { -vendor-short-name }, onun dəstəkçiləri, lisenziya sahibləri və yayanlar { -brand-short-name } və Servislərinin işlənməsindən yarana biləcək hər hansı bir dolayı, xüsusi, təsadüfi, sonradan yaranan, ağır və ya nümunəvi xəsardan cavabdeh deyillər.  Bu şərtlər altında kollektiv cəza $500 (beş yüz USD) üzəri ola bilməz. Bəzi yurisdiksiyalar məlum zərərlərin istisna hal olmasına və ya limitlənməsinə icazə vermirlər, bu səbəbdən bu istisna və limitləmə sizin üçün keçərli olmaya bilər.</strong>
rights-webservices-term-6 = { -vendor-short-name } lazım bilərsə bu şərtləri yeniləyə bilər. Bu şərtlər { -vendor-short-name }-nın yazılı təsdiqi olmadan dəyişdirilə bilməz və ya ləğv edilə bilməz.
rights-webservices-term-7 = Bu şərtlər, qanun mübahisəsi hökmləri xaric olmaqla, ABŞ Kaliforniya ştatı qanunları ilə qorunur. Bu şərtlərin hər hansı bir hissəsinin ləğv və ya tətbiq edilə bilməz vəziyyətdə olduğu halda, geri qalan hissələr etibarlı və effektiv olmaya davam edəcəkdir. Bu şərtlərin tərcümə versiyası ilə İngiliscə versiyası arasında fərq olarsa, İngiliscə versiyası etibarlı sayılacaq.
