# This Source Code Form is subject to the terms of the Waterfox Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

rights-title = Om rettane dine
rights-intro = { -brand-full-name } er programvare basert på fri og open kjeldekode, som er bygd av eit fellesskap av tusenvis rundt om i heile verda. Det er nokre ting du bør vere merksam på:
rights-intro-point-1 = { -brand-short-name } er gjort tilgjengeleg for deg under vilkåra i <a data-l10n-name="mozilla-public-license-link">Waterfox Public License</a>. Dette tyder at du kan bruke, kopiere og distribuere { -brand-short-name } til andre. Du kan også endre kjeldekoden til { -brand-short-name } som du vil, for å passe til dine behov. Waterfox Public License gjev deg også rett til å distribuere endra versjonar.
rights-intro-point-2 = Du vert ikkje gjeve varemerkerettar eller lisensar til varemerke som tilhøyrer Waterfox Foundation eller andre, noko som òg gjeld Waterfox-namnet og logoen. Meir informasjon om varemerke finn du  <a data-l10n-name="mozilla-trademarks-link">her</a>.
rights-intro-point-3 = Nokre funksjonar i { -brand-short-name }, som til dømes krasjrapporteraren, gjev deg høve til å gje tilbakemelding til { -vendor-short-name }. Ved å sende tilbakemelding gjev du { -vendor-short-name } løyve til å bruke tilbakemeldingane for å forbetre produkta sine, publisere tilbakemeldingane på nettstadane sine, og å distribuere tilbakemeldingane.
rights-intro-point-4 = Korleis vi brukar personleg informasjon og tilbakemeldingar som er sendt til { -vendor-short-name } gjennom { -brand-short-name } er skildra i <a data-l10n-name="mozilla-privacy-policy-link">{ -brand-short-name }s personvernpraksis</a>.
rights-intro-point-4-unbranded = Eventuelle personvernpaksisar for dette produktet bør førast opp her.
rights-intro-point-5 = Nokre { -brand-short-name }-funksjonar brukar nettbaserte informasjonstenester, men vi kan ikkje garantere at dei er 100 % nøyaktige eller feilfrie. Meir informasjon, også om korleis tenestene som brukar desse funksjonane kan slåast av, kan du finne i <a data-l10n-name="mozilla-service-terms-link">tenestevilkåra</a>.
rights-intro-point-5-unbranded = Dersom dette produktet omfattar informasjonstenester, så bør tenestevilkår for tenestene lenkast opp i <a data-l10n-name="mozilla-website-services-link">nettstadtenester</a>-seksjonen.
rights-intro-point-6 = For å spele av forskjellige typar videoinnhald, lastar { -brand-short-name } ned dekrypteringsmodular frå tredjepartar.
rights-webservices-header = { -brand-full-name } nettbaserte informasjonstenester
rights-webservices = { -brand-full-name } brukar nettbaserte informasjonstenester («Tenester») for å gjere nokre av funksjonane tilgjengelege i den binære versjonen av { -brand-short-name }, under vilkår som er skildra nedanfor. Dersom du ikkje ønskjer å bruke ei eller fleire av tenestene, eller om du ikkje kan akseptere vilkåra, kan du slå av funksjonen eller tenesta/tenestene. Instruksjonar om korleis du slår av ein bestemt funksjon eller teneste finn du <a data-l10n-name="mozilla-disable-service-link">her</a>. Andre funksjonar og tenester kan slåast av i program-innstillingane.
rights-safebrowsing = <strong>Trygg nettlesing: </strong>Å slå av funksjonen Trygg nettlesing er ikkje tilrådd, sidan det kan føre til at du vitjar utrygge nettstadar.  Dersom du ønskjer å skru av funksjonen heilt, følg desse stega:
rights-safebrowsing-term-1 = Opne program-innstillingane
rights-safebrowsing-term-2 = Vel Sikkerheits-fana
rights-safebrowsing-term-3 = Slå av valet for å "{ enableSafeBrowsing-label }"
enableSafeBrowsing-label = Blokker farleg og villeiande innhald
rights-safebrowsing-term-4 = Trygg nettlesing er no slått av
rights-locationawarebrowsing = <strong>Stad-medviten nettlesing:</strong>er alltid ein funksjon du må aktivt velje å slå på for at han skal brukast. Ingen stadinfo vert sendt utan at du gjev løyve til det. Dersom du ønskjer å slå av denne funksjonen heilt, følg desse stega:
rights-locationawarebrowsing-term-1 = I adresselinja, skriv du inn <code>about:config</code>
rights-locationawarebrowsing-term-2 = Skriv inn geo.enabled
rights-locationawarebrowsing-term-3 = Dobbelklikk på geo.enabled preference
rights-locationawarebrowsing-term-4 = Stad-medviten nettlesing er no slått av
rights-webservices-unbranded = Ei oversikt over informasjonstenestene som dette produktet inneheld, samt informasjon om korleis du kan slå dei av, bør inkluderast her.
rights-webservices-term-unbranded = Andre tenestevilkår for dette produktet bør førast opp her.
rights-webservices-term-1 = { -vendor-short-name } og bidragsytarane, lisensgjevarar og partnarar jobbar for å tilby den mest nøyaktige og oppdaterte tenesta.  Vi kan likevel ikkje garantere at denne informasjonen er fullstendig og feilfri. Det kan til dømes hende at nokre risikable nettstader ikkje er oppdaga enno, og nokre trygge nettstadar kan feilaktig ha blitt klassifiserte som risikable. All info som vert returnert frå tenestetilbydarane våre er berre estimat, og korkje vi eller tenestetilbydarane garanterer at informasjonen som vert spesifisert er heilt nøyaktig.
rights-webservices-term-2 = { -vendor-short-name } kan avbryte eller endre Tenestene etter eige ønskje.
rights-webservices-term-3 = Du er velkomen til å bruke desse Tenestene med den medfølgjande versjonen av { -brand-short-name }, og { -vendor-short-name } gjev deg retten til å gjera det. { -vendor-short-name } og lisensgjevarane reserverer alle andre rettar til Tenestene.  Desse vilkåra er ikkje der for å avgrense rettane som er gjevne under open kjeldekode-lisensane som gjeld for { -brand-short-name }, og den tilhøyrande kjeldekodeutgåva av { -brand-short-name }.
rights-webservices-term-4 = <strong>Tenestene er tilbydde "som-dei-er." { -vendor-short-name }, bidragsytarane, lisensgjevarane og distributørane gjev ingen garantiar, korkje eksplisitt eller implisitt, inkludert utan avgrensingar, garantiar for at Tenestene skal passe til føremåla dine. Du har den fulle og heile risikoen for å velje Tenestene for å oppnå dine føremål, samt for kvaliteten og ytinga til Tenestene. Nokre jurisdiksjonar tillèt ikkje at implisitte garantiar vert ekskluderte, så dette dementiet gjeld kanskje ikkje deg.</strong>
rights-webservices-term-5 = <strong>Med unntak av der det er påkravd av lova, { -vendor-short-name }, dess bidragsytarar, lisensgjevarar og distributørar er ikkje ansvarlege for nokon indirekte, spesiell, tilfeldig, følgjeleg, strafferettsleg eller mønstergyldige skadar eller ulemper som skjer som ei følgje av eller relatert til bruk av { -brand-short-name } og Tenestene. Det kollektive ansvaret i desse vilkåra vil ikkje overstige $500 (fem hundre amerikanske dollar). Nokre jurisdiksjonar tillèt ikkje eksklusjon eller avgrensing av enkelte former av skade, så det er mogleg desse eksklusjonane og avgrensingane ikkje gjeld deg.</strong>
rights-webservices-term-6 = { -vendor-short-name } kan oppdatere desse vilkåra etter behov med jamne mellomrom. Vilkåra kan ikkje endrast eller annullerast utan skriftleg avtale frå { -vendor-short-name }.
rights-webservices-term-7 = Desse vilkåra er underlagt lova til staten California, U.S.A., med unntak av der lovpålegg krev unntak. Dersom nokre av desse vilkåra viser seg å vere ugyldige eller ikkje rettskraftige, vil dei attverande delane framleis ha effekt. Dersom det er avvik mellom ein omsett versjon av desse vilkåra og den engelske utgåva, vil den engelske utgåva gjelde.
