# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#filter emptyLines

#define MOZ_LANGPACK_CREATOR mozilla.org

# If non-English locales wish to credit multiple contributors, uncomment this

# variable definition and use the format specified.

#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>अनिकेत देशपांडे</em:contributor> <em:contributor>सुरज कवडे</em:contributor> <em:contributor>संदीप शेडमाके</em:contributor> <em:contributor>चंद्रकांत धुतडमल</em:contributor>

#unfilter emptyLines
