# This Source Code Form is subject to the terms of the Waterfox Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with
# your locale code, and link to your translated pages as soon as they're
# live.

#define bookmarks_title العلامات
#define bookmarks_heading العلامات

#define bookmarks_toolbarfolder مجلّد شريط العلامات
#define bookmarks_toolbarfolder_description أضِف هنا العلامات التي تريد ظهورها في شريط العلامات

# LOCALIZATION NOTE (getting_started):
# link title for https://www.mozilla.org/en-US/firefox/central/
#define getting_started البداية

# LOCALIZATION NOTE (firefox_heading):
# Waterfox links folder name
#define firefox_heading Waterfox

# LOCALIZATION NOTE (firefox_help):
# link title for https://www.mozilla.org/en-US/firefox/help/
#define firefox_help المساعدة والدروس

# LOCALIZATION NOTE (firefox_get_help):
# link title for https://www.mozilla.org/en-US/firefox/help/
#define firefox_get_help مُساعدة

# LOCALIZATION NOTE (firefox_customize):
# link title for https://www.mozilla.org/en-US/firefox/customize/
#define firefox_customize خصّص Waterfox

# LOCALIZATION NOTE (firefox_community):
# link title for https://www.mozilla.org/en-US/contribute/
#define firefox_community شارك

# LOCALIZATION NOTE (firefox_about):
# link title for https://www.mozilla.org/en-US/about/
#define firefox_about عن موزيلا

# LOCALIZATION NOTE (nightly_heading):
# Waterfox Nightly links folder name
#define nightly_heading موارد Waterfox الليلية

# LOCALIZATION NOTE (nightly_blog):
# Nightly builds only, link title for https://blog.nightly.mozilla.org/
#define nightly_blog مدونة Waterfox الليلية

# LOCALIZATION NOTE (bugzilla):
# Nightly builds only, link title for https://bugzilla.mozilla.org/
#define bugzilla متتبع علل Waterfox

# LOCALIZATION NOTE (mdn):
# Nightly builds only, link title for https://developer.mozilla.org/
#define mdn شبكة Waterfox للمطورين

# LOCALIZATION NOTE (nightly_tester_tools):
# Nightly builds only, link title for https://addons.mozilla.org/en-US/firefox/addon/nightly-tester-tools/
#define nightly_tester_tools أدوات المختبِر الليلي

# LOCALIZATION NOTE (crashes):
# Nightly builds only, link title for about:crashes
#define crashes كل الانهيارات

# LOCALIZATION NOTE (planet):
# Nightly builds only, link title for https://planet.mozilla.org/
#define planet كوكب Waterfox

#unfilter emptyLines
