# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

safeb-blocked-phishing-page-title = ’S e làrach foille a tha seo
safeb-blocked-malware-page-title = Dh’fhaoidte gun èirich cron air a’ choimpiutair agad ma thadhlas tu air an làrach-lìn seo
safeb-blocked-unwanted-page-title = Dh’fhaoidte gu bheil prògraman dochainneach air an làrach seo
safeb-blocked-harmful-page-title = Dh’fhaoidte gu bheil bathar-bog droch rùnach air an làrach seo
safeb-blocked-phishing-page-short-desc = Bhac { -brand-short-name } an duilleag seo air dh’fhaoidte gum bi e ri foill chunnartach, mar eisimpleir a bhith a’ stàladh bathar-bog no a’ goid fiosrachadh pearsanta ort mar fhaclan-faire no cairtean-creideis.
safeb-blocked-malware-page-short-desc = Bhac { -brand-short-name } an duilleag seo airson ’s nach feuch e ri bathar-bog droch-rùnach a stàladh a bhiodh airson dàta pearsanta a ghoid no a sguabadh às a’ choimpiutair agad.
safeb-blocked-unwanted-page-short-desc = Bhac { -brand-short-name } an duilleag seo oir tha cunnart gum bi e ri foill is e a’ feuchainn ri prògraman a stàladh air an uidheam agad a nì cron air do bhrabhsadh (mar eisimpleir, le bhith ag atharrachadh na duilleige-dachaidh agad no a’ sealltainn sanasachd air làraichean air an tadhail thu).
safeb-blocked-harmful-page-short-desc = Bhac { -brand-short-name } an duilleag seo oir tha teans gum feuch e ri aplacaidean cunnartach a stàladh a ghoideas no a sguabas às fiosrachadh agad (mar eisimpleir, dealbhan, faclan-faire, teachdaireachdan is cairtean-creideis).
safeb-palm-advisory-desc = Comhairle air a sholar le <a data-l10n-name='advisory_provider'>{ $advisoryname }</a>.
safeb-palm-accept-label = Air ais
safeb-palm-see-details-label = Faic am mion-fhiosrachadh
safeb-blocked-phishing-page-error-desc-override = Chaidh <a data-l10n-name='error_desc_link'>aithris a dhèanamh gur e làrach foille</a> a tha ann an <span data-l10n-name='sitename'>{ $sitename }</span>. ’S urrainn dhut <a data-l10n-name='report_detection'>aithris a dhèanamh gu bheil seo cearr</a> no <a data-l10n-name='ignore_warning_link'>an cunnart a leigeil seachad</a> agus tadhal air an làrach mhì-shàbhailte seo co-dhiù.
safeb-blocked-phishing-page-error-desc-no-override = Chaidh <a data-l10n-name='error_desc_link'>aithris a dhèanamh</a> gur e làrach foille a tha ann an <span data-l10n-name='sitename'>{ $sitename }</span>. ’S urrainn dhut <a data-l10n-name='report_detection'>aithris a dhèanamh thu fhèin gu bheil rudeigin cearr a thaobh sin</a>.
safeb-blocked-phishing-page-learn-more = Faigh barrachd fiosrachaidh mu làraichean foille agus fiasgach aig <a data-l10n-name='learn_more_link'>www.antiphishing.org</a>. Faigh barrachd fiosrachaidh mun dìon a tha { -brand-short-name }’s a’ toirt dhut o bhathar-bog droch-rùnach agus fiasgach aig <a data-l10n-name='firefox_support'>support.mozilla.org</a>.
safeb-blocked-malware-page-error-desc-override = Chaidh <a data-l10n-name='error_desc_link'>aithris</a> a dhèanamh gu bheil bathar-bog droch-rùnach air <span data-l10n-name='sitename'>{ $sitename }</span>. ’S urrainn dhut <a data-l10n-name='report_detection'>aithris a dhèanamh thu fhèin gu bheil rudeigin cearr a thaobh sin</a> no <a data-l10n-name='ignore_warning_link'>an cunnart a leigeil seachad</a> agus tadhal air an làrach mhì-shàbhailte co-dhiù.
safeb-blocked-malware-page-error-desc-no-override = Chaidh <a data-l10n-name='error_desc_link'>aithris</a> a dhèanamh gu bheil bathar-bog droch-rùnach air <span data-l10n-name='sitename'>{ $sitename }</span>. ’S urrainn dhut <a data-l10n-name='report_detection'>aithris a dhèanamh thu fhèin gu bheil rudeigin cearr a thaobh sin</a>.
safeb-blocked-malware-page-learn-more = Faigh barrachd fiosrachaidh mu shusbaint-lìn dhochainneach, a’ gabhail a-staigh bhìorasan agus bathar droch-rùnach eile agus mar a dhìonas tu an coimpiutair agad aig <a data-l10n-name='learn_more_link'>StopBadware.org</a>. Faigh barrachd fiosrachaidh mun dìon aig { -brand-short-name }’s ro bhathar droch-rùnach agus fiasgach aig <a data-l10n-name='firefox_support'>support.mozilla.org</a>.
safeb-blocked-unwanted-page-error-desc-override = Chaidh <a data-l10n-name='error_desc_link'>aithris a dhèanamh gu bheil bathar-bog dochainneach</a> air <span data-l10n-name='sitename'>{ $sitename }</span>. ’S urrainn dhut <a data-l10n-name='ignore_warning_link'>an cunnart a leigeil seachad</a> agus tadhail air an làrach mhì-shàbhailte seo a dh’aindeoin sin.
safeb-blocked-unwanted-page-error-desc-no-override = Chaidh <a data-l10n-name='error_desc_link'>aithris a dhèanamh gu bheil bathar-bog dochainneach</a> air <span data-l10n-name='sitename'>{ $sitename }</span>.
safeb-blocked-unwanted-page-learn-more = Faigh barrachd fiosrachaidh air bathar-bog gun iarraidh no bathar dochainneach sa <a data-l10n-name='learn_more_link'>phoileasaidh mu bhathar-bog gun iarraidh</a>. Faigh barrachd fiosrachaidh air an dìon a bheir { -brand-short-name }’s dhut o bhathar droch-rùnach is fiasgach air <a data-l10n-name='firefox_support'>support.mozilla.org</a>.
safeb-blocked-harmful-page-error-desc-override = Chaidh <a data-l10n-name='error_desc_link'>aithris a dhèanamh gu bheul aplacaid chunnartach</a> air <span data-l10n-name='sitename'>{ $sitename }</span>. ’S urrainn dhut <a data-l10n-name='ignore_warning_link'>an cunnart a leigeil seachad</a> agus tadhal air an làrach mhì-shàbhailte co-dhiù.
safeb-blocked-harmful-page-error-desc-no-override = Chaidh <a data-l10n-name='error_desc_link'>aithris a dhèanamh gu bheul aplacaid chunnartach</a> air <span data-l10n-name='sitename'>{ $sitename }</span>.
safeb-blocked-harmful-page-learn-more = Faigh barrachd fiosrachaidh mun dìon a tha { -brand-short-name }’s a’ toirt dhut o bhathar-bog droch-rùnach agus fiasgach aig <a data-l10n-name='firefox_support'>support.mozilla.org</a>.
safeb-palm-notdeceptive =
    .label = Chan e làrach foill a tha seo…
    .accesskey = d
