<hbox data-subcategory="permissions-images">
<checkbox id="loadImages" class="tail-with-learn-more"
            data-l10n-id="load-images"
            preference="permissions.default.image"
            flex="1"/>
</hbox>

<hbox data-subcategory="permissions-scripts">
<checkbox id="enableJavaScript" class="tail-with-learn-more"
            data-l10n-id="enable-javascript"
            preference="javascript.enabled"
            flex="1"/>
</hbox>