# This Source Code Form is subject to the terms of the Waterfox Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

rights-title = I tuoi diritti
rights-intro = { -brand-full-name } è un software libero e Open Source, realizzato da una comunità di migliaia di persone provenienti da tutto il mondo. Ci sono alcuni aspetti che è utile conoscere:
rights-intro-point-1 = { -brand-short-name } è disponibile nei termini della <a data-l10n-name="mozilla-public-license-link">Waterfox Public License</a>. Questo significa che è possibile usare, copiare e distribuire { -brand-short-name } ad altre persone. Le modifiche al codice sorgente di { -brand-short-name } per adattarlo alle proprie esigenze sono benaccette. Inoltre, la Waterfox Public License garantisce il diritto di distribuire tali versioni modificate.
rights-intro-point-2 = Waterfox non attribuisce all’utente alcun diritto o licenza relativamente all’utilizzo dei marchi registrati da Waterfox Foundation o da altri soggetti, inclusi senza alcuna limitazione il nome Thunderbird e i logo associati. Ulteriori informazioni su questo argomento sono disponibili <a data-l10n-name="mozilla-trademarks-link">in questa pagina</a>.
rights-intro-point-3 = Alcune caratteristiche di { -brand-short-name }, come ad esempio Crash Reporter, offrono la possibilità di inviare commenti e suggerimenti a { -vendor-short-name }. Scegliendo di trasmettere questi dati, si garantisce a { -vendor-short-name } il permesso di utilizzare queste informazioni per migliorare i propri prodotti, pubblicare sui propri siti web o distribuire i dati raccolti.
rights-intro-point-4 = Le modalità di utilizzo dei dati personali, dei commenti e dei suggerimenti raccolti da { -vendor-short-name } attraverso { -brand-short-name } sono descritte nella <a data-l10n-name="mozilla-privacy-policy-link">Informativa sulla privacy di { -brand-short-name }</a>.
rights-intro-point-4-unbranded = Qualsiasi informativa sulla privacy relativa a questo prodotto dovrà essere riportata in questa sezione.
rights-intro-point-5 = Alcune caratteristiche di { -brand-short-name } si appoggiano a servizi di informazioni basati sul Web, anche se non è possibile garantire la completa accuratezza e l’affidabilità di tali servizi. Ulteriori dettagli, comprese indicazioni per disattivare questi servizi, sono disponibili <a data-l10n-name="mozilla-service-terms-link">nei termini di utilizzo</a>.
rights-intro-point-5-unbranded = Se questo prodotto include dei servizi web, tutti i termini di utilizzo dovranno essere riportati nella sezione <a data-l10n-name="mozilla-website-services-link">Servizi web</a>.
rights-intro-point-6 = Per riprodurre alcuni tipi di contenuti video, { -brand-short-name } scarica dei moduli di decrittazione da terze parti.
rights-webservices-header = Servizi di informazioni basati sul Web di { -brand-full-name }
rights-webservices = { -brand-full-name } utilizza alcuni servizi web (“Servizi”) distribuiti con questa versione dell’eseguibile di { -brand-short-name } nei termini descritti di seguito. Se non si desidera utilizzare tali Servizi oppure i termini di utilizzo risultano inaccettabili, è possibile disattivarli. Istruzioni per disattivare una caratteristica specifica o un Servizio sono disponibili <a data-l10n-name="mozilla-disable-service-link">in questa pagina</a>. Altre caratteristiche e servizi possono essere disattivati nelle preferenze dell’applicazione.
rights-locationawarebrowsing = <strong>Navigazione geolocalizzata: </strong>richiede sempre un consenso esplicito. Nessuna informazione sulla posizione viene mai trasmessa senza consenso. Per disattivare completamente questa caratteristica procedere nel seguente modo:
rights-locationawarebrowsing-term-1 = Nella barra degli indirizzi digitare <code>about:config</code>
rights-locationawarebrowsing-term-2 = Digitare geo.enabled
rights-locationawarebrowsing-term-3 = Fare doppio clic sulla voce geo.enabled
rights-locationawarebrowsing-term-4 = Da questo momento la navigazione geolocalizzata è disattivata
rights-webservices-unbranded = Una panoramica dei servizi web inclusi nel prodotto, comprese le indicazioni per disattivarli (se applicabile), dovranno essere riportati in questa sezione.
rights-webservices-term-unbranded = Tutti i termini di utilizzo dei servizi relativi a questo prodotto dovranno essere riportati in questa sezione.
rights-webservices-term-1 = { -vendor-short-name } e i suoi collaboratori, i licenziatari e i partner si impegnano a fornire i servizi nella forma più accurata e aggiornata possibile. Tuttavia non è sempre possibile garantire la completezza e l’affidabilità di tali informazioni. Ad esempio, il servizio di Safe Browsing potrebbe non essere in grado di individuare siti web pericolosi o identificare erroneamente alcuni siti affidabili come pericolosi. Inoltre, tutte le posizioni fornite dal servizio di navigazione geolocalizzata sono stime trasmesse dai nostri fornitori, per cui non siamo in grado, né lo sono i nostri fornitori, di garantire l’accuratezza di questi dati.
rights-webservices-term-2 = { -vendor-short-name } si riserva il diritto di modificare o interrompere il Servizio a propria discrezione.
rights-webservices-term-3 = L’utente è invitato a utilizzare i Servizi inclusi in questa versione di { -brand-short-name } e { -vendor-short-name } gli garantisce tutti i diritti necessari per farlo. { -vendor-short-name } e i suoi licenziatari si riservano tutti gli altri diritti relativi ai Servizi. Questi termini di utilizzo non intendono in alcun modo limitare i diritti derivanti da licenze Open Source applicabili a { -brand-short-name } e alla versioni corrispondenti del codice sorgente di { -brand-short-name }.
rights-webservices-term-4 = <strong>I servizi sono distribuiti “così come descritti”. { -vendor-short-name }, i collaboratori, i licenziatari e i distributori non forniscono alcuna garanzia, implicita o esplicita, incluse, senza alcuna limitazione, garanzie sulla possibilità di vendere i Servizi o sull’adeguatezza alle esigenze dell’utilizzatore. L’utente si assume l’intero rischio scegliendo di utilizzare il servizio, sia per quanto riguarda l’adeguatezza delle funzioni, sia per la qualità e le prestazioni del servizio stesso. In alcune giurisdizioni non è possibile imporre esclusioni o limitazioni alle garanzie implicite, in tali casi questa dichiarazione di non responsabilità non sarà applicabile.</strong>
rights-webservices-term-5 = <strong>Escluse le eccezioni previste dalla legge, { -vendor-short-name }, i collaboratori, i licenziatari e i distributori non potranno essere considerati responsabili per qualsiasi danno indiretto, speciale, accidentale, consequenziale, punitivo o esemplare causato o legato in qualsiasi modo all’uso di { -brand-short-name } e dei Servizi. La responsabilità complessiva nei termini indicati non potrà superare la somma di 500$ (cinquecento dollari). In alcune giurisdizioni non è possibile imporre esclusioni o limitazioni a determinati tipi di danno, in tali casi questa dichiarazione non sarà applicabile.</strong>
rights-webservices-term-6 = { -vendor-short-name } si riserva il diritto di aggiornare periodicamente questi termini di utilizzo. Tali termini non possono essere modificati o cancellati senza l’autorizzazione scritta di { -vendor-short-name }.
rights-webservices-term-7 = Questi termini sono disciplinati dalle leggi dello stato della California, U.S.A., ad esclusione delle disposizioni sul conflitto di leggi. Se una qualsiasi parte di questi termini verrà giudicata invalida o inefficace, la rimanente parte rimarrà valida ed efficace. In caso di incoerenza tra la versione tradotta dei presenti termini e la versione in lingua inglese, avrà priorità la versione in lingua inglese.
