#filter emptyLines

#define MOZ_LANGPACK_CREATOR mozilla.rs

# If non-English locales wish to credit multiple contributors, uncomment this
# variable definition and use the format specified.
#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Марко Костић</em:contributor> <em:contributor>Марко Андрејић</em:contributor> <em:contributor>Александра Узелац</em:contributor> <em:contributor>Вања Тумбас</em:contributor>

#unfilter emptyLines
