#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in some URLs will be replaced with
# your locale code, and link to your translated pages as soon as they're live.

#define bookmarks_title Marcadores
#define bookmarks_heading Marcadores

#define personal_toolbarfolder Pasta da barra de ferramentas pessoal

#define seamonkey_and_mozilla SeaMonkey e Mozilla

# LOCALIZATION NOTE (seamonkey):
# link title for https://www.seamonkey-project.org/ (in the personal toolbar)
#define seamonkey SeaMonkey

# LOCALIZATION NOTE (seamonkey_long):
# link title for https://www.seamonkey-project.org/ (in normal bookmarks)
#define seamonkey_long O projeto SeaMonkey

# LOCALIZATION NOTE (mozilla_org):
# link title for http://www.mozilla.org/ (in the personal toolbar)
#define mozilla_org mozilla.org

# LOCALIZATION NOTE (mozilla_org_long):
# link title for https://www.mozilla.org/ (in normal bookmarks)
#define mozilla_org_long A Organização Mozilla

# LOCALIZATION NOTE (mozilla_projects):
# link title for http://www.mozilla.org/projects/
#define mozilla_projects Projetos Mozilla

# LOCALIZATION NOTE (mozilla_about):
# link title for http://www.mozilla.org/about/
#define mozilla_about Acerca da Mozilla

#define extend_seamonkey Expandir o SeaMonkey

# LOCALIZATION NOTE (seamonkey_addons):
# link title for https://addons.thunderbird.net/en-US/seamonkey/
#define seamonkey_addons Extras do SeaMonkey

# LOCALIZATION NOTE (seamonkey_themes):
# link title for https://addons.thunderbird.net/en-US/seamonkey/themes
#define seamonkey_themes Temas do SeaMonkey

# LOCALIZATION NOTE (seamonkey_dictionaries):
# link title for https://addons.thunderbird.net/en-US/seamonkey/dictionaries
#define seamonkey_dictionaries Dicionários de verificação ortográfica

# LOCALIZATION NOTE (seamonkey_plugins):
# link title for https://addons.thunderbird.net/en-US/seamonkey/plugins
#define seamonkey_plugins Plugins para o SeaMonkey

# LOCALIZATION NOTE (mozdev):
# link title for http://www.mozdev.org/
#define mozdev mozdev.org

# LOCALIZATION NOTE (mozdev_seamonkey):
# link title for http://www.mozdev.org/projects/applications/SeaMonkey.html
#define mozdev_seamonkey Extensões para o SeaMonkey da mozdev.org

#define community_support Comunidade e apoio

# LOCALIZATION NOTE (seamonkey_community):
# link title for https://www.seamonkey-project.org/community
#define seamonkey_community Comunidade do SeaMonkey

# LOCALIZATION NOTE (mozillazine):
# link title for http://www.mozillazine.org/
#define mozillazine mozillaZine

# LOCALIZATION NOTE (seamonkey_support):
# link title for the mozillaZine SeaMonkey Support forum
#define seamonkey_support Fórum de apoio do SeaMonkey (mozillaZine)

# LOCALIZATION NOTE (seamonkey_l10n):
# insert full bookmark line for localized SeaMonkey page (personal toolbar)
# e.g. #define seamonkey_l10n <DT><A HREF="https://www.seamonkey.tlh/">SeaMonkey tlhIngan</a>
#define seamonkey_l10n

 <DT><A HREF="https://www.seamonkey-project.org/">Seamonkey</a># LOCALIZATION NOTE (seamonkey_l10n_long):
# insert full bookmark line for localized SeaMonkey page (normal bookmark)
# e.g. #define seamonkey_l10n_long <DT><A HREF="https://www.seamonkey.tld/">tlhIngan Hol SeaMonkey</a>
#define seamonkey_l10n_long

#unfilter emptyLines
