# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
---
loader: taskgraph.loader.transform:loader

kind-dependencies:
    - packages

transforms:
    - taskgraph.transforms.docker_image:transforms
    - taskgraph.transforms.cached_tasks:transforms
    - taskgraph.transforms.task:transforms

# make a task for each docker-image we might want.  For the moment, since we
# write artifacts for each, these are whitelisted, but ideally that will change
# (to use subdirectory clones of the proper directory), at which point we can
# generate tasks for every docker image in the directory, secure in the
# knowledge that unnecessary images will be omitted from the target task graph
jobs:
    image_builder:
        symbol: I(ib)
    desktop1604-test:
        symbol: I(dt16t)
    debian10-test:
        symbol: I(deb10-test)
    ubuntu1804-test-base:
        symbol: I(ub18-test-base)
    ubuntu1804-test:
        symbol: I(ub18-test)
        parent: ubuntu1804-test-base
    # Neither the debian8-*raw nor the debian8-*packages images can have
    # packages dependencies.
    debian8-raw:
        symbol: I(deb8-raw)
        definition: debian-raw
        args:
            BASE_IMAGE: debian:jessie-20200422
            DIST: jessie
            SNAPSHOT: '20200422T205110Z'
    debian8-packages:
        symbol: I(deb8-pkg)
        definition: debian-packages
        parent: debian8-raw
    debian8-i386-raw:
        symbol: I(deb8-32-raw)
        definition: debian-raw
        args:
            BASE_IMAGE: i386/debian:jessie-20200422
            DIST: jessie
            SNAPSHOT: '20200422T205110Z'
    debian8-i386-packages:
        symbol: I(deb8-32-pkg)
        definition: debian-packages
        parent: debian8-i386-raw
    debian8-base:
        symbol: I(deb8-base)
        definition: debian-base
        parent: debian8-raw
        packages:
            - deb8-gdb
            - deb8-git
            - deb8-mercurial
            - deb8-python3.5
            - deb8-python3-defaults
            - deb8-python-zstandard
            - deb8-xz-utils
    deb8-toolchain-build:
        symbol: I(toolchain)
        parent: debian8-base
        definition: toolchain-build
        packages:
            - deb8-cmake
            - deb8-ninja
    deb9-toolchain-build:
        symbol: I(deb9-toolchain)
        parent: debian9-base
        definition: toolchain-build
    deb10-toolchain-build:
        symbol: I(deb10-toolchain)
        parent: debian10-base
        definition: toolchain-build
        packages:
            - deb10-cmake
    custom-v8:
        symbol: I(custom-v8)
        parent: debian9-base
    debian8-amd64-build-base:
        symbol: I(deb8-bb)
        parent: debian8-base
        definition: debian-build
        args:
            ARCH: amd64
    debian8-amd64-build:
        symbol: I(deb8)
        parent: debian8-base
        definition: debian-build
        packages:
            - deb8-valgrind
        args:
            ARCH: amd64
    debian8-i386-build:
        symbol: I(deb8-32)
        parent: debian8-base
        definition: debian-build
        packages:
            - deb8-valgrind
            - deb8-32-xz-utils
        args:
            ARCH: i386
    debian8-mozjs-rust-build:
        symbol: I(deb8jsrs)
        parent: debian8-amd64-build
        packages:
            - deb8-cmake
    valgrind-build:
        symbol: I(vb)
        parent: debian8-amd64-build
    lint:
        symbol: I(lnt)
    # Neither the debian9-raw nor the debian9-packages images can have
    # packages dependencies.
    debian9-raw:
        symbol: I(deb9-raw)
        definition: debian-raw
        args:
            BASE_IMAGE: debian:stretch-20200422
            DIST: stretch
            SNAPSHOT: '20200422T205110Z'
    debian9-packages:
        symbol: I(deb9-pkg)
        definition: debian-packages
        parent: debian9-raw
    debian9-base:
        symbol: I(deb9-base)
        definition: debian-base
        parent: debian9-raw
        packages:
            - deb9-mercurial
            - deb9-python-zstandard
    debian9-amd64-build:
        symbol: I(deb9)
        parent: debian9-base
        definition: debian-build
        args:
            ARCH: amd64
    # Neither the debian10-raw nor the debian10-packages images can have
    # packages dependencies.
    debian10-raw:
        symbol: I(deb10-raw)
        definition: debian-raw
        args:
            BASE_IMAGE: debian:buster-20200422
            DIST: buster
            SNAPSHOT: '20200422T205110Z'
    debian10-packages:
        symbol: I(deb10-pkg)
        definition: debian-packages
        parent: debian10-raw
    debian10-base:
        symbol: I(deb10-base)
        definition: debian-base
        parent: debian10-raw
        packages:
            - deb10-mercurial
            - deb10-python-zstandard
    debian10-amd64-build:
        symbol: I(deb10)
        parent: debian10-base
        definition: debian-build
        args:
            ARCH: amd64
    debian10-arm64-build:
        symbol: I(deb10-arm64)
        parent: debian10-base
        definition: debian-build
        args:
            ARCH: arm64
    toolchain-arm64-build:
        symbol: I(toolchain-arm64)
        parent: debian10-arm64-build
        definition: toolchain-build
    debian10-test-iris:
        symbol: I(deb10-ti)
        parent: debian10-test
        packages:
            - deb10-python-zstandard
    android-build:
        symbol: I(agb)
        parent: debian9-base
        packages:
            - deb8-valgrind
    fetch:
        symbol: I(fetch)
        parent: debian10-raw
        packages:
            - deb10-python-zstandard
    static-analysis-build:
        symbol: I(static-analysis-build)
        parent: debian9-base
    gdb-test:
        symbol: I(gdb)
        parent: debian8-amd64-build
        definition: gdb-test
    mingw32-build:
        symbol: I(mingw)
        parent: debian9-base
    index-task:
        symbol: I(idx)
    funsize-update-generator:
        symbol: I(pg)
    update-verify:
        symbol: I(uv)
    diffoscope:
        symbol: I(diff)
        parent: debian10-base
    partner-repack:
        symbol: I(PR)
        parent: debian9-base
        definition: partner-repack
    periodic-updates:
        symbol: I(file)
    python-dependency-update:
        symbol: I(pip)
    firefox-snap:
        symbol: I(snap)
    firefox-flatpak:
        symbol: I(flatpak)
    webrender:
        symbol: I(webrender)
        parent: debian9-base
    wgpu:
        symbol: I(wgpu)
        parent: debian9-base
    condprof:
        symbol: I(condprof)
        parent: ubuntu1804-test
    visual-metrics:
        symbol: I(visual-metrics)
        parent: debian9-base
    github-sync:
        symbol: I(github-sync)
        parent: debian9-base
    system-symbols-mac:
        symbol: I(system-symbols-mac)
        parent: debian10-base
    system-symbols-win:
        symbol: I(system-symbols-win)
        parent: debian10-base
