#filter emptyLines

#define MOZ_LANGPACK_CREATOR mozilla.org

# If non-English locales wish to credit multiple contributors, uncomment this
# variable definition and use the format specified.
#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Nguyễn Xuân Minh</em:contributor> <em:contributor>Quế Tùng</em:contributor> <em:contributor>Nguyễn Mạnh Hùng</em:contributor> <em:contributor>Huỳnh Hải Đăng</em:contributor> <em:contributor>Bùi Việt Khoa</em:contributor> <em:contributor>Trần Nguyễn Sơn</em:contributor> <em:contributor>Pierre Neter</em:contributor>

#unfilter emptyLines
