# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#filter emptyLines

#define MOZ_LANGPACK_CREATOR ខ្មែរ (km)

# If non-English locales wish to credit multiple contributors, uncomment this

# variable definition and use the format specified.

#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Eng Vannak</em:contributor> <em:contributor>Khoem Sokhem</em:contributor> <em:contributor>Seng Sutha</em:contributor> <em:contributor>Sok Sophea</em:contributor> <em:contributor>Morn Met</em:contributor> <em:contributor>Chank Sambathratanak</em:contributor>

#unfilter emptyLines
