# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#filter emptyLines

#define MOZ_LANGPACK_CREATOR Mozilla Japanese L10N Community

# If non-English locales wish to credit multiple contributors, uncomment this
# variable definition and use the format specified.
#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Hiroki Abe</em:contributor><em:contributor>Makoto Arai</em:contributor><em:contributor>Tomoya Asai</em:contributor><em:contributor>Hideyuki EMURA</em:contributor><em:contributor>Shaw Hosaka</em:contributor><em:contributor>Joji Ikeda</em:contributor><em:contributor>Masahiko Imanaka</em:contributor><em:contributor>Kosuke Kaizuka</em:contributor><em:contributor>Hidehiro Kozawa</em:contributor><em:contributor>Teiji Matsuba</em:contributor><em:contributor>Shigeki Narisawa</em:contributor><em:contributor>Takeshi Nishimura</em:contributor><em:contributor>Toshiyuki Oka</em:contributor><em:contributor>Atsushi Sakai</em:contributor><em:contributor>Hiroshi Sekiya</em:contributor><em:contributor>Youhei Tooyama</em:contributor><em:contributor>Satoru Yamaguchi</em:contributor>

#unfilter emptyLines
