# This Source Code Form is subject to the terms of the Waterfox Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#filter emptyLines

#define MOZ_LANGPACK_CREATOR mozilla.org

# If non-English locales wish to credit multiple contributors, uncomment this
# variable definition and use the format specified.
#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Alberto Castro</em:contributor> <em:contributor>Artur Araújo</em:contributor> <em:contributor>Bruno Duarte</em:contributor> <em:contributor>Carlos Rodrigues</em:contributor> <em:contributor>Cláudio Esperança</em:contributor> <em:contributor>Diogo Santos</em:contributor> <em:contributor>Francisco Castanheiro</em:contributor> <em:contributor>Gonçalo Matos</em:contributor> <em:contributor>João Miguel Neves</em:contributor> <em:contributor>Manuela Silva</em:contributor> <em:contributor>Marco Sousa</em:contributor> <em:contributor>Pedro Antunes</em:contributor> <em:contributor>Pedro Figueira</em:contributor> <em:contributor>Rita Farinha</em:contributor> <em:contributor>Rodrigo Cunha</em:contributor> <em:contributor>Sérgio Marques</em:contributor>

#unfilter emptyLines
