# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
---
loader: taskgraph.loader.transform:loader

transforms:
    - taskgraph.transforms.task:transforms

job-defaults:
    attributes:
        cron: true
        # This enables uploading symbols.
        enable-full-crashsymbols: true
    treeherder:
        platform: symbols/opt
        kind: build
        tier: 2
    worker-type: b-linux

jobs:
    mac:
        description: Extract macOS system symbols found in crashreports
        index:
            product: system-symbols
            job-name: mac
            type: generic
        worker:
            env:
                PROCESSED_PACKAGES_INDEX: gecko.v2.mozilla-central.latest.system-symbols.mac
                PROCESSED_PACKAGES_PATH: public/build/processed-packages.gz
            artifacts:
                - name: public/build
                  type: directory
                  path: /home/worker/artifacts/
            docker-image: {in-tree: system-symbols-mac}
            max-run-time: 28800
        treeherder:
            symbol: system-symbols-mac
    win:
        description: Extract windows system symbols found in crashreports
        worker:
            artifacts:
                - name: public/build
                  type: directory
                  path: /home/worker/artifacts/
            docker-image: {in-tree: system-symbols-win}
            max-run-time: 3600
        treeherder:
            symbol: system-symbols-win
