[package]
name = "xpcom_macros"
version = "0.1.0"
authors = ["Michael Layzell <michael@thelayzells.com>"]

[lib]
proc-macro = true

[dependencies]
syn = "1"
quote = "1"
proc-macro2 = "1"
lazy_static = "1.0"
