[package]

name = "rust_url_capi"
version = "0.0.1"
authors = ["Valentin Gosu <valentin.gosu@gmail.com>"]

[profile.dev]
opt-level = 3
debug = true
rpath = true
lto = true

[lib]
name = "rust_url_capi"


[dependencies]
libc = "0.2.0"
url = "1.2.1"
