#filter emptyLines

#define MOZ_LANGPACK_CREATOR mozilla.org

# If non-English locales wish to credit multiple contributors, uncomment this

# variable definition and use the format specified.

#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Softaragones</em:contributor><em:contributor>Juan Pablo Martínez Cortés</em:contributor><em:contributor>Chesús Daniel Trigo</em:contributor><em:contributor>Daniel Martínez Cucalón</em:contributor>

#unfilter emptyLines
