#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in some URLs will be replaced with
# your locale code, and link to your translated pages as soon as they're live.

#define bookmarks_title Záložky
#define bookmarks_heading Záložky

#define personal_toolbarfolder Priečinok Osobného panela

#define seamonkey_and_mozilla SeaMonkey a Mozilla

# LOCALIZATION NOTE (seamonkey):
# link title for http://www.seamonkey-project.org/ (in the personal toolbar)
#define seamonkey SeaMonkey

# LOCALIZATION NOTE (seamonkey_long):
# link title for http://www.seamonkey-project.org/ (in normal bookmarks)
#define seamonkey_long Projekt SeaMonkey

# LOCALIZATION NOTE (mozilla_org):
# link title for http://www.mozilla.org/ (in the personal toolbar)
#define mozilla_org mozilla.org

# LOCALIZATION NOTE (mozilla_org_long):
# link title for http://www.mozilla.org/ (in normal bookmarks)
#define mozilla_org_long Organizácia Mozilla

# LOCALIZATION NOTE (mozilla_projects):
# link title for http://www.mozilla.org/projects/
#define mozilla_projects Projekty Mozilla

# LOCALIZATION NOTE (mozilla_about):
# link title for http://www.mozilla.org/about/
#define mozilla_about O Mozille

#define extend_seamonkey Prispôsobenie SeaMonkey

# LOCALIZATION NOTE (seamonkey_addons):
# link title for https://addons.mozilla.org/en-US/seamonkey/
#define seamonkey_addons Doplnky pre SeaMonkey

# LOCALIZATION NOTE (seamonkey_themes):
# link title for https://addons.mozilla.org/en-US/seamonkey/themes
#define seamonkey_themes Témy pre SeaMonkey

# LOCALIZATION NOTE (seamonkey_dictionaries):
# link title for https://addons.mozilla.org/en-US/seamonkey/dictionaries
#define seamonkey_dictionaries Slovníky na kontrolu pravopisu

# LOCALIZATION NOTE (seamonkey_plugins):
# link title for https://addons.mozilla.org/en-US/seamonkey/plugins
#define seamonkey_plugins Zásuvné moduly pre SeaMonkey

# LOCALIZATION NOTE (mozdev):
# link title for http://www.mozdev.org/
#define mozdev mozdev.org

# LOCALIZATION NOTE (mozdev_seamonkey):
# link title for http://www.mozdev.org/projects/applications/SeaMonkey.html
#define mozdev_seamonkey Rozšírenia pre SeaMonkey z mozdev.org

#define community_support Komunita a podpora

# LOCALIZATION NOTE (seamonkey_community):
# link title for http://www.seamonkey-project.org/community
#define seamonkey_community Komunita SeaMonkey

# LOCALIZATION NOTE (mozillazine):
# link title for http://www.mozillazine.org/
#define mozillazine mozillaZine

# LOCALIZATION NOTE (seamonkey_support):
# link title for the mozillaZine SeaMonkey Support forum
#define seamonkey_support Fórum podpory pre SeaMonkey (mozillaZine)

# LOCALIZATION NOTE (seamonkey_l10n):
# insert full bookmark line for localized SeaMonkey page (personal toolbar)
# e.g. #define seamonkey_l10n <DT><A HREF="http://www.seamonkey.tlh/">SeaMonkey tlhIngan</a>
#define seamonkey_l10n <DT><A HREF="http://www.mozilla.sk/seamonkey/">SeaMonkey v slovenčine</a>

# LOCALIZATION NOTE (seamonkey_l10n_long):
# insert full bookmark line for localized SeaMonkey page (normal bookmark)
# e.g. #define seamonkey_l10n_long <DT><A HREF="http://www.seamonkey.tld/">tlhIngan Hol SeaMonkey</a>
#define seamonkey_l10n_long <DT><A HREF="http://www.mozilla.sk/seamonkey/">SeaMonkey v slovenčine</a>

#unfilter emptyLines
