# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with

# your locale code, and link to your translated pages as soon as they're

# live.


#define bookmarks_title ಪುಟಗುರುತುಗಳು


#define bookmarks_heading ಪುಟಗುರುತುಗಳು


#define bookmarks_toolbarfolder ಪುಟಗುರುತುಗಳ ಉಪಕರಣಪಟ್ಟಿ ಕಡತಕೋಶ


#define bookmarks_toolbarfolder_description ಪುಟಗುರುತಿನ ಉಪಕರಣಪಟ್ಟಿಯಲ್ಲಿ ತೋರಿಸಲು ಪುಟಗುರುತುಗಳನ್ನು ಈ ಕಡತಕೋಶಕ್ಕೆ ಸೇರಿಸಿ


# LOCALIZATION NOTE (getting_started):


# link title for https://www.mozilla.org/en-US/firefox/central/


#define getting_started ಆರಂಭಿಸುವಿಕೆ


# LOCALIZATION NOTE (firefox_heading):


# Firefox links folder name


#define firefox_heading ಮೋಜಿಲ್ಲಾ ಫೈರ್ಫಾಕ್ಸ್


# LOCALIZATION NOTE (firefox_help):


# link title for https://www.mozilla.org/en-US/firefox/help/


#define firefox_help ನೆರವು ಮತ್ತು ಟ್ಯುಟೋರಿಯಲ್‌ಗಳು


# LOCALIZATION NOTE (firefox_customize):


# link title for https://www.mozilla.org/en-US/firefox/customize/


#define firefox_customize ಫೈರ್ಫಾಕ್ಸನ್ನು ಅಗತ್ಯಾನುಗುಣಗೊಳಿಸಿ


# LOCALIZATION NOTE (firefox_community):


# link title for https://www.mozilla.org/en-US/contribute/


#define firefox_community ಸೇರಿಕೊಳ್ಳಿ


# LOCALIZATION NOTE (firefox_about):


# link title for https://www.mozilla.org/en-US/about/


#define firefox_about About Us


# LOCALIZATION NOTE (nightly_heading):


# Firefox Nightly links folder name


#define nightly_heading Firefox Nightly Resources


# LOCALIZATION NOTE (nightly_blog):


# Nightly builds only, link title for https://blog.nightly.mozilla.org/


#define nightly_blog Firefox Nightly blog


# LOCALIZATION NOTE (bugzilla):


# Nightly builds only, link title for https://bugzilla.mozilla.org/


#define bugzilla Mozilla Bug Tracker


# LOCALIZATION NOTE (mdn):


# Nightly builds only, link title for https://developer.mozilla.org/


#define mdn Mozilla Developer Network


# LOCALIZATION NOTE (nightly_tester_tools):


# Nightly builds only, link title for https://addons.mozilla.org/en-US/firefox/addon/nightly-tester-tools/


#define nightly_tester_tools Nightly Tester Tools


# LOCALIZATION NOTE (crashes):


# Nightly builds only, link title for about:crashes


#define crashes All your crashes


# LOCALIZATION NOTE (irc):


# Nightly builds only, link title for ircs://irc.mozilla.org/nightly


#define irc Discuss Nightly on IRC


# LOCALIZATION NOTE (planet):


# Nightly builds only, link title for https://planet.mozilla.org/


#define planet Planet Mozilla


#unfilter emptyLines
