# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with
# your locale code, and link to your translated pages as soon as they're
# live.

#define bookmarks_title ਬੁੱਕਮਾਰਕ
#define bookmarks_heading ਬੁੱਕਮਾਰਕ

#define bookmarks_toolbarfolder ਬੁੱਕਮਾਰਕ ਟੂਲ-ਪੱਟੀ ਫੋਲਡਰ
#define bookmarks_toolbarfolder_description ਬੁੱਕਮਾਰਕ ਟੂਲ-ਪੱਟੀ ਵਿੱਚ ਦਿਖਾਉਣ ਲਈ ਬੁੱਕਮਾਰਕਾਂ ਨੂੰ ਇਸ ਫੋਲਡਰ ਵਿੱਚ ਜੋੜੋ

# LOCALIZATION NOTE (getting_started):
# link title for https://www.mozilla.org/en-US/firefox/central/
#define getting_started ਸ਼ੁਰੂ ਕਰੋ

# LOCALIZATION NOTE (firefox_heading):
# Firefox links folder name
#define firefox_heading Mozilla Firefox

# LOCALIZATION NOTE (firefox_help):
# link title for https://www.mozilla.org/en-US/firefox/help/
#define firefox_help ਮਦਦ ਅਤੇ ਸਿੱਖਣ ਲਈ ਜਾਣਕਾਰੀ

# LOCALIZATION NOTE (firefox_customize):
# link title for https://www.mozilla.org/en-US/firefox/customize/
#define firefox_customize ਫਾਇਰਫਾਕਸ ਨੂੰ ਮਨ ਮੁਤਾਬਕ ਬਣਾਓ

# LOCALIZATION NOTE (firefox_community):
# link title for https://www.mozilla.org/en-US/contribute/
#define firefox_community ਹਿੱਸਾ ਬਣੋ

# LOCALIZATION NOTE (firefox_about):
# link title for https://www.mozilla.org/en-US/about/
#define firefox_about ਸਾਡੇ ਬਾਰੇ

# LOCALIZATION NOTE (nightly_heading):
# Firefox Nightly links folder name
#define nightly_heading ਫਾਇਰਫਾਕਸ ਨਾਈਟਲੀ ਸਰੋਤ

# LOCALIZATION NOTE (nightly_blog):
# Nightly builds only, link title for https://blog.nightly.mozilla.org/
#define nightly_blog ਫਾਇਰਫਾਕਸ ਨਾਈਟਲੀ ਬਲਾਗ

# LOCALIZATION NOTE (bugzilla):
# Nightly builds only, link title for https://bugzilla.mozilla.org/
#define bugzilla ਮੌਜ਼ੀਲਾ ਬੱਗ ਟਰੈਕਰ

# LOCALIZATION NOTE (mdn):
# Nightly builds only, link title for https://developer.mozilla.org/
#define mdn Mozilla Developer Network

# LOCALIZATION NOTE (nightly_tester_tools):
# Nightly builds only, link title for https://addons.mozilla.org/en-US/firefox/addon/nightly-tester-tools/
#define nightly_tester_tools Nightly Tester Tools

# LOCALIZATION NOTE (crashes):
# Nightly builds only, link title for about:crashes
#define crashes ਤੁਹਾਡੇ ਸਾਰੇ ਕਰੈਸ਼

# LOCALIZATION NOTE (irc):
# Nightly builds only, link title for ircs://irc.mozilla.org/nightly
#define irc IRC ਉੱਤੇ ਨਾਈਟਲੀ ਬਾਰੇ ਵਿਚਾਰ ਕਰੋ

# LOCALIZATION NOTE (planet):
# Nightly builds only, link title for https://planet.mozilla.org/
#define planet Planet Mozilla

#unfilter emptyLines
