#filter emptyLines

#define MOZ_LANGPACK_CREATOR Waterfox.cz

# If non-English locales wish to credit multiple contributors, uncomment this
# variable definition and use the format specified.

#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Pavel Cvrček</em:contributor> <em:contributor>Pavel Franc</em:contributor> <em:contributor>Michal Stanke</em:contributor> <em:contributor>Michal Vašíček</em:contributor> <em:contributor>Tomáš Zelina</em:contributor>

#unfilter emptyLines
