# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

rights-title = A-zivout ho kwirioù
rights-intro = { -brand-full-name } zo ur meziant digoust ha digor e darzh, savet gant miliadoù a dud dre ar bed a-bezh. Gwell eo deoc'h gouzout un toulladig traoù :
rights-intro-point-1 = Reiñ a reer tro deoc'h d'ober gant { -brand-short-name } dindan an termenoù eus <a data-l10n-name="mozilla-public-license-link">Lañvaz Foran Mozilla</a>. An dra-mañ a dalv e c'hallit arverañ, eilañ ha skignañ { -brand-short-name } da dud all. Aotreet oc'h da zaskemmañ boneg tarzh { -brand-short-name } diouzh hoc'h ezhommoù. Aotreet oc'h, gant Lañvaz Foran Mozilla, da zasparzhañ ho handelvoù daskemmet.
rights-intro-point-2 = N'eus tamm gwir ebet grataet deoc'h e-keñver gwirioù ar merkoù marilhet pe al lañvazioù eus Diazezadenn Mozilla pe un trede stal, en o zouez (hep bevenn ebet) anv Firefox hag e siell. Titouroù ouzhpenn diwar-benn ar merkoù marilhet e vez kavet <a data-l10n-name="mozilla-trademarks-link">amañ</a>.
rights-intro-point-3 = Molladoù zo e { -brand-short-name }, evel Danevell ar Sac'hadennoù, a ro tro deoc'h da reiñ ho meno da { -vendor-short-name }. Mar dibabot reiñ ho meno e roiot hoc'h aotre da  { -vendor-short-name } da arverañ ar meno a-benn gwellaat e genderc'hadoù, da embann ar meno war e lec'hienn internet ha da zasparzhañ ar meno.
rights-intro-point-4 = Penaos ez arveront ho titouroù personel hag ar meno kaset da { -vendor-short-name } dre { -brand-short-name } zo deskrivet war <a data-l10n-name="mozilla-privacy-policy-link">Reolennoù { -brand-short-name } a-fet buhez prevez</a>.
rights-intro-point-4-unbranded = An holl reolennoù arloadus a-zivout ar vuhez prevez a rankfe bezañ kavet amañ.
rights-intro-point-5 = Keweriusterioù zo eus { -brand-short-name } a ra gant gwazerezhioù kelaouiñ diazezet war ar genrouedad, koulskoude n'omp ket evit gwarantiñ ez int spis penn-da-benn ha hep fazioù. Titouroù ouzhpenn (en o zouez penaos diweredekaat ar c'heweriusterioù a ra gant ar gwazerezhioù-mañ) a vez kavet e <a data-l10n-name="mozilla-service-terms-link">termenoù ar gwazerezh</a>.
rights-intro-point-5-unbranded = Mar bez enkorfet gwazerezhioù web er c'henderc'had-mañ e tlefe bezañ ereet an holl dermenoù arloadus e-keñver arver ar gwazerezh(ioù) ouzh <a data-l10n-name="mozilla-website-services-link">Gwazerezhioù al lec'hiennoù web</a> ar gevrenn.
rights-intro-point-6 = Evit gallout lenn mentrezhoù endalc'hadoù video 'zo e pellgarg { -brand-short-name } molladoù dienrinegañ adalek perzhidi trede.
rights-webservices-header = Gwazerezhioù kelaouiñ diazezet war ar genrouedad { -brand-full-name }
rights-webservices = { -brand-full-name } a ra gant gwazerezhioù diazezet war ar genrouedad ("Gwazerezhioù") evit pourchas un darn eus ar c'heweriusterioù pourchaset evit hoc'h arver gant an handelv daouredel-mañ eus { -brand-short-name } dindan an termenoù deskrivet amañ dindan. Ma ne fell ket deoc'h ober gant unan pe veur a wazerezh pe ma ne fell ket deoc'h degemer an termenoù e c'hallit diweredekaat ar c'heweriuster pe ar gwazerezh(ioù). Kavet e vez an ditouroù a-benn diweredekaat ur c'heweriuster pe ur gwazerezh dibar <a data-l10n-name="mozilla-disable-service-link">amañ</a>. Ar c'heweriusterioù pe ar gwazerezhioù all a c'hell bezañ diweredekaet e-barzh gwellvezioù an arload.
rights-safebrowsing = <strong>Merdeiñ Diarvar : </strong>Diweredekaat mollad ar Merdeiñ diarvar n'eo ket erbedet rak da lec'hiennoù arvarus ez eot marteze. Mar fell deoc'h diweredekaat ar mollad-mañ penn-da-benn, grit evel-henn :
rights-safebrowsing-term-1 = Digeriñ gwellvezioù an arload
rights-safebrowsing-term-2 = Diuzit an diuzad a-fet diogelroez
rights-safebrowsing-term-3 = Digevaskit an dibarzh evit "{ enableSafeBrowsing-label }"
enableSafeBrowsing-label = Stankañ endalc'hadoù arvarus pe touellus
rights-safebrowsing-term-4 = Diweredekaet eo ar merdeiñ diarvar bremañ
rights-locationawarebrowsing = <strong>Merdeiñ gant kelaouiñ ho lec'hiadur : </strong>a vez asantet a-ratozh bepred. Ne vo ket kaset titouroù a-zivout ho lec'hiadur hep hoc'h aotre. Mar fell deoc'h diweredekaat ar mollad-mañ da vat, grit evel ma 'z eo displeget :
rights-locationawarebrowsing-term-1 = War barrenn an URL, biziatait <code>a-zivout : kefluniañ</code>
rights-locationawarebrowsing-term-2 = Biziata geo.enabled
rights-locationawarebrowsing-term-3 = Daouglikañ war gwellvez geo.enabled
rights-locationawarebrowsing-term-4 = Diweredekaet eo ar merdeiñ gant kelaouiñ ho lec'hiadur
rights-webservices-unbranded = Un alberz war gwazerezhioù al lec'hiennoù web enkorfet er c'henderc'had, gant an titouroù evit gouzout penaos o tiweredekaat, mar bez tro, a zlefe bezañ kavet amañ.
rights-webservices-term-unbranded = An holl dermenoù arloadus e-keñver ar gwazerezh evit ar c'henderc'had-mañ a rankfe bezañ kavet amañ.
rights-webservices-term-1 = { -vendor-short-name } hag an dud o deus kemeret perzh, lañvazourion ha kevelerion a labour a-benn pourchas ar gwazerezhioù spisañ ha hizivaet. Koulskoude n'omp ket evit gwarantiñ e vo an titouroù hep fazi ha klok. Da skouer, marteze ne vo ket hennadet lec'hiennoù arvarus gant Gwazerezh ar merdeiñ diarvar ha lakaet lec'hiennoù diarvar evel re arvarus dre fazi. Gwazerezh da gelaouiñ ho lec'hiadur a gas lec'hiadurioù priziet well-wazh hepken ha n'omp ket evit gwarantiñ ez eo spis al lec'hiadurioù pourchaset ganeomp pe gant hor pourchaser gwazerezhioù.
rights-webservices-term-2 = { -vendor-short-name } a c'hell troc'hañ pe gemmañ ar Gwazerezhioù evel ma plij dezhañ.
rights-webservices-term-3 = Degemeret oc'h mat mar fell deoc'h ober gant ar gwazerezhioù-mañ gant an handelvoù eus { -brand-short-name } o tont gantañ, ha { -vendor-short-name } a ro deoc'h e aotre d'ober gantañ. { -vendor-short-name } hag ar re a zo gwirioù al lañvaz ganto a vir an holl wirioù all er Gwazerezh. N'eo ket graet an termenoù-mañ a-benn lakaat bevennoù d'ar gwirioù gwarantet dindan lañvazioù digor o zarzh a vez arloet da { -brand-short-name } ha d'an handelvoù eus ar bonegoù tarzh eus { -brand-short-name } o klotañ ganti.
rights-webservices-term-4 = <strong>"Evel m'emaint" ez eo pourchaset ar gwazerezhioù. { -vendor-short-name }, e berzhidi, e lañvazourion hag e zasparzhourion a zinac'h an holl watantoù, pe gantrat pe emplegat, en o zouez, hep bezañ bevennet ganto avat, gwarantoù e vez kenwerzhadus ar gwazerezhioù hag e klotont gant hoc'h ezhommoù hiniennel. Ganeoc'h emañ an holl arvarioù e-keñver diuzañ ar gwazerezhioù evit hoc'h ezhommoù hag e-keñver perzhded ha digonusted ar gwazerezhioù. Barnadurezhioù zo ne aotreont ket ma vefe ezlakaet pe bevennet gwarantoù emplegat, neuze marteze ne vo ket arloet an diferadenn ezlakaat-mañ ouzhoc'h.</strong>
rights-webservices-term-5 = <strong>Anez ma vefe azgoulennet gant al lezenn, ne gouezho ket { -vendor-short-name }, e berzhidi, e lañvazourion hag e zasparzhourion dindan gaouadoù ameeun, arbennik, adgaouadoù, gaouadoù ha kampioù kastizañ, pe c'haouadoù skoueriek en abeg d'un arver eus { -brand-short-name } pe en abeg da forzh peseurt arver eus { -brand-short-name } hag ar gwazerezhioù. An atebegezh stroll, dindan an termenoù-mañ, ned ay ket dreist 500 $ (pemp kant dollar). Barnadurezhioù zo n'aotreont ket ma vefe ezlakaet pe bevennet gwarantoù emplegat, neuze marteze ne vo ket arloet an diferadenn ezlakaat-mañ ouzhoc'h.</strong>
rights-webservices-term-6 = { -vendor-short-name } en deus ar gwir da hizivaat an termenoù mar bez ezhomm ur wech an amzer. An termenoù-mañ n'hallint ket bezañ daskemmet pe zilezet hep aotre dre skrid { -vendor-short-name }.
rights-webservices-term-7 = Renet eo an termenoù-mañ gant lezennoù Stad Kalifornia, Stadoù-Unanet, ar c'henniñvoù e-keñver an divizoù lezennek lakaet er-maez. Mard ay ul lodenn eus an termenoù da zidalvoudek pe ziarloadus e chomo kreñv hag efedus al lodennoù all. Mar degouezhfe ur c'henniñv etre un handelv eus an termenoù-mañ bet troet hag an hini e saozneg ez ay ar reol gant an handelv e saozneg.
