#filter emptyLines

#define MOZ_LANGPACK_CREATOR mozilla.org

# If non-English locales wish to credit multiple contributors, uncomment this
# variable definition and use the format specified.
#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Jeferson Hultmann</em:contributor> <em:contributor>Fernando Pereira Silveira</em:contributor> <em:contributor>Marco Aurélio Krause</em:contributor> <em:contributor>Maykon Chagas</em:contributor>

#unfilter emptyLines
