# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

rights-title = Mu do chòraichean
rights-intro = Tha { -brand-full-name } 'na bhathar-bog a tha saor an-asgaidh agus 'na chòd fosgailte a tha 'ga leasachadh le coimhearsnachd mhòr a dhaoine o cheithir ceàrnan an t-saoghail. Tha rud na dhà ann a tha cudromach:
rights-intro-point-1 = Tha { -brand-short-name } 'ga sholar dhut fo theirmichean <a data-l10n-name="mozilla-public-license-link">Ceadachas Poblach Mozilla</a>. 'S ciall dha seo gu bheil cead agad { -brand-short-name } a chleachdadh, lethbhreacan a dhèanamh dheth agus a thoirt do dhaoine eile.  Tha fàilte romhad cuideachd an còd tùsail aig { -brand-short-name } atharrachadh ach an obraich e nas fhearr dhut. Tha Ceadachas Poblach Mozilla a' toirt cead dhut cuideachd na tionndaidhean a dh'atharraich thu a sgaoileadh.
rights-intro-point-2 = Chan eil sinn a' toirt seachad còir air comharran-malairt no ceadachas air comharran-malairt aig Fonndas Mozilla no pàrtaidh sam bith, a' gabhail a-steach (gun chuingeachadh) ainm no suaicheantas Firefox. Gheibh thu fiosrachadh sam bith mu na comharran-malairt <a data-l10n-name="mozilla-trademarks-link">an-seo</a>.
rights-intro-point-3 = 'S urrainn dhut fiosrachadh a thilleadh dha { -vendor-short-name } le cuid dhe na feartan ann am { -brand-short-name }, can aithrisiche nan tuislidhean. Ma bheir thu fiosrachadh mar sinn dhuinn, bidh thu a' toirt cead dha { -vendor-short-name } am fiosrachadh seo a chleachdadh gus am bathar aca a leasachadh, cead am fiosrachadh seo fhoillseachadh no sgaoileadh air na làraichean-lìn.
rights-intro-point-4 = Tha sinn a' mìneachadh mar a chleachdas sinn am fiosrachadh pearsanta 's na beachdan a bheir thu dha { -vendor-short-name } slighe { -brand-short-name } ann am <a data-l10n-name="mozilla-privacy-policy-link">poileasaidh prìobhaideachd { -brand-short-name }</a>.
rights-intro-point-4-unbranded = Chì thu poileasaidhean prìobhaideachd sam bith a tha iomchaidh dhan bhathar seo an-seo.
rights-intro-point-5 = Tha cuid dhe na feartan aig { -brand-short-name } a' cleachdadh seirbheisean fiosrachaidh a tha stèidhichte air an lìon. Chan urrainn dhuinn làn-bharantas a thoirt gu bheil iad gu tur ceart. Gheibh thu barrachd fiosrachaidh, a' gabhail a-steach fiosrachadh a dh'innseas dhut mar a chuireas tu na seirbheisean seo à comas ann an <a data-l10n-name="mozilla-service-terms-link">teirmichean na seirbheise</a>.
rights-intro-point-5-unbranded = If this product incorporates web services, any applicable service terms for the service(s) should be linked to the <a data-l10n-name="mozilla-website-services-link">Web Site Services</a> section.
rights-intro-point-6 = Airson ’s gun urrainn dha cuid a shusbaint video a chluich, luchdaichidh { -brand-short-name } a-nuas cuid a mhòidealan dì-chrioptachaidh o threas-phàrtaidhean.
rights-webservices-header = { -brand-full-name } Web-Based Information Services
rights-webservices = { -brand-full-name } uses web-based information services ("Services") to provide some of the features provided for your use with this binary version of { -brand-short-name } under the terms described below. If you do not want to use one or more of the Services or the terms below are unacceptable, you may disable the feature or Service(s). Instructions on how to disable a particular feature or Service may be found <a data-l10n-name="mozilla-disable-service-link">here</a>. 'S urrainn dhut feartan is seirbheisean eile a chur à comas ann an roghainnean na h-aplacaid.
rights-safebrowsing = <strong>BrabhsadhTèarainte: </strong>Cha mholar dhut am brabhsadh tèarainte a chur à comas oir faodaidh gun tadhal thu air làraichean mì-thèarainte mar sin.  Ma tha thu airson am feart seo a chur dheth gu tur, dèan na leanas:
rights-safebrowsing-term-1 = Fosgail roghainnean na h-aplacaid
rights-safebrowsing-term-2 = Tagh roghainn na tèarainteachd
rights-safebrowsing-term-3 = Thoir air falbh a’ chromag o “{ enableSafeBrowsing-label }”
enableSafeBrowsing-label = Bac susbaint chunnartach is susbaint foill
rights-safebrowsing-term-4 = Tha am brabhsadh tèarainte dheth a-nis
rights-locationawarebrowsing = <strong>Brabhsadh a mhothaiches dha d' àite: </strong>seo rud a dh'fheumas tu a chur air an-còmhnaidh.  Cha dèid fiosrachadh mu d' àite a chur a-null gun do chead idir.  Ma tha thu airson am feart seo a chur dheth gu tur, dèan nan leanas:
rights-locationawarebrowsing-term-1 = Cuir na leanas sa bhàr URL <code>about:config</code>
rights-locationawarebrowsing-term-2 = Cuir a-steach geo.enabled
rights-locationawarebrowsing-term-3 = Dèan briogadh dùbailte air an roghainn geo.enabled
rights-locationawarebrowsing-term-4 = Tha brabhsadh a mhothaicheas dha d' àite dheth a-nis
rights-webservices-unbranded = An overview of the web site services the product incorporates, along with instructions on how to disable them, if applicable, should be included here.
rights-webservices-term-unbranded = Any applicable service terms for this product should be listed here.
rights-webservices-term-1 = { -vendor-short-name } and its contributors, licensors and partners work to provide the most accurate and up-to-date Services.  However, we cannot guarantee that this information is comprehensive and error-free.  For example, the Safe Browsing Service may not identify some risky sites and may identify some safe sites in error and the Location Aware Service all locations returned by our service providers are estimates only and neither we nor our service providers guarantee the accuracy of the locations provided.
rights-webservices-term-2 = { -vendor-short-name } may discontinue or change the Services at its discretion.
rights-webservices-term-3 = You are welcome to use these Services with the accompanying version of { -brand-short-name }, and { -vendor-short-name } grants you its rights to do so.  { -vendor-short-name } and its licensors reserve all other rights in the Services.  These terms are not intended to limit any rights granted under open source licenses applicable to { -brand-short-name } and to corresponding source code versions of { -brand-short-name }.
rights-webservices-term-4 = <strong>The Services are provided "as-is."  { -vendor-short-name }, its contributors, licensors, and distributors, disclaim all warranties, whether express or implied, including without limitation, warranties that the Services are merchantable and fit for your particular purposes.  You bear the entire risk as to selecting the Services for your purposes and as to the quality and performance of the Services. Some jurisdictions do not allow the exclusion or limitation of implied warranties, so this disclaimer may not apply to you.</strong>
rights-webservices-term-5 = <strong>Except as required by law, { -vendor-short-name }, its contributors, licensors, and distributors will not be liable for any indirect, special, incidental, consequential, punitive, or exemplary damages arising out of or in any way relating to the use of { -brand-short-name } and the Services.  The collective liability under these terms will not exceed $500 (five hundred dollars). Some jurisdictions do not allow the exclusion or limitation of certain damages, so this exclusion and limitation may not apply to you.</strong>
rights-webservices-term-6 = { -vendor-short-name } may update these terms as necessary from time to time. These terms may not be modified or canceled without { -vendor-short-name }'s written agreement.
rights-webservices-term-7 = These terms are governed by the laws of the state of California, U.S.A., excluding its conflict of law provisions. If any portion of these terms is held to be invalid or unenforceable, the remaining portions will remain in full force and effect. In the event of a conflict between a translated version of these terms and the English language version, the English language version shall control.
