# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with
# your locale code, and link to your translated pages as soon as they're
# live.

#define bookmarks_title বুকমার্ক
#define bookmarks_heading বুকমার্ক

#define bookmarks_toolbarfolder বুকমার্ক টুলবারের ফোল্ডার
#define bookmarks_toolbarfolder_description বুকমার্ক টুলবারে প্রদর্শনের জন্য এই ফোল্ডারে বুকমার্ক যোগ করুন

# LOCALIZATION NOTE (getting_started):
# link title for https://www.mozilla.org/en-US/firefox/central/
#define getting_started আরম্ভ হতে যাচ্ছে

# LOCALIZATION NOTE (firefox_heading):
# Firefox links folder name
#define firefox_heading Mozilla Firefox

# LOCALIZATION NOTE (firefox_help):
# link title for https://www.mozilla.org/en-US/firefox/help/
#define firefox_help সহায়তা ও টিউটোরিয়াল

# LOCALIZATION NOTE (firefox_customize):
# link title for https://www.mozilla.org/en-US/firefox/customize/
#define firefox_customize Firefox কাস্টোমাইজ

# LOCALIZATION NOTE (firefox_community):
# link title for https://www.mozilla.org/en-US/contribute/
#define firefox_community সম্পৃক্ত হোন

# LOCALIZATION NOTE (firefox_about):
# link title for https://www.mozilla.org/en-US/about/
#define firefox_about আমাদের পরিচিতি

# LOCALIZATION NOTE (nightly_heading):
# Firefox Nightly links folder name
#define nightly_heading Firefox Nightly রিসোর্স

# LOCALIZATION NOTE (nightly_blog):
# Nightly builds only, link title for https://blog.nightly.mozilla.org/
#define nightly_blog Firefox Nightly ব্লগ

# LOCALIZATION NOTE (bugzilla):
# Nightly builds only, link title for https://bugzilla.mozilla.org/
#define bugzilla Mozilla বাগ ট্র্যাকার

# LOCALIZATION NOTE (mdn):
# Nightly builds only, link title for https://developer.mozilla.org/
#define mdn Mozilla Developer Network

# LOCALIZATION NOTE (nightly_tester_tools):
# Nightly builds only, link title for https://addons.mozilla.org/en-US/firefox/addon/nightly-tester-tools/
#define nightly_tester_tools Nightly পরীক্ষক টুল

# LOCALIZATION NOTE (crashes):
# Nightly builds only, link title for about:crashes
#define crashes অাপনার সব ক্র্যাশ

# LOCALIZATION NOTE (irc):
# Nightly builds only, link title for ircs://irc.mozilla.org/nightly
#define irc IRC তে Nightly নিয়ে আলোচনা

# LOCALIZATION NOTE (planet):
# Nightly builds only, link title for https://planet.mozilla.org/
#define planet Planet Mozilla

#unfilter emptyLines
