# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

rights-title = Arredol d'os suyos dreitos
rights-intro = { -brand-full-name } ye un software gratuito y de codigo ubierto construiu por una comunidat de milars de colaboradors de totz. I hai quantas cosetas que habría de conoixer:
rights-intro-point-1 = { -brand-short-name } ye disponible ta vusté baixo os termins d'a <a data-l10n-name="mozilla-public-license-link">Mozilla Public License (Licencia Publica de Mozilla)</a>. Isto significa que puede fer servir, copiar y distribuir o { -brand-short-name } a atras personas.  Tamién puede modificar o codigo fuent d'o { -brand-short-name } ta adaptar-lo a las suyas necesidatz. A licencia Mozilla Public License (Licencia Publica de Mozilla) le atorga o dreito de distribuir as suyas versions modificadas.
rights-intro-point-2 = No se le atorga garra dreito ni licencia sobre las marcas comercials de Mozilla Foundation u os suyos filials, incluindo sin limitación o nombre y logo de Firefox. Puede trobar-ie información adicional sobre as marcas comercials <a data-l10n-name="mozilla-trademarks-link">aquí</a>.
rights-intro-point-3 = Qualques caracteristicas d'o { -brand-short-name }, como achent de fallos, le dan a opción de proporcionar información a { -vendor-short-name }. En esleir ninviar ixa información, atorga o permiso a { -vendor-short-name } ta usar a mesma ta amillorar os suyos productos, ta publicar ixa información en os suyos puestos web y ta distribuir-la.
rights-intro-point-4 = A traza en que usamos a suya información personal y as opinions ninviadas ta { -vendor-short-name } a traviés de { -brand-short-name } se describe en a <a data-l10n-name="mozilla-privacy-policy-link">Politica de privacidat de { -brand-short-name }</a>.
rights-intro-point-4-unbranded = Qualsiquier politica de privacidat aplicable a iste producto s'ha de listar aquí.
rights-intro-point-5 = Belunas d'as funcionalidatz d'o { -brand-short-name } fan servir servicios d'información web; manimenos, no podemos guarenciar que sigan 100% precisos u sinde errors. Mas detalles, incluindo-ie información de cómo inhabilitar istos servicios, puet trobar-se en os <a data-l10n-name="mozilla-service-terms-link">termins d'o servicio</a>.
rights-intro-point-5-unbranded = Si iste producto incorpora servicios web, totz os termins de servicio aplicables a o(s) servicio(s) habrían d'enlazar-se en a sección <a data-l10n-name="mozilla-website-services-link">de servicios web</a> sección.
rights-intro-point-6 = Ta reproducir bels tipos de contenius de video, { -brand-short-name } descarga bels modulos de descifrau de conteniu de terceros.
rights-webservices-header = Servicios d'información web de { -brand-full-name }
rights-webservices = O { -brand-full-name } emplega servicios d'información web ("servicios" d'agora entabant), ta proporcionar belunas d'as funcionalidatz disponibles t'o suyo emplego con ista versión binaria d'o { -brand-short-name }; como se describe a continuación. Si no en quiere fer servir un (o mas), o bien no considera lurs termins acceptables, puet trigar inhabilitar-los. I ha instruccions de como inhabilitar una funcionalidat u servicio concreto <a data-l10n-name="mozilla-disable-service-link">aquí</a>. A resta de caracteristicas y servicios se pueden desactivar en as preferencias de l'aplicación.
rights-safebrowsing = <strong>Navegación segura: </strong>Desactivar a caracteristica de navegación segura no se recomienda porque puede dar como resultau que visite puestos no seguros.  Si deseya desactivar de tot ista caracteristica, siga os trangos siguients:
rights-safebrowsing-term-1 = Ubra as preferencias de l'aplicación
rights-safebrowsing-term-2 = Seleccione o panel Seguranza
rights-safebrowsing-term-3 = Desmarcar la opción pa "{ enableSafeBrowsing-label }"
enableSafeBrowsing-label = Blocar lo conteniu perigloso y malicioso
rights-safebrowsing-term-4 = A navegación segura ye agora desactivada
rights-locationawarebrowsing = <strong>Navegación basada en a ubicación cheografica: </strong>siempre son a esleción de l'usuario.  Nunca no se ninviará garra información sobre a suya ubicación sin o suyo permiso.  Si deseya desactivar a caracteristica por completo, siga istos trangos:
rights-locationawarebrowsing-term-1 = En a barra d'adrezas, escriba <code>about:config</code>
rights-locationawarebrowsing-term-2 = Escriba-ie geo.enabled
rights-locationawarebrowsing-term-3 = Faiga doble clic en a preferencia geo.enabled
rights-locationawarebrowsing-term-4 = A navegación basada en ubicación cheografica s'ha desactivau
rights-webservices-unbranded = Aquí s'ha d'incluir un resumen d'os servicios web que o producto incorpora, de conchunta con instruccions sobre cómo deshabilitar-los si cal.
rights-webservices-term-unbranded = Qualsiquier termin de servicio ta iste producto ha d'estar listau aquí.
rights-webservices-term-1 = { -vendor-short-name } y os suyos colaboradors, licenciatarios y socios treballan ta furnir os servicios mas precisos y actualizaus.  Manimenos, no podemos guarenciar que ista información sía completa y libre d'errors.  Por eixemplo, o servicio de navegación segura puede no identificar qualques puestos periglosos y puede identificar qualques puestos seguros por error y as adrezas tornadas por os nuestros proveyedors d'o servicio de navegación basada en a ubicación son solament estimacions y ni nusatros ni os nuestros proveyedors guarenciamos a exactitut d'as ubicacions proporcionadas.
rights-webservices-term-2 = { -vendor-short-name } puede deixar d'ufrir u cambiar os servicios en qualsiquier inte.
rights-webservices-term-3 = Puede fer servir istos servicios con a versión correspondient de { -brand-short-name } y { -vendor-short-name } le atorga dreitos ta fer-lo.  { -vendor-short-name } y os suyos licenciatarios se reservan a resta de dreitos d'os servicios. Istos termins no limitan garra dreito atorgau por as licencias de codigo ubierto aplicables a { -brand-short-name } y as versions d'o codigo fuent correspondient de { -brand-short-name }.
rights-webservices-term-4 = <strong>Os servicios se presentan "tal qual son".  { -vendor-short-name }, os suyos colaboradors, licenciadors, y distribuidors negan dar qualsiquier guarancia, ya siga expresa u implicita, incluindo-ie, sin garra mena de limitación, guarancias de que os servicios sigan comercials y que respondan a os suyos propositos particulars.  Vusté asume tot o risgo de trigar os servicios t'os suyos propositos, asinas como lur qualidat y rendimiento. Bellas churisdiccions no permiten a exclusión o limitación d'as guarancias implicitas y, doncas, ista norma talment no le afecte.</strong>
rights-webservices-term-5 = <strong>Fueras d'an que sía requeriu por a lei, { -vendor-short-name }, os suyos colaboradors, licenciatarios y distribuidors no serán responsables de garra danyo indirecto, especial, imprevisto, resultant, punitivo u eixemplar relacionau con l'uso de { -brand-short-name } y os servicios. a responsabilidat colectiva baixo istes termins no podrán exceder os US$500 (cincientos dolars). Qualques churisdiccions no permiten a exclusión u limitación de bells danyos, asinas que ista exclusión y limitación puede no estar aplicable ta vusté.</strong>
rights-webservices-term-6 = { -vendor-short-name } puede actualizar istos termins quan sía necesario, de tiempo en tiempo. Istos termins no pueden estar modificaus u cancelaus sin o consentimiento por escrito de { -vendor-short-name }.
rights-webservices-term-7 = Istos termins son rechius por as leis d'o Estau de California, E.U.A., excluindo-ne os conflictos previstos por a lei. Si qualsiquier parte d'istos termins fuesen consideraus no validos u no aplicables, a resta de partes continarían tenendo a suya fuerza y efecto total. Caso d'haber un conflicto entre una versión traducida d'istes termins y a versión en idioma Anglés, a versión en Anglés será a que prevaldrá.
