[package]
name = "mp4parse"
version = "0.8.0"
authors = [
  "Ralph Giles <giles@mozilla.com>",
  "Matthew Gregan <kinetik@flim.org>",
  "Alfredo Yang <ayang@mozilla.com>",
]

description = "Parser for ISO base media file format (mp4)"
documentation = "https://docs.rs/mp4parse/"
license = "MPL-2.0"
categories = ["multimedia::video"]

repository = "https://github.com/mozilla/mp4parse-rust"

# Avoid complaints about trying to package test files.
exclude = [
  "*.mp4",
]


[dependencies]
byteorder = "1.0.0"
bitreader = { version = "0.3.0" }
num-traits = "0.1.37"
mp4parse_fallible = { path = "../mp4parse_fallible" }

[dev-dependencies]
test-assembler = "0.1.2"

