# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

rights-title = Sobre os seus direitos
rights-intro = O { -brand-full-name } é um software livre e de código aberto, construído por uma comunidade de milhares de pessoas de todo o mundo. Há algumas coisas que deve saber:
rights-intro-point-1 = O { -brand-short-name } é disponibilizado de acordo com os termos da <a data-l10n-name="mozilla-public-license-link">Licença Pública Mozilla</a>. Isso significa que pode usar, copiar e distribuir o { -brand-short-name } para outras pessoas.  Também é bem-vindo para modificar o código-fonte do { -brand-short-name } para atender suas necessidades. A Licença Pública Mozilla também lhe dá o direito de distribuir as suas versões modificadas.
rights-intro-point-2 = Não lhe são concedidos quaisquer direitos sobre marcas comerciais ou licenças das marcas comerciais da Fundação Mozilla nem de terceiros, incluindo, entre outros, o nome Thunderbird e seu logotipo. Informações adicionais sobre marcas comerciais podem ser encontradas <a data-l10n-name="mozilla-trademarks-link">aqui</a>.
rights-intro-point-3 = Algumas funcionalidades do { -brand-short-name }, como o relator de travamentos, dão a você a opção de enviar comentários à { -vendor-short-name }. Ao escolher enviar sua opinião, você dá à { -vendor-short-name } permissão de usá-la para aperfeiçoar seus produtos, publicá-la em seus sites e distribuí-la.
rights-intro-point-4 = A forma como nós usamos seus dados pessoais e informações enviadas à { -vendor-short-name } pelo { -brand-short-name } está descrita na <a data-l10n-name="mozilla-privacy-policy-link">Política de privacidade do { -brand-short-name }</a>.
rights-intro-point-4-unbranded = Quaisquer políticas de privacidade aplicáveis a este produto devem ser listadas aqui.
rights-intro-point-5 = Algumas funcionalidades do { -brand-short-name } usam serviços de informação baseados na web. No entanto, não podemos garantir que sejam 100% precisos ou livres de erro. Mais informações, incluindo sobre como desativar os recursos que usam esses serviços, podem ser encontradas nos <a data-l10n-name="mozilla-service-terms-link">termos do serviço</a>.
rights-intro-point-5-unbranded = Se este produto incorporar serviços web, quaisquer termos de serviço aplicáveis aos serviços devem possuir um link para a seção <a data-l10n-name="mozilla-website-services-link">Serviços web</a>.
rights-intro-point-6 = Para poder reproduzir alguns tipos de vídeo, o { -brand-short-name } baixa alguns módulos de terceiros para decodificar o conteúdo.
rights-webservices-header = Serviços de informação do { -brand-full-name } baseados na web
rights-webservices = O { -brand-full-name } usa serviços de informações baseados na web ("Serviços") para fornecer algumas funcionalidades para seu uso com esta versão binária do { -brand-short-name } de acordo com os termos descritos abaixo. Se não quiser usar um ou mais Serviços ou não aceitar os termos a seguir, você pode desativar funcionalidades e Serviços. Instruções sobre como desativar uma funcionalidade ou Serviço em particular podem ser encontradas <a data-l10n-name="mozilla-disable-service-link">aqui</a>. Outras funcionalidades e Serviços podem ser desativados nas preferências da aplicação.
rights-locationawarebrowsing = <strong>Navegação sensível à localização: </strong>é sempre opcional. Nenhuma informação de localização é enviada sem a sua permissão. Se quiser desativar totalmente este recurso, siga essas etapas:
rights-locationawarebrowsing-term-1 = Na barra de endereço, digite <code>about:config</code>
rights-locationawarebrowsing-term-2 = Digite geo.enabled
rights-locationawarebrowsing-term-3 = Dê um duplo clique na preferência geo.enabled
rights-locationawarebrowsing-term-4 = O serviço de Navegação sensível à localização agora está desativado
rights-webservices-unbranded = Uma visão geral dos serviços web que o produto inclui, assim como instruções de como os desativar (se aplicáveis), deve ser colocada aqui.
rights-webservices-term-unbranded = Quaisquer termos de serviço aplicáveis a este produto devem ser listados aqui.
rights-webservices-term-1 = A { -vendor-short-name } e seus colaboradores, licenciadores e parceiros trabalham para fornecer serviços o mais precisos e atualizados possível. Entretanto, não podemos garantir a abrangência e a ausência de erros dessas informações. Por exemplo, o serviço de navegação segura pode não identificar alguns sites arriscados e alguns sites seguros podem ser identificados erroneamente. No serviço de navegação sensível à localização, todas as localizações fornecidas por nossos provedores de serviço são somente estimativas e nem nós nem nossos provedores de serviço podemos garantir a precisão das localizações fornecidas.
rights-webservices-term-2 = A { -vendor-short-name } pode descontinuar ou alterar os serviços a critério dela.
rights-webservices-term-3 = Você é bem-vindo para usar esses Serviços com a versão associada do { -brand-short-name } e a { -vendor-short-name } concede a você os direitos para fazê-lo. A { -vendor-short-name } e seus licenciadores reservam todos os outros direitos sobre os Serviços. Estes termos não têm intenção de limitar nenhum dos direitos concedidos sob as licenças de código aberto aplicáveis ao { -brand-short-name } e às correspondentes versões do código-fonte do { -brand-short-name }.
rights-webservices-term-4 = <strong>Os Serviços são fornecidos “tais como estão”. A { -vendor-short-name }, seus colaboradores, licenciadores e distribuidores se isentam de todas as garantias, sejam expressas ou implícitas, incluindo, entre outras, garantias de que os Serviços sejam comercializáveis e apropriados para os seus fins particulares. Você tolera todo o risco quanto a seleção dos Serviços para os seus fins e quanto à qualidade e desempenho dos Serviços. Algumas jurisdições não permitem a exclusão ou limitação de garantias implícitas, de forma que esta isenção pode não se aplicar a você.</strong>
rights-webservices-term-5 = <strong>Exceto quando exigido pela lei, a { -vendor-short-name }, seus colaboradores, licenciadores e distribuidores não serão responsabilizados por quaisquer danos indiretos, especiais, acidentais, consequentes, punitivos ou exemplares decorrentes ou de alguma forma relacionados ao uso do { -brand-short-name } e dos Serviços. A responsabilidade coletiva sob estes termos não excederá $500 (quinhentos dólares). Algumas jurisdições não permitem a exclusão ou limitação de certos danos, de forma que esta limitação e exclusão pode não se aplicar a você.</strong>
rights-webservices-term-6 = A { -vendor-short-name } pode atualizar estes termos ocasionalmente, na medida do necessário. Estes termos não podem ser alterados ou cancelados sem o acordo escrito da { -vendor-short-name }.
rights-webservices-term-7 = Estes termos são regidos pelas leis do estado da Califórnia, E.U.A., excluindo seu conflito de cláusulas legais. Se qualquer parte destes termos for identificado como inválido ou não aplicável, as partes restantes permanecerão em pleno vigor e efeito. Na eventualidade de um conflito entre uma versão traduzida destes termos e versão do idioma inglês, a versão em inglês prevalecerá.
