# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#filter emptyLines

#define MOZ_LANGPACK_CREATOR mozfr.org

# If non-English locales wish to credit multiple contributors, uncomment this
# variable definition and use the format specified.
#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Vincent Béron</em:contributor><em:contributor>Théo Chevalier</em:contributor><em:contributor>Cédric Corazza</em:contributor><em:contributor>Philippe Dessante</em:contributor><em:contributor>Benoît Leseul</em:contributor><em:contributor>Marie Léger-St-Jean</em:contributor><em:contributor>Jean-Bernard Marcon</em:contributor><em:contributor>Jérôme Schell</em:contributor>

#unfilter emptyLines
