#filter emptyLines

#define MOZ_LANGPACK_CREATOR A ChatZilla csapata

#define MOZ_LANGPACK_HOMEPAGE http://chatzilla.hacksrus.com/

# If non-English locales wish to credit multiple contributors, uncomment this
# variable definition and use the format specified.
#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Kelemen Gábor</em:contributor> <em:contributor>Meskó Balázs</em:contributor> <em:contributor>Szalai Kálmán</em:contributor> <em:contributor>Tímár András</em:contributor>

#unfilter emptyLines
