# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# 
# Entities below were automatically added by compare-locales,
#  based on en-US entities.


#define bookmarks_title Bookmarks
#define seamonkey_long The SeaMonkey Project
#define mozillazine mozillaZine
#define mozilla_about About Mozilla
#define seamonkey_l10n 
#define seamonkey_and_mozilla SeaMonkey and Mozilla
#define mozdev_seamonkey SeaMonkey Extensions from mozdev.org
#define mozilla_projects Mozilla Projects
#define seamonkey_themes SeaMonkey Themes
#define seamonkey_addons SeaMonkey Add-ons
#define bookmarks_heading Bookmarks
#define mozdev mozdev.org
#define community_support Community &amp; Support
#define extend_seamonkey Extending SeaMonkey
#define seamonkey_dictionaries Spell Checking Dictionaries
#define seamonkey SeaMonkey
#define seamonkey_plugins Plugins for SeaMonkey
#define seamonkey_support SeaMonkey Support Forum (mozillaZine)
#define personal_toolbarfolder Personal Toolbar Folder
#define seamonkey_l10n_long 
#define mozilla_org_long The Mozilla Organization
#define seamonkey_community SeaMonkey Community
#define mozilla_org mozilla.org
