# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with
# your locale code, and link to your translated pages as soon as they're
# live.

#define bookmarks_title Kirjanmerkit
#define bookmarks_heading Kirjanmerkit

#define bookmarks_toolbarfolder Kirjanmerkkipalkin kirjanmerkit
#define bookmarks_toolbarfolder_description Tässä kansiossa olevat ja tänne lisättävät kirjanmerkit ovat Kirjanmerkkipalkissa

# LOCALIZATION NOTE (getting_started):
# link title for https://www.mozilla.org/en-US/firefox/central/
#define getting_started Aloitussivu

# LOCALIZATION NOTE (firefox_heading):
# Firefox links folder name
#define firefox_heading Mozilla Firefox

# LOCALIZATION NOTE (firefox_help):
# link title for https://www.mozilla.org/en-US/firefox/help/
#define firefox_help Ohje ja oppaat

# LOCALIZATION NOTE (firefox_customize):
# link title for https://www.mozilla.org/en-US/firefox/customize/
#define firefox_customize Muokkaa Firefox-selainta

# LOCALIZATION NOTE (firefox_community):
# link title for https://www.mozilla.org/en-US/contribute/
#define firefox_community Osallistu projektiin

# LOCALIZATION NOTE (firefox_about):
# link title for https://www.mozilla.org/en-US/about/
#define firefox_about Tietoja Mozillasta

# LOCALIZATION NOTE (nightly_heading):
# Firefox Nightly links folder name
#define nightly_heading Firefox Nightly -resurssit

# LOCALIZATION NOTE (nightly_blog):
# Nightly builds only, link title for https://blog.nightly.mozilla.org/
#define nightly_blog Firefox Nightly -blogi

# LOCALIZATION NOTE (bugzilla):
# Nightly builds only, link title for https://bugzilla.mozilla.org/
#define bugzilla Mozillan vianseurantajärjestelmä

# LOCALIZATION NOTE (mdn):
# Nightly builds only, link title for https://developer.mozilla.org/
#define mdn Mozilla Developer Network

# LOCALIZATION NOTE (nightly_tester_tools):
# Nightly builds only, link title for https://addons.mozilla.org/en-US/firefox/addon/nightly-tester-tools/
#define nightly_tester_tools Nightly-testaajan työkalut

# LOCALIZATION NOTE (crashes):
# Nightly builds only, link title for about:crashes
#define crashes Kaikki kaatumisilmoituksesi

# LOCALIZATION NOTE (irc):
# Nightly builds only, link title for ircs://irc.mozilla.org/nightly
#define irc Keskustele Nightlystä IRC:ssä

# LOCALIZATION NOTE (planet):
# Nightly builds only, link title for https://planet.mozilla.org/
#define planet Planet Mozilla

#unfilter emptyLines
