# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
---
loader: taskgraph.loader.transform:loader

transforms:
    - taskgraph.transforms.python_update:transforms
    - taskgraph.transforms.task:transforms


job-defaults:
    name: python_dependency_update
    description: Update requirements.txt
    run-on-projects: []
    treeherder:
        kind: build
        platform: linux64/opt
        tier: 1
    worker-type: b-linux
    worker:
        implementation: docker-worker
        os: linux
        docker-image: {in-tree: python-dependency-update}
        taskcluster-proxy: true
        max-run-time: 2400
        command:
            - /runme.sh
        artifacts:
            - name: 'public/build/requirements.txt.diff'
              path: '/home/worker/artifacts/requirements.txt.diff'
              type: file
    scopes:
        - secrets:get:project/releng/gecko/build/level-{level}/arc-phabricator-token


jobs:
    funsize-update-generator:
        treeherder:
            symbol: pydep(fug)
        worker:
            env:
                REQUIREMENTS_FILE: "taskcluster/docker/funsize-update-generator/requirements.in"
                PYTHON3: "1"
                REVIEWERS: "sfraser, bhearsum"
