# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

rights-title = Mayela namalungelo akho
rights-intro = I-{ -brand-full-name } ikhululekile kwaye ivula isoftwe yoxwebhu, eyenziwe luluntu olungamawaka kwihlabathi jikelele. Kukho izinto ezimbalwa ekumele uzazi:
rights-intro-point-1 = I-{ -brand-short-name } yenziwe yafumaneka kuwe phantsi kwemiqathango <a data-l10n-name="mozilla-public-license-link">Mozilla Public License</a>. Oku kuthetha ukuba ungayisebenzisa, ungayikhuphela kwaye ungayinikezela i-{ -brand-short-name } kwabanye.  Unakho nokuyilungisa ikhowudi yoxwebhu i-{ -brand-short-name } njengoko ufuna ukuhlangabezana neemfuno zakho. I-Mozilla Public License ikwakunika ilungelo lokunikezela ngeenguqulelo zakho ezilungisiweyo.
rights-intro-point-2 = Akunikwanga nawaphi na amalungelo ophawu lorhwebo okanye amaphepha-mvume eempawu zorhwebo Mozilla Foundation okanye ezalo naliphi na iqela kuqukwa, ngokungenamida, igama lakwa-Firefox okanye imbasa yabo. Inkcazelo engaphezulu ngeempawu zorhwebo ingafumaneka <a data-l10n-name="mozilla-trademarks-link">apha</a>.
rights-intro-point-3 = Ezinye iimpawu ze-{ -brand-short-name }, ezinjenge-Crash Reporter zikunika enye indlela yokunika ingxelo i-{ -vendor-short-name }. Ngokukhetha ukuthumela ingxelo, unika i-{ -vendor-short-name } imvume yokusebenzisa ingxelo ukuze iphucule imveliso yayo, yokupapasha ingxelo kwiiwebhusayithi zayo nokunikezela ngengxelo.
rights-intro-point-4 = Indlela esisebenzisa ngayo iinkcukacha zakho kwanengxelo ethunyelweyo ye-{ -vendor-short-name } nge-{ -brand-short-name } ichazwe <a data-l10n-name="mozilla-privacy-policy-link">I-{ -brand-short-name } Umgaqo-nkqubo wangasese</a>.
rights-intro-point-4-unbranded = Nayiphi na imigaqo-nkqubo yangasese esebenzayo yale mveliso imele idweliswe apha.
rights-intro-point-5 = Ezinye iimpawu ze-{ -brand-short-name } zisebenzisa iinkonzo zenkcukacha esekeke kwiwebhu, nangona kunjalo, asinakuziqinisekisa ukuba zichaneke ngo-100% okanye azinazimposiso. Iinkcukacha ezingaphezulu kuqukwa nenkcazelo yokuqhwalelisa iimpawu ezisebenzisa ezi nkonzo, zingafumaneka <a data-l10n-name="mozilla-service-terms-link">kwimiqathango yenkonzo</a>.
rights-intro-point-5-unbranded = Ukuba le mveliso ibandakanya iinkonzo zewebhu, nayiphi na imiqathango yenkonzo esebenzayo kwi(i)nkonzo kumele inxityelelaniswe <a data-l10n-name="mozilla-website-services-link">Iinkonzo zewebhusayithi</a> icandelo.
rights-intro-point-6 = Khon' ukuze uzidlale ezinye iintlobo zesixhobo sevidiyo, i-{ -brand-short-name } ikhuphela iimodyuli ezithile zokuguqula ukusuka kwabanye abantu.
rights-webservices-header = I-{ -brand-full-name } Iinkonzo zenkcazelo ezisekelwe kwiwebhu
rights-webservices = I-{ -brand-full-name } isebenzisa iinkonzo zenkcukacha esekeke kwiwebhu ("Iinkonzo") ukunikeza ngezinye zeempawu ezinikezelwe ukusebenzisa kwakho ngale nguqulelo yebhayinari ye-{ -brand-short-name } ngaphantsi kwemiqathango echazwe ngaphantsi. Ukuba akufuni ukusebenzisa enye okanye ezinye zeenkonzo okanye ukuba imiqathango engezantsi ayamnkelekanga, ungaluqhwalelisa uphawu okanye i(i)nkonzo. Imiyalelo yokuqhwalelisa uphawu oluthile okanye inkonzo ifumaneka <a data-l10n-name="mozilla-disable-service-link">apha</a>. Ezinye iinkalo neeNkonzo zinokuvalwa zingasebenzi kwiipriferensi zokusebenza.
rights-safebrowsing = <strong>Ukubhrawuza okukhuselekileyo: </strong>Ukuqhwalelisa uphawu lokubhrawuza okukhuselekileyo makungenziwa kuba kunokukhokelela ekubeni ungene kwiisayithi ezingakhuselekanga.  Ukuba ufuna ukuqhwalelisa uphawu ngokupheleleyo, landela la manyathelo:
rights-safebrowsing-term-1 = Vula iipriferensi zeaplikheshini
rights-safebrowsing-term-2 = Khetha ukhetho loKhuseleko
rights-safebrowsing-term-3 = Cima ukhetho oluthi "{ enableSafeBrowsing-label }"
enableSafeBrowsing-label = Bloka isiqulatho esiyingozi nesiqhathayo
rights-safebrowsing-term-4 = Ukubhrawuza okukhuselekileyo ngoku kuqhwalelisiwe
rights-locationawarebrowsing = <strong>Ukubhrawuza okufunisela ngendawo: </strong>isoloko ilukhetho. Akukho nkcazelo yendawo ethunyelwa ngaphandle kwemvume yakho. Ukuba ufuna ukuqhwalelisa uphawu ngokupheleleyo, landela la manyathelo:
rights-locationawarebrowsing-term-1 = Kwibha ye-URL, chwetheza <code>malunga nolungiselelo</code>
rights-locationawarebrowsing-term-2 = Chwetheza geo.enabled
rights-locationawarebrowsing-term-3 = Cofa kabini kwipriferensi ye-geo.enabled
rights-locationawarebrowsing-term-4 = Ukubhrawuza okufunisela indawo ngoku kuqhwalelisiwe
rights-webservices-unbranded = Isishwankathelo sewebhusayithi esilungiselela okubandakanywa yimveliso, ndawonye nemiyalelo yendlela yokusiqhwalelisa, ukuba kuyenzeka, kufuneka zibandakanywe apha.
rights-webservices-term-unbranded = Nayiphi na imiqathango yenkonzo esebenzayo yale mveliso kufuneka idweliswe apha.
rights-webservices-term-1 = I-{ -vendor-short-name } nababhaleli bayo, abaniki-maphephamvume nabalingane basebenzela ukunikezela ngeenkonzo ezisulungekileyo nezigqibeleleyo.  Naxa kunjalo, asinakuqinisekisa ukuba le nkcazelo igqibelele kwaye iyinasiphoso.  Umzekelo, iNkonzo yokuBhrawuza ekhuselekileyo isenokungazichongi iisayithi ezinobungozi, zichonge iisayithi ezikhuselekileyo ngempazamo kunye neNkonzo yokufunisela indawo, zonke iindawo ezibuyiswe ngabanikezeli-nkonzo bethu ziintelekelelo kuphela kwaye akukho namnye phakathi kwethu nabanikezeli-nkonzo bethu oqinisekisa ngokuchaneka kweendawo ezinikezelweyo.
rights-webservices-term-2 = I-{ -vendor-short-name } isenokuziyeka okanye izitshintshe iinkonzo ngokubona kwayo.
rights-webservices-term-3 = Ungazisebenzisa ezi nkonzo nenguqulelo ekhoyo ye-{ -brand-short-name }, kwaye i-{ -vendor-short-name } ikunika ilungelo lokwenza oko.  I-{ -vendor-short-name } nabaniki-maphephamvume ayo iwabambile onke amanye amalungelo kwiinkonzo.  Le miqathango ayijoliswanga ekunciphiseni nawaphi na amalungelo anikezelwe phantsi kwamaphepha-mvume oxwebhu oluvulekileyo asebenza kwi-{ -brand-short-name } nakwiinguqulelo zekhowudi yoxwebhu oluhambelanayo ne-{ -brand-short-name }.
rights-webservices-term-4 = <strong>IiNkonzo zinikezwa "zinjengoko zinjalo." i-{ -vendor-short-name }, abaniki-galelo, abaniki-layisensi, kunye nabasasazi bazo, bayazikhupha kwibango lazo zonke iziqinisekiso, nokuba zivakalisa ngokuphandle okanye ngokusebenzayo, ukuquka ngaphandle kwezithintelo, iziqinisekiso zokuba iiNkonzo ziyarhwebeka kwaye zizilungele iinjongo  zakho ezithile. Uya kubuthathela kuwe bonke ubungozi obunokuvela ekukhetheni kwakho iinkonzo ezifanele iinjongo zakho nangokumayela nomgangatho kwanokusebenza kweenkonzo. Ezinye iindawo zolawulo azikuvumeli ukukhutshelwa ngaphandle okanye ukuncitshiswa kweewaranti ezingathiwanga pahaha, ngoko ke oku kungabi nabutyala abusebenzi kuwe.</strong>
rights-webservices-term-5 = <strong>Ngaphandle kokusemthethweni, i-{ -vendor-short-name }, ababhaleli, abaniki-maphephamvume nabanikezeli bayo abayi kuba nabutyala ngawo nawuphi na umonakalo ongathanga ngqo, okhethekileyo, owengozi, ongumvuka, osisohlwayo okanye ongumzekelo ongumvuka okanye ophathelele ekusetyenzisweni kwe-{ -brand-short-name } neenkonzo.  Ubutyala obudibeneyo phantsi kwale miqathango abuyi kudlula kuma-$500 (amakhulu amahlanu eedola). Ezinye iindawo zolawulo azikuvumeli ukukhutshelwa ngaphandle okanye ukuncitshiswa komonakalo othile, ngoko ke oku kukhutshelwa ngaphandle nokuncitshiswa kusenokungasebenzi kuwe.</strong>
rights-webservices-term-6 = I-{ -vendor-short-name } ingayihlaziya le miqathango ngokwemfuneko yoko ngamaxesha athile. Le miqathango ayinakulungiswa okanye irhoxiswe ngaphandle kwesivumelwano esibhaliweyo se-{ -vendor-short-name }.
rights-webservices-term-7 = Le miqathango ilawulwa yimithetho yelizwe laseCalifornia, eMelika, ngaphandle kwemigaqo engokungqubana nomthetho. Ukuba kukho inxalenye yale miqathango engasebenziyo okanye engenakusetyenziswa, inxalenye eyintsalela iya kusebenza yona. Ukuba kuthe kwakho ukungqubana phakathi kwenguqulelo yale miqathango nolwimi lwesiNgesi, ulwimi lwesiNgesi lulo oluya kusetyenziswa.
