[package]
name = "style_derive"
version = "0.0.1"
authors = ["The Servo Project Developers"]
license = "MPL-2.0"
publish = false

[lib]
path = "lib.rs"
proc-macro = true

[dependencies]
quote = "0.3"
syn = { version = "0.11", features = ["visit"] }
synstructure = "0.5.2"
