#filter emptyLines

#define MOZ_LANGPACK_CREATOR Het ChatZilla-team

#define MOZ_LANGPACK_HOMEPAGE http://chatzilla.hacksrus.com/

# If non-English locales wish to credit multiple contributors, uncomment this
# variable definition and use the format specified.
#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>MarkH</em:contributor> <em:contributor>Fjoerfoks</em:contributor> <em:contributor>Tim</em:contributor>

#unfilter emptyLines
