#filter emptyLines

#define MOZ_LANGPACK_CREATOR mozilla-nl.org

# If non-English locales wish to credit multiple contributors, uncomment this
# variable definition and use the format specified.
#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Tim Maks van den Broek</em:contributor><em:contributor>Niek Dekker</em:contributor><em:contributor>Onno Ekker</em:contributor><em:contributor>Ruben v/d Ven</em:contributor>

#unfilter emptyLines
