# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with

# your locale code, and link to your translated pages as soon as they're

# live.


#define bookmarks_title Comharran-lìn


#define bookmarks_heading Comharran-lìn


#define bookmarks_toolbarfolder Pasgan do bhàr nan comharra-lìn


#define bookmarks_toolbarfolder_description Cuir comharran-lìn sa phasgan seo gus am faicinn air bàr nan comharra-lìn


# LOCALIZATION NOTE (getting_started):


# link title for https://www.mozilla.org/en-US/firefox/central/


#define getting_started Toiseach tòiseachaidh


# LOCALIZATION NOTE (firefox_heading):


# Firefox links folder name


#define firefox_heading Mozilla Firefox


# LOCALIZATION NOTE (firefox_help):


# link title for https://www.mozilla.org/en-US/firefox/help/


#define firefox_help Cobhair agus gleusan teagaisg


# LOCALIZATION NOTE (firefox_customize):


# link title for https://www.mozilla.org/en-US/firefox/customize/


#define firefox_customize Gnàthaich Firefox


# LOCALIZATION NOTE (firefox_community):


# link title for https://www.mozilla.org/en-US/contribute/


#define firefox_community Gabh pàirt


# LOCALIZATION NOTE (firefox_about):


# link title for https://www.mozilla.org/en-US/about/


#define firefox_about Mu ar dèidhinn


# LOCALIZATION NOTE (nightly_heading):


# Firefox Nightly links folder name


#define nightly_heading Goireasan Firefox Nightly


# LOCALIZATION NOTE (nightly_blog):


# Nightly builds only, link title for https://blog.nightly.mozilla.org/


#define nightly_blog Bloga Firefox Nightly


# LOCALIZATION NOTE (bugzilla):


# Nightly builds only, link title for https://bugzilla.mozilla.org/


#define bugzilla Tracaiche bugaichean Mozilla


# LOCALIZATION NOTE (mdn):


# Nightly builds only, link title for https://developer.mozilla.org/


#define mdn Lìonra luchd-leasachaidh Mozilla


# LOCALIZATION NOTE (nightly_tester_tools):


# Nightly builds only, link title for https://addons.mozilla.org/en-US/firefox/addon/nightly-tester-tools/


#define nightly_tester_tools Innealan luchd-deuchainn Nightly


# LOCALIZATION NOTE (crashes):


# Nightly builds only, link title for about:crashes


#define crashes Gach tuisleadh a bha agad


# LOCALIZATION NOTE (irc):


# Nightly builds only, link title for ircs://irc.mozilla.org/nightly


#define irc Dèan deasbad air Nightly air IRC


# LOCALIZATION NOTE (planet):


# Nightly builds only, link title for https://planet.mozilla.org/


#define planet Planaid Mozilla


#unfilter emptyLines
