[package]
name = "webrender_api"
version = "0.48.0"
authors = ["Glenn Watson <gw@intuitionlibrary.com>"]
license = "MPL-2.0"
repository = "https://github.com/servo/webrender"

[features]
nightly = ["euclid/unstable", "serde/unstable"]
ipc = ["ipc-channel"]
webgl = ["offscreen_gl_context"]

[dependencies]
app_units = "0.5"
bincode = "0.8"
byteorder = "1.0"
euclid = "0.15"
gleam = "0.4.5"
heapsize = ">= 0.3.6, < 0.5"
ipc-channel = {version = "0.8", optional = true}
offscreen_gl_context = {version = "0.11", features = ["serde"], optional = true}
serde = { version = "1.0", features = ["rc", "derive"] }
time = "0.1"

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "0.3"
core-graphics = "0.8"

[target.'cfg(target_os = "windows")'.dependencies]
dwrote = "0.4"
