# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

rights-intro = { -brand-full-name } အားကမ္ဘာတစ်ဝှမ်းရှိ ထောင်ချီသော အဖွဲ့ဝင်များ မှတည်ဆောက်ခဲ့ပြီး အခမဲ့ပြီး အရင်းအမြစ် ရယူနိုင်သော ဆော့ဝဲတစ်ခုဖြစ်သည်။ ဤတွင်သင်သိရှိထားရန် အချက်အလက် အချို့ရှိသည်၊
rights-intro-point-1 = { -brand-short-name } အားသင်သုံးစွဲနေသည်မှာအောက်ပါ သဘောတူညီချက်အရဖြစ်သည်<a data-l10n-name="mozilla-public-license-link">မော်ဇီလာ၏ဖြန့်ချီရေးလိုင်စင်</a>သင်သည် { -brand-short-name } အား ကူးယူခြင်းသော်လည်ကောင်း၊ဖြန့်ချီခြင်းသော်လည်းကောင်းလုပ်နိုင်ပါသည်။သင်သည်  { -brand-short-name } ၏အခြေခံ ကုဒ်များအားသင်၏လိုအပ်ချက်အတိုင်းပြောင်းလဲသုံးဆွဲနိုင်ပါသည်။ မော်ဇီလာ၏ဖြန့်ချီရေးလိုင်စင်သည်သင်ပြင်ဆင်ထားသော ဗားရှင်းကိုလည်းပိုင်ဆိုင်ဖြန့်ချီခွင့်ပေးပါသည်။
rights-intro-point-2 = သင်သည် မီးမြေခွေး နာမည်နှင့် တံဆိပ်အပါအဝင် မော်ဇီလာ အဖွဲ့အစည်း (သို့မဟုတ်)  အခြားသူများ၏ ကုန်အမှတ်တံဆိပ်နှင့် ဖြန့်ချီရေးလိုင်စင်များ အသုံးပြုပိုင်ခွင့် မရှိပါ။ နောက်ထပ် ကုန်အမှတ်တံဆိပ်နှင့် ပတ်သက်သော အချက်အလက်များကို ရှာတွေ့နိုင်ပါသည် <a data-l10n-name="mozilla-trademarks-link">ဒီမှာ</a>.
rights-intro-point-3 = { -brand-short-name } တွင်ပါဝင်သောအချို့စွမ်းဆောင်ရေးများ (ပြသာနာတင်ပြပေးသူကဲ့သို) သည်သင့်အား တုန့်ပြန်ထင်မြင်ချက်  { -vendor-short-name } သို့ပေးပို့ခွင့်ပြုပါသည်။တုန့်ပြန်ထင်မြင်ချက်ပေးပို့ ခြင်းအား ရွေချယ်ခြင်းအားဖြင့် သင်သည် { -vendor-short-name } အား တုန့်ပြန်ထင်မြင်ချက် အသုံးပြုပြီး၎င်း၏ ထုတ်ကုန်အားအဆင့်တိုးမြှင့်ခြင်း၊တုန့်ပြန်ထင်မြင်ချက် ကို ဝတ်ဆိုက်တွင် တင်ပြခွင့်ပြုခြင်း ဖြန့်ဝင်ခြင်းပြုခြင်း သဘောမည်ပါသည်။
rights-intro-point-4 = သင် { -vendor-short-name } သို့ပေးပို့ခဲ့သော  { -brand-short-name } နှင့်ပတ်သတ်သည် တုန့်ပြန်ထင်မြင်ချက်များ နှင့် ပုဂ္ဂိုလ်ရေးအချက်အလက် များအားမည်သို့အသုံးပြုသည် ကိုဤတွင်ဖော်ပြထားသည်<a data-l10n-name="mozilla-privacy-policy-link">{ -brand-short-name }၏ပရိုက်ဗစ်ဆီပေါ်လစီ</a>.
rights-intro-point-4-unbranded = ဤထုတ်ကုန်နှင့်ပတ်သတ်သောမည်သည့်ပရိုက်ဗစ်ဆီပေါ်လစီများအား ဒီတွင် စာရင်းပြုစုထားသည်။
rights-intro-point-5 = အချို့ { -brand-short-name } ကွန်ယက်အခြေခံ သတင်းအချက်အလက် ဝန်ဆောင်မှုများ အသုံးပြုထားပါသည်။ သို့သော် ကျွန်ုပ်တို့သည် ထိုဝန်ဆောင်မှုများ ရာနှုန်းပြည့် မှန်ကန်ကြောင်း အာမခံချက် မပေးနိုင်ပါ။ ထိုဝန်ဆောင်မှုများကို ရပ်တန့်ခြင်း အစရှိသည့် အသေးစိတ် အကြောင်းအရာများကို ရှာဖွေနိုင်ပါသည်။ <a data-l10n-name="mozilla-service-terms-link">ဝန်ဆောင်မှူဆိုင်ရာစည်းမျဉ်းများ</a>.
rights-intro-point-5-unbranded = အကယ်လို့ဒီထုတ်ကုန်ဟာ ဝတ်ဆိုက်ဝန်ဆောင်မှူများဖြင့်အလုပ်လုပ်သောအရာမဟုတ်ပါက မည်သည့်အသုံးချနိုင်သောဝန်ဆောင်မှူသဘောတူညီချက်များအားလုံးလင်ခ့်ပေးရန်နေရာမှာ<a data-l10n-name="mozilla-website-services-link">ဝတ်ဆိုက်ဝန်ဆောင်မှူများ</a>section.
rights-intro-point-6 = အမျိုးအစားသေချာပါရှိသည့် ဗွီဒီယိုများကို ဖွင့်ရန်၊ { -brand-short-name } သည် ဖိုင်အမျိုးအစားနှင့် ပတ်သက်သည့် အခြားအဖွဲ့ထံမှ ဝှက်စာဖြည်အစိတ်အပိုင်းကို ကူးယူဆွဲချပါမည်။
rights-webservices-header = { -brand-full-name }၏အင်တာနက်ခြေခံသတင်းအချက်အလက်ဝန်ဆောင်မှူ
rights-webservices = { -brand-full-name } သည်သင်အသုံးပြုရန်အတွက်အောက်တွင်ဖော်ပြထားသောသဘောတူညီချက်များဖြင့် { -brand-short-name } အားသင်အသုံးပြုရန် အတွက် ဝတ်အခြေခံသတင်းအချက်အလက် ဝန်ဆောင်မှူများအားအသုံးပြုသည်("Services")။အကယ်လို့ သင်သည်တစ်ခုသို့မဟုတ် တစ်ခုထက်ပိုသော သဘောတူညီချက်များအားလက်မခံနိုင်ပါက အဆိုပါဝန်ဆောင်မှူသို့ဆားဗစ်အားပိတ်ထားနိုင်ပါသည်။ထိုသို့ပိတ်ပင်ရန်အတွက်လုပ်ဆောင်ချက်အဆင့်ဆင့်အားဖော်ပြထားသည်မှာ ..<a data-l10n-name="mozilla-disable-service-link">ဒီမှာ</a>ဆော့ဝဲ၏ အပြင်အဆင်ဆက်တင်များတွင် အခြားလုပ်ဆောင်ချက်များအား ပိတ်ထားနိုင်ပါသှ်
rights-safebrowsing = <strong>လုံခြုံစိတ်ချရသောအင်တာနက်ရှာဖွေခြင်း၊</strong>လုံခြုံသော ရှာဖွေခြင်းအား ပိတ်ထားခြင်းကို အားမပေးပါအဘယ့်ကြောင့်ဆိုသော် မလုံခြုံသော ဝတ်ဆိုက်များမှ တိုက်ခိုက်ခြင်းကို ခံရနိုင်ဖွယ်ရှိသောကြောင့်ဖြစ်သည်။၎င်းအောင်း သင်အမှန်တကယ် ဖြုတ်ချင်လိုပါက အောက်ပါအချက်များကိုလိုက်လံဆောင်ရွက်ပါ :
rights-safebrowsing-term-1 = အက်ပလီးကေးရှင်းအပြင်အဆင်များအားဖွင့်ပါ။
rights-safebrowsing-term-2 = လုံခြုံရေးအပြင်အဆင်အားရွေးပါ
rights-safebrowsing-term-3 = "{ enableSafeBrowsing-label }" ကို ရွေးချယ်ထားခြင်းမှ ဖြုတ်ရန်
enableSafeBrowsing-label = အန္တရာယ်ရှိသည့် အကြောင်းအရာတုများကို တားဆီးပါ
rights-safebrowsing-term-4 = လုံခြုံသောအင်တာနက်အသုံးပြုခြင်းအပြင်အဆင်အား ဖျက်သိမ်းပြီး။
rights-locationawarebrowsing = <strong>တည်နေရာအလိုက်အင်တာနက်အသုံးပြုခြင်း</strong>is always opt-in.  No location information is ever sent without your permission.  If you wish to disable the feature completely, follow these steps:
rights-locationawarebrowsing-term-1 = URL ဘားတွင်၊ရိုက်ထည့်ပါ<code>about:config</code>
rights-locationawarebrowsing-term-2 = geo.enabled လို့ ရိုက်ထည့်ပါ
rights-locationawarebrowsing-term-3 = Double click on the geo.enabled preference
rights-locationawarebrowsing-term-4 = တည်နေရာအလိုက်အင်တာနက်အသုံးပြုခြင်းအား ပိတ်ပြီး။
rights-webservices-unbranded = ဝတ်ဆိုက်ဝန်ဆောင်မှူများ၏အကျဉ်းချုံးဖော်ပြချက်။အကယ်လို့ထောက်ပံ့ပေးထားပါကဤတွင်ပေါ်ရမည်ဖြစ်သည်။
rights-webservices-term-unbranded = ဒီထုတ်ကုန်အတွက် မည်သည့်အသုံးချနိုင်သော ဝန်ဆောင်မှူသဘောတူညီချက်အားလုံးဤတွင် စာရင်းပြုစုထားသင့်သည်။
rights-webservices-term-1 = { -vendor-short-name } နှင့် စေတနာ့ဝန်ထမ်းများ၊ လိုင်စင်ပေးသူများ နှင့်ပါတနာများသည် အတတ်နိုင်ဆုံး တိကျသော ခေတ်မှီသော ဝန်ဆောင်မှူများကို ပေးရန်လုပ်ဆောင်နေကြပါသည်။သို့သော်လည်း ဤသတင်းအချက်အလက် သည် အမှားလုံးဝကင်းပါသည်ဟု ကျွန်ုပ်တို့ အာမမခံပါ။ဥမာအားဖြင့် လုံးခြုံစိတ်ချ အင်တာနက်သုံးစွဲခြင်း ဆားဗစ်သည်အချို့သောဝတ်ဆိုက်များ အား အန္တရာယ်ရှိသည် ဟုမုချမသိနိုင်ကောင်း မသိနိုင်လိမ့်မည်။ ဝန်ဆောင်မှူများအားလုံးသည် ခန့်မှန်းတွက်ချက်ထားသော ဝန်ဆောင်မှူများဖြစ်သည်ကို သတိထားစေလိုပါသည်။
rights-webservices-term-2 = { -vendor-short-name }သည်ပြုလုပ်နေခြင်းကိုရပ်တန့်သွားလိမ့်မည် သို့မဟုတ်ပါက ဝန်ဆောင်မှူများအားရည်ညွှန်းချက်အတိုင်းပြောင်းသွားလိမ့်မည်။
rights-webservices-term-3 = You are welcome to use these Services with the accompanying version of { -brand-short-name }, and { -vendor-short-name } grants you its rights to do so. { -vendor-short-name } and its licensors reserve all other rights in the Services. These terms are not intended to limit any rights granted under open source licenses applicable to { -brand-short-name } and to corresponding source code versions of { -brand-short-name }.
rights-webservices-term-4 = <strong>The Services are provided "as-is." { -vendor-short-name }, its contributors, licensors, and distributors, disclaim all warranties, whether express or implied, including without limitation, warranties that the Services are merchantable and fit for your particular purposes. You bear the entire risk as to selecting the Services for your purposes and as to the quality and performance of the Services. Some jurisdictions do not allow the exclusion or limitation of implied warranties, so this disclaimer may not apply to you.</strong>
rights-webservices-term-5 = <strong>Except as required by law, { -vendor-short-name }, its contributors, licensors, and distributors will not be liable for any indirect, special, incidental, consequential, punitive, or exemplary damages arising out of or in any way relating to the use of { -brand-short-name } and the Services.  The collective liability under these terms will not exceed $500 (five hundred dollars). Some jurisdictions do not allow the exclusion or limitation of certain damages, so this exclusion and limitation may not apply to you.</strong>
rights-webservices-term-6 = { -vendor-short-name } သည် ဤသဘောတူညီချက်များအားအချိန်နှင့်အမျှ လိုအပ်သလို သစ်လွင်အောင်လုပ်နေပါမည်။ဤသဘောတူညီချက်များသည် { -vendor-short-name } ၏ ရေးသားထားသော ခံယူ၀န်မပါပဲ ပြင်ဆင်ခြင်းဖျက်ပစ်ခြင်းမပြုခံရနိုင်ပါ။
rights-webservices-term-7 = ဤစည်းကမ်းချက်များကို အမေရိကန်နိုင်ငံ၊ ကယ်လီဖိုးနီးယားပြည်နယ်၏ အငြင်းပွားနိုင်သော ဥပဒေခံစားခွင့်များ မပါဝင်သည့်  ဥပဒေများနှင့် ကာကွယ်ထားပါသည်။ အကယ်၍ အချို့စည်းကမ်းချက်များမှာ အကျုံးမဝင် သို့မဟုတ် အတည်မပြုနိုင်ဖြစ်လာပါက ကျန်ရှိသော စည်းကမ်းချက်များမှာ ဆက်လက်၍ အပြည့်အဝ အကျိုးသက်ရောက်မှု ရှိအုံးမည် ဖြစ်သည်။ ဤစည်းကမ်းချက်များကို ဘာသာပြန်ဆိုမှုများနှင့် အင်္ဂလိပ်မူ တို့ ကွဲပြားအငြင်းပွားစရာ ဖြစ်လာခဲ့ပါက အင်္ဂလိပ်မူကသာ အတည်ဖြစ်သည်။
