# This Source Code Form is subject to the terms of the Waterfox Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with
# your locale code, and link to your translated pages as soon as they're
# live.

#define bookmarks_title Marcadores
#define bookmarks_heading Marcadores

#define bookmarks_toolbarfolder Carpeta de la barra de marcadores
#define bookmarks_toolbarfolder_description Añada marcadores a esta carpeta para verlos en la barra de herramientas de marcadores

# LOCALIZATION NOTE (getting_started):
# link title for https://www.mozilla.org/en-US/firefox/central/
#define getting_started Comenzar a usar Waterfox

# LOCALIZATION NOTE (firefox_heading):
# Waterfox links folder name
#define firefox_heading Waterfox Waterfox

# LOCALIZATION NOTE (firefox_help):
# link title for https://www.mozilla.org/en-US/firefox/help/
#define firefox_help Ayuda y tutoriales

# LOCALIZATION NOTE (firefox_get_help):
# link title for https://www.mozilla.org/en-US/firefox/help/
#define firefox_get_help Obtener ayuda

# LOCALIZATION NOTE (firefox_customize):
# link title for https://www.mozilla.org/en-US/firefox/customize/
#define firefox_customize Personalice Waterfox

# LOCALIZATION NOTE (firefox_community):
# link title for https://www.mozilla.org/en-US/contribute/
#define firefox_community ¡Involúcrese!

# LOCALIZATION NOTE (firefox_about):
# link title for https://www.mozilla.org/en-US/about/
#define firefox_about Acerca de nosotros

# LOCALIZATION NOTE (nightly_heading):
# Waterfox Nightly links folder name
#define nightly_heading Recursos de Waterfox Nightly

# LOCALIZATION NOTE (nightly_blog):
# Nightly builds only, link title for https://blog.nightly.mozilla.org/
#define nightly_blog Blog de Waterfox Nightly

# LOCALIZATION NOTE (bugzilla):
# Nightly builds only, link title for https://bugzilla.mozilla.org/
#define bugzilla Herramienta de registro de fallos de Waterfox

# LOCALIZATION NOTE (mdn):
# Nightly builds only, link title for https://developer.mozilla.org/
#define mdn Waterfox Developer Network

# LOCALIZATION NOTE (nightly_tester_tools):
# Nightly builds only, link title for https://addons.mozilla.org/en-US/firefox/addon/nightly-tester-tools/
#define nightly_tester_tools Nightly Tester Tools

# LOCALIZATION NOTE (crashes):
# Nightly builds only, link title for about:crashes
#define crashes Todos sus fallos

# LOCALIZATION NOTE (planet):
# Nightly builds only, link title for https://planet.mozilla.org/
#define planet Planet Waterfox

#unfilter emptyLines
