[package]
name = "binast"
version = "0.2.0"
authors = ["David Teller <D.O.Teller@gmail.com>"]
autobins = false

[dependencies]
binjs_meta = "^0.5.2"
clap = "^2"
env_logger = "^0.6"
Inflector = { version="^0.11", default-features=false }
itertools = "^0.8"
log = "0.4"
yaml-rust = "^0.4.2"

[[bin]]
name = "binast"
path = "src/main.rs"
