#define VERSION_MAJOR  2
#define VERSION_MINOR  0
#define VERSION_PATCH  2
#define VERSION_EXTRA  ""
#define VERSION_PACKED ((VERSION_MAJOR<<16)|(VERSION_MINOR<<8)|(VERSION_PATCH))
#define VERSION_STRING_NOSP "v2.0.2"
#define VERSION_STRING      " v2.0.2"
