# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

rights-title = Ynghylch eich hawliau
rights-intro = Mae { -brand-full-name } yn feddalwedd cod agored rhydd a rhad, wedi ei adeiladu gan gymuned o filoedd o bobl ar draws y byd i gyd. Mae yna rhai pethau i chi gael gwybod:
rights-intro-point-1 = Mae { -brand-short-name } ar gael i chi o dan amodau'r <a data-l10n-name="mozilla-public-license-link">Trwydded Gyhoeddus Mozilla</a>. Mae hyn yn golygu y cewch ddefnyddio, gopïo a dosbarthu { -brand-short-name } i eraill.  Mae croeso i chi newid cod ffynhonnell { -brand-short-name } yn ôl eich angen. Mae Trwydded Gyhoeddus Mozilla yn rhoi'r hawl i chi ddosbarthu'r fersiwn rydych wedi ei newid.
rights-intro-point-2 = Nid ydych yn derbyn unrhyw hawliau nod masnachu na thrwyddedau i nod masnach y Mozilla Foundation neu unrhyw barti, gan gynnwys y Mozzilla Foundation heb gyfyngiadau i enw na logo Firefox. Mae gwybodaeth bellach am nodau masnach i’w cael <a data-l10n-name="mozilla-trademarks-link">yma</a>.
rights-intro-point-3 = Mae rhai nodweddion yn { -brand-short-name }, megis yr Adroddwr Chwalu, yn rhoi'r dewis i chi gyfrannu adborth i { -vendor-short-name }. Drwy ddewis cyflwyno adborth rydych yn rhoi i { -vendor-short-name } ganiatâd i ddefnyddio'r adborth i wella ei gynnyrch, i gyhoeddi'r adborth ar ei wefannau, ac i ddosbarthu'r adborth.
rights-intro-point-4 = Mae sut rydym yn defnyddio y data personol ac adborth rydych wedi ei gyflwyno i { -vendor-short-name } drwy { -brand-short-name } yn cael ei ddisgrifio yn <a data-l10n-name="mozilla-privacy-policy-link">Polisi Preifatrwydd { -brand-short-name }</a>.
rights-intro-point-4-unbranded = Rhaid rhestri unrhyw bolisïau preifatrwydd perthnasol yma.
rights-intro-point-5 = Mae rhai nodweddion { -brand-short-name } yn gwneud defnydd p wasanaethau gwybodaeth gwe, er hynny nid ydym yn gallu gwarantu eu bod yn 100% yn gywir nac yn rhydd o wallau. Mae rhagor o fanylion, gan gynnwys gwybodaeth ar sut i'w hanalluogi i'w cael yn yr <a data-l10n-name="mozilla-service-terms-link">amodau gwasanaeth</a>.
rights-intro-point-5-unbranded = Os yw'r cynnyrch yn cynnwys gwasanaethau gwe, rhaid cysylltu unrhyw amodau gwasanaeth perthnasol ar gyfer y gwasanaeth(au) i'r adran <a data-l10n-name="mozilla-website-services-link">Gwasanaethau Gwefan</a> Gwe.
rights-intro-point-6 = Er mwyn chwarae rhai mathau o gynnwys fideo, mae { -brand-short-name } yn llwytho i lawr rhywfaint o gynnwys modiwlau dadgryptio gan drydydd partïon.
rights-webservices-header = Gwasanaethau Gwybodaeth Gwe { -brand-full-name }
rights-webservices = Mae { -brand-full-name } yn defnyddio gwasanaethau gwybodaeth gwe ("Gwasanaethau") i ddarparu rhai o'r nodweddion sy'n cael eu darparu ar eich cyfer yn y fersiwn yma o { -brand-short-name } o fewn yr amodau disgrifir isod. Os nad ydych am ddefnyddio un neu fwy o'r Gwasanaethau neu mae'r amodau yn annerbyniol, mae modd i chi analluogi'r nodwedd neu'r Gwasanaeth(au). Mae gwybodaeth ar sut i analluogi nodwedd neu Wasanaeth penodol i'w cael <a data-l10n-name="mozilla-disable-service-link">yma</a>. Mae modd analluogi nodweddion a Gwasanaethau eraill yn newisiadau'r rhaglen.
rights-safebrowsing = <strong>Pori Diogel: </strong>Nid yw anablu Pori Diogel yn cael ei gymeradwyo gan y gall arwain i chi fynd i wefannau anniogel.  Os ydych eisiau analluogi'r nodwedd yn llwyr, dilynwch y camau hyn:
rights-safebrowsing-term-1 = Agor dewisiadau'r rhaglen
rights-safebrowsing-term-2 = Dewis Diogelwch
rights-safebrowsing-term-3 = Dad dicio'r dewis i "{ enableSafeBrowsing-label }"
enableSafeBrowsing-label = Rhwystro cynnwys peryglus a thwyllodrus
rights-safebrowsing-term-4 = Mae Pori Diogel wedi ei analluogi
rights-locationawarebrowsing = <strong>Pori Ymwybodol o Leoliad: </strong>yn ddewis i chi bob tro.  Ni fydd gwybodaeth yn cael ei anfon heb eich caniatâd.  Os hoffech chi analluogi'r nodwedd yn llwyr, dilynwch y camau hyn:
rights-locationawarebrowsing-term-1 = Yn y bar URL, teipiwch <code>about:config</code>
rights-locationawarebrowsing-term-2 = Teipio geo.enabled
rights-locationawarebrowsing-term-3 = Clic dwbl i'r dewis geo.enabled
rights-locationawarebrowsing-term-4 = Mae Pori Ymwybodol o Leoliad wedi ei analluogi
rights-webservices-unbranded = Rhaid cynnwys yn fan hyn, drosolwg o'r gwasanaeth gwefan gwe mae'r cynnyrch yn ei gynnwys, ynghyd â chyfarwyddiadau ar sut i'w hatal os yn berthnasol.
rights-webservices-term-unbranded = Rhaid rhestru amodau gwasanaethau gwe yma.
rights-webservices-term-1 = Mae { -vendor-short-name } a'i gyfranwyr, trwyddedwyr, a phartneriaid yn gweithio i ddarparu'r Gwasanaethau mwyaf cywir a chyfredol.  Er hynny, nid oes modd i ni warantu fod y wybodaeth yn gynhwysfawr a diwall.  Er enghraifft, efallai na fydd y Gwasanaeth Pori Diogel yn adnabod rhai gwefannau anniogel ac efallai adnabod rhai gwefannau diogel ar gam. Mae pob lleoliad sy'n cael ei ddychwelyd gan ein darparwyr gwasanaeth ar gyfer y Gwasanaeth Ymwybodol o Leoliad yn amcanion yn unig. Nid ydym ni na'r darparwyr gwasanaeth yn gallu gwarantu cywirdeb y lleoliadau hyn.
rights-webservices-term-2 = Gall { -vendor-short-name } atal neu newid y Gwasanaethau yn ôl eu mympwy.
rights-webservices-term-3 = Mae croeso i chi ddefnyddio'r Gwasanaethau hyn gyda'r fersiwn yma o { -brand-short-name }, ac mae { -vendor-short-name } rhoi ei hawl i chi wneud hynny.  Mae { -vendor-short-name } a'i drwyddedwyr yn diogelu pob hawl arall yn y Gwasanaethau.  Nid yw'r amodau wedi eu hanelu at gyfyngu unrhyw hawliau o dan drwyddedau cod agored sy'n perthyn i { -brand-short-name } ac i'r fersiynau perthnasol o ffynonellau cod { -brand-short-name }.
rights-webservices-term-4 = <strong>Mae'r gwasanaeth yn cael ei ddarparu "fel ag y mae".  Mae { -vendor-short-name }, ei gyfranwyr, trwyddedwyr, a dosbarthwyr, yn gwadu unrhyw warant, p'un ai yn cael ei fynegi neu ei awgrymu, gan gynnwys heb gyfyngiad, gwarant fod y Gwasanaethau yn farchnadadwy nac yn addas i'ch pwrpas penodol.  Rydych yn derbyn yr holl risg o ddewis y Gwasanaethau ar gyfer eich pwrpas ac i natur ansawdd a pherfformiad y Gwasanaeth. Nid yw rhai awdurdodau'n caniatáu eithrio neu gyfyngu gwarant sy'n cael ei awgrymu felly efallai nad yw'r gwadiad hwn yn berthnasol i chi.</strong>
rights-webservices-term-5 = <strong>Yn wahanol i'r hyn sy'n angenrheidiol yn ôl y gyfraith, ni fydd { -vendor-short-name }, ei gyfranwyr, trwyddedwyr a dosbarthwyr yn agored i unrhyw iawndal anuniongyrchol, arbenigol, achlysurol, neu enghreifftiol yn codi o neu mewn unrhyw ffordd yn berthnasol i'r defnydd o { -brand-short-name } a'r Gwasanaethau.   Ni fydd yr atebolrwydd cyfunol o dan yr amodau hyn yn fwy na $500 (pum can dollar). Nid yw rhai awdurdodau yn caniatáu cyfyngu ar rhai materion difrod, felly efallai na fydd hyn yn berthnasol i chi.</strong>
rights-webservices-term-6 = Gall { -vendor-short-name } ddiweddaru'r amodau yn ôl y galw o bryd i'w gilydd. Nid oes modd newid na dileu'r amodau heb ganiatâd ysgrifenedig { -vendor-short-name }.
rights-webservices-term-7 = Mae'r amodau yn cael eu rheoli gan gyfreithiau talaith California, UDA, gan hepgor ei ddarpariaethau gwrthdaro cyfreithiol. Os yw unrhyw ran o'r amodau i'w cael heb rym cyfreithiol byd y gweddill yn sefyll mewn grym llawn ac effaith. Os digwydd gwrthdaro rhwng fersiwn sydd wedi ei gyfieithu a'r amodau hyn a'r fersiwn Saesneg, y fersiwn Saesneg fydd yn rheoli.
