# This Source Code Form is subject to the terms of the Waterfox Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with
# your locale code, and link to your translated pages as soon as they're
# live.

#define bookmarks_title Bladwijzers
#define bookmarks_heading Bladwijzers

#define bookmarks_toolbarfolder Map Bladwijzerwerkbalk
#define bookmarks_toolbarfolder_description Voeg bladwijzers aan deze map toe om ze op de bladwijzerwerkbalk weer te geven

# LOCALIZATION NOTE (getting_started):
# link title for https://www.mozilla.org/en-US/firefox/central/
#define getting_started Aan de slag

# LOCALIZATION NOTE (firefox_heading):
# Waterfox links folder name
#define firefox_heading Waterfox Waterfox

# LOCALIZATION NOTE (firefox_help):
# link title for https://www.mozilla.org/en-US/firefox/help/
#define firefox_help Hulp en handleidingen

# LOCALIZATION NOTE (firefox_get_help):
# link title for https://www.mozilla.org/en-US/firefox/help/
#define firefox_get_help Hulp verkrijgen

# LOCALIZATION NOTE (firefox_customize):
# link title for https://www.mozilla.org/en-US/firefox/customize/
#define firefox_customize Waterfox aanpassen

# LOCALIZATION NOTE (firefox_community):
# link title for https://www.mozilla.org/en-US/contribute/
#define firefox_community Meewerken

# LOCALIZATION NOTE (firefox_about):
# link title for https://www.mozilla.org/en-US/about/
#define firefox_about Over Waterfox

# LOCALIZATION NOTE (nightly_heading):
# Waterfox Nightly links folder name
#define nightly_heading Waterfox Nightly-bronnen

# LOCALIZATION NOTE (nightly_blog):
# Nightly builds only, link title for https://blog.nightly.mozilla.org/
#define nightly_blog Waterfox Nightly-blog

# LOCALIZATION NOTE (bugzilla):
# Nightly builds only, link title for https://bugzilla.mozilla.org/
#define bugzilla Waterfox-bugtracker

# LOCALIZATION NOTE (mdn):
# Nightly builds only, link title for https://developer.mozilla.org/
#define mdn Waterfox Developer Network

# LOCALIZATION NOTE (nightly_tester_tools):
# Nightly builds only, link title for https://addons.mozilla.org/en-US/firefox/addon/nightly-tester-tools/
#define nightly_tester_tools Nightly Tester Tools

# LOCALIZATION NOTE (crashes):
# Nightly builds only, link title for about:crashes
#define crashes Al uw crashes

# LOCALIZATION NOTE (planet):
# Nightly builds only, link title for https://planet.mozilla.org/
#define planet Planet Waterfox

#unfilter emptyLines
