[package]
name = "smoosh"
version = "0.1.0"
authors = ["The jsparagus Project Developers"]
edition = "2018"
license = "MIT/Apache-2.0"

[dependencies]
bumpalo = "2.6.0"
log = "0.4"
# Setup RUST_LOG logging.
# Disable regex feature for code size.
env_logger = {version = "0.6", default-features = false}
# For non-jsparagus developers.
jsparagus = { git = "https://github.com/mozilla-spidermonkey/jsparagus", rev = "efc1291d05e5ba8dbb4bd1197937a0291e72742c" }
# For local development, replace above with
# jsparagus = { path = "{path to jsparagus}" }

[build-dependencies]
# For non-jsparagus developers.
jsparagus = { git = "https://github.com/mozilla-spidermonkey/jsparagus", rev = "efc1291d05e5ba8dbb4bd1197937a0291e72742c" }
# For local development, replace above with
# jsparagus = { path = "{path to jsparagus}" }
