[package]
name = "smoosh"
version = "0.1.0"
authors = ["The jsparagus Project Developers"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
bumpalo = "3.4.0"
log = "0.4"
# Setup RUST_LOG logging.
# Disable regex feature for code size.
env_logger = {version = "0.10", default-features = false}
# For non-jsparagus developers.
jsparagus = { git = "https://github.com/mozilla-spidermonkey/jsparagus", rev = "64ba08e24749616de2344112f226d1ef4ba893ae" }
# For local development, replace above with
# jsparagus = { path = "{path to jsparagus}" }

[build-dependencies]
# For non-jsparagus developers.
jsparagus = { git = "https://github.com/mozilla-spidermonkey/jsparagus", rev = "64ba08e24749616de2344112f226d1ef4ba893ae" }
# For local development, replace above with
# jsparagus = { path = "{path to jsparagus}" }
