#filter emptyLines

#define MOZ_LANGPACK_CREATOR mozilla.org

# If non-English locales wish to credit multiple contributors, uncomment this

# variable definition and use the format specified.

#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Carlos Simão</em:contributor> <em:contributor>Cláudio Esperança</em:contributor> <em:contributor>João Miguel Neves</em:contributor> <em:contributor>Manuela Silva</em:contributor> <em:contributor>Rodrigo Cunha</em:contributor>

#unfilter emptyLines
