[package]
name = "glean"
version = "0.1.0"
authors = ["Glean SDK team <glean-team@mozilla.com>"]
edition = "2018"
publish = false

[dependencies]
chrono = "0.4.10"
glean-core = "31.0.2"
log = "0.4"
once_cell = "1.2.0"
uuid = { version = "0.8.1", features = ["v4"] }

[dev-dependencies]
tempfile = "3.1.0"
