# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

rights-title = Tentang Hak Anda
rights-intro = { -brand-full-name } adalah perangkat lunak bebas dan terbuka yang dibangun oleh ribuan anggota komunitas dari berbagai penjuru dunia. Ada beberapa hal yang perlu Anda ketahui:
rights-intro-point-1 = { -brand-short-name } disediakan berdasarkan persyaratan dalam lisensi <a data-l10n-name="mozilla-public-license-link">Mozilla Public License</a>. Ini berarti Anda dapat menggunakan, menyalin, dan mendistribusikan { -brand-short-name } kepada pihak lain. Anda juga dapat memodifikasi kode sumber program { -brand-short-name } sesuai dengan kebutuhan Anda. Lisensi Mozilla Public License memberi hak kepada Anda untuk mendistribusikan versi yang telah Anda modifikasi.
rights-intro-point-2 = Anda tidak diberi hak atau lisensi apa pun atas merek dagang Mozilla Foundation atau pihak lainnya, termasuk tanpa batas, nama atau logo Thunderbird. Informasi lebih lanjut mengenai merek dagang dapat Anda temukan <a data-l10n-name="mozilla-trademarks-link">di sini</a>.
rights-intro-point-3 = Sebagian fitur dalam { -brand-short-name }, misalnya Pelapor Kerusakan, memberi Anda pilihan untuk memberi saran pada { -vendor-short-name }. Dengan memilih mengajukan saran, Anda memberi { -vendor-short-name } izin untuk menggunakan saran ini guna memperbaiki produk tersebut, untuk menayangkan saran di situs tersebut dan mendistribusikan saran.
rights-intro-point-4 = Cara penggunaan informasi pribadi dan saran Anda yang dikirimkan kepada { -vendor-short-name } lewat { -brand-short-name } dijelaskan dalam <a data-l10n-name="mozilla-privacy-policy-link">Kebijakan Privasi { -brand-short-name }</a>.
rights-intro-point-4-unbranded = Segala kebijakan privasi yang berlaku untuk produk ini harus dicantumkan di sini.
rights-intro-point-5 = Sebagian fitur { -brand-short-name } menggunakan layanan informasi berbasis web. Akan tetapi kami tidak dapat menjamin keakuratan atau tingkat layanan tersebut secara 100%. Untuk keterangan lebih lanjut, termasuk bagaimana cara mematikan fungsi layanan ini dapat ditemukan pada <a data-l10n-name="mozilla-service-terms-link">ketentuan layanan</a>.
rights-intro-point-5-unbranded = Jika produk ini menyertakan layanan web, seluruh ketentuan layanan tersebut akan ditaut ke bagian <a data-l10n-name="mozilla-website-services-link">Layanan Situs Web</a>.
rights-intro-point-6 = Untuk memutar jenis konten video tertentu, { -brand-short-name } mengunduh modul dekripsi konten tertentu dari pihak ketiga.
rights-webservices-header = Layanan Informasi Berbasis Web { -brand-full-name }
rights-webservices = { -brand-full-name } menggunakan layanan informasi berbasis web ("Layanan") yang menyediakan sebagian fitur untuk Anda gunakan pada versi binari { -brand-short-name } dalam persyaratan yang dijelaskan di bawah ini. Jika Anda tidak ingin untuk menggunakan satu atau beberapa Layanan tersebut atau persyaratan di bawah ini tidak dapat diterima, Anda dapat mematikan fitur atau Layanan tersebut. Petunjuk untuk mematikan fitur atau Layanan tertentu dapat ditemukan <a data-l10n-name="mozilla-disable-service-link">di sini</a>. Fitur dan Layanan lainnya dapat dinonaktifkan lewat pengaturan aplikasi.
rights-locationawarebrowsing = <strong>Penjelajahan Berbasis Lokasi: </strong>selalu bersifat dapat dipilih. Tidak ada informasi lokasi yang akan dikirim tanpa seizin Anda. Jika Anda ingin mematikannya secara keseluruhan, ikuti petunjuk berikut:
rights-locationawarebrowsing-term-1 = Pada bilah URL, ketikkan <code>about:config</code>
rights-locationawarebrowsing-term-2 = Ketikkan geo.enabled
rights-locationawarebrowsing-term-3 = Klik ganda pada item pengaturan geo.enabled
rights-locationawarebrowsing-term-4 = Penjelajahan Berbasis Lokasi telah dinonaktifkan
rights-webservices-unbranded = Deskripsi mengenai layanan web yang tersedia bersama produk, beserta petunjuk untuk mematikan layanan tersebut, jika dapat diterapkan, akan tersedia di bawah ini.
rights-webservices-term-unbranded = Semua persyaratan layanan yang dapat diterapkan akan tersedia di bawah ini.
rights-webservices-term-1 = { -vendor-short-name }, kontributornya, lisensornya, dan partnernya bekerja untuk menyediakan Layanan terakurat dan terbaru. Akan tetapi kami tidak dapat menjamin informasi tersebut bersifat komprehensif dan bebas dari kesalahan. Sebagai contoh, Layanan Safe Browsing mungkin tidak dapat mengidentifikasi situs yang berisiko dan situs yang aman salah diidentifikasi serta seluruh lokasi pada Layanan Berbasis Lokasi yang dikembalikan dari penyedia layanan kami hanya bersifat perkiraan serta kami atau pun penyedia layanan kami tidak dapat menjamin akurasi lokasi yang disediakan.
rights-webservices-term-2 = { -vendor-short-name } dapat memberhentikan atau mengubah Layanan sesuai dengan kebijaksanaan masing-masing.
rights-webservices-term-3 = Anda dipersilakan untuk menggunakan Layanan tersebut dengan menggunakan { -brand-short-name } yang disertakan dan { -vendor-short-name } memberikan hak kepada Anda untuk menggunakannya.  { -vendor-short-name } dan para lisensornya berhak atas seluruh hak lainnya dalam Layanan tersebut. Persyaratan ini tidak dimaksudkan untuk membatasi hak yang diberikan atas dasar lisensi kode sumber terbuka yang dapat diterapkan pada { -brand-short-name } dan versi kode sumber { -brand-short-name } yang berkaitan.
rights-webservices-term-4 = <strong>Layanan disediakan "sebagaimana adanya". { -vendor-short-name }, para kontributor, lisensor, dan distributor menyangkal semua jaminan dan garansi, baik yang telah disebutkan mau pun tersirat, termasuk secara tak terbatas, bahwa Layanan dapat digunakan untuk kepentingan dagang (merchantable) dan sesuai dengan penggunaan khusus oleh Anda. Anda menanggung seluruh risiko atas Layanan yang Anda pilih untuk Anda gunakan dan atas kinerja Layanan tersebut. Beberapa wilayah hukum tidak mengizinkan pengecualian atau pembatasan pada jaminan yang tersirat sehingga penyangkalan ini tidak dapat diterapkan pada Anda.</strong>
rights-webservices-term-5 = <strong>Kecuali diwajibkan oleh hukum, { -vendor-short-name }, para kontributor, lisensor, dan distributor tidak akan menanggung kerusakan yang bersifat khusus, tidak langsung, insidental, sebab-akibat, pidana, ganti-rugi yang terjadi atas akibat atau yang berhubungan dengan penggunaan { -brand-short-name } beserta Layanan-nya. Pertanggungan secara kolektif di bawah persyaratan ini tidak boleh melebihi $500 (lima ratus dollar). Beberapa yuridiksi tidak mengizinkan pengecualian atau pembatasan atas kerusakan tertentu sehingga penyangkalan ini tidak dapat diterapkan pada Anda.</strong>
rights-webservices-term-6 = { -vendor-short-name } dapat memutakhirkan persyaratan ini secara seperlunya dari waktu ke waktu. Persyaratan ini tidak dapat diubah atau dibatalkan tanpa perjanjian tertulis dengan { -vendor-short-name }.
rights-webservices-term-7 = Persyaratan berikut diatur berdasarkan hukum negara bagian California, Amerika Serikat, dengan mengecualikan pertentangan atas ketentuan hukum yang bersifat sementara. Jika terdapat bagian dari persyaratan ini yang tidak dalam status sah atau tidak dapat dilaksanakan, bagian lainnya tetap berkekuatan penuh. Jika terjadi pertentangan antara versi terjemahan dan versi berbahasa Inggris atas persyaratan ini, versi berbahasa Inggris yang memiliki kekuatan penuh.
