# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

rights-title = Wo wašich prawach
rights-intro = { -brand-full-name } je darmotna softwara wotewrjeneho žórła, wutworjena wot zhromadźenstwa tysacow ludźi z cyłeho swěta. Su někotre wěcy, kotrež wy měł wědźeć:
rights-intro-point-1 = { -brand-short-name } staja so k dispoziciji pod wuměnjenjemi <a data-l10n-name="mozilla-public-license-link">licency Mozilla Public License</a>. To woznamjenja, zo móžeće { -brand-short-name } wužiwać a kopěrować a jón na druhich rozdźělić. Wostanje wam přewostajene, žórłowy kod { -brand-short-name } po wašim wuzdaću změnić, zo by wón wašim potrjebam wotpowědował. Licenca Mozilla Public License tež wam da prawo waše změnjene wersije rozdźělić.
rights-intro-point-2 =
    Njegarantuja wam žane prawa na wikowanskich znamjenjach abo licency na wikowanskich znamjenjach
    załožby Mozilla foundation abo někajkeje druheje strony, bjez wobmjezowanja na
    mjeno abo logo Thunderbird. Přidatne informacije wo wikowanskich znamjenjach namakaće
    <a data-l10n-name="mozilla-trademarks-link">tu</a>.
rights-intro-point-3 = Někotre funkcije w { -brand-short-name }, na př. zdźělenje spadnjenjow, dawaja wam móžnosć waše posudki na { -vendor-short-name } pósłać. Hdyž waše posudki wotesćeleš, daće { -vendor-short-name } dowolnosć, posudki wužiwać, jeho produkty polěpšić, posudki na jeho websydłach wozjewić a posudki rozdźělić.
rights-intro-point-4 = Kak wužiwamy waše wosobinske informacije a posudki, kotrež sće na { -vendor-short-name } přez { -brand-short-name } pósłał, wopisuje so w <a data-l10n-name="mozilla-privacy-policy-link">prawidłach priwatnosće { -brand-short-name }</a>.
rights-intro-point-4-unbranded = Wšě nałožujomne prawidła priwatnosće za tutón produkt měli so tu podać.
rights-intro-point-5 = Někotre funkcije w { -brand-short-name } wužiwaja informaciske websłužby, ale njemóžemy garantować, zo wone su 100% w porjadku abo bjez zmylkow. Dalše podrobnsće, inkluziwne informacije kak móžeće funkcije znjemóžnić, kotrež tute słužby wužiwaja, namakaće we <a data-l10n-name="mozilla-service-terms-link">wužiwanskich wuměnjenjach</a>.
rights-intro-point-5-unbranded = Jeli tutón produkt wopřijima websłužby, nałožujomne wužiwanske wuměnjenja za słužby měli być zwjazane z <a data-l10n-name="mozilla-website-services-link">wotrězkom</a> websydłowych słužbow.
rights-intro-point-6 = Zo by wěste typy widejowobsaha wothrał, sćehnje { -brand-short-name } wěste module za dešifrowanje wobsaha wot třećich poskićowarjow.
rights-webservices-header = { -brand-full-name } informaciske websłužby
rights-webservices = { -brand-full-name } wužiwa informaciske websłužby ("słužby"), zo by někotre funkcije k dispoziciji stajił, kotrež su za wužiwanje z tutej binarnej wersiju { -brand-short-name } pod deleka wopisanymi wuměnjenjemi myslene. Jeli nochceće jednu z tutych słužbow abo wjacore z nich wužiwać, abo slědowace wuměnjenja su njeakceptujomne, móžeće funkciju słužbow znjemóžnić. Instrukcije, kak wěsta funkcija słužby hodźi so znjemóžnić, namakaće <a data-l10n-name="mozilla-disable-service-link">tu</a>. Druhe funkcije a słužby hodźa so w nastajenjach nałoženja znjemóžnić.
rights-locationawarebrowsing = <strong>Přehladowanje z lokalizaciju stejnišća: </strong>je přeco z přizjewjenjom. Žane informacije wo stejnišću so ženje bjez wašeje dowolnosće rozesyła. Jeli chceće tutu funkciju dospołnje znjemóžnić, wuwjedźće slědowace kroki:
rights-locationawarebrowsing-term-1 = Zapisajće do adresoweho pola <code>about:config</code>
rights-locationawarebrowsing-term-2 = Zapisajće geo.enabled
rights-locationawarebrowsing-term-3 = Klikńće dwójce na nastajenje geo.enabled
rights-locationawarebrowsing-term-4 = Přehladowanje z lokalizaciju stejnišća je nětko znjemóžnjene
rights-webservices-unbranded = Přehlad websydłowych słužbow, kotrež produkt wobsahuje, hromadźe z instrukciejemi, kak hodźa so znjemóžnić, je-li móžno, měł so tu zapřijeć.
rights-webservices-term-unbranded = Nałožujomne wužiwanske wuměnjenja za tutón produkt měli so tu podać.
rights-webservices-term-1 = { -vendor-short-name } a jeho sobuskutkowacy, licencydawarjo a partnerojo dźěłaja, zo bychu najdokładniše a najaktualniše słužby k dispoziciji stajili. Ale njemóžemy garantować, zo tute informacije su dospołne a bjez zmylkow. Je na přikład móžno, zo słužba wěsteho přehladowanja nic wšě strašne sydła identifikuje a ma někotre wěste sydła za strašne a přehladowanje z lokalizaciju stejnišća a za słužbu přehladowanja z lokalizaciju stejnišća móhło płaćić, zo wšě městna, kotrež naše poskićowarjo słužby dodawaja, su jenož trochowanja a ani my ani poskićowarjo słužby njegarantuja dokładnosć dodatych městnow.
rights-webservices-term-2 = { -vendor-short-name } móže słužby po swojim wuzdaću zastajić abo změnić.
rights-webservices-term-3 = Sće přeprošene tute słužby z tutej wersiju { -brand-short-name } wužiwać, a { -vendor-short-name } garantuje wam prawa, zo by to činił. { -vendor-short-name } a jeho licencydawarjo wuměnjenjeja sej wšě druhe prawa na tutych słužbach. Tute wuměnjenja nimaja prawa wobmjezować, kotrež so pod licencami wotewrjeneho žórła garantuja a hodźa so na { -brand-short-name } a na wotpowědne wersije žórłoweho koda { -brand-short-name } nałožować.
rights-webservices-term-4 = <strong>Słužby dodawaja so "kaž wone su." { -vendor-short-name }, jeho sobudźěłaćerjo, licencydawarjo a rozdźělowarjo wotpokazuja wše rukowanja, njech wurazne abo zapřijate, inkluziwnje tajke, kotrež su bjez wobmjezowanja, rukowanja, zo słužby su kupne a wotpowěduja wašim wosebitym zaměram. Njeseće połne riziko, štož nastupa wuběranje słužbow za waše zaměry a kwalitu a wukon słužbow. Někotre prawodawstwa njedowoleja wuzamknjenje abo wobmjezowanje zapřijatych rukowanjow, tak tuta wuzamknjenska klawsula njeda so na was nałožić.</strong>
rights-webservices-term-5 = <strong>Chibazo zakon to požada, { -vendor-short-name }, jeho sobudźěłaćerjo, licencydawarjo a rozdźělowarjo njerukuja za indirektne, specialne, připadne, naslědne, chłostajomne abo eksemplariske škody, kotrež wuchadźeja z wašnja wužiwanja { -brand-short-name } a słužbow. Kolektiwne rukowanje pod tutymi wuměnjenjemi njepřesaha 500$ (pjeć stow dolarow). Někotre prawodawstwa njedowoleja wuzamknjenje abo wobmjezowanje wěstych škodow, tak tutej wuzamknjenje a wobmjezowanje njedadźa so na was nałožić.</strong>
rights-webservices-term-6 = { -vendor-short-name } móže tute wuměnjenja, jeli trěbne, hdys a hdys aktualizować. Tute wuměnjenja njehodźa so bjez pisomneho přizwolenja { -vendor-short-name } změnić abo anulować.
rights-webservices-term-7 = Tute wuměnjenja podlěža zakonam stata Kalifornija, USA, nimo prawniskich postajenjow, kotrež su w konflikće z nimi. Jeli maja so dźěl tutych wuměnjenjow za njepłaćiwy abo njepřesadźujomny, zbytne dźěle wobchowaja swoju połnu skutkownosć a płaćiwosć. Jeli je konflikt mjez přełoženej wersiju a jendźělskej wersiju, jendźelska wersija płaći.
