#filter emptyLines

#define MOZ_LANGPACK_CREATOR firefox.no

# If non-English locales wish to credit multiple contributors, uncomment this

# variable definition and use the format specified.

#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Kurt-Rune Bergset</em:contributor>  <em:contributor>Eirik Ulltang Birkeland</em:contributor>  <em:contributor>Håvar Henriksen</em:contributor>  <em:contributor>Torstein Hønsi</em:contributor>  <em:contributor>Erik Klepsvik</em:contributor>  <em:contributor>Håvard Mork</em:contributor>  <em:contributor>Jan-Espen Pettersen</em:contributor>  <em:contributor>Tom Ottar Røw</em:contributor>  <em:contributor>Åsmund Skjæveland</em:contributor>  <em:contributor>Pascual Strømsnæs</em:contributor>  <em:contributor>Vebjørn Sture</em:contributor>  <em:contributor>Kristian Svanes</em:contributor>  <em:contributor>Bjørn I. Svindseth</em:contributor>  <em:contributor>Ronny Vårdal</em:contributor>

#unfilter emptyLines
