#filter emptyLines
#define MOZ_LANGPACK_CREATOR mozilla.org

# If non-English locales wish to credit multiple contributors, uncomment this
# variable definition and use the format specified.
#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Новица Наков</em:contributor> <em:contributor>Дамјан Георгиевски</em:contributor> <em:contributor>Со помош од заедницата на корисници</em:contributor> <em:contributor>Видете mozilla.softver.org.mk</em:contributor> 

#unfilter emptyLines
