# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

rights-title = Aangaande u regte
rights-intro = { -brand-full-name } is vrye, oop sagteware wat deur 'n gemeenskap van derduisende mense van reg oor die wêreld gebou is. Hier is 'n paar dinge wat u moet weet:
rights-intro-point-1 = { -brand-short-name } word aan u beskikbaar gestel ingevolge die <a data-l10n-name="mozilla-public-license-link">Mozilla Publieke Lisensie</a>. Dit beteken dat u { -brand-short-name } kan gebruik, kopieer en versprei.  U kan ook die bronkode van { -brand-short-name } wysig, as u dit wil, om aan u behoeftes te voldoen. Die Mozilla Publieke Lisensie gee u ook die reg om gewysigde weergawes te versprei.
rights-intro-point-3 = Sekere kenmerke in { -brand-short-name }, soos die omvalverslaggewer, gee die opsie om terugvoer aan { -vendor-short-name } te gee. As u kies om terugvoer te gee, gee u { -vendor-short-name } toestemming om die terugvoer te gebruik om sy produkte te verbeter, om die terugvoer op sy webwerwe te publiseer, en om die terugvoer te versprei.
rights-intro-point-4 = Hoe ons u persoonlike inligting en terugvoer gebruik wat aan { -vendor-short-name } deur { -brand-short-name } ingedien is, word beskryf in <a data-l10n-name="mozilla-privacy-policy-link">{ -brand-short-name } se privaatheidbeleid</a>.
rights-intro-point-5 = Sekere { -brand-short-name }-kenmerke gebruik webgebaseerde inligtingdienste, maar ons kan nie waarborg dat hulle 100% akkuraat of foutvry is nie. Meer inligting oor hoe om die kenmerke wat hierdie dienste gebruik, te deaktiveer, is in die <a data-l10n-name="mozilla-service-terms-link">diensbepalings</a> te kry.
rights-intro-point-5-unbranded = Indien hierdie produk webdienste bevat, behoort enige toepaslike diensbepalings vir die diens(te) aan die <a data-l10n-name="mozilla-website-services-link">webwerfdienste</a>-afdeling gekoppel wees.
rights-intro-point-6 = Om sekere soorte video te speel, laai { -brand-short-name } sekere modules vanaf derde partye af vir inhouddekripsie.
rights-webservices-header = { -brand-full-name } se webgebaseerde inligtingsdienste
rights-webservices = { -brand-full-name } gebruik webgebaseerde inligtingsdienste ("dienste") om van die kenmerke te bied in hierdie binêre weergawe van { -brand-short-name } ingevolge die bepalings hier onder. As u een of meer van die dienste nie wil gebruik nie of as die bepalings hier onder onaanvaarbaar is, kan u die kenmerk of diens(te) deaktiveer. Inligting oor hoe om 'n sekere kenmerk of diens te deaktiveer, is <a data-l10n-name="mozilla-disable-service-link">hier</a>. Ander funksies en dienste kan in die voorkeure gedeaktiveer word.
rights-locationawarebrowsing = <strong>Liggingbewuste blaaiery: </strong>werk altyd met vóórtoestemming.  Geen ligginginligting word ooit sonder u toestemming gestuur nie.  As u die kenmerk volledig wil deaktiveer, volg hierdie stappe:
rights-locationawarebrowsing-term-1 = In die URL-balk, tik <code>aangaande:konfig</code>
rights-locationawarebrowsing-term-2 = Tik geo.enabled
rights-locationawarebrowsing-term-3 = Dubbelkliek die geo.enabled-voorkeur
rights-locationawarebrowsing-term-4 = Liggingbewuste blaaiery is nou gedeaktiveer
rights-webservices-unbranded = 'n Oorsig oor die webwerfdienste wat die produk bevat, asook instruksies vir hoe om hulle te deaktiveer, indien van toepassing, behoort hierby ingesluit te wees.
rights-webservices-term-unbranded = Enige toepaslike diensbepalings vir hierdie produk sal daar gelys wees.
rights-webservices-term-1 = { -vendor-short-name } en sy bydraers, lisensiegewers en vennote probeer die akkuraatste, mees bygewerkte dienste bied.  Ons kan egter nie waarborg dat die inligting omvattend of foutvry is nie.  Veiligblaai kan byvoorbeeld nie alle riskante werwe merk nie, en kan ook sekere veilige werwe as onveilig aanmerk.  Die liggingbewuste dienste se resultate is ook net by benadering en daarom kan die diensverskaffers nie die resultate waarborg nie.
rights-webservices-term-2 = { -vendor-short-name } kan die dienste na goeddunke opskort of wysig.
rights-webservices-term-3 = U is welkom om hierdie dienste te gebruik met die meegaande weergawe van { -brand-short-name }, en { -vendor-short-name } ken u die reg toe om dit te doen.  { -vendor-short-name } en sy lisensiegewers behou alle ander regte in die dienste voor.  Hierdie bepalings is nie bedoel om enige regte te beperk wat ingevolge oopbron-lisensies toegeken word wat op { -brand-short-name } en ooreenstemmende bronkode-weergawes van { -brand-short-name } van toepassing is nie.
rights-webservices-term-4 = <strong>Die Dienste word voetstoots verskaf.  { -vendor-short-name }, sy bydraers, lisensieerders en verspreiders ontken alle waarborge, hetsy uitdruklik of geïmpliseer, met inbegrip van, sonder beperking, waarborge dat die Dienste verhandelbaar is en geskik is vir u besondere doeleindes.  U dra die volle risiko wat betref die keuse van die Dienste vir u doeleindes en die gehalte en prestasie van die Dienste. Sommige owerhede verbied die uitsluiting of beperking van geïmpliseerde waarborge. Hierdie ontkenning is dus moontlik nie op u van toepassing nie.</strong>
rights-webservices-term-5 = <strong>Tensy die reg dit vereis is { -vendor-short-name } sy bydraers, lisensieerders en verspreiders nie aanspreeklik vir enige indirekte, spesiale, toevallige, gevolg- of bestraffende skadevergoeding wat spruit uit, of op enige manier te doen het met, die gebruik van { -brand-short-name } en die Dienste nie.  Die gesamentlike aanspreeklikheid van hierdie bepalings sal nie $500 (vyfhonderd dollars) oorskry nie. Sommige owerhede verbied die uitsluiting of beperking van sekere skadevergoeding. Hierdie uitsluiting is dus moontlik nie op u van toepassing nie.</strong>
rights-webservices-term-6 = { -vendor-short-name } kan dalk hierdie bepalings van tyd tot tyd bywerk indien nodig. Hierdie bepalings mag nie sonder { -vendor-short-name } se skriftelike toestemming gewysig of gekanselleer word nie.
rights-webservices-term-7 = Hierdie bepalings word beheer deur die reg van die Staat van Kalifornië, V.S.A., met die uitsluiting van die bepalings in verband met internasionale privaatreg. As beslis word dat enige deel van hierdie bepalings ongeldig of onafdwingbaar is, bly die oorblywende dele ten volle van krag. In die geval waar die vertaalde weergawe in stryd is met die Engelse weergawe van hierdie bepalings, sal die Engelse bepalings geld.
