#filter emptyLines

#define MOZ_LANGPACK_CREATOR mozillaitalia.org - Francesco Lodolo


# If non-English locales wish to credit multiple contributors, uncomment this
# variable definition and use the format specified.
#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Associazione Italiana Supporto e Traduzione Mozilla</em:contributor> <em:contributor>Francesco Lodolo</em:contributor> <em:contributor>Iacopo Benesperi</em:contributor> <em:contributor>Michele Dal Corso</em:contributor> <em:contributor>Sandro Della Giustina</em:contributor> <em:contributor>Simone Lando</em:contributor> <em:contributor>Giacomo Magnini</em:contributor> <em:contributor>Giuliano Masseroni</em:contributor>


#unfilter emptyLines
