#filter emptyLines
#define MOZ_LANGPACK_CREATOR The ChatZilla Team
#define MOZ_LANGPACK_HOMEPAGE http://chatzilla.hacksrus.com/
# If non-English locales wish to credit multiple contributors, uncomment this
# variable definition and use the format specified.
#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Mikael Hedberg</em:contributor> <em:contributor>Hasse Wallanger</em:contributor> <em:contributor>Lars P M</em:contributor>
#unfilter emptyLines
