name: Builds

on:
  # Triggers the workflow on push or pull request events but only for the future branch
  push:
    branches: [ future ]
  pull_request:
    branches: [ future ]
    
  workflow_dispatch:

jobs:
    windows-x64:
      name: 🪟 Windows X64
      runs-on: [self-hosted, linux, X64]
      env:
          MOZCONFIG: ".mozconfig-x86_64-w64-mingw32"
          SHELL: /bin/sh
      steps:
        - name: Cache
          uses: actions/cache@v2
          with:
            path: |
              $HOME/tooltool12
            key: ${{ runner.os }}-${{ hashFiles('**/browser/config/version_display.txt') }}

        - name: Download tooltool
          run: |
            curl -O https://cdn.waterfox.net/tools/tooltool12.tar.xz
          if: steps.cache.outputs.cache-hit != 'true'

        - name: Setup tooltool
          run: |
            tar -xvf tooltool12.tar.xz -C $HOME/
          if: steps.cache.outputs.cache-hit != 'true'

        - name: Checkout branch
          uses: actions/checkout@v2

        - name: Bootstrap
          run: |
            ./mach --no-interactive bootstrap --application-choice=browser

        - name: Build
          run: |
            . taskcluster/docker/recipes/xvfb.sh
            start_xvfb '1920x1080x24+32' 0
            ./mach build

        - name: Package
          run: |
            ./mach package

        - name: Upload artifact
          uses: actions/upload-artifact@v2
          with:
            name: Artifact Classic Linux ${{ github.run_id }}
            path: ./objdir-*/dist/install/sea/*.exe
            
    linux-x64:
      name: 🐧 Linux X64
      runs-on: [self-hosted, linux, X64]
      env:
        SHELL: /bin/sh
        MOZCONFIG: ".mozconfig"
      steps:
        - uses: actions/checkout@v2

        - name: Bootstrap
          run: |
            ./mach --no-interactive bootstrap --application-choice=browser

        - name: Build
          run: |
            ./mach build
            
        - name: Package
          run: |
            ./mach package
            
        - name: Upload Linux artifact
          uses: actions/upload-artifact@v2
          with:
            name: Artifact Classic Linux ${{ github.run_id }}
            path: ./objdir-*/dist/*.tar.bz2
