#filter emptyLines

#define MOZ_LANGPACK_CREATOR firefox.no

# If non-English locales wish to credit multiple contributors, uncomment this

# variable definition and use the format specified.

#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Pascual Strømsnæs</em:contributor> <em:contributor>Vidar Braut Haarr</em:contributor> <em:contributor>Håvar Henriksen</em:contributor> <em:contributor>Reidar Djupvik</em:contributor> <em:contributor>Jan-Espen Pettersen</em:contributor> <em:contributor>Håvard Mork</em:contributor> <em:contributor>Lasse Marøen</em:contributor> <em:contributor>Martin Joné</em:contributor> <em:contributor>Morten Liljegren</em:contributor>

#unfilter emptyLines
